### ISSUE TITLE
Update archie version

### ISSUE THREAD

**Issue by vidi42** [ehrbase/ehrbase#1000]
## Background ##

A new archie version will be released [containing the fix](https://github.com/openEHR/archie/pull/446) for #444

## Acceptance Criteria ##

- [ ] EHRbase is updated with the latest archie version -> [2.1.0](https://github.com/openEHR/archie/releases/tag/v2.1.0)
- [ ] Existing DV_DATE_TIME issues are rechecked once EHRbase is updated

**Comment by stefanspiska** [comment]
closed by https://github.com/ehrbase/openEHR_SDK/pull/410

**Comment by vladislavploaia** [comment]
Hello @vidi42 ,
This ticket has nothing related to [444 ](https://github.com/ehrbase/ehrbase/issues/444).
Confirmed with @stefanspiska.
I think the right ticket is [this one](https://github.com/openEHR/archie/pull/446)
