### ISSUE TITLE
Make the management endpoints publicly available

### ISSUE THREAD

**Issue by DavidWormVitagroup** [ehrbase/ehrbase#1009]
## Background ##

We want to integrate the health status at a public dashboard at: https://health.num-codex.de/
We like to have publicly available management endpoints for displaying the health and readyness status of an EHRBase installation.

## Acceptance criteria ##

/actuator/health endpoint needs to be accessible publicly. 
Including all it's components.

- [ ] There is no authentication needed

It can be done by enabling folowing spring components:

- [ ] management.endpoints.health.enabled=true
- [ ] management.endpoints.show-components='always'

The `management/**` endpoints need to be made publicly (without any authentication)

## Definition of Done ##

- [ ] Review / Merge request approved (P2P session)
- [ ] Unit tests passed
- [ ] Updated documentation (Javadoc and Sphinx)
- [ ] Acceptance criteria fulfilled
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] Runtime warnings
 a public dashboard at: https://health.num-codex.de/

**Comment by vidi42** [comment]
@DavidWormVitagroup We've merged a PR which should take care of the issue described here.

You can now use the newly introduced `management.endpoints.web.access` application property to set the access level of the management endpoints. (see here for more information [application/src/main/resources/application.yml](https://github.com/ehrbase/ehrbase/blob/develop/application/src/main/resources/application.yml#L159))
