### ISSUE TITLE
AQL Error - Could not perform SQL: Syntax Error

### ISSUE THREAD

**Issue by sidharthramesh** [ehrbase/ehrbase#1014]
## Configuration information

Apologies for not filling all the version details in.

```
<status>
<ehrbase_version>0.22.0</ehrbase_version>
<openehr_sdk_version>1.23.0</openehr_sdk_version>
<archie_version>2.0.1</archie_version>
<jvm_version>Oracle Corporation 11.0.16+8</jvm_version>
<os_version>Linux amd64 5.4.219-126.411.amzn2.x86_64</os_version>
<postgres_version>PostgreSQL 13.7 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 7.3.1 20180712 (Red Hat 7.3.1-12), 64-bit</postgres_version>
</status>
```

## Steps to reproduce ## 
```
POST {{ _.openehrBaseUrl }}/query/aql 
```
```
{
	"q": "\n\t\t\tSELECT c/context/start_time/value as time,\n\t\t\tc/uid/value as uid,\n\t\t\tc/name/value as name,\n\t\t\tc/content[openEHR-EHR-EVALUATION.reason_for_encounter.v1]/data[at0001]/items[at0002]/value/value as reason,\n\t\t\tc/composer/name as composer,\n\t\t\tc/context/other_context[at0001]/items[openEHR-EHR-CLUSTER.kenko_encounter_details.v0]/items[at0009]/value/value as comment\n\t\t\tfrom EHR e CONTAINS COMPOSITION c\n\t\t\tWHERE e/ehr_id/value='86614eda-34a2-504f-8972-d805444c38b0' AND c/context/health_care_facility/external_ref/id/value='0b0fe3ce-22a0-559b-8cb3-25bb3d57c937' AND c/name/value='Kenko.Digitization.v0' ORDER BY time DESC\n    "
}
```

## Actual result ##

400 Bad request

```json
{
	"error": "Bad Request",
	"message": "Could not perform SQL query:org.postgresql.util.PSQLException: ERROR: syntax error at or near \")\"\n  Position: 2330, AQL expression:SELECTc/context/start_time/valueastime,c/uid/valueasuid,c/name/valueasname,c/content[openEHR-EHR-EVALUATION.reason_for_encounter.v1]/data[at0001]/items[at0002]/value/valueasreason,c/composer/nameascomposer,c/context/other_context[at0001]/items[openEHR-EHR-CLUSTER.kenko_encounter_details.v0]/items[at0009]/value/valueascommentfromEHReCONTAINSCOMPOSITIONcWHEREe/ehr_id/value='86614eda-34a2-504f-8972-d805444c38b0'ANDc/context/health_care_facility/external_ref/id/value='0b0fe3ce-22a0-559b-8cb3-25bb3d57c937'ANDc/name/value='Kenko.Digitization.v0'ORDER BYtimeDESC<EOF>, Translated SQL:select \"alias_10528884\".\"time\", \"alias_10528884\".\"uid\", \"alias_10528884\".\"name\", \"alias_10528884\".\"reason\", \"alias_10528884\".\"composer\", \"alias_10528884\".\"comment\" from (select jsonb_extract_path_text(cast(\"ehr\".\"js_dv_date_time\"(\n  \"ehr\".\"event_context\".\"start_time\",\n  event_context.START_TIME_TZID\n) as jsonb),'value') as \"time\", jsonb_extract_path_text(cast(\"ehr\".\"js_composition\"(\n  cast(composition_join.id as uuid),\n  'ehrbase.medblocks.in'\n) as jsonb),'uid','value') as \"uid\", jsonb_extract_path_text(cast(\"ehr\".\"js_dv_coded_text_inner\"(\"ehr\".\"entry\".\"name\") as jsonb),'value') as \"name\", \"ehr\".\"entry\".\"entry\" #>> '{/composition[openEHR-EHR-COMPOSITION.encounter.v1],/content[openEHR-EHR-EVALUATION.reason_for_encounter.v1],0,/data[at0001],/items[at0002],0,/value,value}' as \"reason\", \"composer_ref\".\"name\" as \"composer\", (array_1539347267_47.var_1539347267_48)::TEXT as \"comment\" from \"ehr\".\"entry\" right outer join \"ehr\".\"composition\" as \"composition_join\" on \"composition_join\".\"id\" = \"ehr\".\"entry\".\"composition_id\" join \"ehr\".\"event_context\" on \"ehr\".\"event_context\".\"composition_id\" = \"ehr\".\"entry\".\"composition_id\" left outer join \"ehr\".\"party_identified\" as \"facility_ref\" on \"ehr\".\"event_context\".\"facility\" = \"facility_ref\".\"id\" join \"ehr\".\"party_identified\" as \"composer_ref\" on \"composition_join\".\"composer\" = \"composer_ref\".\"id\" right outer join \"ehr\".\"ehr\" as \"ehr_join\" on \"ehr_join\".\"id\" = \"composition_join\".\"ehr_id\" join lateral (\n  select jsonb_extract_path_text(cast(ehr.xjsonb_array_elements(cast(jsonb_extract_path_text(cast(ehr.xjsonb_array_elements(cast(cast(jsonb_extract_path(cast(\"ehr\".\"js_context\"(\"ehr\".\"event_context\".\"id\") as jsonb),'other_context','/items[openEHR-EHR-CLUSTER.kenko_encounter_details.v0]') as jsonb) as jsonb)) as jsonb),'/items[at0009]') as jsonb)) as jsonb),'/value','value')\n AS var_1539347267_48) as \"array_1539347267_47\" on true where (\"ehr\".\"entry\".\"template_id\" = ? and (\"ehr_join\".\"id\" = '86614eda-34a2-504f-8972-d805444c38b0' AND jsonb_extract_path_text(cast(\"ehr\".\"js_party_ref\"(\"facility_ref\".\"party_ref_value\", \"facility_ref\".\"party_ref_scheme\", \"facility_ref\".\"party_ref_namespace\", \"facility_ref\".\"party_ref_type\") as jsonb),'id','value') = '0b0fe3ce-22a0-559b-8cb3-25bb3d57c937' AND jsonb_extract_path_text(cast(\"ehr\".\"js_dv_coded_text_inner\"(\"ehr\".\"entry\".) as jsonb),'value')  = 'Kenko.Digitization.v0'))) as \"alias_10528884\" order by \"time\" desc"
}
```

## Expected result (Acceptance Criteria) ##

200 OK

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by vladislavploaia** [comment]
Hello @sidharthramesh,
Thank you for this ticket.
Could you please refer to any documentation reference, where it is specified that \r\n is accepted in AQL request?
I will report internal bug, if indeed, there is explicitly written that such cases must be accepted.
Thank you!
CC: @vidi42 , @stefanspiska

**Comment by sidharthramesh** [comment]
Hey @vladislavploaia - I think this bug is not because the AQL has `\n`. The AQL is translated into SQL and then the SQL fails the syntax check near a `\n`.

I'm not sure if `\n` and `\t` are officially supported as part of AQL, but that's probably a different issue.

**Comment by vladislavploaia** [comment]
Hey @sidharthramesh ,
Indeed, AQL is translated into SQL, but to properly transform the AQL statement to SQL (including these \n\t...) - these should affect somehow the final SQL.
Right now, seem to not have any effects, except the 400 Bad Request returned.
Next days, will check with Team, if we support such notations and let you know.
Most probably, we don't support, however, if it is needed, I can suggest this improvement and let Team decide.
@birgerhaarbrandt - Could you please check as well and return? Thanks!
CC: @vidi42

**Comment by vladislavploaia** [comment]
Hello @sidharthramesh ,
Could you please attach as well the Template (opt file) and Composition (in FLAT format), so I can reproduce this case.
Indeed, it can be an issue, but I need to find a way how to reproduce it.
It would help me a lot if you can provide the requested data.
Looking forward to your reply.
Thank you!
CC: @ale222

**Comment by sidharthramesh** [comment]
No template and composition was posted to the server to reproduce this issue.

an empty response with 200 was expected.

**Comment by vladislavploaia** [comment]
Hello @sidharthramesh,
Checked with latest version of EHRBase and OpenEHR_SDK and receive another error:
![image](https://user-images.githubusercontent.com/100927963/214832553-dcdac4bb-513d-4e0e-acbc-1ee1fad3a7aa.png)
[stacktrace.txt](https://github.com/ehrbase/ehrbase/files/10509067/stacktrace.txt)
Will check with my team and let you know the status. Most probably it is an issue and I have to report it in our internal JIRA.

**Comment by vladislavploaia** [comment]
Hello @sidharthramesh,
We are analyzing the latest issue provided by me in previous comment.
Your issue (with SQL syntax error) is no more reproducible.
Regarding latest issue, we will check. No ETA for the moment. Will let you know once I have any updates.
Thanks!
CC: @vidi42 , @HolgerReiseVSys , @stefanspiska

**Comment by vladislavploaia** [comment]
Hello @sidharthramesh,
Recently, we found that alias name should be different from the aliased part, if you plan to use aliased part after WHERE clause as well.
Here is the workable example, including \n\t, where I changed from (c/name/value as **name**) to (c/name/value as **c_name**).
![image](https://user-images.githubusercontent.com/100927963/216338816-9b745a7c-2674-4c3a-b460-21613fcc87a1.png)
As you can see, it returns 200.
**The case of the same alias name as in aliased part, will be taken in consideration while creating new AQL engine.**
Full valid query:
`{
	"q": "\n\t\t\tSELECT c/context/start_time/value as time,\n\t\t\tc/uid/value as uid,\n\t\t\tc/name/value as c_name,\n\t\t\tc/content[openEHR-EHR-EVALUATION.reason_for_encounter.v1]/data[at0001]/items[at0002]/value/value as reason,\n\t\t\tc/composer/name as composer,\n\t\t\tc/context/other_context[at0001]/items[openEHR-EHR-CLUSTER.kenko_encounter_details.v0]/items[at0009]/value/value as comment\n\t\t\tfrom EHR e CONTAINS COMPOSITION c\n\t\t\tWHERE e/ehr_id/value='86614eda-34a2-504f-8972-d805444c38b0' AND c/context/health_care_facility/external_ref/id/value='0b0fe3ce-22a0-559b-8cb3-25bb3d57c937' AND c/name/value='Kenko.Digitization.v0' ORDER BY time DESC\n    "
}`
Will close this, as the current version of AQL engine works as expected, returning 200, when following the rule mentioned above.
CC: @vidi42 , @stefanspiska , @HolgerReiseVSys , @micha1970
