### ISSUE TITLE
DOCKER ERROR

### ISSUE THREAD

**Issue by JosephItopa** [ehrbase/ehrbase#1018]
## DOCKER BUILD ERROR

Following the instruction on the documentation, every time I try to build the ehrbase from the docker file it fails to build.

The documentation guideline I followed is shown below:

![image](https://user-images.githubusercontent.com/28071719/207212740-fd3a1508-117a-4a19-bbf5-9a3218e30af4.png)

The error I got every time I build the docker file is shown below:

![image](https://user-images.githubusercontent.com/28071719/207213012-fff958a0-2534-4bf9-8fff-d42cdd8a2b85.png)

I have tried series of approach, including trying to build the file on AWS cloud9 but the error remains the same. Please kindly help. Thank you.

**Comment by stefanspiska** [comment]
@JosephItopa 

Did you install https://docs.docker.com/build/buildx/install/

you can also get the image via dockerhub https://hub.docker.com/r/ehrbase/ehrbase

cc: @vladislavploaia @vidi42

**Comment by JosephItopa** [comment]
Thank you Stefanspika.

I tried pulling the image from dockerhub. The problem remains the same, I guess I have to install buildx.

**Comment by vladislavploaia** [comment]
Hello @JosephItopa,

Could you please return with updates on this ticket?
Did you manage to install EHRBase as well as Docker?

CC: @stefanspiska, @vidi42

**Comment by JosephItopa** [comment]
Hello @vladislavploaia,

I tried some fix with the install docker to recognise the buildx commands but I still, it fails. Is there a version build to run with just docker instead of docker buildx?

**Comment by vladislavploaia** [comment]
Hello @JosephItopa,
I am using Windows OS, installed Docker and EHRBase without any issues.

**Comment by JosephItopa** [comment]
Hi @vladislavploaia,

I am using linux but I will try it out on my windows environment and then revert. 
Thank you,

**Comment by jgarciaroca** [comment]
@JosephItopa If i remember correctly, to build the image in Ubuntu i had to use Docker buildkit to avoid having the same error (It's been months i don't build an image from sourcecode) 

Directly from command line: ```DOCKER_BUILDKIT=1 docker build .```
or modify the daemon configuration:

```sudo nano /etc/docker/daemon.json``` adding ```{ "features": {"buildkit": true}}``` 
and restart it with ```sudo systemctl restart docker```

**Comment by vladislavploaia** [comment]
Hello @JosephItopa ,
Did you try the solution provided by @jgarciaroca ?
Could you please let me know, so I can cleanup a little bit the list of issues from EHRBase repo?
Thank you in advance.
CC: @vidi42

**Comment by vladislavploaia** [comment]
Closing ticket.
CC: @vidi42
