### ISSUE TITLE
AQL - Wrong Results if same Archetype is used twice in a template

### ISSUE THREAD

**Issue by biermapa** [ehrbase/ehrbase#1033]
# Environment information
```
    <ehrbase_version>0.24.0-SNAPSHOT</ehrbase_version>
    <openehr_sdk_version>1.24.0-SNAPSHOT</openehr_sdk_version>
    <archie_version>2.0.1</archie_version>
    <jvm_version>Eclipse Adoptium 17.0.5+8</jvm_version>
    <os_version>Linux amd64 5.10.16.3-microsoft-standard-WSL2</os_version>
    <postgres_version>PostgreSQL 13.4 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20210424) 10.3.1 20210424, 64-bit</postgres_version>
```

# Steps to reproduce

[AqlError.postman_collection.zip](https://github.com/ehrbase/ehrbase/files/10382244/AqlError.postman_collection.zip)

The attached postman composition contains the used template, creates a ehr_id with a given ehr_status and posts a compostion. The first queries ist used to get the compostion UID which is used in the following queries in the where clauses and needs to be exchanged.

Link to the template:[https://ckm.highmed.org/ckm/templates/1246.169.69](https://ckm.highmed.org/ckm/templates/1246.169.69)

The template contains two times the cluster laboratory_test_analyte which are nested in different levels.

# Actual result

```
    "columns": [
        {
            "path": "/items[at0001,'Erregername']/value/value",
            "name": "Name"
        },
        {
            "path": "/items[at0001,'Erregername']/value/defining_code/code_string",
            "name": "ID"
        },
        {
            "path": "/items[at0024]/value/value",
            "name": "ResultString"
        },
        {
            "path": "/items[at0024]/value/value",
            "name": "ResultText"
        },
        {
            "path": "/items[at0003]/value/value",
            "name": "Rate"
        }
    ],
    "rows": [
        [
            "Staphylococcus aureus",
            "sau",
            "Nachweis",
            "Nachweis",
            null
        ],
        [
            null,
            null,
            "Oxacillin",
            "Oxacillin",
            null
        ]
    ]
```

The queries always find both clusters, altough in one queries there is the cluster name in the where-clause given.

# Expected result

```
    "columns": [
        {
            "path": "/items[at0001,'Erregername']/value/value",
            "name": "Name"
        },
        {
            "path": "/items[at0001,'Erregername']/value/defining_code/code_string",
            "name": "ID"
        },
        {
            "path": "/items[at0024]/value/value",
            "name": "ResultString"
        },
        {
            "path": "/items[at0024]/value/value",
            "name": "ResultText"
        },
        {
            "path": "/items[at0003]/value/value",
            "name": "Rate"
        }
    ],
    "rows": [
        [
            "Staphylococcus aureus",
            "sau",
            "Nachweis",
            "Nachweis",
            null
        ]
    ]
```

The queries should just see the first cluster of  laboratory_test_analyte.

**Comment by vladislavploaia** [comment]
Hello @biermapa ,
Thank you for bug ticket and detailed description.
I was trying to reproduce it, but on Commit Composition, it returns 500 Internal Server Error.
![image](https://user-images.githubusercontent.com/100927963/212296079-33281537-6640-440c-9885-93704be350de.png)
Below stack trace is logged in EHRBase.
![image](https://user-images.githubusercontent.com/100927963/212296237-6dd5af30-03a4-4676-a8d0-28d859b721ba.png)
Anyways, will inform team that I cannot commit composition, due to 500 Internal Sever error, and if fixed, will analyze your bug correspondingly.
<ehrbase_version>0.24.0-SNAPSHOT</ehrbase_version>
<openehr_sdk_version>1.24.0-SNAPSHOT</openehr_sdk_version>

CC: @vidi42 , @stefanspiska , @HolgerReiseVSys

**Comment by vladislavploaia** [comment]
Hello @biermapa ,
It's really hard to analyze why 500 Internal Server Error is thrown on Commit Composition steps. I couldn't reach your actual result, mentioned in bug description.
Could you please check your OPT and Composition content and try to reproduce my case locally? Either OPT or Composition content should be modified, so your case described can be reproducible.
Thanks in advance.
CC: @vidi42 , @HolgerReiseVSys

**Comment by biermapa** [comment]
With your given template (#1027) the compositions should work but still give the wrong results.

**Comment by stefanspiska** [comment]
please recheck  with https://github.com/ehrbase/ehrbase/releases/tag/v2.0.0
