### ISSUE TITLE
AQL result is not as expected when the same archetype is used in two different templates

### ISSUE THREAD

**Issue by manci22lc** [ehrbase/ehrbase#1040]
# Environment information

EHRbase version:0.23.0
openEHR_SDK version:1.19.0
Archie version:2.0.1
PostgreSQL version: PostgreSQL 13.7, compiled by Visual C++ build 1914, 64-bit
Java Runtime version: Oracle Corporation 17.0.4.v20221004

# Steps to reproduce

Sample Template-1(encounter-signsymptom-3.en.v0) has composition(encounter) > observation(story)
Sample Template-2(encounter-signsymptom-5.en.v0) has composition(encounter) > observation(story) > cluster(sign-symptom)

Input Eg:->
Sample FLAT- for template 1 only observation is entered, since  template has only observation
    "encounter-signsymptom-3.en.v0/story_history/any_event:0/story:0": "Test-Story-1"

Sample FLAT- for template 2 observation and cluster details is entered, template has both observation and cluster as archetypes
    "encounter-signsymptom-5.en.v0/story_history/any_event:0/story:0": "Test-Story-2",
    "encounter-signsymptom-5.en.v0/story_history/any_event:0/symptom_sign/symptom_sign_name": "Test-sign-symptom-2",

Below is the AQL used :
{
   "q" : "SELECT  e/ehr_id/value as ehrId, c/uid/value as composition_id, c1/items[at0001]/value/value as name, o1/data[at0001]/events[at0002]/data[at0003]/items[at0004]/value/value as story, c/archetype_details/template_id/value as template FROM ehr e[ehr_id/value='{{ehrId}}'] CONTAINS COMPOSITION c[openEHR-EHR-COMPOSITION.encounter.v1] contains (observation o1[openEHR-EHR-OBSERVATION.story.v1] or cluster c1[openEHR-EHR-CLUSTER.symptom_sign.v1]) where (o1/data[at0001]/events[at0002]/data[at0003]/items[at0004]/value/value='Test-Story-1' and c/archetype_details/template_id/value ='encounter-signsymptom-3.en.v0') or (c1/items[at0001]/value/value ='Test-sign-symptom-2' and c/archetype_details/template_id/value ='encounter-signsymptom-5.en.v0')"
}

Attached is the  zip file which has  sample templates , composition and aql
[sign-syptom-AQL-issue.zip](https://github.com/ehrbase/ehrbase/files/10466099/sign-syptom-AQL-issue.zip)

# Actual result
    "rows": [
        [
            "47441ec1-8d2d-40d6-b4ca-9053327747ff",
            "9136e5c4-5bca-4566-832e-ab2a41a2031b::local.ehrbase.org::1",
            "Test-sign-symptom-2",
            "Test-Story-2",
            "encounter-signsymptom-5.en.v0"
        ]
    ]

AQL result is not as expected, since its filtering out with template ID which has all the archetypes mentioned in the containment , if any template that does not contain that archetype its not taken into consideration.
As soon as we query for signsymptom name in select clause or in where clause, its taking only (template2) into consideration, template1 is not considered at all

Further Debugging in code we got this below SQL query against which it return the results

select ehr_join.id as ehrId, jsonb_extract_path_text(cast(ehr.js_composition(
  cast(composition_join.id as uuid),
  'local.ehrbase.org'
) as jsonb),'uid','value') as composition_id, (array_509096368_57.var_509096368_58#>>'{/data[at0003],/items[openEHR-EHR-CLUSTER.symptom_sign.v1],0,/items[at0001],0,/value,value}')::TEXT as name, (array_1197837163_59.var_1197837163_60#>>'{/value,value}')::TEXT as story, ehr.entry.template_id as template from ehr.entry right outer join ehr.composition as composition_join on composition_join.id = ehr.entry.composition_id right outer join ehr.ehr as ehr_join on ehr_join.id = composition_join.ehr_id join lateral (
  select (ehr.xjsonb_array_elements((ehr.entry.entry#>>'{/composition[openEHR-EHR-COMPOSITION.encounter.v1],/content[openEHR-EHR-OBSERVATION.story.v1],0,/data[at0001],/events,/events[at0002]}')::jsonb)) 
 AS var_509096368_58) as array_509096368_57 on true join lateral (
  select (ehr.xjsonb_array_elements((ehr.xjsonb_array_elements((ehr.entry.entry#>>'{/composition[openEHR-EHR-COMPOSITION.encounter.v1],/content[openEHR-EHR-OBSERVATION.story.v1],0,/data[at0001],/events,/events[at0002]}')::jsonb)#>>'{/data[at0003],/items[at0004]}')::jsonb)) 
 AS var_1197837163_60) as array_1197837163_59 on true **where (ehr.entry.template_id = 'encounter-signsymptom-5.en.v0'** and ( ( (array_1197837163_59.var_1197837163_60#>>'{/value,value}')::TEXT  = 'Test-Story-1' and ehr.entry.template_id  = 'encounter-signsymptom-3.en.v0' )  or  ( (array_509096368_57.var_509096368_58#>>'{/data[at0003],/items[openEHR-EHR-CLUSTER.symptom_sign.v1],0,/items[at0001],0,/value,value}')::TEXT  = 'Test-sign-symptom-2' and ehr.entry.template_id  = 'encounter-signsymptom-5.en.v0' )  and ehr_join.id  = '47441ec1-8d2d-40d6-b4ca-9053327747ff'))

As we can see in where clause its considering only template2

# Expected result
  "rows": [
        [
            "47441ec1-8d2d-40d6-b4ca-9053327747ff",
            "9136e5c4-5bca-4566-832e-ab2a41a2031b::local.ehrbase.org::1",
            "Test-sign-symptom-2",
            "Test-Story-2",
            "encounter-signsymptom-5.en.v0"
        ],
	[
            "47441ec1-8d2d-40d6-b4ca-9053327747ff",
            "88367g5c4-3rca-8966-821e-sd2a41w3031b::local.ehrbase.org::1",
            null,
            "Test-Story-1",
            "encounter-signsymptom-3.en.v0"
        ]
    ]

AQL should have returned results across any templates which has archetype openEHR-EHR-OBSERVATION.story.v1 for given ehrId.

**Comment by vladislavploaia** [comment]
Hello @manci22lc,
Thank you for detailed bug description.
Issue was analyzed and reproduced at my side as well.
Defect ticket reported in our internal JIRA: https://jira.vitagroup.ag/browse/CDR-722
Will let you know, when it is fixed.

CC: @vidi42 , @HolgerReiseVSys

**Comment by stefanspiska** [comment]
please recheck  with https://github.com/ehrbase/ehrbase/releases/tag/v2.0.0
