### ISSUE TITLE
Facing issue in AQL when queried across different templates across different archetypes

### ISSUE THREAD

**Issue by manci22lc** [ehrbase/ehrbase#1045]
# Environment information

EHRbase version:0.23.0
openEHR_SDK version:1.19.0
Archie version:2.0.1
PostgreSQL version: PostgreSQL 13.7, compiled by Visual C++ build 1914, 64-bit
Java Runtime version: Oracle Corporation 17.0.4.v20221004

# Steps to reproduce

Have two templates 
One template has openEHR-EHR-OBSERVATION.problem_screening.v1 as archetype
Other template has openEHR-EHR-OBSERVATION.symptom_sign_screening.v1 as archetype

Input example for template1 :
 "sample_template-3.en.v0/problem_diagnosis_screening_questionnaire/any_event:1/specific_problem_or_diagnosis:0/problem_diagnosis_name": "TestProblemScreening-1",
    "sample_template-3.en.v0/problem_diagnosis_screening_questionnaire/any_event:1/specific_problem_or_diagnosis:0/presence/coded_text_value|value": "Yes"
    
Input example for template 2: 
    "sample_template-2.en.v0/symptom_sign_screening_questionnaire/any_event:0/specific_symptom_sign:0/symptom_sign_name": "Test-signsymptom-2",
    "sample_template-2.en.v0/symptom_sign_screening_questionnaire/any_event:0/specific_symptom_sign:0/presence|value": "Yes",
    
  AQL query: 
  {
    "q": "select e/ehr_id/value from ehr e contains composition c[openEHR-EHR-COMPOSITION.encounter.v1] contains (observation o[openEHR-EHR-OBSERVATION.problem_screening.v1]  or  observation o1[openEHR-EHR-OBSERVATION.symptom_sign_screening.v0]) where  (o/data[at0001]/events[at0002]/data[at0003]/items[at0022]/items[at0004]/value/value='TestProblemScreening-1' and  o/data[at0001]/events[at0002]/data[at0003]/items[at0022]/items[at0005]/value/value='Yes') or (o1/data[at0001]/events[at0002]/data[at0003]/items[at0022]/items[at0004]/value/value='Test-signsymptom-2' and o1/data[at0001]/events[at0002]/data[at0003]/items[at0022]/items[at0005]/value/value ='Yes')"
}

Attached is the zip file which has sample templates , composition and aql  
[AQL issue.zip](https://github.com/ehrbase/ehrbase/files/10534248/AQL.issue.zip)

# Actual result
{
    "error": "Bad Request",
    "message": "Could not perform SQL query:org.postgresql.util.PSQLException: ERROR: column alias_117828109.1 does not exist\n  Position: 38, AQL expression:selecte/ehr_id/valuefromehrecontainscompositionc[openEHR-EHR-COMPOSITION.encounter.v1]contains(observationo[openEHR-EHR-OBSERVATION.problem_screening.v1]orobservationo1[openEHR-EHR-OBSERVATION.symptom_sign_screening.v0])where(o/data[at0001]/events[at0002]/data[at0003]/items[at0022]/items[at0004]/value/value='TestProblemScreening-1'ando/data[at0001]/events[at0002]/data[at0003]/items[at0022]/items[at0005]/value/value='Yes')or(o1/data[at0001]/events[at0002]/data[at0003]/items[at0022]/items[at0004]/value/value='Test-signsymptom-2'ando1/data[at0001]/events[at0002]/data[at0003]/items[at0022]/items[at0005]/value/value='Yes')<EOF>, Translated SQL:select distinct on (\"/ehr_id/value\") \"alias_117828109\".\"1\" from (select 1) as \"alias_117828109\""
}

# Expected result

Since ehr_id is the only common entity that was being queried , across different templates and different archetypes, it should have returned ehr_id, since the same ehr_id was used to insert compositions
    "rows": [
        [
            "cb2ebad4-d002-41f0-b9f0-522a7cff1f6b"
        ]
    ]

**Comment by vladislavploaia** [comment]
Hello @manci22lc,
Thank you for informing us.
It seems to be the same issue as in latest comment from https://github.com/ehrbase/ehrbase/issues/1014:
![image](https://user-images.githubusercontent.com/100927963/215458748-89af7f8e-ce1a-4f0f-9684-e33543a0ce19.png)
We know about that already.
We are analyzing that and will let you know once fixed/have an ETA for fix.

Thank you!
CC: @vidi42 , @HolgerReiseVSys , @stefanspiska

**Comment by stefanspiska** [comment]
please recheck  with https://github.com/ehrbase/ehrbase/releases/tag/v2.0.0
