### ISSUE TITLE
Cannot get the composition which is POSTed with invalid DATE. 

### ISSUE THREAD

**Issue by ATHULKNAIR** [ehrbase/ehrbase#1046]
# Environment information

> To help reproducing your problem it is mandatory to give some information on the environment. You can get an aggregate of this data by starting EHRbase and performing a GET request on 
`%ehrbaseBaseUri%/ehrbase/rest/status`.

- EHRbase version: 0.22.0
- openEHR_SDK version: 1.23.0
- Archie version: 2.0.1
- PostgreSQL version: PostgreSQL 13.7 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 7.3.1 20180712 (Red Hat 7.3.1-12), 64-bit
- Java Runtime version: Oracle Corporation 11.0.16+8
- Operating System version: Linux amd64 5.4.219-126.411.amzn2.x86_64

# Steps to reproduce

`{
"template/hospital_bill/bill_date":"20222-09-12"
} `

POSTed to {baseUrl}/ehrbase/rest/ecis/v1/composition?ehrId={ehrId}&templateId={templateId}&format=FLAT

Try getting the composition back with Composition ID

# Actual result

`{"error":"Bad Request","message":"DB inconsistency:java.lang.IllegalArgumentException: Text '+20232-12-11' could not be parsed at index 0:+20232-12-11 (through reference chain: com.nedap.archie.rm.composition.Composition[\"content\"]->java.util.ArrayList[0]->com.nedap.archie.rm.composition.AdminEntry[\"data\"]->com.nedap.archie.rm.datastructures.ItemTree[\"items\"]->java.util.ArrayList[5]->com.nedap.archie.rm.datastructures.Element[\"value\"]->com.nedap.archie.rm.datavalues.quantity.datetime.DvDate[\"value\"])"}`

# Expected result

EHRBase should have given validation error while POSTing the composition

**Comment by vladislavploaia** [comment]
Hello @ATHULKNAIR ,
Could you please provide OPT file and Composition file (in FLAT format)?
CC: @vidi42

**Comment by ATHULKNAIR** [comment]
[composition.txt](https://github.com/ehrbase/ehrbase/files/10553673/composition.txt)
[opt.txt](https://github.com/ehrbase/ehrbase/files/10553674/opt.txt)

@vladislavploaia OPT file and Composition file attached above

**Comment by vladislavploaia** [comment]
Hello @ATHULKNAIR ,
Thanks for sharing OPT and Composition.
I reproduced this issue on my side as well.
JIRA ticket was created [CDR-726](https://jira.vitagroup.ag/browse/CDR-726).
Will let you know if I get any updates on that.

CC: @vidi42 , @stefanspiska , @HolgerReiseVSys

**Comment by vladislavploaia** [comment]
Hello @ATHULKNAIR ,
[CDR-726](https://jira.vitagroup.ag/browse/CDR-726) is closed as Duplicated.
Our team is actively working on it, so, soon we will have fix for that.
I will let you know once it is fixed.
CC: @vidi42 , @vmueller-vg

**Comment by vladislavploaia** [comment]
Tested on EHRbase v. **0.30.0-SNAPSHOT**
Commit composition will not be allowed with **"kenko.digitization.v0/hospital_bill/bill_date":"202222-09-12"**
![image](https://github.com/ehrbase/ehrbase/assets/100927963/e41f4479-10c7-402d-8df8-a259f7fba1f6)
Ticket closed.
CC: @vidi42 , @HolgerReiseVSys
