### ISSUE TITLE
Property `ehr_id` does not exist in ...

### ISSUE THREAD

**Issue by fjukstad** [ehrbase/ehrbase#108]
Hi,

Thanks for open-sourcing the project and including a great test suite!

We are experimenting with running the test suite against a server that implements the openEHR REST API specifications. Currently I want to run the composition tests, but they fail when trying to get the `ehr_id` from the response of a `POST` to `/ehr`. The message is as follows: 

```
Property 'ehr_id' does not exist in:
"﻿{\"_type\":\"PATIENT_EHR\",\"system_id\":{\"value\":\"9624982A-9F42-41A5-9318-AE13D5F5031F\"},\"ehr_id\":{\"value\":\"7ca92fea-8b21-4a0e-9721-2f1640001c2d\"},\"time_created\":{\"value\":\"2020-01-20T19:02:38+01:00\"},\"ehr_status\":{\"uid\":{\"_type\":\"OBJECT_VERSION_ID\",\"value\":\"1e23b020-194e-4d67-bda7-a902721dfc99::9624982A-9F42-41A5-9318-AE13D5F5031F::1\"} .... 

...

Expected property 'response body ehr_id value' was not found. 
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\REST\keywords.py", line 877, in string
    for found in self._find_by_field(field):
  File "c:\python36\lib\site-packages\REST\keywords.py", line 1444, in _find_by_field
    for path in paths
  File "c:\python36\lib\site-packages\REST\keywords.py", line 1444, in <listcomp>
    for path in paths
  File "c:\python36\lib\site-packages\REST\keywords.py", line 1466, in _find_by_path
    "\nExpected property '%s' was not found." % (field)
```

We can unescape the quotes and format the JSON to make it easier to read: 

```
{
    "_type": "PATIENT_EHR",
    "system_id": {
        "value": "9624982A-9F42-41A5-9318-AE13D5F5031F"
    },
    "ehr_id": {
        "value": "83962836-16ba-4053-8c17-800122d26401"
    },
    "time_created": {
        "value": "2020-01-20T18:26:49+01:00"
    },
...
```

If the above JSON is incorrect, how is the JSON supposed to look like? From the [spec](https://specifications.openehr.org/releases/ITS-REST/latest/ehr.html#ehr-ehr-post), the JSON looks correct, but there is probably a small detail that I have missed. 

Thanks,
Bjørn

**Comment by testautomation** [comment]
Hi Bjørn (@fjukstad ), thanks for your feedback. Can you tell me which test case this happens with?  

We should have a look in Robot's log.html in TRACE mode to see all the details. Can you please run related test from command line as shown in example below:

```
robot -d results -L TRACE robot/COMPOSITION_TESTS/JSON1/B.1.a_main_flow_has_existing_COMPOSITION.robot
```

We can then drill down into the keyword to check whats happening. 

Below an example screenshot from related keyword in log.html with TRACE and a response object where extraction of ehr_id is working
![image](https://user-images.githubusercontent.com/38438046/72880649-8beb4480-3cff-11ea-8770-cecc72283ce0.png)

```
{'body': {'compositions': None,
          'contributions': None,
          'ehr_id': {'_type': 'HIER_OBJECT_ID',
                     'value': 'ebebc614-d988-4a99-8312-52223e0709b4'},
          'ehr_status': {'_type': 'EHR_STATUS',
                         'is_modifiable': True,
                         'is_queryable': True,
                         'subject': {'_type': 'PARTY_SELF',
                                     'external_ref': {'_type': 'PARTY_REF',
                                                      'id': {'_type': 'HIER_OBJECT_ID',
                                                             'value': '0899af25-c61c-4b87-908c-d5d1e4b294c8'},
                                                      'namespace': 'default'}},
                         'uid': {'_type': 'HIER_OBJECT_ID',
                                 'value': '37bbc508-25c1-4fcb-afba-d54857e7d428'}},
          'system_id': {'_type': 'HIER_OBJECT_ID',
                        'value': 'afd121a2-69c9-4e52-b7a0-55f7c764c037'},
          'time_created': '2020-01-21T16:15:42.577'},
 'headers': {'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate',
             'Content-Type': 'application/json',
             'Date': 'Tue, 21 Jan 2020 16:15:42 GMT',
             'ETag': '"ebebc614-d988-4a99-8312-52223e0709b4"',
             'Expires': '0',
             'Last-Modified': 'Fri, 02 Jan 1970 10:12:04 GMT',
             'Location': 'http://localhost:8080/ehrbase/rest/openehr/v1/ehr/ebebc614-d988-4a99-8312-52223e0709b4',
             'Pragma': 'no-cache',
             'Transfer-Encoding': 'chunked',
             'X-Application-Context': 'application:local:8080',
             'X-Content-Type-Options': 'nosniff',
             'X-Frame-Options': 'DENY',
             'X-XSS-Protection': '1; mode=block'},
 'seconds': 0.048308,
 'status': 201}
```

**Comment by fjukstad** [comment]
Thanks for help! 

I can produce the error by running any of the `COMPOSTION` tests that require an existing `EHR`. Here's a screenshot of the `log.html`. The `ehr_id` object from our server is missing the `'type':'HIER_OBJECT_ID'`, maybe that's why the test is failing? 

![image](https://user-images.githubusercontent.com/1394111/72886169-a0343f00-3d09-11ea-9906-6ebd91bdfb76.png)

The response you posted includes the fields ` 'compositions': None, 'contributions': None,`, is that according to the [specification](https://specifications.openehr.org/releases/ITS-REST/latest/ehr.html#ehr-ehr-post)?

**Comment by testautomation** [comment]
>The ehr_id object from our server is missing the 'type':'HIER_OBJECT_ID', maybe that's why the test is failing?

No, I don't think so, the test does not care about that item. 
As you can see in the warning the used test library complains about the content of response body not being a proper JSON. The content of your body seems to be a string - but a JSON object is expected. So the response from your server is a valid JSON but the content of the body is a string. Not 100% sure but it might also be a library issue. Can please check what the response looks like when you do it in Postman (or similar client)?

>The response you posted includes the fields 'compositions': None, 'contributions': None,, is that according to the specification?

AFAIK the API spec might be not up-to-date (last update on 17 Oct 2019) and thus (at least yet) can't be trusted 100% :) 
May be a better source is the [openEHR Information Model](https://specifications.openehr.org/releases/RM/latest/ehr.html#_the_ehr_information_model) (Last updated 2019-12-15 23:33:12 UTC). But since I'm not an expert in openEHR feel free to mention our domain expert @ppazos when you have specification related questions.

**Comment by stefanspiska** [comment]
If I look at your screenshot then you response body starts with `\ufeff` indicating that the server returns UTF-8 whit BOM which is not what the test suite expects.

**Comment by fjukstad** [comment]
Hi! Thanks for the help guys! The response was indeed in UTF-8 with a BOM @stefanspiska, and the test continues if we remove the BOM from the response.
