### ISSUE TITLE
Retain Folder sub-folders in update requests

### ISSUE THREAD

**Issue by ThomasKluiters** [ehrbase/ehrbase#1107]
### Background

I was implementing my OpenEHR client for EHRBase and encountered something odd; whenever I would update my Folder I would get my updated folder back.. Except the sub-folders! I spent quite a bit of time looking into the actual cause and managed to isolate the issue: the sub-folders are cleared when creating the EhrFolder record during persistence, as we do not want to marshal the sub-folders.

The spec is not quite clear as what to expect back when performing a PUT request, but I would guess that returning the updated folder is desirable.

### Enhancement

Incude the sub-folders when updating a Folder.

### Discussion

The implementation of my fix can be see in the Pull Request. I had a few options:

- Create a deep copy of a the Folder; prone to issues later where a Folder potentially obtains new Fields
- Temporarily "re-set" the folders, current implementation.

**Comment by vladislavploaia** [comment]
Covered by Robot test case: https://github.com/ehrbase/integration-tests/blob/main/tests/robot/DIRECTORY_TESTS/UPDATE_DIRECTORY/H.1__EHR_with_directory.robot
CC: @vidi42 , @stefanspiska
