### ISSUE TITLE
AQL returns empty rows when queried for composition archetype name/encoding/language/ which has multiple nested json as values

### ISSUE THREAD

**Issue by manci22lc** [ehrbase/ehrbase#1110]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Environment information

EHRbase version:0.23.0
openEHR_SDK version:1.24.0-SNAPSHOT
Archie version:2.0.1
PostgreSQL version: PostgreSQL 13.7
Java Runtime version: Oracle Corporation 17.0.4.v20221004
OS: Windows 11

### Steps to reproduce

1. Template with archetype openEHR-EHR-OBSERVATION.symptom_sign_screening.v0 added in content.
2. Inserted FLAT Composition
3. Run Below AQL :
   {
    "q" : "SELECT c/content[openEHR-EHR-OBSERVATION.symptom_sign_screening.v0]/name/value FROM ehr e[ehr_id/value='$$ehrId'] 
CONTAINS COMPOSITION c[openEHR-EHR-COMPOSITION.encounter.v1] contains observation o1[openEHR-EHR-OBSERVATION.symptom_sign_screening.v0]  "
}

OR 

{
    "q" : "SELECT c/content[openEHR-EHR-OBSERVATION.symptom_sign_screening.v0]/language/terminology_id/name FROM ehr e[ehr_id/value='$$ehrId] CONTAINS COMPOSITION c[openEHR-EHR-COMPOSITION.encounter.v1] contains observation o1[openEHR-EHR-OBSERVATION.symptom_sign_screening.v0]  "

}
[issue_nemed_path.en.v0.zip](https://github.com/ehrbase/ehrbase/files/11293214/issue_nemed_path.en.v0.zip)

### Expected behavior

    "rows": [
        [
            "Diabetes"
        ]
    ]

### Actual result

 "rows": [
        []
    ]

### Further information

This was working in version 20.

**Comment by manci22lc** [comment]
I'm not sure if the issue mentioned is the same, since there no cardinality in templates that I have used, Archetype added  was renamed as "Diabetes", and I'm trying to get the archetype Name in select AQL.

**Comment by stefanspiska** [comment]
please recheck  with https://github.com/ehrbase/ehrbase/releases/tag/v2.0.0
