### ISSUE TITLE
AQL query across two templates returns empty columns and rows.

### ISSUE THREAD

**Issue by pgmullar** [ehrbase/ehrbase#1118]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Environment information

ehrbaseversion :   0.26.0
openehr sdk version :  1.26.0
archie version :  3.0.0
jvm version :  Eclipse Adoptium 17.0.6+10
os version :   Linux amd64 5.19.0-41-generic
postgres version :   PostgreSQL 13.4 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20210424) 10.3.1 20210424, 64-bit

### Steps to reproduce

Attached is the zip file containing sample templates, composition and aql
[AQL issue.zip](https://github.com/ehrbase/ehrbase/files/11463370/AQL.issue.zip)

Using two templates
One template has openEHR-EHR-OBSERVATION.problem_screening.v1 as archetype
Other template has openEHR-EHR-OBSERVATION.symptom_sign_screening.v1 as archetype

Input example for template1 :
"sample_template-3.en.v0/problem_diagnosis_screening_questionnaire/any_event:1/specific_problem_or_diagnosis:0/problem_diagnosis_name": "TestProblemScreening-1",
"sample_template-3.en.v0/problem_diagnosis_screening_questionnaire/any_event:1/specific_problem_or_diagnosis:0/presence/coded_text_value|value": "Yes"

Input example for template 2:
"sample_template-2.en.v0/symptom_sign_screening_questionnaire/any_event:0/specific_symptom_sign:0/symptom_sign_name": "Test-signsymptom-2",
"sample_template-2.en.v0/symptom_sign_screening_questionnaire/any_event:0/specific_symptom_sign:0/presence|value": "Yes",

Running various AQL queries than span the templates return empty columns and rows.

e.g.
```
{
    "q": "select c/uid/value, c/content[openEHR-EHR-OBSERVATION.symptom_sign_screening.v0]/data[at0001]/events[at0002]/data[at0003]/items[at0022]/items[at0004]/value/value, c/content[openEHR-EHR-OBSERVATION.problem_screening.v1]/data[at0001]/events[at0002]/data[at0003]/items[at0022]/items[at0004]/value/value from ehr e contains composition c[openEHR-EHR-COMPOSITION.encounter.v1]",
    "columns": [],
    "rows": [
        []
    ]
}
```

```
{
    "q": "select c/uid/value, o/data[at0001]/events[at0002]/data[at0003]/items[at0022]/items[at0004]/value/value, o1/data[at0001]/events[at0002]/data[at0003]/items[at0022]/items[at0004]/value/value  from ehr e contains composition c[openEHR-EHR-COMPOSITION.encounter.v1] contains (observation o[openEHR-EHR-OBSERVATION.problem_screening.v1]  or  observation o1[openEHR-EHR-OBSERVATION.symptom_sign_screening.v0])",
    "columns": [],
    "rows": [
        []
    ]
}
```

Whilst querying a single column returns the expected results.
e.g.
```
{
    "q": "select c/uid/value, o/data[at0001]/events[at0002]/data[at0003]/items[at0022]/items[at0004]/value/value  from ehr e contains composition c[openEHR-EHR-COMPOSITION.encounter.v1] contains (observation o[openEHR-EHR-OBSERVATION.problem_screening.v1]  or  observation o1[openEHR-EHR-OBSERVATION.symptom_sign_screening.v0])",
    "columns": [
        {
            "path": "/uid/value",
            "name": "#0"
        },
        {
            "path": "/data[at0001]/events[at0002]/data[at0003]/items[at0022]/items[at0004]/value/value",
            "name": "#1"
        }
    ],
    "rows": [
        [
            "5dc3c21f-534a-4d7a-b369-72e3687e97f1::local.ehrbase.org::1",
            "TestProblemScreening-1"
        ]
    ]
```

### Expected behavior

Would expect that the columns array be populated with the columns defined and rows returned

### Actual result

The column array is empty and no rows returned.

**Comment by pgmullar** [comment]
Queries made using http://localhost:8080/ehrbase/rest/openehr/v1/query/aql

**Comment by stefanspiska** [comment]
please recheck  with https://github.com/ehrbase/ehrbase/releases/tag/v2.0.0
