### ISSUE TITLE
Error returning validation error information on updateComposition

### ISSUE THREAD

**Issue by krembiszewski** [ehrbase/ehrbase#1124]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Environment information

EHRBase Version: 0.28

### Steps to reproduce

Incorrect response body during updateComposition. When we call createComposition during validation error returns ValidationException with description, while updateComposition return UnprocessableEntityException without details.

### Expected behavior

Change in CompositionServiceImp.java so that validation errors during creation and update look the same 

### Actual result

Diffrent exception in validation composition

**Comment by vladislavploaia** [comment]
Hello @krembiszewski ,
Thank you for informing us about the issue.
Could you please attach Template (OPT) and Composition (Create and Update) content you have used?
Thank you in advance.
CC: @vidi42 , @stefanspiska

**Comment by vladislavploaia** [comment]
Hello @krembiszewski ,
Could you please return with updates, otherwise current ticket will be closed.
Thanks in advance.
CC: @vidi42
