### ISSUE TITLE
Migration v83 ('change sys tenant to short') fails catastrophically

### ISSUE THREAD

**Issue by jpwiedekopf** [ehrbase/ehrbase#1126]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Environment information

- EHRbase version: 0.27.0
- Operating System version: Docker on Mac M1 (aarch64)

### Steps to reproduce

Start EHRbase 0.27.0 using `docker-compose`. 

### Expected behavior

- All system migrations are carried out correctly, and the database is migrated to version 83.

### Actual result

- The migration v83 fails with the following error message ([full logs attached](https://github.com/ehrbase/ehrbase/files/11615026/ehrbase-error.log)): `unrecognized configuration parameter "ehrbase.current_tenant"`.
- EHRbase doesn't start, since migrations were not carried out successfully.

**Comment by jpwiedekopf** [comment]
The offending line is: https://github.com/ehrbase/ehrbase/blob/cf405d6785b1b438d931530124d20abe7f6031ad/base/src/main/resources/db/migration/V83__change_sys_tenant_to_short.sql#L382

**Comment by jpwiedekopf** [comment]
I'm currently running a build from source, and during the build, the migration is carried out without issue in the "contained" PostgreSQL database. But after build, when running the stack with `docker-compose`, the above issue arises.

As far as I can tell, this option is only set in [this line](https://github.com/ehrbase/ehrbase/blob/cf405d6785b1b438d931530124d20abe7f6031ad/service/src/main/java/org/ehrbase/service/PersistenceConfig.java#LL78C29-L78C29) which isn't called during Flyway migrations upon bringing up the service (verified by making the `connectionProvider` method always throw, and no exception was received in the log, instead, the above error was thrown again).

This config parameter needs to be introduced to Flyway in some fashion, please advise.

**Comment by jpwiedekopf** [comment]
Confirmed that the issue doesn't occur if I very explicitly set `select set_config('ehrbase.current_tenant', '1', false);` in the Flyway script.

**Comment by stefanspiska** [comment]
@jpwiedekopf 

```
EXECUTE format(
                        'CREATE POLICY ehr_policy_all ON ehr.%I FOR ALL USING (sys_tenant = current_setting(''ehrbase.current_tenant'')::smallint)'
```

executes the statement 
```
CREATE POLICY ehr_policy_all ON ehr.<TABLENAME> FOR ALL USING (sys_tenant = current_setting(''ehrbase.current_tenant')::smallint)'
```
Note the double escape here since we have a ' in a String.

current_setting(''ehrbase.current_tenant') will only evaluated during row level security   execution.

Somehow the script tries to evaluate   current_setting here. this is wrong but select set_config('ehrbase.current_tenant', '1', false); is not realy solution 
 But we are currently not able to reproduce that. 
can you try  Dollar quoting  https://pgpedia.info/d/dollar-quoting.html

```
EXECUTE format(
                        $$CREATE POLICY ehr_policy_all ON ehr.%I FOR ALL USING (sys_tenant = current_setting('ehrbase.current_tenant')::smallint)$$
cc: @dmitrytulba 
```

**Comment by stefanspiska** [comment]
@jpwiedekopf 

Dos you docker compose  look like this 
```
      DB_USER_ADMIN: ehrbase
      DB_PASS_ADMIN: ehrbase
      DB_USER: ehrbase_restricted
      DB_PASS: ehrbase_restricted
```

Note the values for DB_USER_ADMIN and DB_USER

**Comment by jpwiedekopf** [comment]
> @jpwiedekopf
> 
> Dos you docker compose look like this
> 
> ```
>       DB_USER_ADMIN: ehrbase
>       DB_PASS_ADMIN: ehrbase
>       DB_USER: ehrbase_restricted
>       DB_PASS: ehrbase_restricted
> ```
> 
> Note the values for DB_USER_ADMIN and DB_USER

Yes, I have settings for `DB_USER_ADMIN` and `DB_USER` set, but not to `ehrbase`/`ehrbase_restricted` respectively. Does that matter? If so, I think it shouldn't?

**Comment by jpwiedekopf** [comment]
> can you try Dollar quoting https://pgpedia.info/d/dollar-quoting.html
> 
> ```sql
> EXECUTE format(
>                         $$CREATE POLICY ehr_policy_all ON ehr.%I FOR ALL USING (sys_tenant = current_setting('ehrbase.current_tenant')::smallint)$$
> ```

That didn't work, unfortunately. With
```sql
EXECUTE format(
  $$CREATE POLICY ehr_policy_all ON ehr.%I FOR ALL USING (sys_tenant = current_setting('ehrbase.current_tenant')::smallint)$$,
  table_name);
````

migrations failed during the Maven build ("Syntax error near CREATE"), and when I added a tag `$fmt$` between the dollar signs, the same migration error as before occured.

**Comment by stefanspiska** [comment]
@jpwiedekopf 
There is a error in the script where it directly references the user  ehrbase.
That seems to be the reason why it fails. see https://github.com/ehrbase/ehrbase/pull/1127
