### ISSUE TITLE
Terminology files not matching specification

### ISSUE THREAD

**Issue by nr23730** [ehrbase/ehrbase#114]
The specification states that `event` instead of `Event` as listed in EHRbase.
See: https://github.com/openEHR/terminology/blob/master/openEHR_RM/en/openehr_terminology.xml#L38
and https://github.com/ehrbase/ehrbase/blob/develop/base/src/main/resources/terminology.xml#L1220

This leads to invalid outputs from ehrBase (AQL and return=representation). However, I changed all occurrences in 19b3796099f9e80ea5a6560bfa61f3157d354b78 but however even with a fresh database it will be always created with an uppercase E. (Update: I had to run `mvn compile` to avoid using an already built V3__terminology.jar file.)

Also: This is not the only inconsistency I saw there. In EHRbase 435 is `laboratory` while the specification says `episodic`. Those things might need to be changed as well. 

In combination with #113 this caused my problems described in #109.

**Comment by ppazos** [comment]
@nr23730 can you clarify what "ehrBase 435 is"?

**Comment by nr23730** [comment]
Sorry, if it was not clear enough. I meant the terminology IDs in specification vs those in EHRbase..

Compare https://github.com/openEHR/terminology/blob/master/openEHR_RM/en/openehr_terminology.xml#L37
with https://github.com/ehrbase/ehrbase/blob/develop/base/src/main/resources/terminology.xml#L1222

**Comment by ppazos** [comment]
@nr23730 the issue is the entry for "episodic" for the composition.category is currently under discussion, I'm not sure why it appeared in the openEHR terminology repository, already asked the question there.

**Comment by freshehr** [comment]
Basically 435:: episodic is there because I jumped the gun on publishing it in the terminology spec.  Can reallocate episodic to another number
