### ISSUE TITLE
Cardinality returning duplicate rows

### ISSUE THREAD

**Issue by manci22lc** [ehrbase/ehrbase#1149]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Environment information

   <ehrbase_version>0.27.4</ehrbase_version>
    <openehr_sdk_version>1.29.0</openehr_sdk_version>
    <archie_version>3.3.0</archie_version>
    <jvm_version>Eclipse Adoptium 17.0.7+7</jvm_version>
    <os_version>Linux amd64 5.10.102.1-microsoft-standard-WSL2</os_version>
    <postgres_version>PostgreSQL 13.4 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20210424) 10.3.1 20210424, 64-bit</postgres_version>

### Steps to reproduce

1. Create template with following content
        a. Content>openEHR-EHR-SECTION.problem_list.v0>items>procedures>openEHR-EHR-ACTION.procedure.v1
        b. Content>openEHR-EHR-ACTION.procedure.v1
2. Change cardinality for problem_list alone(above sub-step a.)
3. There are two data points in problem list and only one data point in procedure, since it has cardinality level 1
4. Run the attached AQL
5. Result retrieved has duplicate entry.

Attaching all relavant templates, compostions and AQL tried
[issue.zip](https://github.com/ehrbase/ehrbase/files/12077561/issue.zip)

### Expected behavior

"rows": [
        [
            "procedure 3",
            "description 3",
            "body site 3"
        ],
        [
            "procedure 1",
            "description 1",
            "body site 1"
        ],
        [
            "procedure 2",
            "description 2",
            "body site 2"
        ]
    ]

### Actual result

"rows": [
        [
            "procedure 3",
            "description 3",
            "body site 3"
        ],
        [
            "procedure 3",
            "description 3",
            "body site 3"
        ],
        [
            "procedure 1",
            "description 1",
            "body site 1"
        ],
        [
            "procedure 2",
            "description 2",
            "body site 2"
        ]
    ]

**Comment by manci22lc** [comment]
Hi Team, any updates on this, or if anyone is facing similar issue can anyone help ?

**Comment by stefanspiska** [comment]
please recheck  with https://github.com/ehrbase/ehrbase/releases/tag/v2.0.0
