### ISSUE TITLE
Different path generated within the web template

### ISSUE THREAD

**Issue by bhaarbrandt** [ehrbase/ehrbase#1163]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Environment information

"ehrbase_version": "0.24.0-SNAPSHOT",
"openehr_sdk_version": "1.24.0-SNAPSHOT",
"archie_version": "2.0.1",
"jvm_version": "Homebrew 19.0.2",
"os_version": "Mac OS X aarch64 13.4",
"postgres_version": "PostgreSQL 13.4 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20210424) 10.3.1 20210424, 64-bit"

### Steps to reproduce

The Template attached contains an element name like the following.

"1. Mein Leben wäre besser, wenn ich bestimmte Dinge besitzen würde, die ich noch nicht habe."

[Template.zip](https://github.com/ehrbase/ehrbase/files/12344506/Template.zip)

### Expected behavior

The resulting paths looks like the following:

"material_value_scale/material_values_scale_g-mvs/any_event:0/**a1**._mein_leben_wäre_besser_wenn_ich_bestimmte_dinge_besitzen_würde_die_ich_noch_nicht_habe.|ordinal": 1,

### Actual result

 "material_value_scale/material_values_scale_g-mvs/any_event:0/mein_leben_wäre_besser_wenn_ich_bestimmte_dinge_besitzen_würde_die_ich_noch_nicht_habe.|ordinal": 1,

### Further information

Please check if the behavior of EHRbase could be aligned with Better.

**Comment by stefanspiska** [comment]
not reproducible on 0.31.0-SNAPSHOT
