### ISSUE TITLE
Deploying to a Cloud Web App

### ISSUE THREAD

**Issue by LuisMateusRibeiro** [ehrbase/ehrbase#1168]
### Background

I'm trying to deploy ehrbase in an azure web app and I seem to struggle with the packaging process

### Task specification

During the web app deployment azure runs a maven clean install which never build successfully not in even locally. I there any documentation or previous attempts?

**Comment by vidi42** [comment]
@LuisMateusRibeiro when building EHRbase, it requires a running postgres to which to connect. Maybe that's why it's failing or are you getting another error?

**Comment by stefanspiska** [comment]
@LuisMateusRibeiro 

There is https://www.linkedin.com/pulse/setting-up-openehr-azure-its-painful-john-meredith

Note that this is for an older version of ehrbase so the statement that "EHRBase requires temporal tables and JSQuery" is no longer correct.

**Comment by LuisMateusRibeiro** [comment]
@vidi42  Thanks for the quick answer. I have a postgres db on azure that I can successfully connect to if I just do a regular maven package locally so I don't think that's my problem

To be more specific the error I get when doing a maven clean package which I inevitably will have to do in order to have a successfully deployment is the following (sorry for the paste):

Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:testCompile (default-testCompile) on project service: Compilation failure: Compilation failure: 
[ERROR] /C:/Users/LuísRibeiro/Projects/ehrbase-control/ehrbase/service/src/test/java/org/ehrbase/service/RecordedDvCodedTextTest.java:[58,74] incompatible types: org.jooq.TableField<org.ehrbase.jooq.pg.tables.records.EventContextRecord,org.ehrbase.jooq.pg.udt.records.DvCodedTextRecord> cannot be converted to org.jooq.Field<DvCodedTextRecord>
[ERROR] /C:/Users/LuísRibeiro/Projects/ehrbase-control/ehrbase/service/src/test/java/org/ehrbase/service/RecordedDvCodedTextTest.java:[77,98] incompatible types: org.jooq.TableField<org.ehrbase.jooq.pg.tables.records.EventContextRecord,org.ehrbase.jooq.pg.udt.records.DvCodedTextRecord> cannot be converted to org.jooq.Field<DvCodedTextRecord>
[ERROR] /C:/Users/LuísRibeiro/Projects/ehrbase-control/ehrbase/service/src/test/java/org/ehrbase/aql/sql/queryimpl/value_field/GenericJsonFieldTest.java:[71,35] incompatible types: org.jooq.TableField<org.ehrbase.jooq.pg.tables.records.EntryRecord,org.ehrbase.jooq.pg.udt.records.DvCodedTextRecord> cannot be converted to org.jooq.Field<DvCodedTextRecord>
[ERROR] /C:/Users/LuísRibeiro/Projects/ehrbase-control/ehrbase/service/src/test/java/org/ehrbase/aql/sql/queryimpl/value_field/GenericJsonFieldTest.java:[88,35] incompatible types: org.jooq.TableField<org.ehrbase.jooq.pg.tables.records.EntryRecord,org.ehrbase.jooq.pg.udt.records.DvCodedTextRecord> cannot be converted to org.jooq.Field<DvCodedTextRecord>
[ERROR] /C:/Users/LuísRibeiro/Projects/ehrbase-control/ehrbase/service/src/test/java/org/ehrbase/aql/sql/queryimpl/value_field/GenericJsonFieldTest.java:[112,35] incompatible types: org.jooq.TableField<org.ehrbase.jooq.pg.tables.records.EntryRecord,org.ehrbase.jooq.pg.udt.records.DvCodedTextRecord> cannot be converted to org.jooq.Field<DvCodedTextRecord>
[ERROR] /C:/Users/LuísRibeiro/Projects/ehrbase-control/ehrbase/service/src/test/java/org/ehrbase/dao/access/jooq/party/PersistedPartyIdentifiedTest.java:[45,72] incompatible types: java.util.List<org.ehrbase.jooq.pg.tables.records.PartyIdentifiedRecord> cannot be converted to java.util.Collection<PartyIdentifiedRecord>
[ERROR] /C:/Users/LuísRibeiro/Projects/ehrbase-control/ehrbase/service/src/test/java/org/ehrbase/dao/access/jooq/party/PersistedPartyRelatedTest.java:[52,26] cannot access PartyIdentifiedRecord
[ERROR]   class file for PartyIdentifiedRecord not found
[ERROR] /C:/Users/LuísRibeiro/Projects/ehrbase-control/ehrbase/service/src/test/java/org/ehrbase/dao/access/jooq/party/PersistedPartyRelatedTest.java:[57,53] incompatible types: inference variable E has incompatible bounds
[ERROR]     equality constraints: PartyIdentifiedRecord
[ERROR]     lower bounds: org.ehrbase.jooq.pg.tables.records.PartyIdentifiedRecord
[ERROR] /C:/Users/LuísRibeiro/Projects/ehrbase-control/ehrbase/service/src/test/java/org/ehrbase/dao/access/jooq/party/PartyIdentifiersTest.java:[44,100] incompatible types: java.util.List<org.ehrbase.jooq.pg.tables.records.PartyIdentifiedRecord> cannot be converted to java.util.Collection<PartyIdentifiedRecord>
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :service

**Comment by LuisMateusRibeiro** [comment]
> @LuisMateusRibeiro
> 
> There is https://www.linkedin.com/pulse/setting-up-openehr-azure-its-painful-john-meredith
> 
> Note that this is for an older version of ehrbase so the statement that "EHRBase requires temporal tables and JSQuery" is no longer correct.

@stefanspiska I saw the same post but I think it's a bit outdated at this point

**Comment by vidi42** [comment]
> To be more specific the error I get when doing a maven clean package which I inevitably will have to do in order to have a successfully deployment is the following (sorry for the paste):

To me it looks like the `jooq-pq` classes are not generated with the latest version, which might cause the issue. Could you try just building `jooq-pq` first and make sure it regenerates the classes?

**Comment by LuisMateusRibeiro** [comment]
@vidi42 running a maven install of that specific package fails on checking the migrations in the postgresql

**Comment by vidi42** [comment]
> @vidi42 running a maven install of that specific package fails on checking the migrations in the postgresql

That's why the classes are not generated and you get the compilation errors then. You might have some older classes in there.
Now you have to figure out why the migrations check is failing in PostgreSQL. Do you have stack traces from jooq?

**Comment by simonFuturePerfect** [comment]
Hi we've been running ehrbase on Azure for a year or so. We use an Azure container instance and we reference the particular ehrbase image from the docker repository. You need to set the docker properties in the configuration area.

Additionally we use Azure PostgresSQL for the database. You do need to run the create database scripts but after that ehrbase take care of the rest. 

I'm not really sure why you need to do the build yourself. I have done that myself before but unless you are altering ehrbase why not just use their deployed images. 

:)

**Comment by LuisMateusRibeiro** [comment]
@simonFuturePerfect  thank you for the response. So you do something like this for deployment? https://learn.microsoft.com/en-us/azure/app-service/quickstart-multi-container and you have a Azure database for Postgres flexible server on the side configured on just the docker-compose?

**Comment by simonFuturePerfect** [comment]
Nope mine is a lot simpler. As we are using Azure Postgres we only have one container. The container is really hidden away by the Azure Container (you could use a Web App). All you do is set the image property to something like ehrbase/ehrbase:0.27.3 the image source to Docker Hub or other registries. The database is just an ordinary JDBC url and you set that in the Environment Variables. 

The tricky thing is that you need to learn Azure Containers and ehrbase docker stuff. You really don't need to be building source code that, as you found out, has its own issues.

**Comment by simonFuturePerfect** [comment]
Don't forget even with Azure Postgres you need to run the database setup as stated above.

**Comment by LuisMateusRibeiro** [comment]
@simonFuturePerfect I currently have a Postgres data base in azure with the setup done that I know works because if I run the docker-compose up locally to that database its fine. But my question is (forgive me if it's very unexperienced but I'm tryin learn as much as possible) if I just call the image from docker hub it wont have my db configurations right? Could you specify more on that?

**Comment by simonFuturePerfect** [comment]
You are confusing a docker image with a docker container. You tell the container what images it is based on (ehrbase/ehrbase:0.27.3)  you also set its properties. Azure calls them Environmental Variables. You need to look at the ehrbase docker properties (its all documented)  and set them. For example the property **DB_URL** is where you set the loacation of the database.

**Comment by LuisMateusRibeiro** [comment]
@simonFuturePerfect you created something like this then?

az container create --resource-group QPARK_POC_AIOPS --name ehrbase-cr-sandbox --image ehrbase/ehrbase:0.27.3 --restart-policy OnFailure --environment-variables DB_URL=jdbc:postgresql://name.postgres.database.azure.com:5432/db DB_USER_ADMIN=user DB_PASS_ADMIN=password DB_USER=user DB_PASS=password

**Comment by LuisMateusRibeiro** [comment]
@simonFuturePerfect  I managed to get it to work but I'm wondering how do you post to the api? There's no indication of the host.

**Comment by simonFuturePerfect** [comment]
Well done. I always use the swagger page to make sure its all running. Mine is a bit like this, I've changed it but the components are the same **https://ehrbase.kindsmoke.azurecontainerapps.io/ehrbase/swagger-ui/index.html**

**Comment by simonFuturePerfect** [comment]
On the Azure web portal you have an overview tab, at the top is the application url, then just add the ehrbase stuff and you have your url for your containerized ehrbase ...

For the logs, I just use the portal.

**Comment by LuisMateusRibeiro** [comment]
@simonFuturePerfect then I must me missing something because the container instance overview doesn't have and application url

![image](https://github.com/ehrbase/ehrbase/assets/47797607/c095bc42-ddc5-4b21-a650-48cffed3d760)

**Comment by simonFuturePerfect** [comment]
uuuurgh apologies but I wasn't quite correct about the container service. Its and Azure Container App **NOT** Azure container instance. In my defence Microsoft are proliferating their types of container. ACI are a lower level use of the container, you need to read up on that too. I think you are best just setting up an App.

Sorry about that.

**Comment by vidi42** [comment]
@LuisMateusRibeiro @simonFuturePerfect I will close now the issue as it seems to not be related to the EHRbase codebase directly.
I hope your discussion however will help whoever stumbles upon this in the future.
