### ISSUE TITLE
AQL doubles time when a cluster is included

### ISSUE THREAD

**Issue by simonFuturePerfect** [ehrbase/ehrbase#1169]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Environment information

Solution	EHRbase
Version	0.28.0-SNAPSHOT
Openehr SDK Version	2.0.0-SNAPSHOT
Archie Version	3.3.0
JVM Version	Eclipse Adoptium 17.0.7+7
OS Version	Linux amd64 5.10.0-24-amd64
PostGres Version	PostgreSQL 13.11 (Debian 13.11-0+deb11u1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit

### Steps to reproduce

{"q":"SELECT c/uid/value AS CompositionId,l/data[at0001]/events[at0002]/data[at0003]/items[at0005]/value/value AS TestName,**l/protocol[at0004]/items[at0094]/items[at0106]/value/value AS ReceiverOrderIdentifier**,l/data[at0001]/events[at0002]/data[at0003]/items[at0073]/value/value AS OverallTestStatus,l/data[at0001]/events[at0002]/data[at0003]/items[at0075]/value/value AS OverallTestStatusTimestamp FROM EHR e[ehr_id/value='******'] CONTAINS COMPOSITION c CONTAINS OBSERVATION l[openEHR-EHR-OBSERVATION.laboratory_test_result.v1] WHERE c/name/value='FP - Generic Lab import' ORDER BY OverallTestStatusTimestamp DESC LIMIT 10 OFFSET 10"}

versus (by removing **ReceiverOrderIdentifier**

{"q":"SELECT c/uid/value AS CompositionId,l/data[at0001]/events[at0002]/data[at0003]/items[at0005]/value/value AS TestName, l/data[at0001]/events[at0002]/data[at0003]/items[at0073]/value/value AS OverallTestStatus,l/data[at0001]/events[at0002]/data[at0003]/items[at0075]/value/value AS OverallTestStatusTimestamp FROM EHR e[ehr_id/value='******'] CONTAINS COMPOSITION c CONTAINS OBSERVATION l[openEHR-EHR-OBSERVATION.laboratory_test_result.v1] WHERE c/name/value='FP - Generic Lab import' ORDER BY OverallTestStatusTimestamp DESC LIMIT 10 OFFSET 10"}

[FP _ Generic Lab Import.txt](https://github.com/ehrbase/ehrbase/files/12429177/FP._.Generic.Lab.Import.txt)

### Expected behavior

Takes 3 seconds

### Actual result

Execution time at least 7 seconds

**Comment by vidi42** [comment]
@simonFuturePerfect there are indeed some AQL queries that are causing the system to slow down when it comes to certain JSONB elements and adding indexes is quite limited in the current data structure that EHRbase uses.

We are aware of these limitations and are doing some refactoring https://discourse.openehr.org/t/index-on-jsonb-column/4182/3?u=vidi42

**Comment by stefanspiska** [comment]
please recheck  with https://github.com/ehrbase/ehrbase/releases/tag/v2.0.0

**Comment by simonFuturePerfect** [comment]
OK will do, I'll let you know how we get on.
