### ISSUE TITLE
AQL issue when selecting content

### ISSUE THREAD

**Issue by rafalszu-ives** [ehrbase/ehrbase#1173]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Environment information

EHRBASE 0.30.0

### Steps to reproduce

I am trying do query some detailed parameters using AQL. I am trying to select by content, like:

`SELECT c FROM EHR e CONTAINS COMPOSITION c WHERE c/content/archetype_node_id = 'openEHR-EHR-SECTION.adhoc.v1'"
`

But: 
`SELECT c FROM EHR e CONTAINS COMPOSITION c WHERE c/archetype_node_id = 'openEHR-EHR-COMPOSITION.health_summary.v1'
` works well.

### Expected behavior

The request above should return the composition filtered by archetype_node_id in content.

### Actual result

Could not process query/stored-query, reason: java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 

### Further information

The excerpt of compositon:

`   },
    "archetype_node_id": "openEHR-EHR-COMPOSITION.health_summary.v1",
    "content": [
        {
              "name": {
                  "value": "History of present illness section",
                  "_type": "DV_TEXT"
              },
              "archetype_node_id": "openEHR-EHR-SECTION.adhoc.v1",
              "_type": "SECTION",
              "items": [
                  {
                      "name": {
                          "value": "History of present illness",
                          "_type": "DV_TEXT"
                      },`

**Comment by stefanspiska** [comment]
@rafalszu-ives 

 Paths with without Archetype_node_id are not supported.

You could do 
 ```
SELECT c FROM EHR e CONTAINS COMPOSITION c WHERE EXISTS c/content[openEHR-EHR-SECTION.adhoc.v1]/archetype_node_id 
```

or

```
SELECT c FROM EHR e CONTAINS COMPOSITION c[ openEHR-EHR-COMPOSITION.health_summary.v1] contains SECTION [openEHR-EHR-SECTION.adhoc.v1]
```

**Comment by vladislavploaia** [comment]
Hello @rafalszu-ives,

Could you please check latest comment provided by @stefanspiska and let us know if you still have any other questions?
Thank you in advance.

CC: @vidi42

**Comment by rafalszu-ives** [comment]
> @rafalszu-ives
> 
> Paths with without Archetype_node_id are not supported.
> 
> You could do
> 
> ```
> SELECT c FROM EHR e CONTAINS COMPOSITION c WHERE EXISTS c/content[openEHR-EHR-SECTION.adhoc.v1]/archetype_node_id 
> ```
> 
> or
> 
> ```
> SELECT c FROM EHR e CONTAINS COMPOSITION c[ openEHR-EHR-COMPOSITION.health_summary.v1] contains SECTION [openEHR-EHR-SECTION.adhoc.v1]
> ```

Dear Stefan,

I have tried the first query. The response from ehr is 200, but with empty body. In logs I have:

ERROR:  column "/content[openEHR-EHR-SECTION.adhoc.v1]/archetype_node_id" does not exist at character 305

However, SELECT c FROM EHR e CONTAINS COMPOSITION c WHERE EXISTS c/content[openEHR-EHR-SECTION.adhoc.v1] is working.

And about second proposition:
SELECT c FROM EHR e CONTAINS COMPOSITION c[ openEHR-EHR-COMPOSITION.health_summary.v1] contains SECTION [openEHR-EHR-SECTION.adhoc.v1]
It seems to be ok, but I still have to test it for querying content data.

**Comment by stefanspiska** [comment]
please recheck  with https://github.com/ehrbase/ehrbase/releases/tag/v2.0.0
