### ISSUE TITLE
Web template POST REST request always returns error: Content is not allowed in prolog.

### ISSUE THREAD

**Issue by jorgejesus** [ehrbase/ehrbase#1215]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Environment information

ehrbase_version=0.31.0
openehr_sdk_version>2.3.0
archie_version=3.3.0
jvm_version=Eclipse Adoptium 17.0.9+9
os_version=Linux amd64 6.1.0-1025-oem
postgres_version=PostgreSQL 13.4 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20210424) 10.3.1 20210424, 64-bit

### Steps to reproduce

Using the web-template on RTD:  https://ehrbase.readthedocs.io/en/latest/08_flat/00_description/index.html#web-template and saved as web_template.json.

```
docker compose up -d

curl -v -u ehrbase-user:SuperSecretPassword 'http://localhost:8080/ehrbase/rest/ecis/v1/template' -H 'Accept: application/json' -H 'Content-Type: Application/json' -d @web_template.json

*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
* Server auth using Basic with user 'ehrbase-user'
> POST /ehrbase/rest/ecis/v1/template HTTP/1.1
> Host: localhost:8080
> Authorization: Basic ZWhyYmFzZS11c2VyOlN1cGVyU2VjcmV0UGFzc3dvcmQ=
> User-Agent: curl/7.81.0
> Accept: application/json
> content-Type: Application/json
> Content-Length: 3124
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 
< Vary: Origin
< Vary: Access-Control-Request-Method
< Vary: Access-Control-Request-Headers
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 0
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Pragma: no-cache
< Expires: 0
< X-Frame-Options: DENY
< Content-Type: application/json
< Transfer-Encoding: chunked
< Date: Thu, 16 Nov 2023 09:17:09 GMT
< Connection: close
< 
* Closing connection 0
{"error":"Bad Request","message":"error: Content is not allowed in prolog."}%   
```

[web_template.json](https://github.com/ehrbase/ehrbase/files/13375606/web_template.json)

### Expected behavior

Expected a HTTP 200 and `TemplatesResponseData` Json

### Actual result

```* Mark bundle as not supporting multiuse
< HTTP/1.1 400 
< Vary: Origin
< Vary: Access-Control-Request-Method
< Vary: Access-Control-Request-Headers
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 0
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Pragma: no-cache
< Expires: 0
< X-Frame-Options: DENY
< Content-Type: application/json
< Transfer-Encoding: chunked
< Date: Thu, 16 Nov 2023 09:17:09 GMT
< Connection: close
< 
* Closing connection 0
{"error":"Bad Request","message":"error: Content is not allowed in prolog."}
```

### Further information

Tested several webtemplates found online or in ehrbase tickets and always got the same error message. 

Increasing the error logging on [docker-entrypoint.sh](ttps://github.com/ehrbase/ehrbase/blob/develop/.docker_scripts/docker-entrypoint.sh) with java flags (java -Dspring.profiles.active=docker -Dlogging.level.org.ehrbase=DEBUG -Dlogging.level.org.springframework=DEBUG -jar ehrbase.jar) only reports the same error, without extra information. 

Using Curl or Swagger UI the error is the same. Also escaping the json doesn't solve the problem.

Can some one add to this issue a web_template that is certain to work ?!

**Comment by stefanspiska** [comment]
@jorgejesus 
webtemplate  is a read only format

You can only create new templates using the opt format which is xml  based.  
For example https://github.com/ehrbase/openEHR_SDK/tree/develop/test-data/src/main/resources/operationaltemplate

**Comment by jorgejesus** [comment]
Dear @stefanspiska  

Thank you for the fast reply and information.  So I can only POST new templates using the below REST end point and opt format.

`/rest/openehr/v1/definition/template/{adl1.4/adl2}`

**Comment by stefanspiska** [comment]
@jorgejesus 
Yes. But only adl1.4 is supported.

**Comment by jorgejesus** [comment]
@stefanspiska  thank you I am closing the ticket as it was not a real bug
