### ISSUE TITLE
[API] Upload template gives 401 Unauthorized if Accept header is application/json

### ISSUE THREAD

**Issue by ppazos** [ehrbase/ehrbase#1251]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Environment information

JDK 11
Last docker-composer

### Steps to reproduce

```
curl --request POST \
  --url http://localhost:8080/ehrbase/rest/openehr/v1/definition/template/adl1.4 \
  --header 'Accept: application/json' \
  --header 'Authorization: Basic ZWhyYmFzZS11c2VyOlN1cGVyU2VjcmV0UGFzc3dvcmQ=' \
  --header 'Content-Type: application/xml' \
  --cookie JSESSIONID=41E34F2B245877C78AD9D03A1276B371 \
  --data '____PASTE_OPT_HERE____'
```

### Expected behavior

If the Accept content type is not supported, something like 406 Not Acceptable should be returned.

### Actual result

401 Unauthorized is returned, but that status has nothing to do with EHRBASE not supporting the content type in the Accept header.

Also found an inconsistency: when uploading the same template twice and the second response is 409 Conflict, it actually returns a JSON response, which kinds of contradicts not supporting an Accept: application/json header. If the endpoint returns JSON, then the Accept:application/json should be accepted. Otherwise the error object should be serialized in another format, like application/xml instead of JSON.

```
{
	"error": "Conflict",
	"message": "Operational template with this template ID already exists: RIPPLE - Conformance Test template"
}
```

### Further information

Note: the inconsistency for the response content type happens when there is a Prefer: return=representation header in the request. If that is not in the request, then the response error is XML.

**Comment by vladislavploaia** [comment]
Tested on EHRBase version 2.12.0-SNAPSHOT.
Should be available in https://github.com/ehrbase/ehrbase/releases/tag/v2.11.0 as well.
@ppazos - Could you please check in latest released version and let me know if you still get any errors.
![Image](https://github.com/user-attachments/assets/bda8c265-7846-4afa-b1b5-3eac160c8486)

Thanks in advance!

**Comment by ppazos** [comment]
@vladislavploaia I stopped working in ehrbase about three years ago.
