### ISSUE TITLE
Composer and start time not updated on PUT composition

### ISSUE THREAD

**Issue by grantforrester-nes** [ehrbase/ehrbase#131]
Composer.name and start_time.value are not updated by PUT Composition request.

**Steps To Reproduce**
- POST a composition with:
  - start_time.value : `“2019-12-22T16:56:35.000Z”`
  - composer.name:  `“John Smith”`
- PUT a new version of the composition with:
  - start_time.value : `“2020-01-01T10:10:10.000Z”`
  - composer.name:  `“Jane Smith”`
- GET the new version of the composition.
- Check the values of:
  - start_time.value, and
  - composer.name

**Expected Result**
- start_time.value : `“2020-01-01T10:10:10.000Z”`
- composer.name:  `“Jane Smith”`

**Actual Result**
- start_time.value : `“2019-12-22T16:56:35.000Z”`
- composer.name:  `“John Smith”`

**Environment**
- Reproduced on EHRBase v0.9 and v0.10
- MacOS 10.14.6 (Mojave), Java 8, ehrbaseorg/ehrbase-database-docker:11.5

**Comment by chevalleyc** [comment]
Hi Grant, I have pushed a PR (https://github.com/ehrbase/ehrbase/pull/137) with the changes fixing this issue. Could you check it out?

**Comment by grantforrester-nes** [comment]
Hi Christian,

I have done some quick testing of the branch and the issue looks resolved 👍

**Comment by Geisterfalle** [comment]
Resolved by https://github.com/ehrbase/ehrbase/pull/137
