### ISSUE TITLE
Create database fails on Azure Postgres Flexi Server

### ISSUE THREAD

**Issue by simonFuturePerfect** [ehrbase/ehrbase#1317]
### Background

When setting up the script line

ALTER FUNCTION jsonb_path_query(jsonb,jsonpath,jsonb,boolean) ROWS 1

Fails because the function's owner is 'azuresu' as this is a PAAS only Microsoft have access to the 'Super User Account'

Is there any other way around this ?

### Enhancement

Is it possible to have a SQL script that does not require these elevated privileges ?

**Comment by stefanspiska** [comment]
You can remove 

`ALTER FUNCTION jsonb_path_query(jsonb,jsonpath,jsonb,boolean) ROWS 1`

since it is just a minor optimization.

**Comment by simonFuturePerfect** [comment]
Thank for that @stefanspiska your swift feedback is very much appreciated.

**Comment by simonFuturePerfect** [comment]
I would close this ticket. Any other issues I can raise separately.

Thanks for all the help.
