### ISSUE TITLE
Create EHR REST Endpoint Erroring

### ISSUE THREAD

**Issue by SamPIngram** [ehrbase/ehrbase#1318]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Environment information

Issue seen on DockerHub versions: 2.0.0, 2.1.0 and next.

### Steps to reproduce

1. Going to http://localhost:8080/ehrbase/swagger-ui/index.html?
3. Attempting to run post at /rest/openehr/v1/ehr to Create EHR
5. Tried the default request body data and the one in the [tutorial](https://docs.ehrbase.org/docs/EHRbase/openEHR-Introduction/Create-EHR) both fail.

### Expected behavior

"ehr_id": {
  "value": "7d44b88c-4199-4bad-97dc-d78268e01398"
}

### Actual result

{
  "error": "Bad Request",
  "message": "Could not resolve subtype of [simple type, class com.nedap.archie.rm.RMObject]: missing type id property '_type'\n at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 505]"
}

### Further information

Apologies if I have overlooked something simple, but appreciate any help to resolve this issue.

**Comment by vidi42** [comment]
@SamPIngram it seems the text in the tutorial is not properly formulated, so that's where the confusion comes from.

You would need to use the payload from here https://specifications.openehr.org/releases/ITS-REST/latest/ehr.html#tag/EHR, however, this won't work until you also add the `"_type": "EHR_STATUS"`, because EHRbase is more restricted in that regards.

This will be your payload then:

```JSON
{
	"archetype_node_id": "openEHR-EHR-EHR_STATUS.generic.v1",
	"name": {
		"value": "EHR status"
	},
	"uid": {
		"_type": "OBJECT_VERSION_ID",
		"value": "8849182c-82ad-4088-a07f-48ead4180515::openEHRSys.example.com::1"
	},
	"subject": {
		"_type": "PARTY_SELF"
	},
	"is_queryable": true,
	"is_modifiable": true,
	"_type": "EHR_STATUS"
}

Thanks for pointing it out, we will update the documentation to make it more clear.
```

**Comment by SamPIngram** [comment]
@vidi42 thanks for the quick response. That is much clearer and it works.
