### ISSUE TITLE
ORDER BY Alias causes AQL Parser Error

### ISSUE THREAD

**Issue by simonFuturePerfect** [ehrbase/ehrbase#1322]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Environment information

<ehrbase_version>2.1.0</ehrbase_version>
    <openehr_sdk_version>2.10.0</openehr_sdk_version>
    <archie_version>3.3.0</archie_version>
    <jvm_version>Eclipse Adoptium 21.0.3+9-LTS</jvm_version>
    <os_version>Linux amd64 5.15.153.1-2.cm2</os_version>
    <postgres_version>PostgreSQL 13.14 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, 64-bit</postgres_version>

### Steps to reproduce

**OverallTestStatusTimestamp** is the alias that causes the query to fail.

{"q":"SELECT c/uid/value AS CompositionId,l/data[at0001]/events[at0002]/data[at0003]/items[at0005]/value/value AS TestName,y/items[at0034]/value/value AS SpecimenDateTimeRecieved,l/data[at0001]/events[at0002]/data[at0003]/items[at0073]/value/value AS OverallTestStatus,l/data[at0001]/events[at0002]/data[at0003]/items[at0075]/value/value AS OverallTestStatusTimestamp,y/items[at0029]/value/value AS SpecimenType FROM EHR e[ehr_id/value='ee76c5c1-2fd7-472d-9e04-5fb65e9af041'] CONTAINS COMPOSITION c CONTAINS OBSERVATION l[openEHR-EHR-OBSERVATION.laboratory_test_result.v1] CONTAINS (CLUSTER r[openEHR-EHR-CLUSTER.laboratory_test_analyte.v1] OR CLUSTER y[openEHR-EHR-CLUSTER.specimen.v1]) WHERE c/name/value='FP - Generic Lab import' ORDER BY OverallTestStatusTimestamp DESC LIMIT 5OFFSET 0 "}

### Expected behavior

Query to parse and then execute. Query works correctly on old EHRbase 

### Actual result

{
  "error": "Bad Request",
  "message": "Could not parse AQL query: Cannot parse SELECT c/uid/value AS CompositionId,l/data[at0001]/events[at0002]/data[at0003]/items[at0005]/value/value AS TestName,y/items[at0034]/value/value AS SpecimenDateTimeRecieved,l/data[at0001]/events[at0002]/data[at0003]/items[at0073]/value/value AS OverallTestStatus,l/data[at0001]/events[at0002]/data[at0003]/items[at0075]/value/value AS OverallTestStatusTimestamp,y/items[at0029]/value/value AS SpecimenType FROM EHR e[ehr_id/value='**********'] CONTAINS COMPOSITION c CONTAINS OBSERVATION l[openEHR-EHR-OBSERVATION.laboratory_test_result.v1] CONTAINS (CLUSTER r[openEHR-EHR-CLUSTER.laboratory_test_analyte.v1] OR CLUSTER y[openEHR-EHR-CLUSTER.specimen.v1]) WHERE c/name/value='FP - Generic Lab import' ORDER BY OverallTestStatusTimestamp DESC LIMIT 5OFFSET 0 : unknown FROM alias 'OverallTestStatusTimestamp'"
}

### Further information

(work around) Query works correctly when the alias is removed and the full path is used instead

**Comment by vidi42** [comment]
@simonFuturePerfect since version 2.0.0, aliases are only supported in the SELECT clause and no longer in `WHERE` or `ORDER BY`.
Might be added in the future as we are enhancing the new AQL engine, but for now I suggest you use the whole identified path in `WHERE` or `ORDER BY`

**Comment by simonFuturePerfect** [comment]
> @simonFuturePerfect since version 2.0.0, aliases are only supported in the SELECT clause and no longer in `WHERE` or `ORDER BY`. Might be added in the future as we are enhancing the new AQL engine, but for now I suggest you use the whole identified path in `WHERE` or `ORDER BY`
