### ISSUE TITLE
EHRBase 2 - Error when posting composition

### ISSUE THREAD

**Issue by steveFuturePerfect** [ehrbase/ehrbase#1323]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Environment information

<?xml version='1.0' encoding='UTF-8'?>
  <status>
    <ehrbase_version>2.1.0</ehrbase_version>
    <openehr_sdk_version>2.10.0</openehr_sdk_version>
    <archie_version>3.3.0</archie_version>
    <jvm_version>Eclipse Adoptium 21.0.3+9-LTS</jvm_version>
    <os_version>Linux amd64 5.15.153.1-2.cm2</os_version>
    <postgres_version>PostgreSQL 13.14 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, 64-bit</postgres_version>
  </status>

### Steps to reproduce

Attached composition submitted against attached template
POST /rest/openehr/v1/ehr/{ehr_id}/composition API
[FP - Generic Lab import.json](https://github.com/ehrbase/ehrbase/files/15376580/FP.-.Generic.Lab.import.json)
[ehrbase_2_composition.txt](https://github.com/ehrbase/ehrbase/files/15376538/ehrbase_2_composition.txt)

### Expected behavior

Composition to be submitted successfully, and a uid returned

### Actual result

{
    "error": "Bad Request",
    "message": "Could not consume Parts [fp_-_generic_lab_import/laboratory_test_result/any_event:0/laboratory_analyte_result:0/analyte_result/coded_text_value|value, fp_-_generic_lab_import/laboratory_test_result/any_event:0/laboratory_analyte_result:0/analyte_result/coded_text_value|code, fp_-_generic_lab_import/laboratory_test_result/any_event:0/laboratory_analyte_result:0/analyte_result/coded_text_value|terminology]"
}

### Further information

Remove the 3 lines from the composition and the submission is successful

**Comment by vladislavploaia** [comment]
Hello @steveFuturePerfect,
Could you please provide template content in OPT format (if file with .opt extension is not possible to attach here, save it as txt file)?
Thank you in advance.
CC: @vidi42

**Comment by steveFuturePerfect** [comment]
Hi ,

OPT file attached.

Many thanks

Steve
________________________________

**Comment by vladislavploaia** [comment]
@steveFuturePerfect - seems that it didn't work with .opt extension.
Please add it in .txt file and attach here.
Thanks!

**Comment by steveFuturePerfect** [comment]
Attached,

Thanks

Steve
________________________________

**Comment by vladislavploaia** [comment]
@steveFuturePerfect - even though you've attached template content, it is still incomplete, as shown in below image:
![image](https://github.com/ehrbase/ehrbase/assets/100927963/ba64cbc1-a409-4549-a9fb-28699dce9448)
These are the last lines of the template file, so, it seems to be corrupted.
Add the template content in .txt file and then attach it to bug description.
I hope that it will allow to do so.

**Comment by steveFuturePerfect** [comment]
Hi,

Not sure what's wrong, its all valid XML. I've re-attached the file (xml format), as a txt file.

Hopefully that'll be ok for you.

Thanks

Steve
________________________________

**Comment by steveFuturePerfect** [comment]
[FP - Generic Lab import.zip](https://github.com/ehrbase/ehrbase/files/15377420/FP.-.Generic.Lab.import.zip)

**Comment by steveFuturePerfect** [comment]
Hi,

Template has been zipped and placed in bug description

Steve


________________________________

**Comment by vladislavploaia** [comment]
@steveFuturePerfect - I cannot reproduce the bug, based on your attached composition and template.
In my case, I was able to commit successfully the composition (201 Created).
![image](https://github.com/ehrbase/ehrbase/assets/100927963/fa0f5286-7861-4873-92dd-5d83480cda42)
![image](https://github.com/ehrbase/ehrbase/assets/100927963/30337175-8742-470c-b12e-804f6db85932)
Here are the API calls sent:
POST http://localhost:8080/ehrbase/rest/openehr/v1/ehr/4c575bd9-3c8d-4bc8-aa31-c6640b43f74a/composition?format=FLAT&templateId=FP%20-%20Generic%20Lab%20import
and
POST http://localhost:8080/ehrbase/rest/ecis/v1/composition?ehrId=4c575bd9-3c8d-4bc8-aa31-c6640b43f74a&templateId=FP%20-%20Generic%20Lab%20import&format=FLAT
-
EHRBase 2.2.0-SNAPSHOT
openEHR_SDK: 2.11.0-SNAPSHOT
postgresql: 42.7.3
-
Please check one more time with latest versions and let me know if issue persists, otherwise I will close current ticket.
Thanks!

**Comment by steveFuturePerfect** [comment]
We are running version 2.1. Version 2.2 doesn't appear to be available on the Ehrbase Github. Are you able to confirm that the composition submission is still successful with 2.1?

Thanks

**Comment by vladislavploaia** [comment]
@steveFuturePerfect,
Checked as well on the released EHRbase v2.1.0 from [here](https://github.com/ehrbase/ehrbase/releases/tag/v2.1.0) and it is not reproducible.
201 Created in both cases.
POST http://localhost:8080/ehrbase/rest/ecis/v1/composition?ehrId=f66b7fbc-15f0-49c6-ac4f-0536c8a360c9&templateId=FP - Generic Lab import&format=FLAT
POST http://localhost:8080/ehrbase/rest/openehr/v1/ehr/f66b7fbc-15f0-49c6-ac4f-0536c8a360c9/composition?format=FLAT&templateId=FP - Generic Lab import
[issue-1323-evidence.zip](https://github.com/ehrbase/ehrbase/files/15378663/issue-1323-evidence.zip)
EHRBase 2.1.0, openEHR_SDK 2.10.0, postgresql 42.7.3

Please check your setup one more time and let me know in case I could support you with something else.

**Comment by steveFuturePerfect** [comment]
This is puzzling us. We are still unable to successfully submit our composition, in Ehrbase 2.1 with the error reported earlier. Are you able to advise, looking at the template and composition, what might be causing our issue?

Many thanks

Steve

**Comment by vidi42** [comment]
@steveFuturePerfect we've opened an internal ticket for further investigation by the dev team since we were not able to reproduce it yet.

**Comment by sidharthramesh** [comment]
@ATHULKNAIR @neutralboy we may want to verify this on our side as well. Please check if it’s reproduce.

**Comment by steveFuturePerfect** [comment]
Hi

We've resolved the issue. It turns out we were using an old version of our template, while the template I sent to you was the up-to-date version, hence your successful testing, and not reproducing the issue. 

Apologies, and thanks for all your help

Steve
