### ISSUE TITLE
Versioned Objects and datetime queries

### ISSUE THREAD

**Issue by steveFuturePerfect** [ehrbase/ehrbase#1349]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Environment information

Solution EHRbase
Version 2.1.0
Openehr SDK Version 2.10.0
Archie Version 3.3.0
JVM Version Eclipse Adoptium 21.0.3+9-LTS
OS Version Linux amd64 5.15.153.1-2.cm2
PostGres Version PostgreSQL 13.14 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, 64-bit

### Steps to reproduce

I would like to be able to query my CDR to return all compositions submitted in the last week, month...

This can be done in a Better CDR:

_SELECT vo/uid/value, vo/time_created, v/uid/value, v/commit_audit/time_committed FROM EHR e CONTAINS VERSIONED_OBJECT vo CONTAINS VERSION v CONTAINS COMPOSITION c
WHERE vo/time_created > "2023-03-23"_

### Expected behavior

Composition uids returned that meet the date criteria

### Actual result

_{
    "error": "Bad Request",
    "message": "Type VERSIONED_OBJECT is not supported in FROM, only: EHR, CONTENT_ITEM, ENTRY, CARE_ENTRY, EVENT, ITEM_STRUCTURE, ITEM, COMPOSITION, FOLDER, EHR_STATUS, EVENT_CONTEXT, SECTION, GENERIC_ENTRY, ADMIN_ENTRY, OBSERVATION, INSTRUCTION, ACTION, EVALUATION, ACTIVITY, HISTORY, POINT_EVENT, INTERVAL_EVENT, FEEDER_AUDIT, ITEM_LIST, ITEM_SINGLE, ITEM_TABLE, ITEM_TREE, CLUSTER, ELEMENT"
}_

### Further information

This is a typical 'bring me back a list of compositions submitted in the last week, month...' 

Is there a workaround for this type of AQL query, apart from bringing back every single versioned composition through the API, to pick out the audit/time_committed/value?

Thanks

**Comment by stefanspiska** [comment]
@steveFuturePerfect 
Just leave out `VERSIONED_OBJECT `

```
SELECT  e/ehr_id/value,
  c/archetype_details/template_id/value,
  cv/uid/value,
  cv/commit_audit/time_committed/value
	FROM EHR e
  CONTAINS VERSION cv[LATEST_VERSION]
  CONTAINS COMPOSITION c
where
	 cv/commit_audit/time_committed >= '2024-05-30T13:58:02.120967+02:00' 
ORDER BY
  cv/commit_audit/time_committed
```

**Comment by stefanspiska** [comment]
@steveFuturePerfect 

please note that there is currently a resection on the Aql -engine that is only sees the newest Version of each composition.
