### ISSUE TITLE
Default values for is_queryable & is_modifiable when creating EHR

### ISSUE THREAD

**Issue by dileep-ehr** [ehrbase/ehrbase#1353]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Environment information

<status>
    <ehrbase_version>2.3.0</ehrbase_version>
    <openehr_sdk_version>2.12.0</openehr_sdk_version>
    <archie_version>3.3.0</archie_version>
    <jvm_version>Eclipse Adoptium 21.0.3+9-LTS</jvm_version>
    <os_version>Linux amd64 6.5.0-1022-azure</os_version>
    <postgres_version>PostgreSQL 16.3 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20240309) 13.2.1 20240309, 64-bit</postgres_version>
</status>

### Steps to reproduce

Create EHR (POST https://{baseUrl}/v1/ehr) with out is_queryable & is_modifiable. The EHR is created with default values as "false". 

This is troublesome as the EHRs do not allow addition of compositions with out updating the EHR_STATUS

### Expected behavior

OpenEHR REST documentation mentions them as required and default values as 'true". So the behaviour should be

1. option1 - make them mandatory so that the user is forced to provide the correct values
2. option2 - If the user does not provide, make the default behaviour as "true"

### Actual result

 EHR created with default values for is_queryable & is_modifiable as false

**Comment by alexlehn** [comment]
@dileep-ehr It was a little bit more work then expected, but it's now fixed in the upcoming version (`2.7.0`). You can test the fix using the current develop branch or by using the image `ehrbase/ehrbase:next`.

**Comment by dileep-ehr** [comment]
Thanks. Will take a look

Reg
