### ISSUE TITLE
Posting a composition with id does not work when using flat or structured formats.

### ISSUE THREAD

**Issue by robahs** [ehrbase/ehrbase#1368]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Environment information

{
    "ehrbase_version": "2.0.0",
    "openehr_sdk_version": "2.9.1",
    "archie_version": "3.3.0",
    "jvm_version": "Eclipse Adoptium 21.0.2+13-LTS",
    "os_version": "Linux amd64 5.15.153.1-microsoft-standard-WSL2",
    "postgres_version": "PostgreSQL 16.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20231014) 13.2.1 20231014, 64-bit"
}

### Steps to reproduce

Post a new composition with uid set using the official openEHR REST-api with FLAT or STRUCTURED format.

### Expected behavior

The composition should be created with the given uid.

### Actual result

 o.e.c.exception.DefaultExceptionHandler  : Provided Id 1fe56016-7137-4117-b49b-60ae0319fb84::local.fancy.cdr::1 is not a ObjectVersionId

### Further information

Posting with a uid set works as expected when using the canonical json format, but not when using flat or structured

**Comment by robahs** [comment]
I have attached some curl examples. You need to change host, ehr_id and authentication headers to make them work.

[examples.zip](https://github.com/user-attachments/files/16067736/examples.zip)

**Comment by vladislavploaia** [comment]
Hello @robahs,
Issue reported internally.
Once I get any updates about it, I will let you know.

**Comment by alexlehn** [comment]
Hello @robahs a fix for this issue is available in the current develop branch or using the docker image `ehrbase/ehrbase:next`.

**Comment by alexlehn** [comment]
Fixed in [v2.6.0 ](https://github.com/ehrbase/ehrbase/releases/tag/v2.6.0)
