### ISSUE TITLE
500 internal server error on get on a non-existing composition

### ISSUE THREAD

**Issue by dileep-ehr** [ehrbase/ehrbase#1382]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Environment information

<status>
    <ehrbase_version>2.6.0</ehrbase_version>
    <openehr_sdk_version>2.15.0</openehr_sdk_version>
    <archie_version>3.3.0</archie_version>
    <jvm_version>Eclipse Adoptium 21.0.4+7-LTS</jvm_version>
    <os_version>Linux amd64 6.5.0-1024-azure</os_version>
    <postgres_version>PostgreSQL 16.3 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20240309) 13.2.1 20240309, 64-bit</postgres_version>
</status>

### Steps to reproduce

Try to retrieve a composition using a non-existing id

### Expected behavior

Should respond with not found

### Actual result

{
    "error": "Internal Server Error",
    "message": "An internal error has occurred. Please contact your administrator."
}

**Comment by vladislavploaia** [comment]
Hello @dileep-ehr,
Could you please provide the REST API call you've sent?
I checked the Get Composition by non-existing id and it's returning 404 Not Found.
![image](https://github.com/user-attachments/assets/dc3723f9-2978-42a5-a640-7ce2488b1839)

Thank you!

**Comment by dileep-ehr** [comment]
@vladislavploaia Sorry about the confusion. I am trying the GET FLAT format API

curl --location '{{baseUrl}}/ehrbase/rest/ecis/v1/composition/a72d6f90-65dc-4282-99cc-59c2ae0af7cd?format=FLAT' \
--header 'Accept: application/json'
![get_flat](https://github.com/user-attachments/assets/9148e906-1d2b-44d0-86c1-0ead86eec513)

**Comment by dileep-ehr** [comment]
@vladislavploaia Thanks. That works. 

Does that mean the other CRUD APIs for FLAT have also changed? Can you direct me to the APIdocs for the new FLAT composition APIs?

**Comment by vladislavploaia** [comment]
@dileep-ehr - it's based on openEHR REST API latest specifications.
For instance, on Get Composition: https://specifications.openehr.org/releases/ITS-REST/latest/ehr.html#tag/COMPOSITION/operation/composition_get
I know that mentions about FLAT are missing in openEHR REST API, however, you can take a look at the Swagger UI definitions:
http://localhost:8080/ehrbase/swagger-ui/index.html?urls.primaryName=1.+openEHR+API#/COMPOSITION/getComposition
Mainly, it's about **format** request parameter and **Accept** header you are sending, to send/receive content in FLAT format.

**Comment by dileep-ehr** [comment]
Thanks

**Comment by dileep-ehr** [comment]
@vladislavploaia Sorry for reopening this. If the ecis paths are being depreciated, what are the new paths for the following

1. Get web template - /ehrbase/rest/ecis/v1/template/:templateId
2. Get FLAT example - /ehrbase/rest/ecis/v1/template/:template_id/example?format=FLAT&exampleFilter=INPUT

There does not seem to be anything in the openEHR REST specs covering this

**Comment by vladislavploaia** [comment]
Hello @dileep-ehr,
For endpoints mentioned, we have the following:
![image](https://github.com/user-attachments/assets/19626c1a-f96a-433e-a091-b2f442281b1c)
![image](https://github.com/user-attachments/assets/4e17bd9a-80cc-4221-b55d-a682dc83e9d4)
For Get an example composition for the specified template, **format** parameter can be send with (FLAT|JSON|XML|STRUCTURED)
You can use them and achieve the same as you've got previously with ecis paths.

**Comment by dileep-ehr** [comment]
Thanks


Dileep V S
*Founder*
HealtheLife Ventures LLP
m: +91 79756 70933
a: No.39, 2nd Floor, NGEF Lane,  Indiranagar first stage, Bangalore 560038
w: <http://ayushehr.com>ehr.network, <http://ehr.network>ayushehr.com
<http://ayushehr.com> e: ***@***.***
-------------------------------------------------------------------------------
“IMPORTANT: The contents of this email and any attachments are
confidential. They are intended for the named recipient(s) only. If you
have received this email by mistake, please notify the sender immediately
and do not disclose the contents to anyone or make copies thereof”

**Comment by vladislavploaia** [comment]
Hello @dileep-ehr,
What do you mean by "none of the options seems to match with...?"
**GET ADL 1.4 Template** is following what is specified in openEHR REST Specifications: https://specifications.openehr.org/releases/ITS-REST/Release-1.0.3/definition.html#tag/ADL1.4/operation/definition_template_adl1.4_get, meaning, you can use **Accept** header to return template in different formats:
1. application/xml
2. application/json
3. application/openehr.wt+json
4. text/plain - with this one, returns 406 Not Acceptable but will be reported in separate ticket.
![image](https://github.com/user-attachments/assets/35c01476-6feb-4ef4-9f2f-e1501a871bde)

BTW, 500 Internal Server Error was fixed for curl --location '{{baseUrl}}/ehrbase/rest/ecis/v1/composition/a72d6f90-65dc-4282-99cc-59c2ae0af7cd?format=FLAT' --header 'Accept: application/json'
![image](https://github.com/user-attachments/assets/a71b3371-4c9e-4571-a6d8-00711e6394da)


Fix will be available in next release of **EHRBase with version 2.7.0** or you can take the current version from [develop](https://github.com/ehrbase/ehrbase/tree/develop) branch.
Current ticket closed.
Feel free to open new ones if there are any problems or enhancements. Thank you!
CC: @vidi42
