### ISSUE TITLE
Get deleted composition returns empty composition and doe snot indicate that it is deleted

### ISSUE THREAD

**Issue by dileep-ehr** [ehrbase/ehrbase#1383]
### Background

Currently when we do a GET on a deleted composition, the API returns 204 and an empty body. The response does not give any indication that the composition has been deleted. 

### Enhancement

Response should carry a body containing the versioned compositionId, along with lifecycle_state=deleted

**Comment by vladislavploaia** [comment]
Hello @dileep-ehr,
204 No Content is the indication that composition with corresponding version_id was deleted.
![image](https://github.com/user-attachments/assets/d053d1c8-551f-40da-a784-9ea85bfb59d4)
https://specifications.openehr.org/releases/ITS-REST/latest/ehr.html#tag/COMPOSITION/operation/composition_get

Once you have provided the composition UID in API call, you already know what is its value, so, not sure if worth to duplicate it in response body, but will check with the team.
CC: @vidi42, @HolgerReiseVSys

**Comment by dileep-ehr** [comment]
Thanks @vladislavploaia . I can see that the implementation is as per the official REST specs. 

However, I still feel that explicit deleted indication will be useful. But that may need a change in specs

**Comment by vladislavploaia** [comment]
@dileep-ehr - As previously said, we are returning 204 No Content as per REST API specifications.
The 204 response must not include a message body. See HTTP/1.1 specification (RFC 7231), https://datatracker.ietf.org/doc/html/rfc7231#section-6.3.5
You have already the composition UID for which you made the call, no need to duplicate it in body somehow.
Please let me know if you still have any questions / concerns about it.
CC: @vidi42 , @alexlehn
