### ISSUE TITLE
Unable to pass an array as a variable in AQL for WHERE ..... MATCHES

### ISSUE THREAD

**Issue by dileep-ehr** [ehrbase/ehrbase#1384]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Environment information

2.6.0 2.15.0 3.3.0 Eclipse Adoptium 21.0.4+7-LTS Linux amd64 6.5.0-1024-azure PostgreSQL 16.3 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20240309) 13.2.1 20240309, 64-bit 

### Steps to reproduce

Execute the following query. The need is to pass an array of strings as an input to the query using $hiTypeArray variable
`{
    "q": "SELECT c1/uid/value as uid, c4/items[at0009]/items[at0010]/value/value as encounterId, c4/items[at0014]/items[at0016]/value/value as hiType FROM EHR e CONTAINS COMPOSITION c1 CONTAINS CLUSTER c4[openEHR-EHR-CLUSTER.ehrn_metadata.v1] WHERE c4/items[at0009]/items[at0010]/value/value MATCHES {$EncounterIdArray} and c4/items[at0014]/items[at0016]/value/value MATCHES {$hiTypeArray}",
    "offset": 0,
    "fetch": 10,
    "query_parameters": {
        "EncounterIdArray": "Encounter/ee2c037d-c499-4aa0-9097-03f6c7e7aa74",
        "hiTypeArray": "Prescription, DischargeSummary"
    }
}
`
The actual executed query is 
`  "_executed_aql": "SELECT c1/uid/value AS uid, c4/items[at0009]/items[at0010]/value/value AS encounterId, c4/items[at0014]/items[at0016]/value/value AS hiType FROM EHR e CONTAINS COMPOSITION c1 CONTAINS CLUSTER c4[openEHR-EHR-CLUSTER.ehrn_metadata.v1] WHERE (c4/items[at0009]/items[at0010]/value/value MATCHES {'Encounter/ee2c037d-c499-4aa0-9097-03f6c7e7aa74'} AND c4/items[at0014]/items[at0016]/value/value MATCHES {'Prescription, DischargeSummary'}) LIMIT 10 OFFSET 0`

The server ignores the comma in the variable value and identifies as a single string. It then puts it inside a single quote an executes the query

### Expected behavior

A better way to handle the variable input so that arrays can be passed using variables

Option1 - Do not add the single quoted to the variable value so that the full value that goes inside the curly brackets can be passed inside the variable(including the single quotes for each string in the array)

Option2 - define the comma (or some other character) as a delimiter so that the server can identify the end of each string and add sinmgle quotes as required around each string separately.

### Actual result

The entire variable value is takes as single string

**Comment by vladislavploaia** [comment]
@dileep-ehr - For me it looks like an enhancement, not an issue.
The same format you defined in query_parameters "hiTypeArray": "Prescription, DischargeSummary" is applied in resulted query: ... MATCHES {'Prescription, DischargeSummary'}.
@stefanspiska , @HolgerReiseVSys - what do you think?

**Comment by dileep-ehr** [comment]
@vladislavploaia I agree that the behaviour in handling parameters is consistent. However in the case of MATCHES which takes an array of values, the expectation is different. Ideally the handling of parameters should be decided by the context in which it is used, so that it works always as expected.

**Comment by HolgerReiseVSys** [comment]
@vladislavploaia @dileep-ehr Interpreting the parameter string as array is no option because the intention of a comma in is not clear, e.g. it could just happen be part of the string to be matched. 
We have, however, already thought about allowing json arrays as parameter values, so it could be queried as 
```json
{ "q": "SELECT c1/uid/value as uid, c4/items[at0009]/items[at0010]/value/value as encounterId, c4/items[at0014]/items[at0016]/value/value as hiType FROM EHR e CONTAINS COMPOSITION c1 CONTAINS CLUSTER c4[openEHR-EHR-CLUSTER.ehrn_metadata.v1] WHERE c4/items[at0009]/items[at0010]/value/value MATCHES {$EncounterIdArray} and c4/items[at0014]/items[at0016]/value/value MATCHES {$hiTypeArray}", 
"offset": 0, "fetch": 10, 
"query_parameters": { 
  "EncounterIdArray": "Encounter/ee2c037d-c499-4aa0-9097-03f6c7e7aa74", 
  "hiTypeArray": ["Prescription", "DischargeSummary"] } 
}
```

**Comment by vladislavploaia** [comment]
Thanks @HolgerReiseVSys!
@dileep-ehr - please check the option provided by Holger.
If it's producing what you was expecting for, then I will close this ticket.
Thank you!

**Comment by HolgerReiseVSys** [comment]
@dileep-ehr @vladislavploaia This is just an idea and not yet implemented :)

**Comment by dileep-ehr** [comment]
@HolgerReiseVSys Yes. I realized that, as I am getting error. Is this scheduled for any recent release

**Comment by stefanspiska** [comment]
@dileep-ehr 

please check https://github.com/ehrbase/ehrbase/pull/1399

**Comment by dileep-ehr** [comment]
@stefanspiska I have done one round of testing and it seems to work. 

Will do further testing and revert if any issues are noticed.

**Comment by vladislavploaia** [comment]
Hello @dileep-ehr ,
Please let us know when you finish testing this part, so we can close (or not) this issue.
Thank you!
