### ISSUE TITLE
Aggregate functions 

### ISSUE THREAD

**Issue by freek-code24** [ehrbase/ehrbase#1397]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Environment information

- EHRbase version: 2.7.0-SNAPSHOT
- openEHR_SDK version: 2.17.0-SNAPSHOT
- Archie version: 3.3.0
- PostgreSQL version: PostgreSQL 16.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20231014) 13.2.1 20231014, 64-bit
- Java Runtime version: Eclipse Adoptium 21.0.4+7-LTS
- Operating System version: Linux amd64 5.15.153.1-microsoft-standard-WSL2

### Steps to reproduce

1. Create EHR
2. [Upload template](https://github.com/ehrbase/integration-tests/blob/main/tests/robot/_resources/test_data_sets/aql/data_load/opts/conformance_ehrbase.de.v0.opt)
3. [Create COMPOSITION](https://github.com/ehrbase/integration-tests/blob/main/tests/robot/_resources/test_data_sets/aql/data_load/compositions/conformance_ehrbase.de.v0_max_v3.json)
4. Execute query: `SELECT max(o/data[at0001]/events[at0002]/data[at0003]/items[at0008]/value/magnitude), o/data[at0001]/events[at0002]/data[at0003]/items[at0008]/value/magnitude FROM EHR e CONTAINS COMPOSITION c CONTAINS OBSERVATION o [openEHR-EHR-OBSERVATION.conformance_observation.v0]`

### Expected behavior

I expect that the max column returns the actual max value of all the events. If using the provided data, the max value is 82.0.
e.g.:

| MAX magnitude      | Magnitude      |
| ------------- | ------------- |
| 82.0 | 22.0 |
| 82.0 | 82.0 |
| 82.0 | null |

### Actual result

What I get is that for each event individually, the max value is calculated. 
E.g.

| MAX magnitude      | Magnitude      |
| ------------- | ------------- |
| 22.0 | 22.0 |
| 82.0 | 82.0 |
| null | null |

### Further information

The query provided does not have an actual use case. But, it is functions as an example for a discussion if this is a bug or not.
It seems to me this is unwanted behaviour, but let me know if you disagree.

**Comment by vmueller-vg** [comment]
This works as intended. If an aggregate function is used all paths that are not aggregated are used as implicit grouping. Since you used the same path inside and outside of an aggregate function, the path is part of the grouping. Note that paths are not independent. Especially equal paths will not be treated as separate entities.
