### ISSUE TITLE
OPT upload results in 4 byte error

### ISSUE THREAD

**Issue by johnmeredith** [ehrbase/ehrbase#151]
Uploading an OPT from the Better Archetype Designer results in the following error:
`{
    "error": "Characters larger than 4 bytes are not supported: byte 0xb5 implies a length of more than 4 bytes",
    "status": "Bad Request"
}`

This does not apply to all OPTs as I have had success with others. Attached is the relervant template file set in question.

Steps to recreate:

1. API call: `POST http://localhost:8080/ehrbase/rest/openehr/v1//definition/template/adl1.4`
2. Inc;lude OPT XML as body of the message
3. Send

[NWIS Medication Statement.v0.zip](https://github.com/ehrbase/ehrbase/files/4249214/NWIS.Medication.Statement.v0.zip)

**Comment by nr23730** [comment]
Hi!

I had the same issue when I ran EHRbase on my Windows workstation that runs openjdk11.
On my Debian server with adoptopenjdk (as recommended), I didn't have the issue and was also able to upload your opt file without any issue.

**Comment by johnmeredith** [comment]
Ahh... OK. I will try using something other than openjdk 11. I'll try something else.

**Comment by Geisterfalle** [comment]
Hi John, 

on windows, setting the JAVA_TOOL_OPTIONS resolves the issue for me:

![image](https://user-images.githubusercontent.com/2463423/75243127-9ea6dc80-57c9-11ea-89c4-a51364966079.png)

This is a know error and we will try to resolve this internally asap

**Comment by johnmeredith** [comment]
> on windows, setting the JAVA_TOOL_OPTIONS resolves the issue for me:

SUPERB!!! Sorted.
