### ISSUE TITLE
Composition commit fails if start_time value does not have a timezone suffix

### ISSUE THREAD

**Issue by freshehr** [ehrbase/ehrbase#203]
The DATE_TIME issue is that EhrBase expects a Timezone suffix on COMPOSITION/context/start_time/value - weirdly it does not care otherwise!

```
 "start_time": {
            "_type": "DV_DATE_TIME",
            "value": "2018-12-11T11:20:07,227"
        },
```
```
{
    "error": "Internal Server Error: java.time.temporal.UnsupportedTemporalTypeException: Unsupported field: InstantSeconds",
    "status": "Internal Server Error"
}
```

 "start_time": {
            "_type": "DV_DATE_TIME",
            "value": "2018-12-11T11:20:07,227Z"
        },
```

works. 

Dates on ENTRY classes accept strings without Timezones

**Comment by chevalleyc** [comment]
Thanks! We could default the missing timezone to Zulu then?

**Comment by Geisterfalle** [comment]
IMO we should use the local timezone

**Comment by freshehr** [comment]
Yes -agree default to local server timezone
