### ISSUE TITLE
Attribute namespace for canonical XML when there is no default namespace

### ISSUE THREAD

**Issue by ricardofago** [ehrbase/ehrbase#22]
If I do a ``POST (...)/composition`` using canonical XML, it seems that the default namespace is assumed to be ``xmlns="http://schemas.openehr.org/v1"``, so I can submit a composition without namespace declaration. But if I qualify it to have a namespace prefix (i.e. ``xmlns:oe="http://schemas.openehr.org/v1"``) and refactor the XML to include the namespace prefix for all elements and attributes, the server requires the value of the ``xsi:type`` attributes not to be prefixed, otherwise (for instance, using ``xsi:type="oe:(...)"``) I get a ``Unable to create an instance of com.nedap.archie.rm.(...)`` error. The elements themselves are fine and can be prefixed. Since different parsers have different behaviors when parsing ``xsi:type`` attributes, is this expected?

I tried it running v0.9.0 from the master branch, using a composition that matches a OPT file used in Brazil (but generally the same should happen for any composition), in which the compositions are transformed from TDDs so the namespace prefix is parsed from the original document, but we may rework it to force it as the default namespace instead.

**Comment by stefanspiska** [comment]
Ehrbase right now assume that everything is in the default namespace.
I have an Idee how to fix that but I'am no sure wenn we come around to fix that. 
It would be great If you could force your temples for now to use the default namespace .
