### ISSUE TITLE
AQL statement fails due to ordering param

### ISSUE THREAD

**Issue by lmarcoruiz** [ehrbase/ehrbase#230]
The following test fails with an error indicating the lack of the ordering keyword. When they keyword (e.g. DESC) is added it still fails.

----TEST 1------
SELECT u/data[at0001]/items[at0004]/value/value as Beginn, u/data[at0001]/items[at0005]/value/value as Ende, u/data[at0001]/items[at0006]/value/value as Bewegungsart, a/items[at0048]/value/defining_code/code_string as Fachabteilung, a/items[at0027, 'Stationskennung']/value as Station, e/ehr_status/subject/external_ref/id/value as PatientID, n/items[at0001,'Zugehörige Versorgungsfall-Kennung']/value/value as FallID FROM EHR e CONTAINS COMPOSITION c[openEHR-EHR-COMPOSITION.event_summary.v0] CONTAINS (ADMIN_ENTRY u[openEHR-EHR-ADMIN_ENTRY.hospitalization.v0] CONTAINS CLUSTER a[openEHR-EHR-CLUSTER.location.v1] and CLUSTER n[openEHR-EHR-CLUSTER.case_identification.v0]) WHERE c/name/value='Patientenaufenthalt' and e/ehr_status/subject/external_ref/id/value MATCHES {list} ORDER BY e/ehr_status/subject/external_ref/id/value, u/data[at0001]/items[at0004]/value/value

TEST RUN:

{"q" : "SELECT u/data[at0001]/items[at0004]/value/value as Beginn, u/data[at0001]/items[at0005]/value/value as Ende, u/data[at0001]/items[at0006]/value/value as Bewegungsart, a/items[at0048]/value/defining_code/code_string as Fachabteilung, a/items[at0027, 'Stationskennung']/value as Station, e/ehr_status/subject/external_ref/id/value as PatientID, n/items[at0001,'Zugehörige Versorgungsfall-Kennung']/value/value as FallID FROM EHR e CONTAINS COMPOSITION c[openEHR-EHR-COMPOSITION.event_summary.v0] CONTAINS (ADMIN_ENTRY u[openEHR-EHR-ADMIN_ENTRY.hospitalization.v0] CONTAINS CLUSTER a[openEHR-EHR-CLUSTER.location.v1] and CLUSTER n[openEHR-EHR-CLUSTER.case_identification.v0]) WHERE c/name/value='Patientenaufenthalt' and e/ehr_status/subject/external_ref/id/value MATCHES {'Flormidal', 'Kloralhidrat'} ORDER BY e/ehr_status/subject/external_ref/id/value, u/data[at0001]/items[at0004]/value/value DESC"}

RESULT:
{
"error": "Could not process query, reason:org.antlr.v4.runtime.misc.ParseCancellationException: AQL Parse exception: line 1: char 851 missing {DESCENDING, ASCENDING, DESC, ASC} at ','",
"status": "Bad Request"
}

-----END TEST 1----

**Comment by chevalleyc** [comment]
The current supported ORDER BY syntax requires the order to be specified (e.g. ASC, DESC, ASCENDING, DESCENDING), no default order is assumed. The above example should read:

```
... ORDER BY 
      e/ehr_status/subject/external_ref/id/value DESC, 
      u/data[at0001]/items[at0004]/value/value DESC
```
