### ISSUE TITLE
Temporal constraints are not correctly processed in the AQL WHERE clause

### ISSUE THREAD

**Issue by lmarcoruiz** [ehrbase/ehrbase#244]
The test for the query below fails due to not detecting time overlaps among patients:

Contact_Nth_Degree_TTP_Degree_II

SELECT e/ehr_status/subject/external_ref/id/value as PatientID, o/data[at0001]/items[at0004]/value/value as Beginn, o/data[at0001]/items[at0005]/value/value as Ende FROM EHR e CONTAINS COMPOSITION c CONTAINS ADMIN_ENTRY o[openEHR-EHR-ADMIN_ENTRY.hospitalization.v0] CONTAINS CLUSTER l[openEHR-EHR-CLUSTER.location.v1] where c/name/value='Patientenaufenthalt' and o/data[at0001]/items[at0004]/value/value >= '{starttime}' and o/data[at0001]/items[at0004]/value/value <= '{endtime}' and l/items[at0048]/value/defining_code/code_string = '{departement}' and l/items[at0027,'Stationskennung']/value = '{station}' and not e/ehr_status/subject/external_ref/id/value = '{patientID}' UNION ALL SELECT e/ehr_status/subject/external_ref/id/value as PatientID, o/data[at0001]/items[at0004]/value/value as Beginn, o/data[at0001]/items[at0005]/value/value as Ende FROM EHR e CONTAINS COMPOSITION c CONTAINS ADMIN_ENTRY o[openEHR-EHR-ADMIN_ENTRY.hospitalization.v0] CONTAINS CLUSTER l[openEHR-EHR-CLUSTER.location.v1] where c/name/value='Patientenaufenthalt' and o/data[at0001]/items[at0004]/value/value <= '{starttime}' and o/data[at0001]/items[at0005]/value/value > '{starttime}' and l/items[at0048]/value/defining_code/code_string = '{departement}' and l/items[at0027,'Stationskennung']/value = '{station}' and not e/ehr_status/subject/external_ref/id/value = '{patientID}'
[openEHR COID ContactNthDegree_TTP_Degree_II.postman_collection.json.zip](https://github.com/ehrbase/ehrbase/files/4581728/openEHR.COID.ContactNthDegree_TTP_Degree_II.postman_collection.json.zip)

**Comment by chevalleyc** [comment]
UNION ALL is not supported at the moment, the AQL expression parsing fails.

**Comment by lmarcoruiz** [comment]
I think did not explain it well. If you split in two queries the temporal constraint is not taken into account either.
