### ISSUE TITLE
Getting a validation error on a null_flavour

### ISSUE THREAD

**Issue by ppazos** [ehrbase/ehrbase#251]
It is complaining about the coded text value for the code_string, but the value is the one defined in the openEHR terminology for that code.

Response

`{"error":"org.ehrbase.validation.constraints.wrappers.ValidationException: :-Validation error at /content[openEHR-EHR-OBSERVATION.glasgow_coma_scale.v1]/data[at0001]/events[at0002]/data[at0003]/items[at0007]:Validation error at /content[openEHR-EHR-OBSERVATION.glasgow_coma_scale.v1]/data[at0001]/events[at0002]/data[at0003]/items[at0007], CODED_TEXT_01:CodedText value is not valid:DvCodedText{code_string=273, terminology_id=openehr, value=not applicable}.\n\n","status":"Bad Request"}`

Request

`{"_type":"COMPOSITION","name":{"_type":"DV_TEXT","value":"Review"},"archetype_details":{"archetype_id":{"value":"openEHR-EHR-COMPOSITION.review.v1"},"template_id":{"value":"Review"},"rm_version":"1.0.2"},"archetype_node_id":"openEHR-EHR-COMPOSITION.review.v1","language":{"terminology_id":{"value":"ISO_639-1"},"code_string":"es"},"territory":{"terminology_id":{"value":"ISO_3166-1"},"code_string":"UY"},"category":{"value":"evento","defining_code":{"terminology_id":{"value":"openehr"},"code_string":"433"}},"composer":{"_type":"PARTY_IDENTIFIED","external_ref":{"id":{"_type":"HIER_OBJECT_ID","value":"40b69e14-7c5a-4520-9769-268310ca5a0c"},"namespace":"DEMOGRAPHIC","type":"PERSON"},"name":"Dr. House"},"context":{"start_time":{"value":"20200602T224201,146-0300"},"setting":{"value":"atenci\u00f3n de emergencia","defining_code":{"terminology_id":{"value":"openehr"},"code_string":227}}},"content":[{"_type":"OBSERVATION","name":{"_type":"DV_TEXT","value":"Glasgow coma scale"},"archetype_node_id":"openEHR-EHR-OBSERVATION.glasgow_coma_scale.v1","language":{"terminology_id":{"value":"ISO_639-1"},"code_string":"es"},"encoding":{"terminology_id":{"value":"Unicode"},"code_string":"UTF-8"},"subject":{"_type":"PARTY_SELF"},"protocol":{"_type":"ITEM_TREE","name":{"_type":"DV_TEXT","value":"Tree"},"archetype_node_id":"at0038","items":[]},"data":{"_type":"HISTORY","name":{"_type":"DV_TEXT","value":"Event Series"},"archetype_node_id":"at0001","origin":{"_type":"DV_DATE_TIME","value":"20200602T224201,149-0300"},"events":[{"_type":"POINT_EVENT","name":{"_type":"DV_TEXT","value":"Point in time"},"archetype_node_id":"at0002","time":{"_type":"DV_DATE_TIME","value":"20200602T224201,150-0300"},"data":{"_type":"ITEM_TREE","name":{"_type":"DV_TEXT","value":"Tree"},"archetype_node_id":"at0003","items":[{"_type":"ELEMENT","name":{"_type":"DV_TEXT","value":"Best eye response (E)"},"archetype_node_id":"at0009","value":{"_type":"DV_ORDINAL","value":1,"symbol":{"value":"None","defining_code":{"terminology_id":{"value":"local"},"code_string":"at0010"}}}},{"_type":"ELEMENT","name":{"_type":"DV_TEXT","value":"Best verbal response (V)"},"archetype_node_id":"at0007","null_flavour":{"_type":"DV_CODED_TEXT","value":"not applicable","defining_code":{"terminology_id":{"value":"openehr"},"code_string":"273"}}},{"_type":"ELEMENT","name":{"_type":"DV_TEXT","value":"Best motor response (M)"},"archetype_node_id":"at0008","value":{"_type":"DV_ORDINAL","value":1,"symbol":{"value":"None","defining_code":{"terminology_id":{"value":"local"},"code_string":"at0019"}}}},{"_type":"ELEMENT","name":{"_type":"DV_TEXT","value":"Total score"},"archetype_node_id":"at0026","value":{"_type":"DV_COUNT","magnitude":9}},{"_type":"ELEMENT","name":{"_type":"DV_TEXT","value":"EVM profile"},"archetype_node_id":"at0030","value":{"_type":"DV_TEXT","value":"eByDKjlBhourmFbvTriixlMsF.ADLpOZyUztNazbJ.wjAKbdGoaWPVIyJQCnwosXqovLHnqVARrjGwfdUbE VcMazRpBXaEojhGoxIYLNxIWJWjGLdwfT.IWtyYKVxTIZWbWIJnfjPeJvKVRPpORtTiUV.sVTAjeEDUQkPLuItyuQbIYAkapBOoswwND.qeyeRGbVYwbvVdftUKhJtbXIxhhulhU.hBxKPoPqqzxfXHhkRpGRXZhWpJJDAYlgvp"}},{"_type":"ELEMENT","name":{"_type":"DV_TEXT","value":"Comment"},"archetype_node_id":"at0037","value":{"_type":"DV_TEXT","value":"OXUOLwrAEikiRcRXkSyNyhGKOylGtPSeAkzVAordOEcDhKSI K,wnVqWhpTadyAWmRNQIgLvHOBmjVpeZpdvIrBnEZDYpQpRhBTgarTB.m.KllDAZEPZLQrfY.XeONtWOIS LoawEvWnholvBfUXOGcZxD.HXU BqszkqsmRpFDTKQLeDLxkOSjRQSSuh,I BJhrF,COYvjKYIJ,RRGel sentzEqHSRYOJnIBvYJC,BtYgVdbLCRPvColJQlZY"}}]},"state":{"_type":"ITEM_TREE","name":{"_type":"DV_TEXT","value":"Tree"},"archetype_node_id":"at0040","items":[{"_type":"ELEMENT","name":{"_type":"DV_TEXT","value":"Confounding factors"},"archetype_node_id":"at0041","value":{"_type":"DV_TEXT","value":"terndVvRwDiaSwvmRwVyDgtPXVgHRrTOihrdtxlYfbzpjoTfpEgrHbGbIbaQXzZRmecjnfcQClQPYSfHuPertG,rQFdNZp.XClNZxXnAWYbUBZaQCfXWrWbgA,hdloQcOYzimuaHehAMjoqJYt aSLshtwUT.FhCunAHYPHqIGVHKeukmByh.JAyKWMN.USROLDbgZvlMvJTmjnWORqsGtIcuoTHzZDJXIVWBqDuJbIGc,sWlVODAuRtdMBCqRG"}}]}}]}}]}`

**Comment by chevalleyc** [comment]
Hi @ppazos could you please post template 'Review' ? Thanks!

**Comment by chevalleyc** [comment]
I could successfully post a composition with the following (from minimal_admin.json, template minimal_admin.opt):
```
			"items": [{
				"_type": "ELEMENT",
				"name": {
					"_type": "DV_TEXT",
					"value": "ordinal"
				},
				"archetype_node_id": "at0002",
				"null_flavour": {
				  "value": "not applicable",
				  "defining_code": {
					"terminology_id": {
					  "value": "openehr"
					},
					"code_string": "273"
				  }
				}
			}]
```
With either language 'es' or 'en' 

I am not sure now what is the issue with your example. Could you please post the template so I can try to reproduce it locally. Thanks

**Comment by ppazos** [comment]
@chevalleyc can you attach the full composition you used for testing? I'll test it here, thanks.

**Comment by ppazos** [comment]
@chevalleyc one of the templates I'm using is https://github.com/ppazos/testehr/blob/master/src/main/resources/opts/Review.opt that has a constraint on some null_flavours

**Comment by chevalleyc** [comment]
This composition is successfully saved/retrieved with the fix in PR https://github.com/ehrbase/ehrbase/pull/257

[minimal_null_flavour.txt](https://github.com/ehrbase/ehrbase/files/4749677/minimal_null_flavour.txt)

**Comment by ppazos** [comment]
@chevalleyc after reviewing your feedback I think the difference is the template I'm using has an explicit constraint for a null_flavour node, while the minimal_admin OPT doesn't. So this case is different: the null_flavour is in the OPT and in the data.

https://github.com/ppazos/testehr/blob/master/src/main/resources/opts/Review.opt#L277-L326

**Comment by ppazos** [comment]
2020-07-29: re-tested for https://github.com/ehrbase/project_management/issues/319

Tried to set the language on the composition to "en" and remove optional nodes, and I see the same behavior: if the OPT has the null_flavour constraint and the data contains a null_flavour node, it is not validating.

Template: https://github.com/ppazos/testehr/blob/master/src/main/resources/opts/Review.opt#L277-L326

Simplified compo:
```

{
	"_type": "COMPOSITION",
	"name": {
		"_type": "DV_TEXT",
		"value": "Review"
	},
	"archetype_details": {
		"archetype_id": {
			"value": "openEHR-EHR-COMPOSITION.review.v1"
		},
		"template_id": {
			"value": "Review"
		},
		"rm_version": "1.0.2"
	},
	"archetype_node_id": "openEHR-EHR-COMPOSITION.review.v1",
	"language": {
		"terminology_id": {
			"value": "ISO_639-1"
		},
		"code_string": "en"
	},
	"territory": {
		"terminology_id": {
			"value": "ISO_3166-1"
		},
		"code_string": "UY"
	},
	"category": {
		"value": "evento",
		"defining_code": {
			"terminology_id": {
				"value": "openehr"
			},
			"code_string": "433"
		}
	},
	"composer": {
		"_type": "PARTY_IDENTIFIED",
		"external_ref": {
			"id": {
				"_type": "HIER_OBJECT_ID",
				"value": "40b69e14-7c5a-4520-9769-268310ca5a0c"
			},
			"namespace": "DEMOGRAPHIC",
			"type": "PERSON"
		},
		"name": "Dr. House"
	},
	"context": {
		"start_time": {
			"value": "20200602T224201,146-0300"
		},
		"setting": {
			"value": "emergency care",
			"defining_code": {
				"terminology_id": {
					"value": "openehr"
				},
				"code_string": 227
			}
		}
	},
	"content": [{
		"_type": "OBSERVATION",
		"name": {
			"_type": "DV_TEXT",
			"value": "Glasgow coma scale"
		},
		"archetype_node_id": "openEHR-EHR-OBSERVATION.glasgow_coma_scale.v1",
		"language": {
			"terminology_id": {
				"value": "ISO_639-1"
			},
			"code_string": "en"
		},
		"encoding": {
			"terminology_id": {
				"value": "Unicode"
			},
			"code_string": "UTF-8"
		},
		"subject": {
			"_type": "PARTY_SELF"
		},
		"data": {
			"_type": "HISTORY",
			"name": {
				"_type": "DV_TEXT",
				"value": "Event Series"
			},
			"archetype_node_id": "at0001",
			"origin": {
				"_type": "DV_DATE_TIME",
				"value": "20200602T224201,149-0300"
			},
			"events": [{
				"_type": "POINT_EVENT",
				"name": {
					"_type": "DV_TEXT",
					"value": "Point in time"
				},
				"archetype_node_id": "at0002",
				"time": {
					"_type": "DV_DATE_TIME",
					"value": "20200602T224201,150-0300"
				},
				"data": {
					"_type": "ITEM_TREE",
					"name": {
						"_type": "DV_TEXT",
						"value": "Tree"
					},
					"archetype_node_id": "at0003",
					"items": [{
						"_type": "ELEMENT",
						"name": {
							"_type": "DV_TEXT",
							"value": "Best eye response (E)"
						},
						"archetype_node_id": "at0009",
						"value": {
							"_type": "DV_ORDINAL",
							"value": 1,
							"symbol": {
								"value": "None",
								"defining_code": {
									"terminology_id": {
										"value": "local"
									},
									"code_string": "at0010"
								}
							}
						}
					}, {
						"_type": "ELEMENT",
						"name": {
							"_type": "DV_TEXT",
							"value": "Best verbal response (V)"
						},
						"archetype_node_id": "at0007",
						"null_flavour": {
							"_type": "DV_CODED_TEXT",
							"value": "not applicable",
							"defining_code": {
								"terminology_id": {
									"value": "openehr"
								},
								"code_string": "273"
							}
						}
					}, {
						"_type": "ELEMENT",
						"name": {
							"_type": "DV_TEXT",
							"value": "Best motor response (M)"
						},
						"archetype_node_id": "at0008",
						"value": {
							"_type": "DV_ORDINAL",
							"value": 1,
							"symbol": {
								"value": "None",
								"defining_code": {
									"terminology_id": {
										"value": "local"
									},
									"code_string": "at0019"
								}
							}
						}
					}, {
						"_type": "ELEMENT",
						"name": {
							"_type": "DV_TEXT",
							"value": "Total score"
						},
						"archetype_node_id": "at0026",
						"value": {
							"_type": "DV_COUNT",
							"magnitude": 9
						}
					}]
				}
			}]
		}
	}]
}
```

Result: status 400

```
{
  "error": "org.ehrbase.validation.constraints.wrappers.ValidationException: :-Validation error at /content[openEHR-EHR-OBSERVATION.glasgow_coma_scale.v1]/data[at0001]/events[at0002]/data[at0003]/items[at0007]:Validation error at /content[openEHR-EHR-OBSERVATION.glasgow_coma_scale.v1]/data[at0001]/events[at0002]/data[at0003]/items[at0007], CODED_TEXT_01:CodedText value is not valid:DvCodedText{code_string=273, terminology_id=openehr, value=not applicable}.\n\n",
  "status": "Bad Request"
}
```
