### ISSUE TITLE
POST /composition is composition.content is null, the server returns 500

### ISSUE THREAD

**Issue by ppazos** [ehrbase/ehrbase#255]
While testing I generated a composition with no content by mistake and committed that to the server:

```
{
	"_type": "COMPOSITION",
	"name": {
		"_type": "DV_TEXT",
		"value": "Minimal"
	},
	"archetype_details": {
		"archetype_id": {
			"value": "openEHR-EHR-COMPOSITION.minimal.v1"
		},
		"template_id": {
			"value": "Minimal action 2"
		},
		"rm_version": "1.0.2"
	},
	"archetype_node_id": "openEHR-EHR-COMPOSITION.minimal.v1",
	"language": {
		"terminology_id": {
			"value": "ISO_639-1"
		},
		"code_string": "es"
	},
	"territory": {
		"terminology_id": {
			"value": "ISO_3166-1"
		},
		"code_string": "UY"
	},
	"category": {
		"value": "evento",
		"defining_code": {
			"terminology_id": {
				"value": "openehr"
			},
			"code_string": "433"
		}
	},
	"composer": {
		"_type": "PARTY_IDENTIFIED",
		"external_ref": {
			"id": {
				"_type": "HIER_OBJECT_ID",
				"value": "0dfd923c-4315-4c04-a599-8ee4449185c4"
			},
			"namespace": "DEMOGRAPHIC",
			"type": "PERSON"
		},
		"name": "Dr. House"
	},
	"context": {
		"start_time": {
			"value": "20200608T161603,605-0300"
		},
		"setting": {
			"value": "homar",
			"defining_code": {
				"terminology_id": {
					"value": "openehr"
				},
				"code_string": 225
			}
		}
	},
	"content": [null]
}
```

It seems to fail before reaching the validation:

```
HTTP/1.1 500 
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY
Content-Type: application/json
Transfer-Encoding: chunked
Date: Mon, 08 Jun 2020 19:16:02 GMT
Connection: close

{"error":"Internal Server Error: java.lang.NullPointerException","status":"Internal Server Error"}
```

In the server terminal I can see this exception:

```
2020-06-08 16:16:01 INFO  Http11Processor:175 - Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
java.lang.IllegalArgumentException: Invalid character found in the HTTP protocol
	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:532)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:260)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1598)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

I think the server should not fail, validate that composition, and reject it gracefully because has no content, unless we actually want to support compos with no content which is valid in the spec.

**Comment by chevalleyc** [comment]
We do support composition without content (that is, there is no 'content' key in the canonical json) https://github.com/ehrbase/ehrbase/pull/129. I suggest to post a composition without the key.

**Comment by ppazos** [comment]
This bug report wasn't about testing the compo with empty content, but to show one case that generates an exception. That case was generated by mistake because of a bug in my JSON generator, but either way, is a good test case for fuzz testing. At some point in the future would be good to do some fuzzing on the server to see how it behaves under bad inputs. @Geisterfalle what do you think?

I think the server should respond with a friendly message on the case above, for instance, if that is not a valid JSON, give a JSON validation error or something similar and return 400 instead of 500 with an exception.

**Comment by Geisterfalle** [comment]
I agree with Pablo here. We cannot assume that developers will always be on the happy path. Hence, providing meaningful error messages will certainly help to improve the developer experience.

**Comment by ppazos** [comment]
2020-07-30: re-tested for https://github.com/ehrbase/project_management/issues/319

Tested 3 alternatives:
- no content key
- content key with null value
- content key with empty array value

All three are creating the composition without content returning 201. IMO that is a correct behavior. What do you think @Geisterfalle ?

**Comment by ppazos** [comment]
Consulted with Birger and got his OK to close this one.
