### ISSUE TITLE
Update of ehr_status raises an error due to version

### ISSUE THREAD

**Issue by lmarcoruiz** [ehrbase/ehrbase#258]
The attached postman collection attempts an update in the ehr_status. Irrespectively of the versión indicated Ehrbase raises the following issue:

{
    "error": "Given If-Match header does not match latest existing version",
    "status": "Precondition Failed"
}

REPRODUCE US
[openEHR SMICS INTEGRATION.postman_collection.zip](https://github.com/ehrbase/ehrbase/files/4751931/openEHR.SMICS.INTEGRATION.postman_collection.zip)

ING THE POSTMAN COLLECTION AS:
1-create EHR
2-Try PUT method with the ehr_id of the ehr created in (1)

**Comment by jakesmolka** [comment]
That is correct, as in your example request you used the the EHR's ID as value for the `If-Match` header of the PUT. The EHR_STATUS PUT endpoint need the **latest EHR_STATUS version ID** though. See: https://specifications.openehr.org/releases/ITS-REST/latest/ehr.html#ehr_status-ehr_status-put

Hint: To retrieve the latest (i.e. original version ID) of the STATUS when POSTing an EHR add the `PREFER` header with the value `return=representation` to get the ID in the response.

But even when changing your request accordingly the following error is returned:

```
{
    "error": "Message at /archetype_node_id (/archetype_node_id):  Attribute archetype_node_id of class EHR_STATUS does not match existence 1..1\nMessage at /name (/name):  Attribute name of class EHR_STATUS does not match existence 1..1\n",
    "status": "Bad Request"
}
```

Adding an `archetype_node_id` field to the body then results in the same error saying a `name` is missing. But after adding it the request works for me with this body:

```
{
  "_type": "EHR_STATUS",
  "archetype_node_id": "blabla",
  "name": "test",
  "subject": {
    "external_ref": {
      "id": {
        "_type": "GENERIC_ID",
        "value": "1234567890",
        "scheme": "id_scheme"
      },
      "namespace": "ehr_craft",
      "type": "PERSON"
    }
  },
  "is_modifiable": "true",
  "is_queryable": "true"
}
```
