### ISSUE TITLE
Error on queries with ORDER BY

### ISSUE THREAD

**Issue by ppazos** [ehrbase/ehrbase#261]
Tried to execute some of the queries used for the COVID platform and some errors, for instance:

```
{
"q": "SELECT x/data[at0001]/items[at0002]/value/value as diagnosis, x/data[at0001]/items[at0077]/value/value as time FROM EHR e CONTAINS COMPOSITION c CONTAINS EVALUATION x[openEHR-EHR-EVALUATION.problem_diagnosis.v1] where e/ehr_id/value = $ehr_id order by x/data[at0001]/items[at0077]/value/value desc",
"offset": 0,
"fetch": 20,
"query_parameters": { "ehr_id": "8006648c-43bb-4ef2-80a8-99aa9915476e" }
}
```

Is returning:

```
{
 "error": "Could not retrieve stored query, reason:org.antlr.v4.runtime.misc.ParseCancellationException: AQL Parse exception: line 1: char 329 mismatched input 'LIMIT' expecting {DESCENDING, ASCENDING, DESC, ASC, '/', '['}",
 "status": "Bad Request" 
}
```

The error says something about the limit in the AQL expression but the limit was not set, maybe the internal processing is taking the "fetch" from the JSON request and putting a LIMIT internally in the wrong place of the expression?

**Comment by ppazos** [comment]
2020-07-29: re-tested this for https://github.com/ehrbase/project_management/issues/319

The error about the LIMIT is still there if the "fetch" parameter is in the JSON. If I remove the "fetch" it works. I think the error is the AQL processing is not considering the query has an ORDER BY at the end and tries to add the LIMIT based on the "fetch" parameter in the wrong place in the generated SQL.

**Comment by sidharthramesh** [comment]
This works:
```
SELECT 
c/content[openEHR-EHR-OBSERVATION.laboratory_test_result.v1]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.laboratory_test_analyte.v1]/items[at0001]/value as result, 
c/content[openEHR-EHR-OBSERVATION.laboratory_test_result.v1]/data[at0001]/events[at0002]/time as time, 
e/ehr_id/value as id FROM EHR e CONTAINS COMPOSITION c [openEHR-EHR-COMPOSITION.report-result.v1]  
where 
c/archetype_details/template_id/value='MCS.CovidResult.v0' 
AND e/ehr_id/value MATCHES {'a3978e91-41a8-4a69-beb0-dc056085e8b1', 'ba17454b-ff96-4a37-965c-ec8697b74af7'} 
LIMIT 1 
ORDER BY time DESC
```
This doesn't:
```
SELECT 
c/content[openEHR-EHR-OBSERVATION.laboratory_test_result.v1]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.laboratory_test_analyte.v1]/items[at0001]/value as result, 
c/content[openEHR-EHR-OBSERVATION.laboratory_test_result.v1]/data[at0001]/events[at0002]/time as time, 
e/ehr_id/value as id FROM EHR e CONTAINS COMPOSITION c [openEHR-EHR-COMPOSITION.report-result.v1]  
where 
c/archetype_details/template_id/value='MCS.CovidResult.v0' 
AND e/ehr_id/value MATCHES {'a3978e91-41a8-4a69-beb0-dc056085e8b1', 'ba17454b-ff96-4a37-965c-ec8697b74af7'} 
ORDER BY time DESC
LIMIT 1 
```
The only difference is the order of the LIMIT and ORDER BY.

**Comment by juanmajmjr** [comment]
What is the status of this issue?

**Comment by chevalleyc** [comment]
Please use the (working) syntax as defined in https://specifications.openehr.org/releases/QUERY/Release-1.1.0/AQL.html#_limit_syntax

**Comment by tirithen** [comment]
Hi! I work in a team where we have an issue with EHRbase not running the AQL query when the LIMIT keyword is last in the query as mentioned above by @sidharthramesh .

According to the standard linked to by @chevalleyc the LIMIT should come last, but then the AQL query will not run. If we switch the order of ORDER BY and LIMIT the same query runs fine. This creates inconsistencies when we try to use the AQL queries in other software that complies to the standard (where ORDER BY is before LIMIT).

Example from https://specifications.openehr.org/releases/QUERY/Release-1.1.0/AQL.html#_limit_syntax :
```sql
SELECT
   c/name/value AS Name, c/context/start_time AS date_time, c/composer/name AS Composer
FROM
   EHR e[ehr_id/value=$ehrUid]
      CONTAINS COMPOSITION c
ORDER BY c/context/start_time
LIMIT 10 OFFSET 10 -- <-- LIMIT should be placed after ORDER BY according to the documentation.
```

Should I report this as a separate issue or is it better to track that bug here as the discussion has already started here?

**Comment by ppazos** [comment]
@tirithen can you open a new issue?
