### ISSUE TITLE
Direction in TOP  is ignored on ehrbase

### ISSUE THREAD

**Issue by stefanspiska** [ehrbase/ehrbase#265]
Direction in TOP  is ignored on ehrbase . 
see DefaultRestAqlEndpointTestIT.testExecuteEntityTOP in https://github.com/ehrbase/openEHR_SDK/commit/d37081095e1ed23a8e283d4d253b70433b788558

**Comment by Geisterfalle** [comment]
@stefanspiska should this issue still be open?

**Comment by stefanspiska** [comment]
@Geisterfalle 
yes see DefaultRestAqlEndpointTestIT.testExecuteEntityTOP in the sdk

**Comment by chevalleyc** [comment]
The TOP operator is deprecated (https://specifications.openehr.org/releases/QUERY/Release-1.1.0/AQL.html#_top)

Deprecated: Starting with Release 1.1.0, the use of TOP modifier is deprecated in favour of the LIMIT clause combined with ORDER BY (see below). The TOP will be removed in a future major release of AQL specification. It is not allowed to use TOP while also using LIMIT clause in the same query.
