### ISSUE TITLE
XML representation of AQL resultset with multiple columns

### ISSUE THREAD

**Issue by nr23730** [ehrbase/ehrbase#32]
When I execute an AQL query with two (or more) columns the JSON format looks fine but in the XML format it's not possible to see to which column the value belongs.

Would be great to have an equivalent XML representation. 

JSON-Result:
```
"rows": [
  [
    "0",
    "0"
  ],
  [
    "1",
    "1"
  ]
]
```

XML-Result:
```  
<rows>
  <rows>0</rows>
  <rows>0</rows>
  <rows>1</rows>
  <rows>1</rows>
</rows>
```

Expected XML-Result:
```  
<rows>
  <row>
    <row>0</row>
    <row>0</row>
  </row>
  <row>
    <row>1</row>
    <row>1</row>
  </row>
</rows>
```

**Comment by jakesmolka** [comment]
Hey @nr23730 and thanks for the feedback! 
XML is generally not supported as AQL response, by the official openEHR REST API. Unfortunately this is only implicitly stated at the moment, see: https://specifications.openehr.org/releases/ITS-REST/latest/query.html#header-response-structure 

Our API shouldn't allow `Accept: application/xml` for the query endpoints, so I'm going to change the behavior here.
