### ISSUE TITLE
Error executing AQL queries

### ISSUE THREAD

**Issue by yampeku** [ehrbase/ehrbase#321]
## Steps to reproduce ## 

Freshly created ehrdb container and EHRBase 0.13.0 container. Used methods in provided insomnia to create a template, a EHR, and upload a composition. Every ad-hoc aql query or stored query fails. Console log is also provided. Last console lines are the ones caused by the aql queries.
[isomniaWorkspace+log.zip](https://github.com/ehrbase/ehrbase/files/5311552/isomniaWorkspace%2Blog.zip)

## Actual result ##

No '/v1/query' methods worked
When asking for XML (Accept: application/xml)
```
<?xml version='1.0' encoding='UTF-8'?>
<Map>
  <timestamp>2020-10-01T10:00:35.180+00:00</timestamp>
  <status>406</status>
  <error>Not Acceptable</error>
  <message>Could not find acceptable representation</message>
  <path>/ehrbase/rest/openehr/v1/query/es.veratech::testquery</path>
</Map>
```

When asking for json (no Accept header)

```
{
  "error": "Could not traverse cached templates:org.ehrbase.api.exception.InternalServerException",
  "status": "Bad Request"
}

```
## Expected result ##

return AQL query result

## Success criteria ##

- [x] The defect has been fixed
- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] Runtime warnings

**Comment by stefanspiska** [comment]
@yampeku  Can you provide the templates you are submitting to ehrbase?

**Comment by yampeku** [comment]
Everything should be included in the insomnia workspace. Here is the template and the data instance in any case

[psychotherapy_note_example_json.txt](https://github.com/ehrbase/ehrbase/files/5311718/psychotherapy_note_example_json.txt)
[Psychotherapy_Note.EN.v1_opt.txt](https://github.com/ehrbase/ehrbase/files/5311719/Psychotherapy_Note.EN.v1_opt.txt)

**Comment by stefanspiska** [comment]
From my test this seams to work on the actual dev. @yampeku Can you verify that.

**Comment by yampeku** [comment]
I can confirm it works now 👍
