### ISSUE TITLE
POST composition: optional empty protocol throws IllegalArgumentException

### ISSUE THREAD

**Issue by yampeku** [ehrbase/ehrbase#323]
## Steps to reproduce ## 

Using "Signos.opt"
[Signos_opt.txt](https://github.com/ehrbase/ehrbase/files/5317522/Signos_opt.txt)

Posting a composition instance to  "/ehr/{ehr_id}/composition" method with the following XML or JSON as body 
[signos_error_json.txt](https://github.com/ehrbase/ehrbase/files/5317528/signos_error_json.txt)
[signos_error_xml.txt](https://github.com/ehrbase/ehrbase/files/5317529/signos_error_xml.txt)

Contains half empty "state" and "protocol", valid according to the uploaded template. For example, one of the protocols in the json example
```

"protocol": {
          "archetype_node_id": "at0011",
          "_type": "ITEM_TREE",
          "name": { "value": "Tree" }
        },
```

## Actual result ##

Server returns an error with either XML or JSON data instances

```
{
  "error": "java.lang.IllegalArgumentException",
  "status": "Bad Request"
}
```

## Expected result ##

By using a json without state or protocol, the POST composition method works (status 201, created)
[signos_ok_json.txt](https://github.com/ehrbase/ehrbase/files/5317573/signos_ok_json.txt)

## Success criteria ##

- [x] The defect has been fixed
- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] Runtime warnings

**Comment by subigre** [comment]
Retested with:
```json
{
    "ehrbase_version": "0.19.0-SNAPSHOT",
    "openehr_sdk_version": "1.7.0-SNAPSHOT",
    "archie_version": "1.0.4",
    "jvm_version": "AdoptOpenJDK 11.0.11+9",
    "os_version": "Windows 10 amd64 10.0",
    "postgres_version": "PostgreSQL 13.4 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20210424) 10.3.1 20210424, 64-bit"
}
```

After fixing invariant issues (due to archie validation):

- `Encoding_valid`:
  Using
  ```json
  "encoding": {
    "terminology_id": {
      "value": "IANA_character-sets"
    },
    "code_string": "UTF-8"
  }
  ```
  instead of
  ```json
  "encoding": {
    "terminology_id": {
      "value": "Unicode"
    },
    "code_string": "UTF-8"
  }
  ```
- `Is_archetypeRoot`:
  Using `archetype_details` in all OBSERVATIONs
  ```json
  "archetype_details": {
    "archetype_id": {
      "value": "openEHR-EHR-OBSERVATION.pulse.v1"
    },
    "rm_version": "1.0.4"
  }
  ```

I cannot reproduce the issue. EHRbase now returns successful response `201 Created`.
