### ISSUE TITLE
[AQL] Strange epoch_offset attribute on DV_DATE_TIME

### ISSUE THREAD

**Issue by ppazos** [ehrbase/ehrbase#328]
## Background ##

AQL is returning this {"value":"2020-04-23T00:00-03:00","epoch_offset":1.5876108E9,"_type":"DV_DATE_TIME"}

Not sure if that epoch_offset should be there.

**Comment by chevalleyc** [comment]
epoch_offset is there as a workaround to the absence of date/time type in json (along with a lot of other limitations of json). It has been added to allow using conditionals (such as >, < etc.) instead of requiring a string conversion before performing the actual operation.

**Comment by birgerhaarbrandt** [comment]
@ppazos @chevalleyc can you please check if this needs to be kept open or can be closed?

**Comment by chevalleyc** [comment]
This attribute (although useful!) has been removed from the canonical representation to date.
