### ISSUE TITLE
Use Java 11 as default?

### ISSUE THREAD

**Issue by testautomation** [ehrbase/ehrbase#33]
Are there any hard requirements to stick to Java 8?

## Download from suggested link in README.md takes hours:
![image](https://user-images.githubusercontent.com/38438046/68547701-e2293680-03e4-11ea-880b-f049d01f2b45.png)

## Modern installation options on Windows like **scoop** don't provide version 8 any more:
![image](https://user-images.githubusercontent.com/38438046/68547768-a93d9180-03e5-11ea-912a-e30b2f70e38a.png)

**Comment by stefanspiska** [comment]
fixed in https://github.com/ehrbase/ehrbase/pull/110
