### ISSUE TITLE
Possible composition serialization bug

### ISSUE THREAD

**Issue by talex1** [ehrbase/ehrbase#339]
## Background ##

I've tried many times to add a template and a composition that suits it, but every time I try to add composition, I get an error:
{
     "error": "java.lang.IllegalArgumentException",
     "status": "Bad Request"
}
 
## Expected output ##

 Where can I find a working template and composition set that I can send to ehrbase?

## Success criteria ##

- [ ] add template to ehrbase
- [ ] add composition to ehrbase

**Comment by jakesmolka** [comment]
Hey! Can you give a more detailed description of want you are doing (what REST endpoint with what headers etc., what template and composition)? So we can reproduce the error and fix it.

Meanwhile here's a simple set I've been working with:

[template+composition.zip](https://github.com/ehrbase/ehrbase/files/5353323/template%2Bcomposition.zip)

**Comment by stefanspiska** [comment]
@talex1 
you can use https://github.com/ehrbase/documentation/tree/master/examples
Import the files into https://www.postman.com/ and chose the ehrbase Environment and collection

**Comment by talex1** [comment]
Thanks, template+composition.zip is ok, and  postman collection is usefull too :). Now I know that my ehrbase is working and problem is in composition and/or template.
After using composition from 
[error_example.zip](https://github.com/ehrbase/ehrbase/files/5354118/error_example.zip)
 I got an error:
{
"error": "java.lang.IllegalArgumentException",
"status": "Bad Request"
}

**Comment by jakesmolka** [comment]
Was able to follow the problem up to here, but then stopped due to missing time: https://github.com/ehrbase/openEHR_SDK/blob/develop/serialisation/src/main/java/org/ehrbase/serialisation/dbencoding/CompositionSerializer.java#L191
Obviously our serialization works with many examples, so it is really interesting to see and find out what the problem is with the given example set.

Someone needs to take a look at this, so I marked this issue as bug to resolve.

**Comment by birgerhaarbrandt** [comment]
@talex1 

This works with the latest version of EHRbase when changing the composition accordingly:

```
 </name>
            <archetype_details>
            <archetype_id>
                <value>openEHR-EHR-OBSERVATION.laboratory_test_result-coded.v0</value>
            </archetype_id>
            <rm_version>1.0.2</rm_version>
        </archetype_details>
    <language>
      <terminology_id>
        <value>ISO_639-1</value>
      </terminology_id>
      <code_string>en</code_string>
    </language>
        <encoding>
            <terminology_id>
                <value>IANA_character-sets</value>
            </terminology_id>
            <code_string>UTF-8</code_string>
        </encoding>
```

as the archetype_details were missing and the encoding was not correct.
