### ISSUE TITLE
Wrong validation on cloned paths with different data types

### ISSUE THREAD

**Issue by birgerhaarbrandt** [ehrbase/ehrbase#346]
## Steps to reproduce ## 

Please find attached a template and an example composition. 

[LabData.zip](https://github.com/ehrbase/ehrbase/files/5418613/LabData.zip)

The template contains a cloned path with different data types and different names:

`content[openEHR-EHR-OBSERVATION.laboratory_test_result.v1, 'Befund']/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.laboratory_test_panel.v0, 'Test-Panel']/items[openEHR-EHR-CLUSTER.laboratory_test_analyte.v1, 'Pro Virus']/items[at0001, 'Nachweis']/value`

`content[openEHR-EHR-OBSERVATION.laboratory_test_result.v1, 'Befund']/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.laboratory_test_panel.v0, 'Test-Panel']/items[openEHR-EHR-CLUSTER.laboratory_test_analyte.v1, 'Pro Virus']/items[at0001, 'Viruslast (ct-Wert)']/value`

## Actual result ##

```
{
    "error": "org.ehrbase.validation.constraints.wrappers.ValidationException: :-Validation error at /content[openEHR-EHR-OBSERVATION.laboratory_test_result.v1]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.laboratory_test_panel.v0]/items[openEHR-EHR-CLUSTER.laboratory_test_analyte.v1]/items[at0001]:class com.nedap.archie.rm.datavalues.DvText cannot be cast to class com.nedap.archie.rm.datavalues.quantity.DvQuantity (com.nedap.archie.rm.datavalues.DvText and com.nedap.archie.rm.datavalues.quantity.DvQuantity are in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @1efbd816).\n\n",
    "status": "Bad Request"
}
```

## Expected result ##

This should be correct. It looks like the validation module is not considering the name predicate inside the paths.

## Success criteria ##

- [ ] The defect has been fixed
- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] Runtime warnings

**Comment by birgerhaarbrandt** [comment]
I re-tried the develop branch after the PR was merged and the validation still fails:

```
{
    "error": "org.ehrbase.validation.constraints.wrappers.ValidationException: :-Validation error at /content[openEHR-EHR-OBSERVATION.laboratory_test_result.v1]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.laboratory_test_panel.v0]/items[openEHR-EHR-CLUSTER.laboratory_test_analyte.v1]/items[at0001]:class com.nedap.archie.rm.datavalues.DvText cannot be cast to class com.nedap.archie.rm.datavalues.quantity.DvQuantity (com.nedap.archie.rm.datavalues.DvText and com.nedap.archie.rm.datavalues.quantity.DvQuantity are in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @39aeed2f).\n\n",
    "status": "Bad Request"
}
```

**Comment by stefanspiska** [comment]
The sdk version used in ehrbase still needs zu be upgrade. .
