### ISSUE TITLE
Composition is missing data

### ISSUE THREAD

**Issue by robert-hunter-nes** [ehrbase/ehrbase#350]
## Details of attached files ##

After noticing my composition was returning incorrectly in 0.14.0 I created a new composition using Better CDR and validated that I could create and retrieve it with Better CDR to be sure my composition was valid. I then confirmed it was working in EHRbase 0.11.0 which it does, but it returns incorrectly in 0.14.0. Would you be able to confirm if this is an issue or if I'm doing something wrong please? I've attached the files I'm using.

[templateAndCompositions.zip](https://github.com/ehrbase/ehrbase/files/5443799/templateAndCompositions.zip)
* NHS_Care_Scotland-NDS-Anticipatory_Care_Plan-ReSPECT-V0.3.2.opt - My template
* createComposition.json - JSON file with the composition I created in Better CDR
* createComposition.xml - Same composition but in XML
* returnedComposition.xml - The comosition I get back in 0.14.0 which is missing data

## Steps to reproduce ## 

1. Add the attached template.
2. Create a composition using the attached composition.
3. Retrieve the composition.

## Actual result ##

The composition is missing most of the data in the response.

## Expected result ##

The composition should be there in it's entirety.

## Success criteria ##

- [ ] The defect has been fixed
- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] Runtime warnings

**Comment by stefanspiska** [comment]
It seams that the composition is saved correctly in the db however when it is read not all sections a read correctly. I think this is 
https://github.com/ehrbase/openEHR_SDK/issues/117

**Comment by chevalleyc** [comment]
Hi @robert-hunter-nes  I've posted a fix at https://github.com/ehrbase/openEHR_SDK/tree/feature/350_117_missing_data . Pls could you check that out? You may need to compile locally the SDK and change ehrbase pom.xml to use it. Thanks!

**Comment by robert-hunter-nes** [comment]
Hi @chevalleyc . Thanks for such a quick response. I did pull down the branch and build it locally and buid it, but I suspect I was unsuccessful in updating my ehrbase checkout to use the dependencies correctly as I get an error creating an EHR record now. That said, if there is a fix in I can wait until the 0.15.0 release for it 😄
