### ISSUE TITLE
Retrieving saved Composition in JSON format removes all archetypeDetails except the root one on the composition

### ISSUE THREAD

**Issue by bratwurzt** [ehrbase/ehrbase#352]
The root one gets set manually:
org.ehrbase.dao.access.jooq.EntryAccess#buildArchetypeDetails

but others seem to be empty.

How to reproduce:

1. save composition 
2. retrieve it
3. compare json results

Appended file is composition to save in JSON format and its template:
[data.zip](https://github.com/ehrbase/ehrbase/files/5452311/data.zip)

Important: the archetypeDetails seem to be saved correctly:
```json
"/archetype_details": [
  {
    "/value": {
      "rmVersion": "1.0.4",
      "archetypeId": {
        "value": "openEHR-EHR-SECTION.ispek_dialog.v1",
        "rmName": "EHR",
        "rmEntity": "SECTION",
        "versionId": "1",
        "rmOriginator": "openEHR",
        "domainConcept": "ispek_dialog",
        "qualifiedRmEntity": "openEHR-EHR-SECTION"
      }
    },
    "/$CLASS$": "Archetyped"
  }
],
``` 
but this line in `org.ehrbase.dao.access.jooq.EntryAccess#retrieveInstanceInComposition`:
```java
entryAccess.composition = new RawJson().unmarshal(value, Composition.class);
```
doesn't unmarshall them correctly.

**Comment by freshehr** [comment]
This is also apparent in the XML serialisation. Also why do a number of non-RM elements appear? 

```
<qualifiedRmEntity>openEHR-EHR-COMPOSITION</qualifiedRmEntity>
	<domainConcept>report</domainConcept>
	<rmOriginator>openEHR</rmOriginator>
	<rmName>EHR</rmName>
	<rmEntity>COMPOSITION</rmEntity>
	<versionId>1</versionId>
```

These invalidate official XSD validation.

**Comment by birgerhaarbrandt** [comment]
@chevalleyc can you please link the PR here and close the issue afterwards?

**Comment by chevalleyc** [comment]
Fix with SDK PR: https://github.com/ehrbase/openEHR_SDK/pull/121
