### ISSUE TITLE
other_participation fields not being retrieved

### ISSUE THREAD

**Issue by robert-hunter-nes** [ehrbase/ehrbase#366]
Hi

I've noticed that the `other_participations` fields are not all being retrieved (it saves without error), specifically the `performer.external_ref`, `performer.identifiers`, and `time`.

To try and rule out this being user error I have tested this in BetterCDR and it works as expected. So apologies in advance if this is user error.

## Steps to reproduce ## 

I have attached a template, and a composition that shows the error, the composition has the necessary fields populated.

[CompositionMissingOtherParticipationsFields.zip](https://github.com/ehrbase/ehrbase/files/5515763/CompositionMissingOtherParticipationsFields.zip)

1. Add template
2. Create composition
3. Retrieve composition

## Actual result ##

`other_participations.performer.external_ref` is missing.
`other_participations.performer.external_ref` is missing.
`other_participations.time.lower (and upper)` does not contain the date time value.

## Expected result ##

Fields should be populated as they were in the composition when it was saved.

## Success criteria ##

- [ ] The defect has been fixed
- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] Runtime warnings

[CompositionMissingOtherParticipationsFields.zip](https://github.com/ehrbase/ehrbase/files/5515763/CompositionMissingOtherParticipationsFields.zip)

**Comment by robert-hunter-nes** [comment]
Hi. I wanted to leave an update to this issue. When I raised it I had been testing with an older version of EHRbase, but I have just tested it today against the 0.14.0 release, and it looks like it is returning the `other_participations.performer.external_ref` and `other_participations.performer.identifier` fields OK.

**Comment by chevalleyc** [comment]
@robert-hunter-nes many thanks for the update Rob!
