### ISSUE TITLE
AQL query returning only ehr_id cannot be executed

### ISSUE THREAD

**Issue by serefarikan** [ehrbase/ehrbase#367]
## Steps to reproduce ## 

wrote an integration test using a DTO generated by ehrbase SDK. Template [is here](https://ckm.highmed.org/ckm/templates/1246.169.619) 
The integration test is `runsConfirmedCovid19InfectionReportQuery` method of `PhenoTypeAqlTestIT` class in this branch of EhrBase SDK:
https://github.com/ehrbase/openEHR_SDK/tree/feature/num_study_phenotype_aqls

To reproduce the issue, please checkout the above branch and run the test.  EhrBase is running directly from the IDE, based on commit 'c75593d15c037cbd6ac8656aec80cc63050fe53f' on the develop branch, which is the latest at the time of this post.

## Actual result ##

Attempting to run the query returns the following payload:

`{"error":"Could not process query, reason:org.springframework.jdbc.BadSqlGrammarException: Access database using Jooq; bad SQL grammar [select distinct on (\"/ehr_id/value\") \"alias_3064403\".\"/ehr_id/value\" from (select \"ehr_join\".\"id\" as \"/ehr_id/value\" from \"ehr\".\"ehr\" as \"ehr_join\" where (\"ehr\".\"entry\".\"template_id\" = ? and (\"ehr_join\".\"id\"='ff36c89c-33c4-404a-a16d-1b4e48d1a812'))) as \"alias_3064403\"]; nested exception is org.postgresql.util.PSQLException: ERROR: missing FROM-clause entry for table \"entry\"\n  Position: 156","status":"Bad Request"}`

## Expected result ##

Query should return a single row with ehr_id as the only value

## Success criteria ##
The test mentioned above should pass. 

Please note the comment in the integration test code. Using more than one column in the SELECT clause of the query works. It appears the problem emerges when a single path/column is provided in the SELECT clause. 

@lmarcoruiz FYI

**Comment by wlad** [comment]
closing. fixed in https://github.com/ehrbase/ehrbase/pull/369
