### ISSUE TITLE
Order of nodes within XML serialization does not match template

### ISSUE THREAD

**Issue by freshehr** [ehrbase/ehrbase#376]
## Steps to reproduce ## 

Committed xml composition against template where order of archetypes inside content, and the order of the items within each archetype match the order in the template and component archetypes.

## Actual result ##

The retrieved XML composition retrieves some archetypes and nodes within archetypes in a different order.

## Expected result ##

As none of the containers are set as 'ordered' AFAIK, this is arguably not incorrect behaviour but it does make debugging compositions more annoying that it should be e.g using diffing tools.

## Success criteria ##

It would be preferable if the original template order was retained. 

- [ ] The defect has been fixed
- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] Runtime warnings

**Comment by birgerhaarbrandt** [comment]
@freshehr I share the view that from a database perspective, we are working with sets. Hence, preserving the order is not part  of the spec. We might be able to help improve this for the future, but for now I would consider this as "no fix required"
