### ISSUE TITLE
Brackets added to archetypeNodeId in XML serialisaiton other_context node

### ISSUE THREAD

**Issue by freshehr** [ehrbase/ehrbase#377]
## Steps to reproduce ## 

GET / composition with XML 

## Actual result ##

```xml        
<other_context xsi:type="ITEM_TREE" archetype_node_id="[at0001]" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
```

## Expected result ##
```xml
<other_context xsi:type="ITEM_TREE" archetype_node_id="at0001" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
```

## Success criteria ##

- [ ] The defect has been fixed
- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] Runtime warnings

**Comment by subigre** [comment]
Running the latest version, I cannot reproduce the issue.


```xml
<status>
    <ehrbase_version>0.17.1</ehrbase_version>
    <openehr_sdk_version>78e84f6</openehr_sdk_version>
    <archie_version>5a4a9442e5e2516aed5f25636ac236682aace7b9</archie_version>
    <jvm_version>Eclipse Foundation 11.0.12+7</jvm_version>
    <os_version>Windows 10 amd64 10.0</os_version>
    <postgres_version>
         PostgreSQL 11.5 on x86_64-pc-linux-musl, compiled by gcc (Alpine 8.3.0) 8.3.0, 64-bit
    </postgres_version>
</status>
```

XML representation:
```xml
<other_context xsi:type="ITEM_TREE" archetype_node_id="at0001" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
```


PS: Here is the complete [composition](https://github.com/ehrbase/ehrbase/files/7121368/composition.zip) and none of the `archetype_node_id` contains brackets.
