### ISSUE TITLE
FLAT JSON - a number of Entry archetypes not saved ?? THose containing DV_ORDINAL or DV_QUANTITY

### ISSUE THREAD

**Issue by freshehr** [ehrbase/ehrbase#386]
## Steps to reproduce ## 

Successfully uploaded a FLAT JSON composition that is also valid in BetterCDR. Ran GET /composition for FLAT, CANONICAL JSON and CANONICAL XML. 
## Actual result ##

There are a large number of gaps where archetyped data appears not be saved or at least is not exposed.

This appears to me to largely OBSERVATION archetypes that contain QUANTITY or ORDINAL datatypes

I have attached sorted input and output FLAT JSON compositions and canonical examples from GET /composition calls as well as the relevant .opt.

## Success criteria ##

- [x] The defect has been fixed
- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] Runtime warnings

[Compositions.zip](https://github.com/ehrbase/ehrbase/files/5555505/Compositions.zip)
[EREACT - Deterioriation assessment.v0.opt.zip](https://github.com/ehrbase/ehrbase/files/5555509/EREACT.-.Deterioriation.assessment.v0.opt.zip)

**Comment by sidharthramesh** [comment]
Yes. I can confirm that this happens. Even without the `format=FLAT` option, the XML composition is missing a lot of elements in the original. Everything but the context information of the composition was missing.

Posted:
```
{
	"initial_assesment/context/start_time": "2020-12-27T12:17:55.415Z",
	"initial_assesment/context/setting|code": "123",
	"initial_assesment/context/setting|value": "some care",
	"initial_assesment/context/setting|terminology": "local",
	"initial_assesment/glasgow_coma_scale_gcs/time": "2020-12-27T12:17:55.417Z",
	"initial_assesment/glasgow_coma_scale_gcs/language|code": "en",
	"initial_assesment/glasgow_coma_scale_gcs/language|terminology": "ISO_639-1",
	"initial_assesment/glasgow_coma_scale_gcs/encoding|code": "UTF-8",
	"initial_assesment/glasgow_coma_scale_gcs/encoding|terminology": "IANA_character-sets",
	"initial_assesment/pulse/time": "2020-12-27T12:17:55.418Z",
	"initial_assesment/pulse/language|code": "en",
	"initial_assesment/pulse/language|terminology": "ISO_639-1",
	"initial_assesment/pulse/encoding|code": "UTF-8",
	"initial_assesment/pulse/encoding|terminology": "IANA_character-sets",
	"initial_assesment/category|code": "433",
	"initial_assesment/category|value": "event",
	"initial_assesment/category|terminology": "openehr",
	"initial_assesment/language|code": "en",
	"initial_assesment/language|terminology": "ISO_639-1",
	"initial_assesment/territory|code": "IN",
	"initial_assesment/territory|terminology": "ISO_3166-1",
	"initial_assesment/composer|name": "Sidharth Ramesh",
	"initial_assesment/glasgow_coma_scale_gcs/best_eye_response_e|ordinal": 2,
	"initial_assesment/glasgow_coma_scale_gcs/best_verbal_response_v|ordinal": 3,
	"initial_assesment/glasgow_coma_scale_gcs/best_motor_response_m|ordinal": 4,
	"initial_assesment/pulse/presence|code": "at1024",
	"initial_assesment/pulse/rate|unit": "/min",
	"initial_assesment/glasgow_coma_scale_gcs/best_eye_response_e|code": "at0011",
	"initial_assesment/glasgow_coma_scale_gcs/best_eye_response_e|value": "To pressure",
	"initial_assesment/glasgow_coma_scale_gcs/best_verbal_response_v|code": "at0016",
	"initial_assesment/glasgow_coma_scale_gcs/best_verbal_response_v|value": "Words",
	"initial_assesment/glasgow_coma_scale_gcs/best_motor_response_m|code": "at0022",
	"initial_assesment/glasgow_coma_scale_gcs/best_motor_response_m|value": "Normal flexion",
	"initial_assesment/glasgow_coma_scale_gcs/total_score": 9,
	"initial_assesment/pulse/presence|value": "Present",
	"initial_assesment/pulse/presence|terminology": "local",
	"initial_assesment/pulse/rate|magnitude": 56
}
```
Retrieved:
```
{
  "meta": {
    "href": {
      "url": "http://ac921189338f:8080/ehrbase/rest/ecis/v1/composition1bf7ae96-62d8-426e-a6a5-04020bbb4f6f"
    }
  },
  "action": "RETRIEVE",
  "composition": {
    "initial_assesment/language|code": "en",
    "initial_assesment/language|terminology": "ISO_639-1",
    "initial_assesment/composer|name": "Sidharth Ramesh",
    "initial_assesment/territory|code": "IN",
    "initial_assesment/territory|terminology": "ISO_3166-1",
    "initial_assesment/category|terminology": "openehr",
    "initial_assesment/category|value": "event",
    "initial_assesment/category|code": "433",
    "initial_assesment/context/setting|code": "123",
    "initial_assesment/context/setting|value": "some care",
    "initial_assesment/context/setting|terminology": "local",
    "initial_assesment/context/start_time": "2020-12-27T12:17:55.415Z",
    "initial_assesment/_uid": "1bf7ae96-62d8-426e-a6a5-04020bbb4f6f::local.ehrbase.org::1"
  },
  "format": "FLAT",
  "templateId": "kmc.initial_assesment.v0",
  "ehrId": "7f9f922f-461a-484d-95c3-b6961e7d9c7b",
  "compositionUid": "1bf7ae96-62d8-426e-a6a5-04020bbb4f6f"
}
```

Opt: [kmc.initial_assesment.v0.opt.txt](https://github.com/ehrbase/ehrbase/files/5744548/kmc.initial_assesment.v0.opt.txt)

**Comment by sasurfer** [comment]
I confirm I have a similar problem in ehrbase version 0.14 both posting in xml and json. When the composition is retrieved it misses all the items inside the slot archetypes but one.  (It happens both in the representation shown when I post the composition and in the persisted one retrieved via REST GET)
At the following link:
[link to files](https://gist.github.com/sasurfer/5ce614cf4947f1e6ecb843ba081cc566)
I pasted:
-the opt for the compositions. its name is Case4.opt
-a json composition named case.json
-the retrieved json composition named case_retrieved.json
-a xml composition named case2.xml
-the retrieved json composition named case2_retrieved.json
 
For example comparing the json composition with the one retrieved in three points I have and archetype which has more than one item but only one is retrieved, e.g. Archetype openEHR-EHR-CLUSTER.multimedia.v0 has at0001, at0002, at0008, at0006, at0009. Only at0009 is returned
