### ISSUE TITLE
getting of all compositions of specified FOLDER

### ISSUE THREAD

**Issue by mannro** [ehrbase/ehrbase#389]
How can i get all compositions, (whole data object, not only references) of specified FOLDER?
In AQL: SELECT f FROM FOLDER f return something like:
`
{
    "q": "\r\n  SELECT f FROM FOLDER f",
    "columns": [],
    "rows": [
        [],
        [],
        [],
...
        []
    ]
}
`
number of empty arrays in rows is equals to number of contributions

**Comment by birgerhaarbrandt** [comment]
Hi  @mannro, 

unfortunately AQLs on Folders are not (yet) supported in EHRbase. In general, this is not specified in the AQL spec from openEHR but we are really interested how this is done for example in DIPS' implementation.

HTH
