### ISSUE TITLE
Add Spring Boot Actuator / Telemetry for operational monitoring

### ISSUE THREAD

**Issue by grantforrester-nes** [ehrbase/ehrbase#392]
## Background ##

_Describe what this story is for and the value the customer will gain from it._

In order to ensure that operations teams can easily monitor the behaviour of an EHRbase deployment it would be useful for EHRbase to provide [liveness/readiness](https://cloud.google.com/blog/products/gcp/kubernetes-best-practices-setting-up-health-checks-with-readiness-and-liveness-probes) endpoints and a metrics endpoint that provides [RED metrics](https://thenewstack.io/monitoring-microservices-red-method/) that can be easily scraped by a tool such as Prometheus.

In this way should EHRbase availability, responsiveness or error rates begin to report out-of-normal values then the operations team can be alerted quickly and begin investigation.

## Acceptance criteria ##

_These are the functional requirements for this story. Add all steps to be implemented to fulfill the requirements._

- [x] The EHRbase service exposes telemetry on a configurable port which may be separate to the port the REST API is exposed on
- [x] A `/liveness` endpoint is available on the telemetry port that shows the EHRbase service is running
- [x] A `/readiness` endpoint is available on the telemetry port that shows the EHRbase service is ready to accept traffic
- [x] A `/metrics` endpoint is is available on the telemetry port that provides metrics in the [Prometheus exposition format](https://github.com/prometheus/docs/blob/master/content/docs/instrumenting/exposition_formats.md).
- [x] The metrics exposed contain at least the [RED metrics](https://thenewstack.io/monitoring-microservices-red-method/) for Request rate, Error rate, request Duration.
- [x] The Error rates are also provided grouped by status code.
- [x] Other useful metrics would be memory consumption and database connection pool size.

## Success criteria ##

- [ ] Review / Merge request approved (P2P session)
- [x] Unit tests passed
- [x] Updated documentation (Javadoc and Sphinx)
- [x] Acceptance criteria fulfilled
- [x] Build without errors
- [x] Release notes prepared
- [x] Runtime warnings

**Comment by grantforrester-nes** [comment]
I believe that most (or all) of these requirements could be satisfied by including the Maven dependency `spring-boot-starter-actuator` ([documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html)) module into EHRbase.  The above features requested can then be activated & configured through Java system properties. 🤞

**Comment by jakesmolka** [comment]
Adding the Spring Boot Actuator should be easy, while adding many features. So I'm in favor of doing that, also because we had that on our plate some time ago already. :+1:
