### ISSUE TITLE
How to update already created template

### ISSUE THREAD

**Issue by YogeshSomawar** [ehrbase/ehrbase#394]
## Background ##

We are using ehrbase for our research where template is evolving in stages. Fr this we need to update the template with archetypes details. I cant find an API call to update already created template. Could somebody help me for updating templates? 
## Expected output ##

Able to update templates.

**Comment by jakesmolka** [comment]
Hey @YogeshSomawar! This operation is not supported by the official openEHR REST API, which we are implementing in EHRbase. But as this was a requirement before we made it possible to overwrite a template, in the following two ways:

- Set the environment variable `SYSTEM_ALLOW_TEMPLATE_OVERWRITE` to true and just POST the new template, like you submitted the original one. 
- Use our custom Admin API: Set the environment variable `ADMINAPI_ACTIVE` to true and update the template with a PUT (I'm actually working on the documentation of the Admin API right now and I will push it today, so please wait for the details). 

But keep in mind that you have to keep track of your compositions and their validity on your own, when using those advanced options. Overwriting a template might invalidate existing compositions using that template.

A more openEHR compliant ways would be to bump the version number of the template, when you modify it. For instance, the following original template payload

``` xml
 <template_id>
    <value>minimal_admin.en.v1</value>
  </template_id>
```

could be bumped into

``` xml
 <template_id>
    <value>minimal_admin.en.v2</value>
  </template_id>
```

**Comment by jakesmolka** [comment]
Here's the almost-done version of the Admin API documentation: https://ehrbase.readthedocs.io/en/feature-434_admin_api/index.html
