### ISSUE TITLE
possible bug: template retrieved differ from the uploaded one

### ISSUE THREAD

**Issue by sasurfer** [ehrbase/ehrbase#401]
## Configuration information

Result of the GET with that endpoint:
http://localhost:8080/ehrbase/rest/openehr/v1/status
404
{"timestamp":"2020-12-16T16:44:18.146+00:00","status":404,"error":"Not Found","message":"No message available","path":"/ehrbase/rest/openehr/v1/status"}

- EHRbase version: 0.14.0 dockerized
- openEHR_SDK version:
- Archie version:
- PostgreSQL version:
- Java Runtime version:
- Operating System version: Ubuntu 18.04

## Steps to reproduce ## 

I uploaded a template (Case2.opt) and retrieved it (Case2_retrieved.opt).
The two templates are in:
https://gist.github.com/sasurfer/6599af01a0af24e9cfe812ddad816623

They differ. Specifically, in the uploaded one the node at0073 is present both in the structure (line 1451) and in the term definition (1656) while in the retrieved only in the term definition(1655). Moreover the at0074 is present in the structure only for the retrieved one (1310) and the description is wrong (is the same as the at0073 whereas should be Specimen processing type etc) :
Case2.opt line 1656-1663
                                <term_definitions code="at0073">
                                    <items id="text">Image micron per pixel</items>
                                    <items id="description">The sampling method used. e.g dissection, block sampling.</items>
                                </term_definitions>
                                <term_definitions code="at0074">
                                    <items id="text">Specimen processing type</items>
                                    <items id="description">A physical process applied to the specimen e.g.  block embedding.</items>
                                </term_definitions>
Case2_retrieved.opt
                               <term_definitions code="at0073">
                                    <items id="text">Image micron per pixel</items>
                                    <items id="description">The sampling method used. e.g dissection, block sampling.</items>
                                </term_definitions>
                                <term_definitions code="at0074">
                                    <items id="text">Image micron per pixel</items>
                                    <items id="description">A physical process applied to the specimen e.g.  block embedding.</items>
                                </term_definitions>

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by stefanspiska** [comment]
@sasurfer 
I tested you Template with the current dev and the returned template is identical (minus some minor formatting differences) to the provided  one.

Now the template parsing and storage did not change between Version 14 and dev. How there was a bug  where the cache and db could become out of sync when a template was updated.

Was  this template "Case" by any change updatetet?

**Comment by sasurfer** [comment]
ok. I reposted the template changing uid and name and, as you said, there aren't major differences.
As you pointed out the problem must have arisen from the fact that I posted a template and then updated it.

**Comment by sasurfer** [comment]
At the same link:
https://gist.github.com/sasurfer/6599af01a0af24e9cfe812ddad816623
you can find at the end the original template I posted.
So, summarizing, I posted the Case.opt then I posted the Case2.opt and after that the GET method return the buggy template.
If I post the template Case2.opt with a different name and uuid then the GET returns the original template.

**Comment by stefanspiska** [comment]
I did not test this but: 

If you run the docker Image with property:
`CACHE_ENABLED=false`
this should disable  the  cache.
If you then the start the image again with `CACHE_ENABLED=true` ehrbase should rebuild the cache.

**Comment by sasurfer** [comment]
So if I understand correctly it is a bug that you have already fixed in the dev version ( and it will be in the next release). In the meantime if I update a template I have to drop the old cache in order to rebuild it and avoid that kind of conflict between cache and persisted db.

**Comment by stefanspiska** [comment]
yes that's what it looks like for me.

**Comment by stefanspiska** [comment]
You could of cause always run with CACHE_ENABLED=false
But that will cost you performance, especially if you have lots of templates and want to run aql.

**Comment by sasurfer** [comment]
yeah. I see. I would do it if necessary. thanks
