### ISSUE TITLE
Get error creating template in `ehrbaseorg/ehrbase:next` 

### ISSUE THREAD

**Issue by robert-hunter-nes** [ehrbase/ehrbase#404]
## Configuration information

Using the docker image `ehrbaseorg/ehrbase:next` when I try to add my template I get an error. It works fine in `ehrbaseorg/ehrbase:0.14.0`, and also when I try it in `Better CDR`, so I'm wondering if there's a bug introduced. Sorry for raising an issue against the `next` tag, but we're hoping to upgrade to the next beta release when it is out.

- EHRbase version: ehrbaseorg/ehrbase:next (Digest:sha256:376fd010cd90f29afe0cce1bc94f83c84e1dc0bd336eba8d42129663e860cd49) 
- openEHR_SDK version:
- Archie version:
- PostgreSQL version: ehrbaseorg/ehrbase-database-docker:11.5
- Java Runtime version:
- Operating System version:

## Steps to reproduce ## 

Running `ehrbaseorg/ehrbase:next` in docker when I try to add my template (attached) I get a 400 Bad Request response

[ReSPECT-3.v0.opt.zip](https://github.com/ehrbase/ehrbase/files/5729472/ReSPECT-3.v0.opt.zip)

## Actual result ##

```
{
    "error": "Invalid template: Index 1 out of bounds for length 1",
    "status": "Bad Request"
}
```

## Expected result (Acceptance Criteria) ##

Expect the template to be added successfully

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by stefanspiska** [comment]
Caused by https://github.com/ehrbase/openEHR_SDK/issues/158
