### ISSUE TITLE
Running application using Docker database

### ISSUE THREAD

**Issue by DanialBetres** [ehrbase/ehrbase#423]
## Configuration information

I'm trying to run the application but i'm getting the following error when running `java -jar application/target/application-0.14.0.jar`

![image](https://user-images.githubusercontent.com/23747649/106704290-ddd4d480-65b9-11eb-85db-da6b586e2604.png)

I already had postgres running on my computer so I had to change the port the docker container was running on my host computer. I changed it to 5431. I updated the port in the [pom.xml](https://github.com/ehrbase/ehrbase/blob/develop/pom.xml#L139) file but are there other places i'm supposed to update as well? 

- EHRbase version: 0.14.0
- openEHR_SDK version:
- Archie version:
- PostgreSQL version:
- Java Runtime version:
- Operating System version:

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by sidharthramesh** [comment]
Seems like Ehrbase is trying to connect to a different database.

Exact steps to reproduce would help:
1. How did you start your docker database container?
2. How did you start your ehrbase container?
3. Are you running another database on your computer? If so on what port?

You can also take a look at [this guide](https://standardsmania.blogspot.com/2020/09/deploying-ehrbase-to-aws-in-5-minutes.html?m=1).

**Comment by DanialBetres** [comment]
Hey @sidharthramesh,

1. I started my docker database container with this command: `docker run --name ehrdb --network ehrbase-net -e POSTGRES_PASSWORD=postgres -d -p 5431:5432 ehrbase/ehrbase-postgres:latest`

2. I cloned ehrbase on my local computer, so it's not running in a docker container. I tried to run ehrbase using the following command: `java -jar application/target/application-0.14.0.jar`

3. I have another docker database (postgres) container running and it's on port 5432. This is why I tried to change the port for the postgres database (For ehrbase) to 5431. But I think there may be more places to change it but i'm just not sure where.

**Comment by sidharthramesh** [comment]
The ehrbase docker image takes an environment variable `DB_URL`. It is set by default to `jdbc:postgresql://ehrdb:5432/ehrbase`. You can try changing this in your shell before running java. You can also try changing the `DB_USER` and `DB_PASS` environment variables if you've changed them. I am not sure what the db URL in the pom file does.

**Comment by DanialBetres** [comment]
That didn't seem to work. I think it is an issue with the port. I just ended up using 5432. Thanks for the help!
