### ISSUE TITLE
Cant view tables in docker postgres db

### ISSUE THREAD

**Issue by DanialBetres** [ehrbase/ehrbase#426]
## Configuration information

I'm following the instructions found in the [documentation](https://ehrbase.readthedocs.io/en/latest/02_getting_started/index.html) and after completing all the steps in the `Getting Started` section, I'm trying to actually see the tables in postgres. 

My postgres instance is running through a docker container, and when I list all db's I see the following: 
![image](https://user-images.githubusercontent.com/23747649/107179975-c88aec00-69a5-11eb-9751-97b1c2d6966a.png)

When I connect to any of the db and then list the tables, I don't get any results back: 
![image](https://user-images.githubusercontent.com/23747649/107180027-dfc9d980-69a5-11eb-88a9-4961f2ecc40d.png)

Based off the `getting started` guide, I have uploaded a template, created a EHR, and loaded some data based off the template. I would like to see any of this data in the postgres database but doesn't seem like it's there. Am I doing something wrong? Or am I not understanding how this works? 

BTW, the docs are great! They have been amazing at getting me started :) 

Also if there's a better place to post questions like this, please let me know. It doesn't feel right posting this as an issue, but i'm not sure where else to direct this to.

 <ehrbase_version>0.14.0</ehrbase_version>
    <openehr_sdk_version>9dc1adb</openehr_sdk_version>
    <archie_version>dc09642</archie_version>
    <jvm_version>Oracle Corporation 14.0.1+7</jvm_version>
    <os_version>Mac OS X x86_64 10.15.7</os_version>
    <postgres_version>PostgreSQL 11.5 on x86_64-pc-linux-musl, compiled by gcc (Alpine 8.3.0) 8.3.0, 64-bit</postgres_version>

**Comment by jakesmolka** [comment]
Hey @DanialBetres! I'm not 100% sure what your screenshots are showing, but I can access my local EHRbase docker DB instance via tools like pgAdmin. Settings would be
- localhost:5432 and `postgres` user
- select the `ehrbase` DB

Does that help?
