### ISSUE TITLE
A template that is in use by a composition should reject updates

### ISSUE THREAD

**Issue by wlad** [ehrbase/ehrbase#437]
## Test Case/s To Reproduce Issue

```robotframework
011 ADMIN - Update Template That Is In Use
    [Tags]    437    not-ready    bug
    [Documentation]     A template that is in use by a composition has to reject updates.
    upload valid OPT    minimal/minimal_admin.opt
    create new EHR (XML)
    commit composition (XML)    minimal/minimal_admin.composition.extdatetimes.xml
    (admin) update OPT    minimal/minimal_admin_updated.opt
    validate PUT response - 422 unprocessable entity

    # comment: make sure the template was NOT modified:
    ${resp}=    Get Request    ${SUT}    /definition/template/adl1.4/${template_id}
                ...    headers=${headers}
                log    ${resp.content}
                XML.Element Text Should Be    ${resp.content}    Minimal admin
                ...                           xpath=concept

    [Teardown]    Run Keywords    (admin) delete composition    AND
                  ...             (admin) delete all OPTs
```

```
# path to test case
tests/robot/ADMIN_TESTS/005-Template.robot
```

```
# robot command to execute related test case(s) in your terminal/console
cd tests
robot -v SUT:ADMIN-TEST -d results/ -L TRACE -i 437ANDadminANDtemplate robot/ADMIN_TESTS/

```

## Actual Result
200
template is modified

![image](https://user-images.githubusercontent.com/64201310/107942430-822c2300-6f8b-11eb-87c5-eb5ce682d638.png)

## Expected Result

422
template is NOT modified

**Comment by freshehr** [comment]
Completely agree that this is the correct behaviour for a production environment but it will make template development and testing very painful if enforced rigorously. We need a setting to apply in design-time environments that ignore this rule.

**Comment by wlad** [comment]
@maximni-vg  should be (re)assigned ???

**Comment by vladislavploaia** [comment]
Issue checked by CDR Core team. Will update once I have any. As for now, documentation seems to not cover this case.

**Comment by vladislavploaia** [comment]
Comments provided by Alexandru Vidrean. PFB:
![image](https://user-images.githubusercontent.com/100927963/177767049-307c8678-ba27-473a-afcc-db24a28caff9.png)

**Comment by freshehr** [comment]
The .env setting in ehrbase to disable this behaviour for development is

SYSTEM_ALLOW_TEMPLATE_OVERWRITE=true

but is not well documented!!

I'm happy with this is a solution to may concerns but should be clearly documented as it is a common newbie problem

**Comment by vladislavploaia** [comment]
**SYSTEM_ALLOW_TEMPLATE_OVERWRITE** environment variable has nothing to do with ADMIN endpoint to update template (PUT /rest/admin/template/{template_id}).
ADMIN endpoint for update template will update it in all cases (even with Composition linked).
**SYSTEM_ALLOW_TEMPLATE_OVERWRITE** environment variable is enabling/disabling template update through normal endpoint.
POST http://{ehrbase_host:port}/ehrbase/rest/openehr/v1/definition/template/adl1.4

1. overwrite=false
- update template without compo - 409 Conflict
![Image](https://github.com/user-attachments/assets/e59191c6-123a-4dc0-830e-11b3292b0197)
- update template with compo - 409 Conflict
