### ISSUE TITLE
ADMIN PUT /admin/template/${template_id} creates new DB entry instead returning an error

### ISSUE THREAD

**Issue by wlad** [ehrbase/ehrbase#444]
## Test Case/s To Reproduce Issue

```robotframework
016 ADMIN - PUT Method Should Not Create New DB Entries
    [Tags]    444    not-ready    bug
    [Documentation]     1. Upload OPT via 'normal' REST endpoint \n\n
    ...                 2. Use 'admin' update endpoint with template_id from step 1 \n\n
    ...                    with a different payload than in step 1 \n\n
    ...                    (especially with a different uid and template_id in the payload) \n\n
    ...                 3. Assert a proper error message is returned and \n\n
    ...                    no new records created in DB. \n\n
    upload valid OPT    minimal/minimal_admin.opt
    (admin) update OPT    minimal/minimal_action.opt    # NOTE: a different OPT is used as payload!!!
    Connect With DB
    ${opt_records}=     Count Rows In DB Table    ehr.template_store
                        Should Be Equal As Integers    ${opt_records}       ${1}

    [Teardown]    Run Keywords    (admin) delete all OPTs
```

```
# path to test case
tests/robot/ADMIN_TESTS/005-Template.robot
```

```
# robot command to execute related test case(s) in your terminal/console
cd tests
robot -v SUT:ADMIN-TEST -d results/ -L TRACE -i 444 robot/ADMIN_TESTS/

```

## Actual Result

200
a new OPT record is created in DB
![image](https://user-images.githubusercontent.com/64201310/108594820-74581280-737c-11eb-9aba-1cfdf8f35934.png)

## Expected Result
- Proper error message that indicates that `templated_id`in URL parameter does not match the one provided as payload in request's body.
- 404 ???
- 400 - Bad Request ???

**Comment by subigre** [comment]
@wlad, does Admin API have to support `Prefer` header like the standard openEHR REST API?

I just go quickly over the Admin API controllers and none of them is currently handling this header

**Comment by wlad** [comment]
@subigre tbh I don't know. I just expected it, because the other endpoints had it. I guess this should be clarified then? FYI @birgerhaarbrandt @maximni-vg

**Comment by subigre** [comment]
From "business" perspective, I am not sure that there is an added value for Admin API. 
But if we manage it, I think we have to address all Admin API endpoints.

**Comment by maximni-vg** [comment]
Not sure if I understand that correctly, but it seems that we have two separate issues here:

- PUT inserts a new template, instead of updating/failing:
From the [API docs](https://ehrbase.readthedocs.io/en/latest/03_development/07_admin/05_template/index.html#put-admin-template-template-id), this endpoint should update an existing template, also from regular REST PUT semantics, this endpoint behaves like a POST, when the IDs do not match?

- Prefer header support / implementation:
Aside from it seemingly not working, I agree with @subigre that I dont see actual value for the Admin API here, and since it does not seem to work anyway, I'd rather drop this header from the Admin API completely. Its definitly a neat nice-to-have, but I dont see it milestoned priority-wise somewhere currently.

**Comment by wlad** [comment]
> but it seems that we have two separate issues here

yes, the original issue here does not have anything to do with headers. But there is another ticket (I don't have it's ID at hand), which should be updated to say that related test(s) has to be fixed.

**Comment by vladislavploaia** [comment]
Checked manually this flow and only 1 record was present in ehrbase DB, after PUT Template.
![image](https://user-images.githubusercontent.com/100927963/218103258-77637f5f-9d31-48d0-ad2b-15bc4d5bedc9.png)
![image](https://user-images.githubusercontent.com/100927963/218103346-e5bf2214-85ff-44fc-8ee5-955f9153c348.png)
Will update Robot Test Case, to run below mentioned query (template_id will be dynamically set, depending on template used in test):
![image](https://user-images.githubusercontent.com/100927963/218103613-7db6605a-c11b-4f11-b44f-f78c992bd30e.png)
Closing ticket.
CC: @vidi42
