### ISSUE TITLE
AQL path not unique for template nodes while creating WebTemplate

### ISSUE THREAD

**Issue by sasurfer** [ehrbase/ehrbase#464]
## Configuration information

- EHRbase version:
- openEHR_SDK version:
- Archie version:
- PostgreSQL version:
- Java Runtime version:
- Operating System version:
<?xml version='1.0' encoding='UTF-8'?><status><ehrbase_version>0.15.0</ehrbase_version><openehr_sdk_version>fc328d5</openehr_sdk_version><archie_version>dc09642</archie_version><jvm_version>Oracle Corporation 11.0.10+9</jvm_version><os_version>Linux amd64 4.15.0-136-generic</os_version><postgres_version>PostgreSQL 11.5 on x86_64-pc-linux-musl, compiled by gcc (Alpine 8.3.0) 8.3.0, 64-bit</postgres_version></status>
## Steps to reproduce ## 

When I create a template with nested archetypes I receive a warning about aql paths not uniques while they are.

A simple template and the message displayed in EHRbase can be found at this address:

https://gist.github.com/sasurfer/509e778d6e6ecf603dd781e18cc4addb

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by sasurfer** [comment]
The problem persist in the 0.16 version. The warning keep showing and an AQL search on that template doesn't give all the leaf values. In the example I posted only one of the two boolean values is returned. The other is returned as null.

**Comment by chevalleyc** [comment]
Hi @sasurfer the reason of this warning is that we have decided to resolve containment clause on a meta-level using the webtemplate representation. In the past we used path indexing on actual compositions and this has proven to be a massive bottleneck in querying performance. 

Hence, whenever for a CONTAINS clause to be resolved it is expected that the path to an item stucture node is unique. 

As per specification `A node predicate defines criteria on fine-grained data.` (AQL), we have applied this reasoning to our resolution strategy. The benefit is that performance wise, querying is fast and stable regardless of the DB size (at least on the CONTAINS clause level obviously). I would recommend refactoring your template to suit this approach. Thanks!

**Comment by sasurfer** [comment]
Hi @chevalleyc . I'm not sure I got your point. Are you saying that this kind of template cannot be processed by EHRbase?
I still consider the path to the two boolean unique and, for instance, Better(Code4health) hasn't any problem with that. 
In fact the webtemplate from Better(Code4health) has the following aqlpath for the boolean leafs:
Path1) "aqlPath": "/content[openEHR-EHR-EVALUATION.test_container.v0]/data[at0001]/items[openEHR-EHR-CLUSTER.test_cluster_containing_clusters.v0,'metalike2']/items[openEHR-EHR-CLUSTER.testcluster.v0,'updatelike2']/items[at0002]/value"
Path2) "aqlPath": "/content[openEHR-EHR-EVALUATION.test_container.v0]/data[at0001]/items[openEHR-EHR-CLUSTER.test_cluster_containing_clusters.v0,'phenolike']/items[openEHR-EHR-CLUSTER.test_cluster_containing_clusters.v0,'metalike']/items[openEHR-EHR-CLUSTER.testcluster.v0,'updatelike']/items[at0002]/value",

As you can see they are different in many ways (different level of nesting as the second has one more level of CLUSTER and different names assigned to the nodes).

**Comment by chevalleyc** [comment]
Hi @sasurfer I mixed up with issue https://github.com/ehrbase/ehrbase/issues/496 sorry for the confusion. The template is indeed supported and assuming you query using fully qualified paths, the result should be as expected. The issue of disambiguation of non unique path is whenever you query with 'unqualified' contains (and unconstrained nodes). f.e.  

```
SELECT c FROM EHR e CONTAINS CLUSTER c
```
Although the above is as per standard a valid query, this potentially will not return all cluster nodes as their respective full paths cannot be determined at meta-data level (that is at template definition level). The result is not complete whenever the branch to access the cluster nodes differ (f.e. different section structures in an array). But in real life, this type of query is meaningless since AQL aims at querying value points from known Archetypes...

**Comment by sasurfer** [comment]
Hi @chevalleyc. 
I understood your point.: unqualified query may not return all the values.
As you pointed out I got a different problem. I see the issue more similar to #498 . In fact, when I make this query:

select e/ehr_id/value,a_a/items[at0002]/value from EHR e contains COMPOSITION a[openEHR-EHR-COMPOSITION.health_summary.v1] contains CLUSTER a_a[openEHR-EHR-CLUSTER.testcluster.v0]

I get this result:
{"q":"select e/ehr_id/value,a_a/items[at0002]/value from EHR e contains COMPOSITION a[openEHR-EHR-COMPOSITION.health_summary.v1] contains CLUSTER a_a[openEHR-EHR-CLUSTER.testcluster.v0]","columns":[{"path":"/ehr_id/value","name":"#0"},{"path":"/items[at0002]/value","name":"#1"}],"rows":[["2e5ce3fa-67a3-444d-af2e-eb6d5310f75d",{"_type":"DV_BOOLEAN","value":true}],["2e5ce3fa-67a3-444d-af2e-eb6d5310f75d",null]]}

So one of the boolean is correctly retrieved while the other is not. Both the type and the value are not recognized.
If I try a simple REST GET I obtain the correct composition so it seems only an AQL issue.

**Comment by sasurfer** [comment]
Hi @chevalleyc  I saw your answer to #498
I tried to convert my query and I obtained the two booleans wanted.
Just a comment. In EHRbase queries you must know the complete path of the value you are interested in otherwise you cannot find them. Shouldn't be needed only a relative path to the last archetype in the query? Is it something you look forward to fix or do you think this is the correct way to do queries in openEHR? 
@freshehr, @birgerhaarbrandt  what do you think?

**Comment by sasurfer** [comment]
I was thinking about it. If, for instance, I want all the sistolic pressures for a certain patient (so ehrid). Then I create a query that searches for a composition that contains the blood pressure archetype and restrict the query to that certain ehrid. So I'm using a relative path to the known blood pressure archetype without the need to know all the templates used for that patient and their absolute full path to blood pressure. Is it a plausible scenario? Am I missing something?

**Comment by chevalleyc** [comment]
This is indeed a plausible scenario. Generally, the issue you raise is not occurring as templates are build in a way to avoid ambiguous access path for a given archetype.

**Comment by sasurfer** [comment]
ok. thank you. That is good news.
