### ISSUE TITLE
v0.15 missing from Dockerhub

### ISSUE THREAD

**Issue by lbillinghamnds** [ehrbase/ehrbase#466]
## Background ##

Hello folks,

It looks like the latest beta release is not on dockerhub. We'd really love to have the new `/metrics` stuff available for our deployment.

I was not sure which issue template fitted this situation best: please say if I should re-format it.

If we look at the GitHub releases 

```sh
$ curl "https://api.github.com/repos/ehrbase/ehrbase/releases" | jq '.[] | "tag_name=\(.tag_name), published_to_gh_at=\(.published_at)"'

"tag_name=v0.15.0, published_to_gh_at=2021-02-26T01:31:29Z"
"tag_name=v0.14.0, published_to_gh_at=2020-10-01T20:39:20Z"
"tag_name=v0.13.0, published_to_gh_at=2020-05-14T11:10:01Z"
"tag_name=v0.11.0, published_to_gh_at=2020-03-04T08:20:11Z"
"tag_name=v0.10.0, published_to_gh_at=2020-01-13T20:29:06Z"
"tag_name=v0.9.0, published_to_gh_at=2019-10-17T11:58:39Z"
```

We see v0.15 was released about 1 month ago.

When we look at the tags on dockerhub 

```sh
$ curl 'https://registry.hub.docker.com/v2/repositories/ehrbaseorg/ehrbase/tags' | jq '.results[] | "tag_name=\(.name), tag_last_pushed_to_dockerhub=\(.tag_last_pushed)"'

"tag_name=latest, tag_last_pushed_to_dockerhub=2020-10-01T19:51:11.388283Z"
"tag_name=next, tag_last_pushed_to_dockerhub=2021-02-17T15:32:44.702734Z"
"tag_name=0.14.0, tag_last_pushed_to_dockerhub=2020-10-01T20:51:51.756379Z"
"tag_name=0.13.0, tag_last_pushed_to_dockerhub=2020-05-14T11:37:48.492479Z"
"tag_name=0.12.0, tag_last_pushed_to_dockerhub=2020-03-31T12:28:44.611768Z"
"tag_name=0.11.0, tag_last_pushed_to_dockerhub=2020-03-09T10:24:29.184265Z"
"tag_name=0.10.0, tag_last_pushed_to_dockerhub=2020-02-26T12:29:11.298546Z"
```

We see that 0.15.0 is missing, and that the `latest` tag's date suggests it is an alias for v0.14.0.

It seems like the dockerhub parts of the release process([6. merge into develop: note 1](https://github.com/ehrbase/ehrbase/blob/ff8c469be62974986c31447cae6f3d4a5d2fe7ab/doc/release/README.md#06-merge-into-develop) and [7. merge into master: note 1](https://github.com/ehrbase/ehrbase/blob/ff8c469be62974986c31447cae6f3d4a5d2fe7ab/doc/release/README.md#07-merge-into-master)) may have failed.

Possibly related to #449 and #450.

## Acceptance Criteria ##

- [ ] version 0.15.0 will be in the dockerhub tags (via `curl 'https://registry.hub.docker.com/v2/repositories/ehrbaseorg/ehrbase/tags'`)
- [ ] tag `latest` will point to the latest beta version (via same `curl` as above)

## Definition of Done ##

- [ ] Output has been reviewed or presented and has been approved
- [ ] Documentation has been updated (Sphinx, Javadoc, Guidelines, etc.) if applicable

**Comment by sasurfer** [comment]
Hi,
I got it by pulling it by tag: 
ehrbase/ehrbase:0.15.0

I modified the image value in the docker-compose.yml contained in the main dir of the github tar.

Hope it helps
Giovanni
