### ISSUE TITLE
Incorrect uid responses from Commit FLAT JSON

### ISSUE THREAD

**Issue by freshehr** [ehrbase/ehrbase#481]
## Configuration information

{
    "ehrbase_version": "0.16.1",
    "openehr_sdk_version": "6f242df",
    "archie_version": "5a4a9442e5e2516aed5f25636ac236682aace7b9",
    "jvm_version": "Oracle Corporation 11.0.10+9",
    "os_version": "Linux amd64 5.4.0-1031-azure",
    "postgres_version": "PostgreSQL 11.6, compiled by Visual C++ build 1800, 64-bit"
}

## Steps to reproduce ## 

POST ecis FLAT composition

## Actual result ##

```{
    "meta": {
        "href": {
            "url": "http://343de15de87a:8080/ehrbase/rest/ecis/v1/composition8823ab0a-9b34-4bf8-a86a-314b6df8d43f::1"
        }
    },
    "action": "CREATE",
    "compositionUid": "8823ab0a-9b34-4bf8-a86a-314b6df8d43f::1"
}
```
Missing /after composition in the url

SystemID missing from both the url and the compositionUid

## Expected result (Acceptance Criteria) ##

```{
    "meta": {
        "href": {
            "url": "http://343de15de87a:8080/ehrbase/rest/ecis/v1/composition/8823ab0a-9b34-4bf8-a86a-314b6df8d43f::local.ehrbase.org::1"
        }
    },
    "action": "CREATE",
    "compositionUid": "8823ab0a-9b34-4bf8-a86a-314b6df8d43f::local.ehrbase.org::1"
}
```
## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by sidharthramesh** [comment]
Also, why is the host `343de15de87a:8080`? Any way to tell ehrbase what the URL of the server should be?

**Comment by jakesmolka** [comment]
This UID is wrong. It is missing the system identifier, like `.. ::ehrbase.org:: ..` (unless the EhrScape API actually handles this different, historically). This identifier can be set via:
https://github.com/ehrbase/ehrbase/blob/develop/application/src/main/resources/application.yml#L115

**Comment by freshehr** [comment]
@jakesmolka - I think I do have the SYSTEM_NAME set correctly via the .env file (I just changed the SYSTEM_NAME from the provided example) although I can't see how this marries up with the .yml, and I'm not sure what does need to be changed in the config.

original - SYSTEM_NAME=local.ehrbase.org
mine - SYSTEM_NAME=freshehr.ehrbase.org

Maybe the .env is wrong? should it be SERVER_NODENAME?

Also there is a missing / in the response `meta`

```
"meta": {
        "href": {
            "url": "http://343de15de87a:8080/ehrbase/rest/ecis/v1/composition8823ab0a-9b34-4bf8-a86a-314b6df8d43f::1"
        }
```
Should be 

```
    "url": "http://343de15de87a:8080/ehrbase/rest/ecis/v1/composition/8823ab0a-9b34-4bf8-a86a-314b6df8d43f::1"
```

**Comment by jakesmolka** [comment]
@freshehr The shown part in the application.yml is just the root place for the configuration. With Spring Boot the following mechanism and its possibilities to overwrite configs kicks in too: https://docs.spring.io/spring-boot/docs/2.5.0/reference/html/features.html#features.external-config (i.e. env vars are overwriting default values, but maybe your setup has something set that overwrites env vars.)

And yes, your env var should be `SERVER_NODENAME`.
See the complete list of rules for the binding: https://docs.spring.io/spring-boot/docs/2.5.0/reference/html/features.html#features.external-config.typesafe-configuration-properties.relaxed-binding.environment-variables

**Comment by freshehr** [comment]
Yes - the env vars are overwriting quite nicely (except I had the wrong env var which came from the ehrbase example .env -so that needs fixed. I'll submit a CR

**Comment by jakesmolka** [comment]
> Yes - the env vars are overwriting quite nicely (except I had the wrong env var which came from the ehrbase example .env -so that needs fixed. I'll submit a CR

See #537

**Comment by jakesmolka** [comment]
@sidharthramesh The composition UID schema will change now. This will probably affect your MedBlocks code.

**Comment by sidharthramesh** [comment]
Thanks for the mention @jakesmolka! We'll make the changes on our end.
