### ISSUE TITLE
Error in SwaggerUI by response format

### ISSUE THREAD

**Issue by ZhuYufei990** [ehrbase/ehrbase#495]
## Configuration information

    <ehrbase_version>0.16.5</ehrbase_version>
    <openehr_sdk_version>bcc19c2</openehr_sdk_version>
    <archie_version>5a4a9442e5e2516aed5f25636ac236682aace7b9</archie_version>
    <jvm_version>Debian 11.0.11+9-post-Debian-1deb10u1</jvm_version>
    <os_version>Linux amd64 4.19.0-16-amd64</os_version>
    <postgres_version>PostgreSQL 11.11 (Debian 11.11-0+deb10u1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit</postgres_version>

## Steps to reproduce ## 

open SwaggerUI 
go to EHR API --> GET /rest/openehr/v1/ehr,
add "application/json" to "Accept", and set the subject_id and subject_namespace, then "Execute"
then delete the input in "Accept" and execute again, got the 2nd. error reponse.

## Actual result ##
 

1. error response

    <error>Invalid mime type "application/xml, application/json": Invalid token character ',' in token "xml, application/json"</error>
    <status>Bad Request</status>

2. error response

    <error>Invalid mime type "application/xml,": Invalid token character ',' in token "xml,"</error>
    <status>Bad Request</status>

## Expected result (Acceptance Criteria) ##

200 with response body

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by ZhuYufei990** [comment]
If don't input anything in "Accept" and just execute then this error will not occur.

**Comment by jakesmolka** [comment]
Hey @ZhuYufei990! Sorry for the inconvenience, but the whole SwaggerUI part of EHRbase is currently in a transition state. Most of it will be removed.

Can you successfully perform those requests via cURL, Postman or similar tools?

In case you just wanted to check if your EHRbase instance is running correctly (that's what most people seem to use the SwaggerUI for) please try to create an EHR with cURL:

``` bash
curl --header "PREFER: return=representation" \
        --request POST \
    http://localhost:8080/ehrbase/rest/openehr/v1/ehr
```

**Comment by ZhuYufei990** [comment]
Hey @jakesmolka Thanks for the feedback! I think the APIs by EHRBase works fine via curl, Postman, etc. This bug is only by the SwaggerUI.
