### ISSUE TITLE
AQL queries not returning expected ACTIONS

### ISSUE THREAD

**Issue by svituz** [ehrbase/ehrbase#496]
## Configuration information

- EHRbase version: 0.16.5
- openEHR_SDK version: bcc19c2
- Archie version: 5a4a9442e5e2516aed5f25636ac236682aace7b9
- PostgreSQL version: PostgreSQL 11.5 on x86_64-pc-linux-musl, compiled by gcc (Alpine 8.3.0) 8.3.0, 64-bit
- Java Runtime version: Oracle Corporation 11.0.10+9
- Operating System version: "Linux amd64 4.15.0-45-generic",
## Description

When using a template that has two SECTIONS and every section has a nested ACTION, querying for the ACTION returns only the child of the first SECTION and not both. 

## Steps to reproduce ## 

- Download the template from [here](https://gist.github.com/svituz/e2569bb9a870fb55951fdde0d44728c9#file-openehr_example_template-xml) and create it in ehrbase using the REST API
- create an EHR
- Download the composition from [here](https://gist.github.com/svituz/e2569bb9a870fb55951fdde0d44728c9#file-ehrbase_aql_bug_missing_result-json) and create it in ehrbase using the REST API
- Perform the query 
```
select e/ehr_id/value, a/description[at0001]/items[at0002]/name/value from EHR e contains ACTION a
```

## Actual result ##

The output is 
```
{
    "q": "select e/ehr_id/value, a/description[at0001]/items[at0002]/name/value from EHR e contains ACTION a",
    "columns": [
        {
            "path": "/ehr_id/value",
            "name": "#0"
        },
        {
            "path": "/description[at0001]/items[at0002]/name/value",
            "name": "#1"
        }
    ],
    "rows": [
        [
            "e1f54616-338a-4eb6-86e0-621c248f339c",
            "Surgery type"
        ]
    ]
}
```

## Expected result (Acceptance Criteria) ##

```
{
    "q": "select e/ehr_id/value, a/description[at0001]/items[at0002]/name/value from EHR e contains ACTION a",
    "columns": [
        {
            "path": "/ehr_id/value",
            "name": "#0"
        },
        {
            "path": "/description[at0001]/items[at0002]/name/value",
            "name": "#1"
        }
    ],
    "rows": [
        [
            "e1f54616-338a-4eb6-86e0-621c248f339c",
            "Surgery type"
        ],
        [
            "e1f54616-338a-4eb6-86e0-621c248f339c",
            "Therapy"
        ]
    ]
}
```

## Notes:

This bug may be related to https://github.com/ehrbase/ehrbase/issues/464

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by chevalleyc** [comment]
Hi @svituz could you please post the OPT ? Tx

**Comment by svituz** [comment]
Hi @chevalleyc,
the opt is linked in the Steps to reproduce section.
It is at https://gist.github.com/svituz/e2569bb9a870fb55951fdde0d44728c9#file-openehr_example_template-xml

**Comment by chevalleyc** [comment]
Hi @svituz there is some tweaking possible to allow handling arrays at content level. In `application-local.yml`, the following section allows this:

```
  aqlConfig:
    # if true, WHERE clause is using jsquery, false uses SQL only
    useJsQuery: false
    # ignore unbounded item in path starting with one of
    ignoreIterativeNodeList: 'dummy'
    # how many embedded jsonb_array_elements(..) are acceptable? Recommended == 2
    iterationScanDepth: 10
```
However, `example-template` is resulting in a number of non unique AQL paths. Please see my comment in https://github.com/ehrbase/ehrbase/issues/464. Since the iterated section results in structurally different trees, the path to the ACTION entry cannot be uniquely resolved. As indicated, the node/name predicate is intended to be used to constraint fine grained data item. 

Thanks for this very interesting issue.

**Comment by svituz** [comment]
Setting `aqlConfig.ignoreIterativeNodeList` to 'dummy' have worked. 
Can I ask what this configuration means?

**Comment by chevalleyc** [comment]
The idea of this parameter is to identify which node to skip when evaluating the SQL expression for arrays. The problem with array expression in JSONB structure is that (AFAIK) the query planner cannot assess the cost of the query. F.e. the query mentioned in this CR, is evaluated as:

```
select 
  "ehr_join"."id" as "/ehr_id/value", 
  (ehr.xjsonb_array_elements(("ehr"."entry"."entry"#>>'{/composition[openEHR-EHR-COMPOSITION.report.v1],/content[openEHR-EHR-SECTION.procedures_rcp.v1]}')::jsonb)#>>'{/items[openEHR-EHR-ACTION.procedure.v1],0,/description[at0001],/items[at0002],0,/name,0,value}') as "/description[at0001]/items[at0002]/name/value"
from "ehr"."entry"
  right outer join "ehr"."composition" as "composition_join"
    on "composition_join"."id" = "ehr"."entry"."composition_id"
  right outer join "ehr"."ehr" as "ehr_join"
    on "ehr_join"."id" = "composition_join"."ehr_id"
where "ehr"."entry"."template_id" = 'example_template'
```
with the previous configuration, this expression is evaluated as:
```
select 
  "ehr_join"."id" as "/ehr_id/value", 
  "ehr"."entry"."entry" #>> '{/composition[openEHR-EHR-COMPOSITION.report.v1],/content[openEHR-EHR-SECTION.procedures_rcp.v1],0,/items[openEHR-EHR-ACTION.procedure.v1],0,/description[at0001],/items[at0002],0,/name,0,value}' as "/description[at0001]/items[at0002]/name/value"
from "ehr"."entry"
  right outer join "ehr"."composition" as "composition_join"
    on "composition_join"."id" = "ehr"."entry"."composition_id"
  right outer join "ehr"."ehr" as "ehr_join"
    on "ehr_join"."id" = "composition_join"."ehr_id"
where "ehr"."entry"."template_id" = 'example_template'
```
That is the array is no more expanded at content level.
