### ISSUE TITLE
AQL query returning null when different nesting level are present in the composition

### ISSUE THREAD

**Issue by svituz** [ehrbase/ehrbase#498]
## Configuration information

- EHRbase version: 0.16.5
- openEHR_SDK version: bcc19c2
- Archie version: 5a4a9442e5e2516aed5f25636ac236682aace7b9
- PostgreSQL version: PostgreSQL 11.5 on x86_64-pc-linux-musl, compiled by gcc (Alpine 8.3.0) 8.3.0, 64-bit
- Java Runtime version: Oracle Corporation 11.0.10+9
- Operating System version: "Linux amd64 4.15.0-45-generic",

## Description

If a template and a related composition presents two sections with the same child type (e.g., an ACTION) but the child is at different nesting level, when querying the composition for the child, it returns null

## Steps to reproduce ## 

- Download the template from [here](https://gist.github.com/svituz/e2569bb9a870fb55951fdde0d44728c9#file-openehr_example_template) and create it in ehrbase using the REST API
- create an EHR
- Download the composition from [here](https://gist.github.com/svituz/e2569bb9a870fb55951fdde0d44728c9#file-ehrbase_aql_bug_null_result-json) and create it in ehrbase using the REST API
- Perform the query 
```
select e/ehr_id/value, a/description[at0001]/items[at0002]/name/value from EHR e contains ACTION a
```

## Actual result ##

```
{
    "q": "select e/ehr_id/value, a/description[at0001]/items[at0002]/name/value from EHR e contains ACTION a",
    "columns": [
        {
            "path": "/ehr_id/value",
            "name": "#0"
        },
        {
            "path": "/description[at0001]/items[at0002]/name/value",
            "name": "#1"
        }
    ],
    "rows": [
        [
            "e1f54616-338a-4eb6-86e0-621c248f339c",
            null
        ]
    ]
}
```
## Expected result (Acceptance Criteria) ##

```
{
    "q": "select e/ehr_id/value, a/description[at0001]/items[at0002]/name/value from EHR e contains ACTION a",
    "columns": [
        {
            "path": "/ehr_id/value",
            "name": "#0"
        },
        {
            "path": "/description[at0001]/items[at0002]/name/value",
            "name": "#1"
        }
    ],
    "rows": [
        [
            "e1f54616-338a-4eb6-86e0-621c248f339c",
            "Therapy"
        ]
    ]
}
```

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by chevalleyc** [comment]
Pls see issue CR #496 for discussion.

To get the result, you can still constrain the aql path with node/name predicate f.e.

```
{
	"q":"
select distinct e/ehr_id/value, 
	c/content[openEHR-EHR-SECTION.procedures_rcp.v1,'Therapies']/items[openEHR-EHR-SECTION.adhoc.v1]/items[openEHR-EHR-ACTION.procedure.v1]/description[at0001]/items[at0002]/name/value,
	c/content[openEHR-EHR-SECTION.procedures_rcp.v1,'Surgery']/items[openEHR-EHR-ACTION.procedure.v1]/description[at0001]/items[at0002]/name/value
	from EHR e contains composition c contains ACTION a

   "
}
```
The result is:
```
    "columns": [
        {
            "path": "/ehr_id/value",
            "name": "#0"
        },
        {
            "path": "/content[openEHR-EHR-SECTION.procedures_rcp.v1,'Therapies']/items[openEHR-EHR-SECTION.adhoc.v1]/items[openEHR-EHR-ACTION.procedure.v1]/description[at0001]/items[at0002]/name/value",
            "name": "#1"
        },
        {
            "path": "/content[openEHR-EHR-SECTION.procedures_rcp.v1,'Surgery']/items[openEHR-EHR-ACTION.procedure.v1]/description[at0001]/items[at0002]/name/value",
            "name": "#2"
        }
    ],
    "rows": [
        [
            "bf8ba8f3-343f-49da-ae8d-8da70a145d20",
            "Therapy",
            "Surgery type"
        ]
    ]
```
It's a bit verbose but is resole the ambiguous path.

NB. distinct here is required as the query induces a Cartesian product between the section iteration.
