### ISSUE TITLE
Delete template APIs returning 404

### ISSUE THREAD

**Issue by dileep-ehr** [ehrbase/ehrbase#504]
## Configuration information

"ehrbase_version": "0.16.5",
  "openehr_sdk_version": "7efd2c4",
  "archie_version": "5a4a9442e5e2516aed5f25636ac236682aace7b9",
  "jvm_version": "Ubuntu 11.0.11+9-Ubuntu-0ubuntu2.18.04",
  "os_version": "Linux amd64 5.4.0-73-generic",
  "postgres_version": "PostgreSQL 11.5 on x86_64-pc-linux-musl, compiled by gcc (Alpine 8.3.0) 8.3.0, 64-bit"

## Steps to reproduce ## 
Added 2 templates and tried deleting them using both the delete template APIs. Tried using Postman

## Actual result ##
```
<?xml version='1.0' encoding='UTF-8'?>
<Map>
    <timestamp>2021-05-19T10:02:55.551+00:00</timestamp>
    <status>404</status>
    <error>Not Found</error>
    <message></message>
    <path>/ehrbase/rest/openehr/v1/definition/template/all</path>
</Map>
```

I am able to view the templates using GET all templates and GET template by template_id

## Expected result (Acceptance Criteria) ##
200 OK

**Comment by jakesmolka** [comment]
Hey @dileep-ehr! Thanks for your issue.
Unfortunately, there is no such thing as "delete template" in the official openEHR REST API. See https://specifications.openehr.org/releases/ITS-REST/latest/definitions.html#definitions-adl-1.4-template-post
As a workaround we introduced the `allow-template-overwrite=true` configuration in our alpha. This allows to POST the same (probably modified) template again to overwrite the original. As you can image this can produce problems with the referential integrity of existing compositions. Please treat this configuration as option for development or experimenting.

I'll close this issue for now, but feel free to reopen it if you still have problems.

**Comment by sidharthramesh** [comment]
There is a delete template API that's part of the [admin interface](https://ehrbase.readthedocs.io/en/latest/03_development/07_admin/05_template/index.html#delete-admin-template-all).

**Comment by dileep-ehr** [comment]
Two delete template APIs are available in the swagger UI. It can be quite misleading to people new to EHRbase. 

If it is not going to be implemented as it is not part of the openEHR specifications, will you be removing it from the documentation as well?

**Comment by jakesmolka** [comment]
Sorry for the misleading info there. The swagger UI will be removed, more or less, soon. We will go over to point to the official REST API as reference.

Thanks @sidharthramesh! Forgot about that.

**Comment by dileep-ehr** [comment]
Thanks
Dileep V S
*Founder*
HealtheLife Ventures LLP
m: +91 79756 70933
a: 9/1, 19th Main Road, 1st 'N" Block, Rajaji Nagar, Bangalore 560010
w: <http://ayushehr.com>ehr.network, <http://ehr.network>ayushehr.com
<http://ayushehr.com> e: ***@***.***
