### ISSUE TITLE
AQL: receive "400 Bad Request" when AQL has a shortcut of a name/value criterion in node predicate

### ISSUE THREAD

**Issue by ZhuYufei990** [ehrbase/ehrbase#507]
## Configuration information

<ehrbase_version>0.16.5</ehrbase_version>
    <openehr_sdk_version>97a8336</openehr_sdk_version>
    <archie_version>5a4a9442e5e2516aed5f25636ac236682aace7b9</archie_version>
    <jvm_version>Debian 11.0.11+9-post-Debian-1deb10u1</jvm_version>
    <os_version>Linux amd64 4.19.0-16-amd64</os_version>
    <postgres_version>PostgreSQL 11.12 (Debian 11.12-0+deb10u1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit</postgres_version>

## Steps to reproduce ## 

Try the AQL Query:
SELECT p/data[at0001]/items[at0071]/value/value as Beginn FROM EHR e CONTAINS COMPOSITION c[openEHR-EHR-COMPOSITION.fall.v1] CONTAINS ADMIN_ENTRY p[openEHR-EHR-ADMIN_ENTRY.admission.v0] WHERE c/name/value = 'Stationärer Versorgungsfall' and e/ehr_id/value = '<EhrID>' and c/context/other_context[at0001]/items[at0003,'Fall-Kennung']/value/value = '00000005'

When remove the ",'Fall-Kennung'" part in the query, then everything is OK.

## Actual result ##

"error": "Could not perform SQL query:org.postgresql.util.PSQLException: ERROR: syntax error at or near \"Fall\"\n  Position: 888, AQL expression:SELECTp/data[at0001]/items[at0071]/value/valueasBeginnFROMEHReCONTAINSCOMPOSITIONc[openEHR-EHR-COMPOSITION.fall.v1]CONTAINSADMIN_ENTRYp[openEHR-EHR-ADMIN_ENTRY.admission.v0]WHEREc/name/value='Stationärer Versorgungsfall'ande/ehr_id/value='391aa45e-ff0c-4725-828c-95ef7f9ff477'andc/context/other_context[at0001]/items[at0003,'Fall-Kennung']/value/value='00000005'<EOF>, Translated SQL:select \"ehr\".\"entry\".\"entry\" #>> '{/composition[openEHR-EHR-COMPOSITION.fall.v1],/content[openEHR-EHR-ADMIN_ENTRY.admission.v0],0,/data[at0001],/items[at0071],0,/value,value}' as \"Beginn\" from \"ehr\".\"entry\" right outer join \"ehr\".\"composition\" as \"composition_join\" on \"composition_join\".\"id\" = \"ehr\".\"entry\".\"composition_id\" join \"ehr\".\"event_context\" on \"ehr\".\"event_context\".\"composition_id\" = \"ehr\".\"entry\".\"composition_id\" right outer join \"ehr\".\"ehr\" as \"ehr_join\" on \"ehr_join\".\"id\" = \"composition_join\".\"ehr_id\" where (\"ehr\".\"entry\".\"template_id\" = ? and (jsonb_extract_path_text(cast(\"ehr\".\"js_dv_coded_text_inner\"(\"ehr\".\"entry\".\"name\") as jsonb),'value') = 'Stationärer Versorgungsfall' and \"ehr_join\".\"id\" = '391aa45e-ff0c-4725-828c-95ef7f9ff477' and jsonb_extract_path_text(cast(\"ehr\".\"js_context\"(\"ehr\".\"event_context\".\"id\") as jsonb),'other_context','/items[at0003','0',''Fall-Kennung']','/value','value') = '00000005'))",
    "status": "Bad Request"
## Expected result (Acceptance Criteria) ##

200 OK
## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by chevalleyc** [comment]
Predicate in other_context item structure is currently supported with the latest (0.17.1) code base.
