### ISSUE TITLE
AQL with ehr_id returns null results

### ISSUE THREAD

**Issue by dileep-ehr** [ehrbase/ehrbase#515]
## Configuration information
{
  "ehrbase_version": "0.16.5",
  "openehr_sdk_version": "7efd2c4",
  "archie_version": "5a4a9442e5e2516aed5f25636ac236682aace7b9",
  "jvm_version": "Ubuntu 11.0.11+9-Ubuntu-0ubuntu2.18.04",
  "os_version": "Linux amd64 5.4.0-73-generic",
  "postgres_version": "PostgreSQL 11.5 on x86_64-pc-linux-musl, compiled by gcc (Alpine 8.3.0) 8.3.0, 64-bit"
}

## Steps to reproduce ## 
curl --location --request POST 'http://localhost:8080/ehrbase/rest/openehr/v1/query/aql' \
--header 'Content-Type: application/json' \
--data-raw '{
  "q": "select a/composer/name, a/context/start_time/value as createdTime, b/data[at0001]/items[at0002]/value/value as synopsis FROM EHR e[ehr_id/value=$ehr_id] CONTAINS COMPOSITION a[openEHR-EHR-COMPOSITION.encounter.v1] CONTAINS EVALUATION b[openEHR-EHR-EVALUATION.clinical_synopsis.v1] WHERE b/data[at0001]/items[at0002]/value/value = $synopsis",
  "offset": 0,
  "fetch": 3,
  "query_parameters": {
    "ehr_id": "6a637cfe-3ed3-4396-b3a9-46a43187c171",
    "synopsis": "Clinical notes2"
  }
}'

Returns null array even when there is data. If I query all ehr_ids( without giving ehr_id), results are returned for the above ehr_id
## Actual result ##

Null array returned

## Expected result (Acceptance Criteria) ##
Should return result array as there are existing compositions
[EHRN Clinical notes.v1.zip](https://github.com/ehrbase/ehrbase/files/6566227/EHRN.Clinical.notes.v1.zip)

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by chevalleyc** [comment]
The archive only contains the OPT. Could you please post a composition and/or any steps which allow to reproduce this issue. Could you also try out your scenario against the current code base as I have posted a fix earlier today to deal with fetch and offset. Thanks

**Comment by dileep-ehr** [comment]
I do not recall the context fully. Let me try to reproduce the issue and post details

**Comment by dileep-ehr** [comment]
Tested again with 0.16.5 and was able to reproduce the following observations

Composition used
---------------
{
"ctx/language": "en",
"ctx/territory": "IN",
"ctx/time": "2020-07-29T13:04:02.506+05:30",
"clinical_notes/composer|name": "Dr Joyce Smith",
"clinical_notes/context/health_care_facility|id": "123456-123",
"clinical_notes/context/health_care_facility|id_scheme": "UUID",
"clinical_notes/context/health_care_facility|id_namespace": "EHR.NETWORK",
"clinical_notes/context/health_care_facility|name": "HealtheLife",
"clinical_notes/context/setting|code": "228",
"clinical_notes/context/setting|value": "primary medical care",
"clinical_notes/context/setting|terminology": "openehr",
"clinical_notes/category|code":"433",
"clinical_notes/category|value":"event",
"clinical_notes/category|terminology":"openehr",
"clinical_notes/clinical_synopsis:0/synopsis": "Clinical notes"
}
---------------------------------------------

**1. Post AQL **

curl --location --request POST '{{baseUrl}}/ehrbase/rest/openehr/v1/query/aql' \
--header 'Content-Type: application/json' \
--data-raw '{
  "q": "select a/composer/name, a/context/start_time/value as createdTime, b/data[at0001]/items[at0002]/value/value as synopsis FROM EHR e[ehr_id/value=$ehr_id] CONTAINS COMPOSITION a[openEHR-EHR-COMPOSITION.encounter.v1] CONTAINS EVALUATION b[openEHR-EHR-EVALUATION.clinical_synopsis.v1]",
  "offset": 0,
  "fetch": 3,
  "query_parameters": {
    "ehr_id": "29ab9b63-bd2c-4f37-bb86-83ee3e883f4f",
    "synopsis": "Clinical notes2"
  }
}'

Returns correct result with 200 OK

**2. Post AQL (inlined ehr_id)**

curl --location --request POST '{{baseUrl}}ehrbase/rest/openehr/v1/query/aql' \
--header 'Content-Type: application/json' \
--data-raw '{
  "q": "select a/composer/name, a/context/start_time/value as createdTime, b/data[at0001]/items[at0002]/value/value as synopsis FROM EHR e[ehr_id/value=29ab9b63-bd2c-4f37-bb86-83ee3e883f4f] CONTAINS COMPOSITION a[openEHR-EHR-COMPOSITION.encounter.v1] CONTAINS EVALUATION b[openEHR-EHR-EVALUATION.clinical_synopsis.v1]"
}'

Returns - {
    "error": "Could not process query, reason:org.antlr.v4.runtime.misc.ParseCancellationException: AQL Parse exception: line 1: char 144 mismatched input '29ab9b63-bd2c-4f37-bb86-83ee3e883f4f' expecting {TERMINOLOGY, NULL, UNKNOWN, TRUE, FALSE, FUNCTION_IDENTIFIER, CAST_FUNCTION_IDENTIFIER, BOOLEAN, IDENTIFIER, INTEGER, FLOAT, REAL, DATE, PARAMETER, STRING}",
    "status": "Bad Request"
}

**3. Get AQL** 

curl --location --request GET 'http://ubiqaresb.ehr.network:9090/ehrbase/rest/openehr/v1/query/aql?q=select%20a/composer/name,%20a/context/start_time/value%20as%20createdTime,%20b/data[at0001]/items[at0002]/value/value%20as%20synopsis%20FROM%20EHR%20e[ehr_id/value%3D$ehr_id]%20CONTAINS%20COMPOSITION%20a[openEHR-EHR-COMPOSITION.encounter.v1]%20CONTAINS%20EVALUATION%20b[openEHR-EHR-EVALUATION.clinical_synopsis.v1]&ehr_id=29ab9b63-bd2c-4f37-bb86-83ee3e883f4f' \
--header 'Content-Type: application/json'

400 Bad request

In post can we give aql with ehr_id inline?

**Comment by sebastian-iancu** [comment]
I'm not involved in EHRBase at all, just bumped accidentally into this issue report. But I do have some knowledge about AQL specs, and I think here the problem is that:
`FROM EHR e[ehr_id/value=29ab9b63-bd2c-4f37-bb86-83ee3e883f4f]`
should be actually:
`FROM EHR e[ehr_id/value='29ab9b63-bd2c-4f37-bb86-83ee3e883f4f']` as that UUID should be of String type
Hopefully this helps ...

**Comment by dileep-ehr** [comment]
@sebastian-iancu Nice catch. Yes that works.

Thanks
