### ISSUE TITLE
Update FLAT composition gives 500 error

### ISSUE THREAD

**Issue by dileep-ehr** [ehrbase/ehrbase#524]
## Configuration information

<ehrbase_version>0.16.5</ehrbase_version>
    <openehr_sdk_version>39cb1fd</openehr_sdk_version>
    <archie_version>5a4a9442e5e2516aed5f25636ac236682aace7b9</archie_version>
    <jvm_version>Oracle Corporation 11.0.11+9</jvm_version>
    <os_version>Linux amd64 5.4.0-73-generic</os_version>
    <postgres_version>PostgreSQL 11.5 on x86_64-pc-linux-musl, compiled by gcc (Alpine 8.3.0) 8.3.0, 64-bit</postgres_version>

## Steps to reproduce ## 

Update composition in FLAT format

{{serverUrl}}/rest/ecis/v1/composition/{{compositionUid}}?format=FLAT&ehrId={{ehr_id}}&templateId={{template_id}}

## Actual result ##

500 internal server error
{
    "error": "Failed to convert value of type 'java.lang.String' to required type 'java.util.UUID'; nested exception is java.lang.IllegalArgumentException: UUID string too large",
    "status": "Internal Server Error"
}

## Expected result (Acceptance Criteria) ##

204 

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by sidharthramesh** [comment]
Can you please post the FLAT composition?

**Comment by dileep-ehr** [comment]
{
    "clinical_notes/clinical_synopsis:0/synopsis": "Clinical notes5",
    "clinical_notes/clinical_synopsis:0/encoding|code": "UTF-8",
    "clinical_notes/clinical_synopsis:0/encoding|terminology": "IANA_character-sets",
    "clinical_notes/clinical_synopsis:0/language|code": "en",
    "clinical_notes/clinical_synopsis:0/language|terminology": "ISO_639-1",
    "clinical_notes/language|code": "en",
    "clinical_notes/language|terminology": "ISO_639-1",
    "clinical_notes/composer|name": "Dr Joyce Smith",
    "clinical_notes/territory|code": "IN",
    "clinical_notes/territory|terminology": "ISO_3166-1",
    "clinical_notes/context/setting|terminology": "openehr",
    "clinical_notes/context/setting|value": "primary medical care",
    "clinical_notes/context/setting|code": "228",
    "clinical_notes/category|value": "event",
    "clinical_notes/category|code": "433",
    "clinical_notes/category|terminology": "openehr"
    }

Template used
[EHRN Clinical notes.v1.zip](https://github.com/ehrbase/ehrbase/files/6602222/EHRN.Clinical.notes.v1.zip)

**Comment by sidharthramesh** [comment]
This is the same as #513, which has been added as a 1.0 milestone.

**Comment by dileep-ehr** [comment]
Tested with {{compositionUid}} as just the UUID and it works. Looks like EHRBase is expecting simple UUID of the composition and not with the version.
