### ISSUE TITLE
Storing a query gives 500 server error

### ISSUE THREAD

**Issue by dileep-ehr** [ehrbase/ehrbase#525]
## Configuration information
  <ehrbase_version>0.16.5</ehrbase_version>
    <openehr_sdk_version>39cb1fd</openehr_sdk_version>
    <archie_version>5a4a9442e5e2516aed5f25636ac236682aace7b9</archie_version>
    <jvm_version>Oracle Corporation 11.0.11+9</jvm_version>
    <os_version>Linux amd64 5.4.0-73-generic</os_version>
    <postgres_version>PostgreSQL 11.5 on x86_64-pc-linux-musl, compiled by gcc (Alpine 8.3.0) 8.3.0, 64-bit</postgres_version>

## Steps to reproduce ## 
Store a query
 PUT {{serverUrl}}/rest/openehr/v1/definition/query/ehr::test/1.0.0?type=AQL

## Actual result ##

{
    "error": "java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $",
    "status": "Internal Server Error"
}

## Expected result (Acceptance Criteria) ##

200 OK

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by sidharthramesh** [comment]
Can you also post the query that you tried to store?

**Comment by dileep-ehr** [comment]
`SELECT a/composer/name, a/context/start_time/value as createdTime, b/data[at0001]/items[at0002]/value/value as synopsis FROM EHR e[ehr_id/value=$ehr_id] CONTAINS COMPOSITION a[openEHR-EHR-COMPOSITION.encounter.v1] CONTAINS EVALUATION b[openEHR-EHR-EVALUATION.clinical_synopsis.v1] 
WHERE b/data[at0001]/items[at0002]/value/value = $synopsis`

Template
[EHRN Clinical notes.v1.zip](https://github.com/ehrbase/ehrbase/files/6602223/EHRN.Clinical.notes.v1.zip)

**Comment by birgerhaarbrandt** [comment]
Hi @dileep-ehr,

the query needs to follow the format known from the query execution:

```
{
  "q": "select
    a_a/items[at0029]/value/value as Probenart,
    a_a/items[at0001]/value/id as Laboridentifikaton,
    a_a/items[at0087]/value/value as ZeitpunktProbe,
    a_a/items[at0015]/value/value as OrtderEntnahme,
    a_b/data[at0001]/events[at0002]/data[at0003]/items[at0005]/value/value as Bezeichner,
    a_c/items[at0024]/value/value as Virus,
    a_c/items[at0001]/value/magnitude as Viruslast
from EHR e
contains COMPOSITION a
contains (
    CLUSTER a_a[openEHR-EHR-CLUSTER.specimen.v1] and
    OBSERVATION a_b[openEHR-EHR-OBSERVATION.laboratory_test_result.v1] and
    CLUSTER a_c[openEHR-EHR-CLUSTER.laboratory_test_analyte.v1])
WHERE e/ehr_id/value matches{$patID}"
}
```

However, EHRbase should definitely provide a better error message as just 500.

Can you please try this way? I'm actually surprised that the example in the recent version of the spec has changed: https://specifications.openehr.org/releases/ITS-REST/latest/definitions.html#definitions-stored-query-put

**Comment by dileep-ehr** [comment]
Thanks. that works.
