### ISSUE TITLE
Posting just the Date in a Composition

### ISSUE THREAD

**Issue by sidharthramesh** [ehrbase/ehrbase#526]
## Configuration information

```
  <status>
    <ehrbase_version>0.16.5</ehrbase_version>
    <openehr_sdk_version>39cb1fd</openehr_sdk_version>
    <archie_version>5a4a9442e5e2516aed5f25636ac236682aace7b9</archie_version>
    <jvm_version>Oracle Corporation 11.0.11+9</jvm_version>
    <os_version>Linux amd64 5.8.0-43-generic</os_version>
    <postgres_version>PostgreSQL 13.3 (Debian 13.3-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit</postgres_version>
  </status>
```

## Steps to reproduce ## 

[DRX.EntryPoint.v0.opt.txt](https://github.com/ehrbase/ehrbase/files/6604363/DRX.EntryPoint.v0.opt.txt)

FLAT Composition
```
{
	"drx.entrypoint.v0/problem_diagnosis/chief_complaint|value": "Head",
	"drx.entrypoint.v0/problem_diagnosis/chief_complaint|code": "69536005",
	"drx.entrypoint.v0/problem_diagnosis/chief_complaint|terminology": "local",
	"drx.entrypoint.v0/problem_diagnosis/date_of_onset": "2021-06-05",
	"drx.entrypoint.v0/category|code": "433",
	"drx.entrypoint.v0/category|value": "event",
	"drx.entrypoint.v0/category|terminology": "openehr",
	"drx.entrypoint.v0/context/start_time": "2021-06-06T14:49:17.825Z",
	"drx.entrypoint.v0/context/setting|code": "238",
	"drx.entrypoint.v0/context/setting|value": "other care",
	"drx.entrypoint.v0/context/setting|terminology": "openehr",
	"drx.entrypoint.v0/problem_diagnosis/language|code": "en",
	"drx.entrypoint.v0/problem_diagnosis/language|terminology": "ISO_639-1",
	"drx.entrypoint.v0/problem_diagnosis/encoding|code": "UTF-8",
	"drx.entrypoint.v0/problem_diagnosis/encoding|terminology": "IANA_character-sets",
	"drx.entrypoint.v0/composer|name": "Medblocks UI",
	"drx.entrypoint.v0/language|code": "en",
	"drx.entrypoint.v0/language|terminology": "ISO_639-1",
	"drx.entrypoint.v0/territory|code": "IN",
	"drx.entrypoint.v0/territory|terminology": "ISO_3166-1"
}
```

## Actual result ##
Error:
```
{
  "error": "java.lang.IllegalArgumentException: Unsupported field: HourOfDay (through reference chain: com.nedap.archie.rm.datavalues.quantity.datetime.DvDateTime[\"value\"])",
  "status": "Bad Request"
}
```
Seems like the field `"drx.entrypoint.v0/problem_diagnosis/date_of_onset": "2021-06-05"` is the problem. Setting the time also fixes this.

## Expected result (Acceptance Criteria) ##
Accept just a date like `2021-06-05` for type DV_DATE_TIME.

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by dileep-ehr** [comment]
DV_DATE may be more appropriate for recording ISO8601 date string formats. 
https://specifications.openehr.org/releases/RM/Release-1.0.2/data_types.html#_dv_date_class

**Comment by sidharthramesh** [comment]
The DV_DATE might be more appropriate, but shouldn't the DV_DATE_TIME also support an ISO8601 date string? It's usually the case that sometimes the time is known and at other times, it's not. Wouldn't want to change the template just to accommodate this.

**Comment by dileep-ehr** [comment]
DV-DATE accepts Iso8601_date
<https://specifications.openehr.org/releases/BASE/latest/foundation_types.html#_iso8601_date_class>
format which does not have the time and DV_DATE_TIME inherits
Iso8601_date_time
<https://specifications.openehr.org/releases/BASE/latest/foundation_types.html#_iso8601_date_time_class>
which required both date and time. If you have only date for a datetime
data type, you have to use 0s in the time part.

regards
Dileep V S
*Founder*
HealtheLife Ventures LLP
m: +91 79756 70933
a: 9/1, 19th Main Road, 1st 'N" Block, Rajaji Nagar, Bangalore 560010
w: <http://ayushehr.com>ehr.network, <http://ehr.network>ayushehr.com
<http://ayushehr.com> e: ***@***.***

**Comment by birgerhaarbrandt** [comment]
@sidharthramesh @dileep-ehr do you think this issues can be considered resolved?

**Comment by sidharthramesh** [comment]
I think yes @birgerhaarbrandt. Closing.
