### ISSUE TITLE
Commit composition with an event that has an empty state, makes the commit fail

### ISSUE THREAD

**Issue by ppazos** [ehrbase/ehrbase#543]
Result: 

```
{
  "error": "java.lang.IllegalArgumentException",
  "status": "Bad Request"
}
```

No further details appear in the logs.

Removing the event.state makes it work.

[compo.json.txt](https://github.com/ehrbase/ehrbase/files/6805243/compo.json.txt)

**Comment by wlad** [comment]
looks like a good candidate for a new Robot test(?)

**Comment by subigre** [comment]
Fixed with PR mentioned above
