### ISSUE TITLE
Timezone drift in AQL

### ISSUE THREAD

**Issue by stefanspiska** [ehrbase/ehrbase#554]
## Configuration information

```
 <ehrbase_version>0.16.5</ehrbase_version>
    <openehr_sdk_version>14da5ad</openehr_sdk_version>
    <archie_version>5a4a9442e5e2516aed5f25636ac236682aace7b9</archie_version>
    <jvm_version>AdoptOpenJDK 15.0.2+7</jvm_version>
    <os_version>Windows 10 amd64 10.0</os_version>
    <postgres_version>PostgreSQL 11.5 on x86_64-pc-linux-musl, compiled by gcc (Alpine 8.3.0) 8.3.0, 64-bit</postgres_version>
```

## Steps to reproduce ## 

run testObservationDrillDown on a system with German timezone  (on the ci pipeline it runs)

## Actual result ##
```
org.opentest4j.AssertionFailedError: [c/context/start_time] 
Expecting:
 <"{
  "_type" : "DV_DATE_TIME",
  "value" : "2019-01-14T17:36:49,294Z"
}">
to be equal to:
 <"{
  "_type" : "DV_DATE_TIME",
  "value" : "2019-01-14T18:36:49,294Z"
}">
but was not.
```

## Expected result (Acceptance Criteria) ##

Test runs independent of timezone of local system.

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by chevalleyc** [comment]
@stefanspiska out of curiosity, is your DB running in a cloud server ?

**Comment by stefanspiska** [comment]
@chevalleyc  I use the ehrbase Docker

**Comment by chevalleyc** [comment]
ok I acknowledge that. It might be a regression. Thanks

**Comment by wlad** [comment]
fixed by https://github.com/ehrbase/ehrbase/pull/636
