### ISSUE TITLE
AQL error when multiple templates with same archetype in them

### ISSUE THREAD

**Issue by dileep-ehr** [ehrbase/ehrbase#557]
## Configuration information

<ehrbase_version>0.16.5</ehrbase_version>
    <openehr_sdk_version>39cb1fd</openehr_sdk_version>
    <archie_version>5a4a9442e5e2516aed5f25636ac236682aace7b9</archie_version>
    <jvm_version>Oracle Corporation 11.0.11+9</jvm_version>
    <os_version>Linux amd64 5.4.0-80-generic</os_version>
    <postgres_version>PostgreSQL 11.5 on x86_64-pc-linux-musl, compiled by gcc (Alpine 8.3.0) 8.3.0, 64-bit</postgres_version>

## Steps to reproduce ## 
1. Add EHRN Vital signs.v1.opt, add composition(s) and run AQL - Everything works
2. Add EHRN Clinical notes.v1.opt, test vitals aql again - It works
3. Add EHRN Progress note.v2, Vitals AQL fails with psql error
4. Change path '/value/numerator as spo' to '/value as spo' and AQL returns with JSON of spo2 object

This works independent of the order of template addition

## Actual result ##

{
    "error": "Could not perform SQL query:org.postgresql.util.PSQLException: ERROR: UNION types text and numeric cannot be matched\n  Position: 3824, AQL expression:selecta/composer/nameasauthor,a/context/start_time/valueascreatedTime,b/data[at0001]/events[at0006]/data[at0003]/items[at0004]/value/magnitudeassystolicBp,b/data[at0001]/events[at0006]/data[at0003]/items[at0004]/value/unitsassystolicBpUnit,b/data[at0001]/events[at0006]/data[at0003]/items[at0005]/value/magnitudeasdiastolicBp,b/data[at0001]/events[at0006]/data[at0003]/items[at0005]/value/unitsasdiastolicBpUnit,c/data[at0001]/events[at0002]/data[at0003]/items[at0006]/value/numeratorasspo,d/data[at0002]/events[at0003]/data[at0001]/items[at0004]/value/magnitudeastemperature,d/data[at0002]/events[at0003]/data[at0001]/items[at0004]/value/unitsastemperatureUnit,f/data[at0001]/events[at0002]/data[at0003]/items[at0004]/value/magnitudeasrespirationRate,f/data[at0001]/events[at0002]/data[at0003]/items[at0004]/value/unitsasrespirationRateUnit,g/data[at0001]/items[at0002]/value/valueassynopsis,h/data[at0002]/events[at0003]/data[at0001]/items[at0004]/value/magnitudeaspulse,h/data[at0002]/events[at0003]/data[at0001]/items[at0004]/value/unitsaspulseUnitFROMEHReCONTAINSCOMPOSITIONaCONTAINS(OBSERVATIONb[openEHR-EHR-OBSERVATION.blood_pressure.v2]OROBSERVATIONc[openEHR-EHR-OBSERVATION.pulse_oximetry.v1]OROBSERVATIONd[openEHR-EHR-OBSERVATION.body_temperature.v2]OROBSERVATIONf[openEHR-EHR-OBSERVATION.respiration.v1]OREVALUATIONg[openEHR-EHR-EVALUATION.clinical_synopsis.v1]OROBSERVATIONh[openEHR-EHR-OBSERVATION.pulse.v1])<EOF>, Translated SQL:(select \"composer_ref\".\"name\" as \"author\", jsonb_extract_path_text(cast(\"ehr\".\"js_dv_date_time\"(\n  \"ehr\".\"event_context\".\"start_time\", \n  coalesce(\n    event_context.START_TIME_TZID, \n    'UTC'\n  )\n) as jsonb),'value') as \"createdTime\", null::numeric as \"systolicBp\", null as \"systolicBpUnit\", null::numeric as \"diastolicBp\", null as \"diastolicBpUnit\", null as \"spo\", null::numeric as \"temperature\", null as \"temperatureUnit\", null::numeric as \"respirationRate\", null as \"respirationRateUnit\", \"ehr\".\"entry\".\"entry\" #>> '{/composition[openEHR-EHR-COMPOSITION.encounter.v1],/content[openEHR-EHR-EVALUATION.clinical_synopsis.v1],0,/data[at0001],/items[at0002],0,/value,value}' as \"synopsis\", null::numeric as \"pulse\", null as \"pulseUnit\" from \"ehr\".\"entry\" join \"ehr\".\"event_context\" on \"ehr\".\"event_context\".\"composition_id\" = \"ehr\".\"entry\".\"composition_id\" right outer join \"ehr\".\"composition\" as \"composition_join\" on \"composition_join\".\"id\" = \"ehr\".\"entry\".\"composition_id\" join \"ehr\".\"party_identified\" as \"composer_ref\" on \"composition_join\".\"composer\" = \"composer_ref\".\"id\" where \"ehr\".\"entry\".\"template_id\" = ?) union (select \"composer_ref\".\"name\" as \"author\", jsonb_extract_path_text(cast(\"ehr\".\"js_dv_date_time\"(\n  \"ehr\".\"event_context\".\"start_time\", \n  coalesce(\n    event_context.START_TIME_TZID, \n    'UTC'\n  )\n) as jsonb),'value') as \"createdTime\", null::numeric as \"systolicBp\", null as \"systolicBpUnit\", null::numeric as \"diastolicBp\", null as \"diastolicBpUnit\", null as \"spo\", null::numeric as \"temperature\", null as \"temperatureUnit\", null::numeric as \"respirationRate\", null as \"respirationRateUnit\", \"ehr\".\"entry\".\"entry\" #>> '{/composition[openEHR-EHR-COMPOSITION.encounter.v1],/content[openEHR-EHR-EVALUATION.clinical_synopsis.v1],0,/data[at0001],/items[at0002],0,/value,value}' as \"synopsis\", null::numeric as \"pulse\", null as \"pulseUnit\" from \"ehr\".\"entry\" join \"ehr\".\"event_context\" on \"ehr\".\"event_context\".\"composition_id\" = \"ehr\".\"entry\".\"composition_id\" right outer join \"ehr\".\"composition\" as \"composition_join\" on \"composition_join\".\"id\" = \"ehr\".\"entry\".\"composition_id\" join \"ehr\".\"party_identified\" as \"composer_ref\" on \"composition_join\".\"composer\" = \"composer_ref\".\"id\" where \"ehr\".\"entry\".\"template_id\" = ?) union (select \"composer_ref\".\"name\" as \"author\", jsonb_extract_path_text(cast(\"ehr\".\"js_dv_date_time\"(\n  \"ehr\".\"event_context\".\"start_time\", \n  coalesce(\n    event_context.START_TIME_TZID, \n    'UTC'\n  )\n) as jsonb),'value') as \"createdTime\", cast((ehr.xjsonb_array_elements((\"ehr\".\"entry\".\"entry\"#>>'{/composition[openEHR-EHR-COMPOSITION.encounter.v1],/content[openEHR-EHR-SECTION.vital_signs.v1],0,/items[openEHR-EHR-OBSERVATION.blood_pressure.v2]}')::jsonb)#>>'{/data[at0001],/events,/events[at0006],0,/data[at0003],/items[at0004],0,/value,magnitude}') as numeric) as \"systolicBp\", (ehr.xjsonb_array_elements((\"ehr\".\"entry\".\"entry\"#>>'{/composition[openEHR-EHR-COMPOSITION.encounter.v1],/content[openEHR-EHR-SECTION.vital_signs.v1],0,/items[openEHR-EHR-OBSERVATION.blood_pressure.v2]}')::jsonb)#>>'{/data[at0001],/events,/events[at0006],0,/data[at0003],/items[at0004],0,/value,units}') as \"systolicBpUnit\", cast((ehr.xjsonb_array_elements((\"ehr\".\"entry\".\"entry\"#>>'{/composition[openEHR-EHR-COMPOSITION.encounter.v1],/content[openEHR-EHR-SECTION.vital_signs.v1],0,/items[openEHR-EHR-OBSERVATION.blood_pressure.v2]}')::jsonb)#>>'{/data[at0001],/events,/events[at0006],0,/data[at0003],/items[at0005],0,/value,magnitude}') as numeric) as \"diastolicBp\", (ehr.xjsonb_array_elements((\"ehr\".\"entry\".\"entry\"#>>'{/composition[openEHR-EHR-COMPOSITION.encounter.v1],/content[openEHR-EHR-SECTION.vital_signs.v1],0,/items[openEHR-EHR-OBSERVATION.blood_pressure.v2]}')::jsonb)#>>'{/data[at0001],/events,/events[at0006],0,/data[at0003],/items[at0005],0,/value,units}') as \"diastolicBpUnit\", cast((ehr.xjsonb_array_elements((\"ehr\".\"entry\".\"entry\"#>>'{/composition[openEHR-EHR-COMPOSITION.encounter.v1],/content[openEHR-EHR-SECTION.vital_signs.v1],0,/items[openEHR-EHR-OBSERVATION.pulse_oximetry.v1]}')::jsonb)#>>'{/data[at0001],/events,/events[at0002],0,/data[at0003],/items[at0006],0,/value,numerator}') as numeric) as \"spo\", cast((ehr.xjsonb_array_elements((\"ehr\".\"entry\".\"entry\"#>>'{/composition[openEHR-EHR-COMPOSITION.encounter.v1],/content[openEHR-EHR-SECTION.vital_signs.v1],0,/items[openEHR-EHR-OBSERVATION.body_temperature.v2]}')::jsonb)#>>'{/data[at0002],/events,/events[at0003],0,/data[at0001],/items[at0004],0,/value,magnitude}') as numeric) as \"temperature\", (ehr.xjsonb_array_elements((\"ehr\".\"entry\".\"entry\"#>>'{/composition[openEHR-EHR-COMPOSITION.encounter.v1],/content[openEHR-EHR-SECTION.vital_signs.v1],0,/items[openEHR-EHR-OBSERVATION.body_temperature.v2]}')::jsonb)#>>'{/data[at0002],/events,/events[at0003],0,/data[at0001],/items[at0004],0,/value,units}') as \"temperatureUnit\", cast((ehr.xjsonb_array_elements((\"ehr\".\"entry\".\"entry\"#>>'{/composition[openEHR-EHR-COMPOSITION.encounter.v1],/content[openEHR-EHR-SECTION.vital_signs.v1],0,/items[openEHR-EHR-OBSERVATION.respiration.v1]}')::jsonb)#>>'{/data[at0001],/events,/events[at0002],0,/data[at0003],/items[at0004],0,/value,magnitude}') as numeric) as \"respirationRate\", (ehr.xjsonb_array_elements((\"ehr\".\"entry\".\"entry\"#>>'{/composition[openEHR-EHR-COMPOSITION.encounter.v1],/content[openEHR-EHR-SECTION.vital_signs.v1],0,/items[openEHR-EHR-OBSERVATION.respiration.v1]}')::jsonb)#>>'{/data[at0001],/events,/events[at0002],0,/data[at0003],/items[at0004],0,/value,units}') as \"respirationRateUnit\", \"ehr\".\"entry\".\"entry\" #>> '{/composition[openEHR-EHR-COMPOSITION.encounter.v1],/content[openEHR-EHR-SECTION.vital_signs.v1],0,/items[openEHR-EHR-EVALUATION.clinical_synopsis.v1],0,/data[at0001],/items[at0002],0,/value,value}' as \"synopsis\", cast((ehr.xjsonb_array_elements((\"ehr\".\"entry\".\"entry\"#>>'{/composition[openEHR-EHR-COMPOSITION.encounter.v1],/content[openEHR-EHR-SECTION.vital_signs.v1],0,/items[openEHR-EHR-OBSERVATION.pulse.v1]}')::jsonb)#>>'{/data[at0002],/events,/events[at0003],0,/data[at0001],/items[at0004],0,/value,magnitude}') as numeric) as \"pulse\", (ehr.xjsonb_array_elements((\"ehr\".\"entry\".\"entry\"#>>'{/composition[openEHR-EHR-COMPOSITION.encounter.v1],/content[openEHR-EHR-SECTION.vital_signs.v1],0,/items[openEHR-EHR-OBSERVATION.pulse.v1]}')::jsonb)#>>'{/data[at0002],/events,/events[at0003],0,/data[at0001],/items[at0004],0,/value,units}') as \"pulseUnit\" from \"ehr\".\"entry\" join \"ehr\".\"event_context\" on \"ehr\".\"event_context\".\"composition_id\" = \"ehr\".\"entry\".\"composition_id\" right outer join \"ehr\".\"composition\" as \"composition_join\" on \"composition_join\".\"id\" = \"ehr\".\"entry\".\"composition_id\" join \"ehr\".\"party_identified\" as \"composer_ref\" on \"composition_join\".\"composer\" = \"composer_ref\".\"id\" where \"ehr\".\"entry\".\"template_id\" = ?)",
    "status": "Bad Request"
}

Looks like a typecasting issue in the generated PSQL file (for templates that does not have spo node. It is type cast to 'null' instead of 'null:integer'

## Expected result (Acceptance Criteria) ##
Vitals - composition example & AQL
[ehrbase error.zip](https://github.com/ehrbase/ehrbase/files/6915910/ehrbase.error.zip)

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by dileep-ehr** [comment]
All the above templates have the openEHR-EHR-EVALUATION.clinical_synopsis.v1 and that seems to be triggering the problem.

We added the full archetype path of the  EHRN Vital signs.v1.opt template(including the section archetype) and the aql started working. By doing this the query was limited to only one template and we were not selecting all templates with common archetypes in them, eliminating the NULL casting for spo node.

{
  "q": "select a/composer/name as author, a/context/start_time/value as createdTime, b/data[at0001]/events[at0006]/data[at0003]/items[at0004]/value/magnitude as systolicBp, b/data[at0001]/events[at0006]/data[at0003]/items[at0004]/value/units as systolicBpUnit, b/data[at0001]/events[at0006]/data[at0003]/items[at0005]/value/magnitude as diastolicBp, b/data[at0001]/events[at0006]/data[at0003]/items[at0005]/value/units as diastolicBpUnit, c/data[at0001]/events[at0002]/data[at0003]/items[at0006]/value/numerator as spo,
d/data[at0002]/events[at0003]/data[at0001]/items[at0004]/value/magnitude as temperature,
d/data[at0002]/events[at0003]/data[at0001]/items[at0004]/value/units as temperatureUnit,
f/data[at0001]/events[at0002]/data[at0003]/items[at0004]/value/magnitude as respirationRate,
f/data[at0001]/events[at0002]/data[at0003]/items[at0004]/value/units as respirationRateUnit,
g/data[at0001]/items[at0002]/value/value as synopsis,  
h/data[at0002]/events[at0003]/data[at0001]/items[at0004]/value/magnitude as pulse,
h/data[at0002]/events[at0003]/data[at0001]/items[at0004]/value/units as pulseUnit
FROM EHR e CONTAINS COMPOSITION a[openEHR-EHR-COMPOSITION.encounter.v1] CONTAINS SECTION z[openEHR-EHR-SECTION.vital_signs.v1] CONTAINS (OBSERVATION b[openEHR-EHR-OBSERVATION.blood_pressure.v2] OR OBSERVATION c[openEHR-EHR-OBSERVATION.pulse_oximetry.v1] OR OBSERVATION d[openEHR-EHR-OBSERVATION.body_temperature.v2] OR OBSERVATION f[openEHR-EHR-OBSERVATION.respiration.v1] OR EVALUATION g[openEHR-EHR-EVALUATION.clinical_synopsis.v1] OR OBSERVATION h[openEHR-EHR-OBSERVATION.pulse.v1])",
  "query_parameters": {
    "ehr_id": "{{ehr_id}}"
  }
}

**Comment by chevalleyc** [comment]
Hi @dileep-ehr any feedback regarding my comment above? Thanks!

**Comment by dileep-ehr** [comment]
@chevalleyc I am now testing with the 0.17.3 snapshot build. I will test this problem on that and come back to you in 2 days

**Comment by skoba** [comment]
I met this error with a query including numerator/DV_PROPORTION in current 0.18.1 version.
It passed 0.15.0 and seemed to be stored in text, as the following.
```
{
    "q": "SELECT e/ehr_id/value AS ehr_id, c/uid/value AS composition_id, c/context/start_time/value AS Time, c/content[openEHR-EHR-OBSERVATION.body_temperature.v2]/data[at0002]/events[at0003]/data[at0001]/items[at0004]/value/magnitude AS BT, c/content[openEHR-EHR-OBSERVATION.pulse.v2]/data[at0002]/events[at0003]/data[at0001]/items[at0004]/value/magnitude AS HR, c/content[openEHR-EHR-OBSERVATION.blood_pressure.v2]/data[at0001]/events[at0006]/data[at0003]/items[at0004]/value/magnitude AS SBP, c/content[openEHR-EHR-OBSERVATION.blood_pressure.v2]/data[at0001]/events[at0006]/data[at0003]/items[at0005]/value/magnitude AS DBP, c/content[openEHR-EHR-OBSERVATION.blood_pressure.v2]/data[at0001]/events[at0006]/data[at0003]/items[at1006]/value/magnitude AS MAP, c/content[openEHR-EHR-OBSERVATION.pulse_oximetry.v1]/data[at0001]/events[at0002]/data[at0003]/items[at0006]/value/numerator AS SpO2, c/content[openEHR-EHR-OBSERVATION.respiration.v2]/data[at0001]/events[at0002]/data[at0003]/items[at0004]/value/magnitude AS RR from EHR e contains COMPOSITION c WHERE c/name/value='ICU_VITAL_SIGNS' ORDER BY c/context/start_time/value DESC",
    "columns": [
        {
            "path": "/ehr_id/value",
            "name": "ehr_id"
        },
        {
            "path": "/uid/value",
            "name": "composition_id"
        },
        {
            "path": "/context/start_time/value",
            "name": "Time"
        },
        {
            "path": "/content[openEHR-EHR-OBSERVATION.body_temperature.v2]/data[at0002]/events[at0003]/data[at0001]/items[at0004]/value/magnitude",
            "name": "BT"
        },
        {
            "path": "/content[openEHR-EHR-OBSERVATION.pulse.v2]/data[at0002]/events[at0003]/data[at0001]/items[at0004]/value/magnitude",
            "name": "HR"
        },
        {
            "path": "/content[openEHR-EHR-OBSERVATION.blood_pressure.v2]/data[at0001]/events[at0006]/data[at0003]/items[at0004]/value/magnitude",
            "name": "SBP"
        },
        {
            "path": "/content[openEHR-EHR-OBSERVATION.blood_pressure.v2]/data[at0001]/events[at0006]/data[at0003]/items[at0005]/value/magnitude",
            "name": "DBP"
        },
        {
            "path": "/content[openEHR-EHR-OBSERVATION.blood_pressure.v2]/data[at0001]/events[at0006]/data[at0003]/items[at1006]/value/magnitude",
            "name": "MAP"
        },
        {
            "path": "/content[openEHR-EHR-OBSERVATION.pulse_oximetry.v1]/data[at0001]/events[at0002]/data[at0003]/items[at0006]/value/numerator",
            "name": "SpO2"
        },
        {
            "path": "/content[openEHR-EHR-OBSERVATION.respiration.v2]/data[at0001]/events[at0002]/data[at0003]/items[at0004]/value/magnitude",
            "name": "RR"
        }
    ],
    "rows": [
        [
            "0a6bd150-0ed0-415f-bde6-02f007ce7db3",
            "68c5068d-6d2e-4466-8136-e73d0f0df6a9::local.ehrbase.org::1",
            "2021-12-14T14:44:04.474+09:00",
            36.8,
            121.0,
            131.0,
            83.0,
            106.0,
            "98.0",
            23.0
        ],
```

but it also display as numbers.

```
   "q": "SELECT e/ehr_id/value AS ehr_id, c/uid/value AS composition_id, c/context/start_time/value AS Time, c/content[openEHR-EHR-OBSERVATION.body_temperature.v2]/data[at0002]/events[at0003]/data[at0001]/items[at0004]/value/magnitude AS BT, c/content[openEHR-EHR-OBSERVATION.pulse.v2]/data[at0002]/events[at0003]/data[at0001]/items[at0004]/value/magnitude AS HR, c/content[openEHR-EHR-OBSERVATION.blood_pressure.v2]/data[at0001]/events[at0006]/data[at0003]/items[at0004]/value/magnitude AS SBP, c/content[openEHR-EHR-OBSERVATION.blood_pressure.v2]/data[at0001]/events[at0006]/data[at0003]/items[at0005]/value/magnitude AS DBP, c/content[openEHR-EHR-OBSERVATION.blood_pressure.v2]/data[at0001]/events[at0006]/data[at0003]/items[at1006]/value/magnitude AS MAP, c/content[openEHR-EHR-OBSERVATION.pulse_oximetry.v1]/data[at0001]/events[at0002]/data[at0003]/items[at0006]/value AS SpO2, c/content[openEHR-EHR-OBSERVATION.respiration.v2]/data[at0001]/events[at0002]/data[at0003]/items[at0004]/value/magnitude AS RR from EHR e contains COMPOSITION c WHERE c/name/value='ICU_VITAL_SIGNS' ORDER BY c/context/start_time/value DESC",
    "columns": [
        {
            "path": "/ehr_id/value",
            "name": "ehr_id"
        },
        {
            "path": "/uid/value",
            "name": "composition_id"
        },
        {
            "path": "/context/start_time/value",
            "name": "Time"
        },
        {
            "path": "/content[openEHR-EHR-OBSERVATION.body_temperature.v2]/data[at0002]/events[at0003]/data[at0001]/items[at0004]/value/magnitude",
            "name": "BT"
        },
        {
            "path": "/content[openEHR-EHR-OBSERVATION.pulse.v2]/data[at0002]/events[at0003]/data[at0001]/items[at0004]/value/magnitude",
            "name": "HR"
        },
        {
            "path": "/content[openEHR-EHR-OBSERVATION.blood_pressure.v2]/data[at0001]/events[at0006]/data[at0003]/items[at0004]/value/magnitude",
            "name": "SBP"
        },
        {
            "path": "/content[openEHR-EHR-OBSERVATION.blood_pressure.v2]/data[at0001]/events[at0006]/data[at0003]/items[at0005]/value/magnitude",
            "name": "DBP"
        },
        {
            "path": "/content[openEHR-EHR-OBSERVATION.blood_pressure.v2]/data[at0001]/events[at0006]/data[at0003]/items[at1006]/value/magnitude",
            "name": "MAP"
        },
        {
            "path": "/content[openEHR-EHR-OBSERVATION.pulse_oximetry.v1]/data[at0001]/events[at0002]/data[at0003]/items[at0006]/value",
            "name": "SpO2"
        },
        {
            "path": "/content[openEHR-EHR-OBSERVATION.respiration.v2]/data[at0001]/events[at0002]/data[at0003]/items[at0004]/value/magnitude",
            "name": "RR"
        }
    ],
    "rows": [
        [
            "0a6bd150-0ed0-415f-bde6-02f007ce7db3",
            "68c5068d-6d2e-4466-8136-e73d0f0df6a9::local.ehrbase.org::1",
            "2021-12-14T14:44:04.474+09:00",
            36.8,
            121.0,
            131.0,
            83.0,
            106.0,
            {
                "type": 2.0,
                "_type": "DV_PROPORTION",
                "numerator": 98.0,
                "denominator": 100.0
            },
            23.0
        ],
```

**Comment by skoba** [comment]
Oh, sorry. The error is the following
```
{
    "error": "Could not perform SQL query:org.postgresql.util.PSQLException: ERROR: UNION types text and numeric cannot be matched\n  Position: 3508, AQL expression:SELECTe/ehr_id/valueASehr_id,c/uid/valueAScomposition_id,c/context/start_time/valueASTime,c/content[openEHR-EHR-OBSERVATION.body_temperature.v2]/data[at0002]/events[at0003]/data[at0001]/items[at0004]/value/magnitudeASBT,c/content[openEHR-EHR-OBSERVATION.pulse.v2]/data[at0002]/events[at0003]/data[at0001]/items[at0004]/value/magnitudeASHR,c/content[openEHR-EHR-OBSERVATION.blood_pressure.v2]/data[at0001]/events[at0006]/data[at0003]/items[at0004]/value/magnitudeASSBP,c/content[openEHR-EHR-OBSERVATION.blood_pressure.v2]/data[at0001]/events[at0006]/data[at0003]/items[at0005]/value/magnitudeASDBP,c/content[openEHR-EHR-OBSERVATION.blood_pressure.v2]/data[at0001]/events[at0006]/data[at0003]/items[at1006]/value/magnitudeASMAP,c/content[openEHR-EHR-OBSERVATION.pulse_oximetry.v1]/data[at0001]/events[at0002]/data[at0003]/items[at0006]/value/numeratorASSpO2,c/content[openEHR-EHR-OBSERVATION.respiration.v2]/data[at0001]/events[at0002]/data[at0003]/items[at0004]/value/magnitudeASRRfromEHRecontainsCOMPOSITIONcWHEREc/name/value='ICU_VITAL_SIGNS'ORDER BYc/context/start_time/valueDESC<EOF>, Translated SQL:select \"alias_19803274\".\"ehr_id\", \"alias_19803274\".\"composition_id\", \"alias_19803274\".\"Time\", \"alias_19803274\".\"BT\", \"alias_19803274\".\"HR\", \"alias_19803274\".\"SBP\", \"alias_19803274\".\"DBP\", \"alias_19803274\".\"MAP\", \"alias_19803274\".\"SpO2\", \"alias_19803274\".\"RR\" from ((select \"ehr_join\".\"id\" as \"ehr_id\", jsonb_extract_path_text(cast(\"ehr\".\"js_composition\"(\n  cast(composition_join.id as uuid), \n  'local.ehrbase.org'\n) as jsonb),'uid','value') as \"composition_id\", jsonb_extract_path_text(cast(\"ehr\".\"js_dv_date_time\"(\n  \"ehr\".\"event_context\".\"start_time\", \n  event_context.START_TIME_TZID\n) as jsonb),'value') as \"Time\", cast(\"ehr\".\"entry\".\"entry\" #>> '{/composition[openEHR-EHR-COMPOSITION.health_summary.v1],/content[openEHR-EHR-OBSERVATION.body_temperature.v2],0,/data[at0002],/events,/events[at0003],0,/data[at0001],/items[at0004],0,/value,magnitude}' as numeric) as \"BT\", cast(\"ehr\".\"entry\".\"entry\" #>> '{/composition[openEHR-EHR-COMPOSITION.health_summary.v1],/content[openEHR-EHR-OBSERVATION.pulse.v2],0,/data[at0002],/events,/events[at0003],0,/data[at0001],/items[at0004],0,/value,magnitude}' as numeric) as \"HR\", cast(\"ehr\".\"entry\".\"entry\" #>> '{/composition[openEHR-EHR-COMPOSITION.health_summary.v1],/content[openEHR-EHR-OBSERVATION.blood_pressure.v2],0,/data[at0001],/events,/events[at0006],0,/data[at0003],/items[at0004],0,/value,magnitude}' as numeric) as \"SBP\", cast(\"ehr\".\"entry\".\"entry\" #>> '{/composition[openEHR-EHR-COMPOSITION.health_summary.v1],/content[openEHR-EHR-OBSERVATION.blood_pressure.v2],0,/data[at0001],/events,/events[at0006],0,/data[at0003],/items[at0005],0,/value,magnitude}' as numeric) as \"DBP\", cast(\"ehr\".\"entry\".\"entry\" #>> '{/composition[openEHR-EHR-COMPOSITION.health_summary.v1],/content[openEHR-EHR-OBSERVATION.blood_pressure.v2],0,/data[at0001],/events,/events[at0006],0,/data[at0003],/items[at1006],0,/value,magnitude}' as numeric) as \"MAP\", \"ehr\".\"entry\".\"entry\" #>> '{/composition[openEHR-EHR-COMPOSITION.health_summary.v1],/content[openEHR-EHR-OBSERVATION.pulse_oximetry.v1],0,/data[at0001],/events,/events[at0002],0,/data[at0003],/items[at0006],0,/value,numerator}' as \"SpO2\", cast(\"ehr\".\"entry\".\"entry\" #>> '{/composition[openEHR-EHR-COMPOSITION.health_summary.v1],/content[openEHR-EHR-OBSERVATION.respiration.v2],0,/data[at0001],/events,/events[at0002],0,/data[at0003],/items[at0004],0,/value,magnitude}' as numeric) as \"RR\" from \"ehr\".\"entry\" right outer join \"ehr\".\"composition\" as \"composition_join\" on \"composition_join\".\"id\" = \"ehr\".\"entry\".\"composition_id\" join \"ehr\".\"event_context\" on \"ehr\".\"event_context\".\"composition_id\" = \"ehr\".\"entry\".\"composition_id\" right outer join \"ehr\".\"ehr\" as \"ehr_join\" on \"ehr_join\".\"id\" = \"composition_join\".\"ehr_id\" where (\"ehr\".\"entry\".\"template_id\" = ? and (jsonb_extract_path_text(cast(\"ehr\".\"js_dv_coded_text_inner\"(\"ehr\".\"entry\".\"name\") as jsonb),'value') = 'ICU_VITAL_SIGNS'))) union (select \"ehr_join\".\"id\" as \"ehr_id\", jsonb_extract_path_text(cast(\"ehr\".\"js_composition\"(\n  cast(composition_join.id as uuid), \n  'local.ehrbase.org'\n) as jsonb),'uid','value') as \"composition_id\", jsonb_extract_path_text(cast(\"ehr\".\"js_dv_date_time\"(\n  \"ehr\".\"event_context\".\"start_time\", \n  event_context.START_TIME_TZID\n) as jsonb),'value') as \"Time\", array_530376446_1.var_530376446_2::numeric as \"BT\", array_1056764580_3.var_1056764580_4::numeric as \"HR\", array_1729097973_5.var_1729097973_6::numeric as \"SBP\", array_1643185740_7.var_1643185740_8::numeric as \"DBP\", array_844575404_9.var_844575404_10::numeric as \"MAP\", array_1106971106_11.var_1106971106_12::numeric as \"SpO2\", array_1824304885_13.var_1824304885_14::numeric as \"RR\" from \"ehr\".\"entry\" right outer join \"ehr\".\"composition\" as \"composition_join\" on \"composition_join\".\"id\" = \"ehr\".\"entry\".\"composition_id\" join \"ehr\".\"event_context\" on \"ehr\".\"event_context\".\"composition_id\" = \"ehr\".\"entry\".\"composition_id\" right outer join \"ehr\".\"ehr\" as \"ehr_join\" on \"ehr_join\".\"id\" = \"composition_join\".\"ehr_id\" join lateral (\n  select cast((ehr.xjsonb_array_elements((\"ehr\".\"entry\".\"entry\"#>>'{/composition[openEHR-EHR-COMPOSITION.progress_note.v0],/content[openEHR-EHR-OBSERVATION.body_temperature.v2],0,/data[at0002],/events,/events[at0003]}')::jsonb)#>>'{/data[at0001],/items[at0004],0,/value,magnitude}') as numeric) \n AS var_530376446_2) as \"array_530376446_1\" on 1 = 1 join lateral (\n  select cast((ehr.xjsonb_array_elements((\"ehr\".\"entry\".\"entry\"#>>'{/composition[openEHR-EHR-COMPOSITION.progress_note.v0],/content[openEHR-EHR-OBSERVATION.pulse.v2],0,/data[at0002],/events,/events[at0003]}')::jsonb)#>>'{/data[at0001],/items[at0004],0,/value,magnitude}') as numeric) \n AS var_1056764580_4) as \"array_1056764580_3\" on 1 = 1 join lateral (\n  select cast((ehr.xjsonb_array_elements((\"ehr\".\"entry\".\"entry\"#>>'{/composition[openEHR-EHR-COMPOSITION.progress_note.v0],/content[openEHR-EHR-OBSERVATION.blood_pressure.v2],0,/data[at0001],/events,/events[at0006]}')::jsonb)#>>'{/data[at0003],/items[at0004],0,/value,magnitude}') as numeric) \n AS var_1729097973_6) as \"array_1729097973_5\" on 1 = 1 join lateral (\n  select cast((ehr.xjsonb_array_elements((\"ehr\".\"entry\".\"entry\"#>>'{/composition[openEHR-EHR-COMPOSITION.progress_note.v0],/content[openEHR-EHR-OBSERVATION.blood_pressure.v2],0,/data[at0001],/events,/events[at0006]}')::jsonb)#>>'{/data[at0003],/items[at0005],0,/value,magnitude}') as numeric) \n AS var_1643185740_8) as \"array_1643185740_7\" on 1 = 1 join lateral (\n  select cast((ehr.xjsonb_array_elements((\"ehr\".\"entry\".\"entry\"#>>'{/composition[openEHR-EHR-COMPOSITION.progress_note.v0],/content[openEHR-EHR-OBSERVATION.blood_pressure.v2],0,/data[at0001],/events,/events[at0006]}')::jsonb)#>>'{/data[at0003],/items[at1006],0,/value,magnitude}') as numeric) \n AS var_844575404_10) as \"array_844575404_9\" on 1 = 1 join lateral (\n  select cast((ehr.xjsonb_array_elements((\"ehr\".\"entry\".\"entry\"#>>'{/composition[openEHR-EHR-COMPOSITION.progress_note.v0],/content[openEHR-EHR-OBSERVATION.pulse_oximetry.v1],0,/data[at0001],/events,/events[at0002]}')::jsonb)#>>'{/data[at0003],/items[at0006],0,/value,numerator}') as numeric) \n AS var_1106971106_12) as \"array_1106971106_11\" on 1 = 1 join lateral (\n  select cast((ehr.xjsonb_array_elements((\"ehr\".\"entry\".\"entry\"#>>'{/composition[openEHR-EHR-COMPOSITION.progress_note.v0],/content[openEHR-EHR-OBSERVATION.respiration.v2],0,/data[at0001],/events,/events[at0002]}')::jsonb)#>>'{/data[at0003],/items[at0004],0,/value,magnitude}') as numeric) \n AS var_1824304885_14) as \"array_1824304885_13\" on 1 = 1 where (\"ehr\".\"entry\".\"template_id\" = ? and (jsonb_extract_path_text(cast(\"ehr\".\"js_dv_coded_text_inner\"(\"ehr\".\"entry\".\"name\") as jsonb),'value') = 'ICU_VITAL_SIGNS')))) as \"alias_19803274\" order by \"Time\" desc",
    "status": "Bad Request"
}
```

**Comment by skoba** [comment]
I confirmed this behavior in 0.19.0-SNAPSHOT, either.

**Comment by skoba** [comment]
Something wrong after 0.15.0.

**Comment by chevalleyc** [comment]
@skoba (Happy New Year btw!). Could you please post a scenario with the template(s) you have been using and sample composition(s). Thanks!

**Comment by vladislavploaia** [comment]
Hello @skoba,
Tested using your latest OPT+Composition+query.
**PASSED**
![image](https://user-images.githubusercontent.com/100927963/204309617-4363dc6a-9cf1-4c7f-ad77-ffba805395df.png)
CC: @stefanspiska , @vidi42
