### ISSUE TITLE
AQL query with misspelled composition name should return empty result

### ISSUE THREAD

**Issue by wlad** [ehrbase/ehrbase#563]
## Configuration information

```
{
  "ehrbase_version": "0.17.0",
  "openehr_sdk_version": "e4c16f4",
  "archie_version": "5a4a9442e5e2516aed5f25636ac236682aace7b9",
  "jvm_version": "Debian 11.0.11-ea+4-post-Debian-1",
  "os_version": "Linux amd64 5.10.0-kali7-amd64",
  "postgres_version": "PostgreSQL 13.3 on x86_64-pc-linux-musl,
   compiled by gcc (Alpine 10.3.1_git20210424) 10.3.1 20210424, 64-bit"
}
```

## Steps to reproduce ## 

1. upload OPT
2. commit Composition
3. post adhoc_query with gibberish Composition name, i.e.
    ```sql
              SELECT
                c/uid/value, c/name/value, c/archetype_node_id, c/composer/name
              FROM
                EHR e
              CONTAINS
                COMPOSITION c [openEHR-EHR-COMPOSITION.asdfsomegibberish.v1]
    ``` 

## Actual result ##

(example, you'll have different values in rows field)
```json
{
    "q": "SELECT c/uid/value, c/name/value, c/archetype_node_id, c/composer/name FROM EHR e CONTAINS COMPOSITION c [openEHR-EHR-COMPOSITION.asdfsomegibberish.v1]",
    "columns": [
        {
            "path": "/uid/value",
            "name": "#0"
        },
        {
            "path": "/name/value",
            "name": "#1"
        },
        {
            "path": "/archetype_node_id",
            "name": "#2"
        },
        {
            "path": "/composer/name",
            "name": "#3"
        }
    ],
    "rows": [
        [
            "36eb7e78-c99f-40bc-b750-3bb9ec72be0e::local.ehrbase.org::1",
            "Cache Test",
            "openEHR-EHR-COMPOSITION.minimal.v1",
            "Dr. Robot"
        ]
    ]
}
```

## Expected result (Acceptance Criteria) ##

empty result, since there is no Composition with the name xxx

```json
{
    "q": "SELECT c/uid/value, c/name/value, c/archetype_node_id, c/composer/name FROM EHR e CONTAINS COMPOSITION c [openEHR-EHR-COMPOSITION.asdfsomegibberish.v1]",
    "columns": [
        {
            "path": "/uid/value",
            "name": "#0"
        },
        {
            "path": "/name/value",
            "name": "#1"
        },
        {
            "path": "/archetype_node_id",
            "name": "#2"
        },
        {
            "path": "/composer/name",
            "name": "#3"
        }
    ],
    "rows": [
    ]
}
```

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by wlad** [comment]
reproduced in CI pipeline, see build https://24660-213594368-gh.circle-artifacts.com/0/~/projects/tests/results/ADMIN/log-20210810-110826.html (or download attached .zip) and check test `007-Cache-Disabled --> step 04) --> POST /query/... --> Output`

![image](https://user-images.githubusercontent.com/64201310/128893405-1d8d1bc2-78fb-4aff-923b-e0f347763de0.png)

[log-20210810-110826.zip](https://github.com/ehrbase/ehrbase/files/6962777/log-20210810-110826.zip)

**Comment by chevalleyc** [comment]
This issue is fixed in PR #562 I've added you as a reviewer to check it out. Thanks!

**Comment by wlad** [comment]
retest looks fine :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/64201310/130065064-8d193c17-baa3-4abe-af1e-ed5d7882f339.png)

**Comment by chevalleyc** [comment]
Thanks for re-test @wlad
