### ISSUE TITLE
Missing HIER_OBJECT_IDs for FLAT format

### ISSUE THREAD

**Issue by jpwiedekopf** [ehrbase/ehrbase#575]
## Configuration information

```xml
<status>
<ehrbase_version>0.17.1</ehrbase_version>
<openehr_sdk_version>78e84f6</openehr_sdk_version>
<archie_version>5a4a9442e5e2516aed5f25636ac236682aace7b9</archie_version>
<jvm_version>AdoptOpenJDK 11.0.11+9</jvm_version>
<os_version>Windows 10 amd64 10.0</os_version>
<postgres_version>
PostgreSQL 11.5 on x86_64-pc-linux-musl, compiled by gcc (Alpine 8.3.0) 8.3.0, 64-bit
</postgres_version>
</status>
```

## Steps to reproduce ## 

Create an OPT template and upload Flat compositions - the example in the Postman-Collection at https://discourse.openehr.org/uploads/short-url/seVAphaSVEz2c22d2Ta1VthWX4X.json is also affected.

## Actual result ##

The server will return many validation errors that look like the following:

```
Message at /value (/content[openEHR-EHR-ADMIN_ENTRY.admission.v0, 1]/data[at0001]/uid/value):  Attribute value of class HIER_OBJECT_ID does not match existence 1..1
Message at /value (/content[openEHR-EHR-ADMIN_ENTRY.admission.v0, 1]/data[at0001]/items[at0013, 1]/uid/value):  Attribute value of class HIER_OBJECT_ID does not match existence 1..1
```

## Expected result (Acceptance Criteria) ##

EHRbase should not complain about missing UIDs. IMO, this issue is caused by this SDK issue: https://github.com/ehrbase/openEHR_SDK/issues/254

Please merge the PR for the SDK ASAP, and then bump the SDK version for EHRbase itself, so that this fix is delivered to EHRbase. We are currently not able to commit compositions at all due to this issue.

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by jpwiedekopf** [comment]
I was able to verify that the fix in https://github.com/ehrbase/openEHR_SDK/pull/255 resolves this issue by compiling a version of the EHRbase SDK with the fix in place, and then compiling EHRbase against that dependency.

**Comment by jakesmolka** [comment]
@jpwiedekopf The SDK PR was merged and the SDK version in EHRbase bumped. Can you retest?

**Comment by jpwiedekopf** [comment]
Looking good for me, feel free to close!
