### ISSUE TITLE
In web template, the list field under type : CODED_TEXT not found when terminology is "SNOMED_CT"

### ISSUE THREAD

**Issue by Nishtha-236** [ehrbase/ehrbase#576]
**Better web template** 
"inputs": [
                {
                  "suffix": "code",
                  "type": "CODED_TEXT",
                  "list": [
                    {
                      "value": "386661006",
                      "label": "Fever",
                      "localizedLabels": {
                        "en": ""
                      }
                    },
                    {
                      "value": "25064002",
                      "label": "Headache",
                      "localizedLabels": {
                        "en": ""
                      }
                    }
                  ],
                  "terminology": "Snomed CT"
                }
              ]
![Better template](https://user-images.githubusercontent.com/60514867/132120065-53b4e417-b554-4038-b839-a98cd505f7f7.png)
**Ehrbase web template**
"inputs": [
                {
                  "suffix": "code",
                  "type": "TEXT",
                  "terminology": "Snomed CT"
                },
                {
                  "suffix": "value",
                  "type": "TEXT",
                  "terminology": "Snomed CT"
                }
              ],
![Ehrbase template](https://user-images.githubusercontent.com/60514867/132120067-43ae1791-96f6-4f97-b8b9-0d54b5455b15.png)

**Comment by subigre** [comment]
I have just retested using:
```json
{
    "ehrbase_version": "0.19.0-SNAPSHOT",
    "openehr_sdk_version": "1.7.0-SNAPSHOT",
    "archie_version": "1.0.4",
    "jvm_version": "AdoptOpenJDK 11.0.11+9",
    "os_version": "Windows 10 amd64 10.0",
    "postgres_version": "PostgreSQL 11.5 on x86_64-pc-linux-musl, compiled by gcc (Alpine 8.3.0) 8.3.0, 64-bit"
}
```
 and the following template: [ehrbase_576.v0.opt.txt](https://github.com/ehrbase/ehrbase/files/7828427/ehrbase_576.v0.opt.txt)

The output between EHRbase and Better looks pretty much the same:
![image](https://user-images.githubusercontent.com/28752830/148536531-6f157303-f4a2-4d1f-9419-deee8c22097e.png)
