### ISSUE TITLE
java.lang.IllegalArgumentException when POSTing Composition

### ISSUE THREAD

**Issue by wood-pete** [ehrbase/ehrbase#589]
Hello team,
I am new to EHRbase having only used it this week. 
With the help of Sidharth Ramesh's excellent YouTube video I've been exploring how to save a small patient observation for Blood Pressure to EHRbase.
I've created a little template and have been trying to POST the composition.

Steps I have followed:
1) Successfully created a new Composition Template (petetest.opt) using Archetype Designer with Encounter as the root, and BloodPressure archetype (see image below)

2) Successfully POSTED petetest.opt to EHRBase
   POST http://localhost:8080/ehrbase/rest/openehr/v1/definition/template/adl1.4

3) Successfully created a new EHR record. I think this is required to obtain the patient UUID (?)
   POST http://localhost:8080/ehrbase/rest/openehr/v1/ehr/{% uuid 'v4' %}

4) Used the Cabolabs toolkit to generate a Document instance from petetest.opt. Document is called petetest_000001_1.xml

5) Tried to POST petetest_000001_1.xml to EHR Base which generates the following error:
   POST http://localhost:8080/ehrbase/rest/openehr/v1/ehr/5a5e2244-d4bb-4a31-a8cc-f8a02e2e45fc/composition. (UUID generated from step 3 above)

{
  "error": "java.lang.IllegalArgumentException",
  "status": "Bad Request"
}

There is nothing displayed on the EHRBase logs for this error. 
I have tried removing some of the Composition entities which results in 'missing mandatory attributes' error, so I think the document is being validated.

EHRBase version : v0.16.5 (using the Docker images) 

Any help on resolving this issue would be gratefully received :-)

Thanks so much,
Pete
[petetest.opt.txt](https://github.com/ehrbase/ehrbase/files/7142460/petetest.opt.txt)
[petetest_000001_1.xml.txt](https://github.com/ehrbase/ehrbase/files/7142464/petetest_000001_1.xml.txt)
![petetest](https://user-images.githubusercontent.com/5198524/132827660-bfa52dbf-3647-46cd-b82e-12b179e1f9ad.png)

**Comment by sidharthramesh** [comment]
Hey @wood-pete. We'll have to ask @ppazos for this since the XML composition is being generated by his code. 

I don't use Canonical XML that much and I can't figure out what's wrong there.

I do use the FLAT format a lot, for which I have a working example. I have removed the 24 hr average node since DV_DURATION (which is mandatory) is not yet supported by Medblocks UI:

```json
{
    "petetest/category|code": "433",
    "petetest/category|value": "event",
    "petetest/category|terminology": "openehr",
    "petetest/context/start_time": "2021-09-10T13:30:16.590Z",
    "petetest/context/setting|code": "238",
    "petetest/context/setting|value": "other care",
    "petetest/context/setting|terminology": "openehr",
    "petetest/blood_pressure/any_event:0/systolic|unit": "mm[Hg]",
    "petetest/blood_pressure/any_event:0/systolic|magnitude": 120,
    "petetest/blood_pressure/any_event:0/diastolic|unit": "mm[Hg]",
    "petetest/blood_pressure/any_event:0/diastolic|magnitude": 80,
    "petetest/blood_pressure/any_event:0/time": "2021-09-10T13:30:16.590Z",
    "petetest/blood_pressure/language|code": "en",
    "petetest/blood_pressure/language|terminology": "ISO_639-1",
    "petetest/blood_pressure/encoding|code": "UTF-8",
    "petetest/blood_pressure/encoding|terminology": "IANA_character-sets",
    "petetest/composer|name": "Medblocks UI",
    "petetest/language|code": "en",
    "petetest/language|terminology": "ISO_639-1",
    "petetest/territory|code": "IN",
    "petetest/territory|terminology": "ISO_3166-1"
}
```
The above was generated from the browser directly using [Medblocks UI](https://github.com/medblocks/medblocks-ui). You can also find the code for the form [here](https://github.com/medblocks/all-forms/pull/7). There is also a [live deploy of your form](https://deploy-preview-7--unruffled-torvalds-f73b05.netlify.app/Blood_Pressure) and it logs to the console. I'll release a video about this soon 😉.

Here is another more complete composition that was generated by the example endpoint of Better CDR:

```json
{
  "petetest/_link:0|meaning": "Follow up to",
  "petetest/_link:0|type": "Problem",
  "petetest/_link:0|target": "ehr://4b15d43f-d399-470c-b414-691161589d2a",
  "petetest/_uid": "5cbb2bea-2ef8-439d-a3bf-93cdaca144dc::example::1",
  "petetest/context/start_time": "2021-09-10T11:34:15.523Z",
  "petetest/context/setting|code": "238",
  "petetest/context/setting|value": "other care",
  "petetest/context/setting|terminology": "openehr",
  "petetest/blood_pressure/_uid": "d02fa600-6822-48fe-92b5-6c62d98d555d",
  "petetest/blood_pressure/_other_participation:0|function": "performer",
  "petetest/blood_pressure/_other_participation:0|mode": "not specified",
  "petetest/blood_pressure/_other_participation:0|name": "Nurse Bailey",
  "petetest/blood_pressure/_other_participation:1|function": "requester",
  "petetest/blood_pressure/_other_participation:1|mode": "not specified",
  "petetest/blood_pressure/_other_participation:1|name": "Dr. Stiles",
  "petetest/blood_pressure/any_event:0/systolic|magnitude": 624.0,
  "petetest/blood_pressure/any_event:0/systolic|unit": "mm[Hg]",
  "petetest/blood_pressure/any_event:0/diastolic|magnitude": 781.0,
  "petetest/blood_pressure/any_event:0/diastolic|unit": "mm[Hg]",
  "petetest/blood_pressure/any_event:0/time": "2021-09-10T11:34:15.525Z",
  "petetest/blood_pressure/a24_hour_average/math_function|code": "146",
  "petetest/blood_pressure/a24_hour_average/math_function|value": "mean",
  "petetest/blood_pressure/a24_hour_average/math_function|terminology": "openehr",
  "petetest/blood_pressure/a24_hour_average/width": "P3DT3H51M",
  "petetest/blood_pressure/a24_hour_average/time": "2021-09-10T11:34:15.525Z",
  "petetest/blood_pressure/language|code": "en",
  "petetest/blood_pressure/language|terminology": "ISO_639-1",
  "petetest/blood_pressure/encoding|code": "UTF-8",
  "petetest/blood_pressure/encoding|terminology": "IANA_character-sets",
  "petetest/category|code": "433",
  "petetest/category|value": "event",
  "petetest/category|terminology": "openehr",
  "petetest/language|code": "en",
  "petetest/language|terminology": "ISO_639-1",
  "petetest/territory|code": "US",
  "petetest/territory|terminology": "ISO_3166-1"
}
```

I think you'll need to add the composer for it to work with EHRbase:
```json
"petetest/composer" : "Your name"
```

**Comment by ppazos** [comment]
The openEHR-OPT library has been updated with fixes to the generators (CLI). The toolkit will be updated soon.
