### ISSUE TITLE
Docker compose not working

### ISSUE THREAD

**Issue by joshdawson** [ehrbase/ehrbase#597]
## Configuration information

- EHRbase version: n/a
- openEHR_SDK version: n/a
- Archie version: n/a
- PostgreSQL version: n/a
- Java Runtime version: n/a
- Operating System version: MacOS Big Sur 11.5.2 (Apple M1 chip)

## Steps to reproduce ## 
Follow instructions at https://ehrbase.readthedocs.io/en/latest/03_development/04_docker_images/01_ehrbase/02_use_image/index.html#run-ehrbase-db-with-docker-compose to run EHRBase with docker compose.
- `wget https://github.com/ehrbase/ehrbase/raw/develop/docker-compose.yml`
- `wget https://github.com/ehrbase/ehrbase/raw/develop/.env.ehrbase`
- `docker-compose up`

## Actual result ##
- Various errors in docker compose output, gist with output [here](https://gist.github.com/joshdawson/35c19154e5dede7ccf999cdd70050641).
- No server running at `localhost:8080`

## Expected result (Acceptance Criteria) ##
- Docker compose successfully runs EHRBase server and DB.
- Server is available at `localhost:8080`

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by wlad** [comment]
Thanks for contribution @joshdawson . This is a know issue https://github.com/ehrbase/ehrbase/issues/604
