### ISSUE TITLE
Migration V2__ehr.sql fail

### ISSUE THREAD

**Issue by CzarMich** [ehrbase/ehrbase#603]
I am using Postgres-10, on Ubuntu 20

All have all extensions installed and enabled.

##Error Message:
 Error Code : 0
[ERROR] Message    : ERROR: function ext.uuid_generate_v4() does not exist
[ERROR]   Hint: No function matches the given name and argument types. You might need to add explicit type casts.
[ERROR] Location   : db/migration/V2__ehr.sql (/home/user/Documents/ehrbase-develop/file:/home/user/Documents/ehrbase-develop/base/target/base-0.17.2.jar!/db/migration/V2__ehr.sql)
[ERROR] Line       : 44
[ERROR] Statement  : -- storeComposition common_im entities
[ERROR] -- CREATE TABLE "system" ---------------------------------------
[ERROR] CREATE TABLE ehr.system (
[ERROR] 	id UUid PRIMARY KEY DEFAULT ext.uuid_generate_v4(),
[ERROR] 	description TEXT NOT NULL,
[ERROR] 	settings TEXT NOT NULL
[ERROR]  )
[ERROR] 

##What I have done so far:
ehrbase=# SELECT * FROM pg_catalog.pg_extension;
     extname     | extowner | extnamespace | extrelocatable | extversion | extconfig | extcondition 
-----------------+----------+--------------+----------------+------------+-----------+--------------
 plpgsql         |       10 |           11 | f              | 1.0        |           | 
 jsquery         |       10 |         2200 | t              | 1.1        |           | 
 ltree           |       10 |         2200 | t              | 1.1        |           | 
 temporal_tables |    16384 |         2200 | t              | 1.2.0      |           | 
 pgcrypto        |    16384 |         2200 | t              | 1.3        |           | 
 uuid-ossp       |    16384 |         2200 | t              | 1.1        |           | 

####
ehrbase=# SELECT uuid_generate_v4();
           uuid_generate_v4           
--------------------------------------
 2a219e6b-c438-4c4c-8677-ee0bc91f712c
(1 row)

Any help is much appreciated.

**Comment by chevalleyc** [comment]
@CzarMich please make sure the extensions are installed using the provided script in `base/db-setup` f.e. `createdb.sql` this will setup the extensions in schema `ext` (yours is installed in `public` I think)

**Comment by CzarMich** [comment]
Thanks @chevalleyc  This solved the issue.
