### ISSUE TITLE
Deprecated robot keyword

### ISSUE THREAD

**Issue by ppazos** [ehrbase/ehrbase#610]
When running any robot test suite, I'm getting this message: 

`Keyword 'R.Post Request' is deprecated. Please use `POST On Session` instead.`

We might have an outdated library @wlad ?

**Comment by wlad** [comment]
This is a know issue https://github.com/ehrbase/project_management/issues/575

@adilmushtaq is already working on it.

**Comment by adilmushtaq** [comment]
addressed in https://github.com/ehrbase/ehrbase/pull/620
