### ISSUE TITLE
FLAT format not returning all items in ITEM_TREE for POINT_EVENT

### ISSUE THREAD

**Issue by pgmullar** [ehrbase/ehrbase#614]
## Configuration information

<ehrbase_version>0.17.1</ehrbase_version>
<openehr_sdk_version>fac6c67</openehr_sdk_version>
<archie_version>5a4a9442e5e2516aed5f25636ac236682aace7b9</archie_version>
<jvm_version>Ubuntu 11.0.11+9-Ubuntu-0ubuntu2.20.04</jvm_version>
<os_version>Linux amd64 5.4.0-88-generic</os_version>
<postgres_version>PostgreSQL 11.5 on x86_64-pc-linux-musl, compiled by gcc (Alpine 8.3.0) 8.3.0, 64-bit</postgres_version>

## Steps to reproduce ## 
[Multi_list.opt.zip](https://github.com/ehrbase/ehrbase/files/7258977/Multi_list.opt.zip)

    Create a composition with multiple items under a point event ( using the attached opt file) 
    Fetch the composition in the JSON format
    Fetch the composition in the FLAT FORMAT
    Expected results: All items to be returned in both JSON format and FLAT format.

## Actual result ##

Requesting the composition in JSON format returns the list of items.

http://localhost:8080/ehrbase/rest/ecis/v1/composition/045be059-01a8-4a95-974f-8c09aa1b1744?format=JSON

{
"meta": {
"href": {
"url": "http://b1f3a260ece9:8080/ehrbase/rest/ecis/v1/composition045be059-01a8-4a95-974f-8c09aa1b1744"
}
},
"action": "RETRIEVE",
"composition": {
"_type": "COMPOSITION",
"name": {
"_type": "DV_TEXT",
"value": "Multi_list"
},
"archetype_details": {
"archetype_id": {
"value": "openEHR-EHR-COMPOSITION.report.v1"
},
"template_id": {
"value": "Multi_list"
},
"rm_version": "1.0.4"
},
"language": {
"_type": "CODE_PHRASE",
"terminology_id": {
"_type": "TERMINOLOGY_ID",
"value": "ISO_639-1"
},
"code_string": "en"
},
"territory": {
"_type": "CODE_PHRASE",
"terminology_id": {
"_type": "TERMINOLOGY_ID",
"value": "ISO_3166-1"
},
"code_string": "GB"
},
"category": {
"_type": "DV_CODED_TEXT",
"value": "persistent",
"defining_code": {
"_type": "CODE_PHRASE",
"terminology_id": {
"_type": "TERMINOLOGY_ID",
"value": "openehr"
},
"code_string": "431"
}
},
"composer": {
"_type": "PARTY_IDENTIFIED",
"name": "Test"
},
"content": [
{
"_type": "OBSERVATION",
"name": {
"_type": "DV_TEXT",
"value": "Story/History"
},
"language": {
"_type": "CODE_PHRASE",
"terminology_id": {
"_type": "TERMINOLOGY_ID",
"value": "ISO_639-1"
},
"code_string": "en"
},
"encoding": {
"_type": "CODE_PHRASE",
"terminology_id": {
"_type": "TERMINOLOGY_ID",
"value": "IANA_character-sets"
},
"code_string": "UTF-8"
},
"subject": {
"_type": "PARTY_SELF"
},
"provider": {
"_type": "PARTY_IDENTIFIED"
},
"data": {
"name": {
"_type": "DV_TEXT",
"value": "Event Series"
},
"origin": {
"_type": "DV_DATE_TIME",
"value": "2021-09-30T10:10:38,209561+01:00"
},
"events": [
{
"_type": "POINT_EVENT",
"name": {
"_type": "DV_TEXT",
"value": "MultiList"
},
"time": {
"_type": "DV_DATE_TIME",
"value": "2021-09-30T10:10:38,211469+01:00"
},
"data": {
"_type": "ITEM_TREE",
"name": {
"_type": "DV_TEXT",
"value": "Tree"
},
"items": [
{
"_type": "ELEMENT",
"name": {
"_type": "DV_TEXT",
"value": "Items"
},
"value": {
"_type": "DV_TEXT",
"value": "One"
},
"archetype_node_id": "at0004"
},
{
"_type": "ELEMENT",
"name": {
"_type": "DV_TEXT",
"value": "Items"
},
"value": {
"_type": "DV_TEXT",
"value": "Two"
},
"archetype_node_id": "at0004"
},
{
"_type": "ELEMENT",
"name": {
"_type": "DV_TEXT",
"value": "Items"
},
"value": {
"_type": "DV_TEXT",
"value": "Three"
},
"archetype_node_id": "at0004"
}
],
"archetype_node_id": "at0003"
},
"archetype_node_id": "at0002"
}
],
"archetype_node_id": "at0001"
},
"archetype_node_id": "openEHR-EHR-OBSERVATION.story.v1"
}
],
"archetype_node_id": "openEHR-EHR-COMPOSITION.report.v1",
"uid": {
"_type": "OBJECT_VERSION_ID",
"value": "045be059-01a8-4a95-974f-8c09aa1b1744::local.ehrbase.org::1"
}
},
"format": "JSON",
"templateId": "Multi_list",
"ehrId": "d270a63f-2aaf-41f8-bf24-94323bef4f2c",
"compositionUid": "045be059-01a8-4a95-974f-8c09aa1b1744"
}

Whilst the FLAT format only returns the last item.

http://localhost:8080/ehrbase/rest/ecis/v1/composition/045be059-01a8-4a95-974f-8c09aa1b1744?format=FLAT

{
"meta": {
"href": {
"url": "http://b1f3a260ece9:8080/ehrbase/rest/ecis/v1/composition045be059-01a8-4a95-974f-8c09aa1b1744"
}
},
"action": "RETRIEVE",
"composition": {
"multi_list/category|code": "431",
"multi_list/category|value": "persistent",
"multi_list/category|terminology": "openehr",
"multi_list/story_history/items:0": "Three",
"multi_list/story_history/time": "2021-09-30T10:10:38.211469+01:00",
"multi_list/story_history/language|terminology": "ISO_639-1",
"multi_list/story_history/language|code": "en",
"multi_list/story_history/encoding|code": "UTF-8",
"multi_list/story_history/encoding|terminology": "IANA_character-sets",
"multi_list/composer|name": "Test",
"multi_list/language|terminology": "ISO_639-1",
"multi_list/language|code": "en",
"multi_list/territory|code": "GB",
"multi_list/territory|terminology": "ISO_3166-1",
"multi_list/_uid": "045be059-01a8-4a95-974f-8c09aa1b1744::local.ehrbase.org::1"
},
"format": "FLAT",
"templateId": "Multi_list",
"ehrId": "d270a63f-2aaf-41f8-bf24-94323bef4f2c",
"compositionUid": "045be059-01a8-4a95-974f-8c09aa1b1744"
}

## Expected result (Acceptance Criteria) ##

The FLAT composition to contain all elements added.

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)

- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by stefanspiska** [comment]
validated that the issue also happens on dev.
