### ISSUE TITLE
ehrbase-docker - Swagger-ui does not work properly

### ISSUE THREAD

**Issue by up-d-down-v** [ehrbase/ehrbase#623]
## Configuration information

<status>
<ehrbase_version>0.17.2</ehrbase_version>
<openehr_sdk_version>10cce9b</openehr_sdk_version>
<archie_version>1.0.3</archie_version>
<jvm_version>Oracle Corporation 11.0.12+7</jvm_version>
<os_version>Linux amd64 5.4.0-81-generic</os_version>
<postgres_version>
PostgreSQL 10.12 on x86_64-pc-linux-musl, compiled by gcc (Alpine 9.2.0) 9.2.0, 64-bit
</postgres_version>
</status>

## Steps to reproduce ## 

1. cloned latest github repo
2. cd into and `docker-compose up -d`
3. enter `%ehrbaseBaseUri%/ehrbase/swagger-ui.html#/` in browser
4. click on something (arbitrary)
5. no response other than changing the URI

## Actual result ##

![grafik](https://user-images.githubusercontent.com/92175364/136592264-c546bd0b-9654-4a58-82b9-90fb4d19a05e.png)

## Expected result (Acceptance Criteria) ##
displaying the interactive swagger-API 

displaying the interactive swagger-API  
## Definition of Done ##
a working swagger-API
I tested an older image of ehrbase (version 0.15.0) and there swagger-API still works

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by up-d-down-v** [comment]
[ehrbase docker version 0.16.3](https://hub.docker.com/layers/ehrbase/ehrbase/0.16.3/images/sha256-c268bd9c39437d47a04cc38a47a444a72e6e0a3da2a39d40d89eef086e0c023d?context=explore) seems to work with [latest database](https://hub.docker.com/layers/ehrbase/ehrbase-postgres/latest/images/sha256-7e414387d59f601fc9b0da5ec2b1ad73738c43a9f9d2b6e643882b2325533e9d?context=explore)

**Comment by sumitrathi95** [comment]
I also tried now with docker image: ehrbase/ehrbase:0.17.2, but still not able to get swagger data (endpoints), only URL is changing example: http://1.2.3.4:8080/ehrbase/swagger-ui.html#/Composition... which docker image should I use? I am also using Cloud Managed SQL Database.

**Comment by subigre** [comment]
I apologize because I mentioned latest but I was thinking latest version using the develop branch.
Regarding Docker could you please try with: `ehrbase/ehrbase:next`

**Comment by subigre** [comment]
I reopen the issue.
@sumitrathi95, would you so kind to give a try and close it if it works?

**Comment by subigre** [comment]
I close this issue because I try again with the latest images (`latest`, `0.18.3` and `next`) and Swagger UI works properly.

```json
{
    "ehrbase_version": "0.18.3",
    "openehr_sdk_version": "1.6.0",
    "archie_version": "1.0.4",
    "jvm_version": "Oracle Corporation 11.0.13+8",
    "os_version": "Linux amd64 5.10.60.1-microsoft-standard-WSL2",
    "postgres_version": "PostgreSQL 11.5 on x86_64-pc-linux-musl, compiled by gcc (Alpine 8.3.0) 8.3.0, 64-bit"
}
```

```json
{
    "ehrbase_version": "0.19.0-SNAPSHOT",
    "openehr_sdk_version": "1.7.0-SNAPSHOT",
    "archie_version": "1.0.4",
    "jvm_version": "Oracle Corporation 11.0.13+8",
    "os_version": "Linux amd64 5.10.60.1-microsoft-standard-WSL2",
    "postgres_version": "PostgreSQL 11.5 on x86_64-pc-linux-musl, compiled by gcc (Alpine 8.3.0) 8.3.0, 64-bit"
}
```
