### ISSUE TITLE
Commit compo validation error when terminology is local and there is no list provided

### ISSUE THREAD

**Issue by ppazos** [ehrbase/ehrbase#643]
## Configuration information

```
<status>
  <ehrbase_version>0.17.2</ehrbase_version>
  <openehr_sdk_version>30e3c81</openehr_sdk_version>
  <archie_version>1.0.3</archie_version>
  <jvm_version>Oracle Corporation 11.0.6+10</jvm_version>
  <os_version>Linux amd64 4.15.0-91-generic</os_version>
  <postgres_version>PostgreSQL 10.14 (Ubuntu 10.14-0ubuntu0.18.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, 64-bit</postgres_version>
</status>
```

## Steps to reproduce ## 

The OPT test all types for the node at0005 has a DV_CODED_TEXT constraint with terminology_id=local and no list of codes provided.

https://github.com/ehrbase/ehrbase/blob/develop/tests/robot/_resources/test_data_sets/valid_templates/all_types/Test_all_types.opt#L361-L409

With Thomas we think the OPT with that kind of constraint should be treated as invalid, since 'local' means the code SHOULD be in the template. See the discussion:

https://discourse.openehr.org/t/is-terminology-id-local-compatible-to-not-specifying-a-code-list-in-the-archetype/1921

This can be checked via Robot: (remove -v nodocker if you are using docker)

`$ robot -i AQL_loaded_db -e TODO -e FUTURE -d results -L TRACE -v nodocker robot`

## Actual result ##

The issue we have is: the template validates when uploaded, and what fails is the commit of the COMPOSITION, since it has a random code in the DV_CODED_TEXT.

```
{
	"error": "org.ehrbase.validation.constraints.wrappers.ValidationException: :-Validation error at /content[openEHR-EHR-OBSERVATION.test_all_types.v1]/data[at0001]/events[at0002]/data[at0003]/items[at0005]:Validation error at /content[openEHR-EHR-OBSERVATION.test_all_types.v1]/data[at0001]/events[at0002]/data[at0003]/items[at0005], ELT02:Validation error at /content[openEHR-EHR-OBSERVATION.test_all_types.v1]/data[at0001]/events[at0002]/data[at0003]/items[at0005], ELT01:Validation error at /content[openEHR-EHR-OBSERVATION.test_all_types.v1]/data[at0001]/events[at0002]/data[at0003]/items[at0005], Validation error at /content[openEHR-EHR-OBSERVATION.test_all_types.v1]/data[at0001]/events[at0002]/data[at0003]/items[at0005], ELT01:Validation error at /content[openEHR-EHR-OBSERVATION.test_all_types.v1]/data[at0001]/events[at0002]/data[at0003]/items[at0005], CODED_TEXT_01:CodedText value is not valid:DvCodedText{defining_code=local::702051, value=WDvvwQSxQLqGraAaRkB  DEfRoP wZ}.\n\n",
	"status": "Bad Request"
}
```

This error is correct, though allowing that template to upload, generates a deadlock: actually the at0005 coded text can't be used at all in compositions.

## Expected result (Acceptance Criteria) ##

That condition should make the OPT upload to fail.

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by wlad** [comment]
> That condition should make the OPT upload to fail.

@ppazos should we create an invalid test from this one to have a regression test for this case? I've seen that you have  commented out `types/Test_all_types.opt` in PR https://github.com/ehrbase/ehrbase/pull/644 and replaced it with another OPT.

```robotframework
All Types
    [Template]         validate valid OPT

    all_types/Test_all_types.opt
```

**Comment by vladislavploaia** [comment]
Hello @ppazos, @wlad,
Bug reported in JIRA for tracking purposes:
https://jira.vitagroup.ag/browse/CDR-463
Will let you know if there are any updates.
Robot test case will be created once the fix is provided. Should not enable it right now, as it might affect the overall execution with wrong template content.

**Comment by vladislavploaia** [comment]
Was able to upload template.
![image](https://github.com/ehrbase/ehrbase/assets/100927963/d2dc7e4c-c1ac-4153-ac52-b3c601ae0103)
[upload_template_resp.txt](https://github.com/ehrbase/ehrbase/files/12320479/upload_template_resp.txt)
Tested on EHRbase **0.30.0-SNAPSHOT**
Ticket closed.
CC: @vidi42
