### ISSUE TITLE
Make OAuth 2 role names configurable

### ISSUE THREAD

**Issue by elisabethallan** [ehrbase/ehrbase#655]
## Background ##

Hi,

Me and my team are working on a deployment of EHRBase. As part of this deployment, we are looking to enable OAuth 2 role-based authentication in order to manage client credentials for different teams to have access to the EHRBase instance. We are using an AWS Cognito user pool to manage client identity, with our EHRBase instance being registered as a resource provider within Cognito. We would then provision app clients with the "user"/"admin" scope as appropriate.

I note in ﻿#353 that previously EHRBase required the "user"/"admin" role names to be set within a "realm_access.role" claim, with the suggestion that it should instead be in the "scopes" claim, as is standard for JWTs. I can see that this change was made in EHRBase 0.17. However, a subsequent issue is present for compatibility with Cognito (and potentially other identity providers). Cognito prefixes all custom scopes with the URI of the resource server. So, for instance, we cannot declare a "user" or "admin" scope in Cognito, but rather a "ehrbase.healthservice.com/user" or "ehrbase.healthservice.com/admin" scope. Because EHRBase looks strictly for "user" or "admin" in the scope, these scopes will not be detected. This unfortunately blocks us in progressing with our deployment of EHRBase.

Therefore, I propose instead of having the role names fixed as "user" or "admin", they should instead be configurable, e.g. `OAUTH2_USER_ROLE` and `OAUTH2_ADMIN_ROLE`. This config could be set in the YAML configuration or via environment variable, as is the case with other EHRBase configuration.

As this blocks our deployment of EHRBase, my team are going to look at forking the codebase and making this change ourselves. We would then submit the change back as a PR if this is a change you'd like to include in a future release?

Many thanks,
Elisabeth

## Acceptance criteria ##

- [ ] User and admin OAuth2 role names should be configurable through YAML/environment variables
- [ ] EHRBase should look for these configured roles when decoding the OAuth 2 JWT, and apply its RBAC policies accordingly

## Definition of Done ##

- [ ] Review / Merge request approved (P2P session)
- [ ] Unit tests passed
- [ ] Updated documentation (Javadoc and Sphinx)
- [ ] Acceptance criteria fulfilled
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] Runtime warnings

**Comment by birgerhaarbrandt** [comment]
Hi @elisabethallan,

I will check with my team. What you suggest sounds reasonable and we are looking forward to your PR!
