### ISSUE TITLE
Composition not POST-ing to EHRBase, giving error "Could not consume Parts "

### ISSUE THREAD

**Issue by ATHULKNAIR** [ehrbase/ehrbase#659]
#Hi, I am the co-developer of medblocks-ui.

## Configuration information

- EHRbase version:  0.17.2
- openEHR_SDK version:  321ef09
- Archie version:  1.0.3
- PostgreSQL version:  PostgreSQL 13.3 (Debian 13.3-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
- Java Runtime version:  Oracle Corporation 11.0.13+8
- Operating System version:  Linux amd64 5.10.16.3-microsoft-standard-WSL2

## Steps to reproduce ## 

The template that I am using is:   NCD TEMPLATE

[NCD TEMPLATE.txt](https://github.com/ehrbase/ehrbase/files/7504595/NCD.TEMPLATE.txt)

The composition that I have attached is giving an error while POSTing to the EhrBase
, but it is POSTing in Better without any sort of error.

[NCD TEST- COMPOSITION.txt](https://github.com/ehrbase/ehrbase/files/7504598/NCD.TEST-.COMPOSITION.txt)

## Actual result ##

EHRBase is giving this error: 
ERROR : 

{
  "error": "Could not consume Parts [ncd/laboratory_test_result/any_event:0/blood_group/blood_group|terminology, ncd/urinalysis/point_in_time:0/glucose|terminology, ncd/laboratory_test_result/any_event:0/haemoglobin/haemoglobin|unit, ncd/laboratory_test_result/any_event:0/cholesterol/cholesterol|magnitude, ncd/laboratory_test_result/any_event:0/cholesterol/cholesterol|unit, ncd/laboratory_test_result/any_event:0/blood_group/blood_group|value, ncd/laboratory_test_result/any_event:0/uric_acid/uric_acid|magnitude, ncd/urinalysis/point_in_time:0/protein|terminology, ncd/laboratory_test_result/any_event:0/uric_acid/uric_acid|unit, ncd/laboratory_test_result/any_event:0/blood_group/blood_group|code, ncd/laboratory_test_result/any_event:0/blood_glucose/blood_glucose_level|unit, ncd/laboratory_test_result/any_event:0/blood_glucose/blood_glucose_level|magnitude, ncd/laboratory_test_result/any_event:0/haemoglobin/haemoglobin|magnitude]",
  "status": "Internal Server Error"
}

## Expected result (Acceptance Criteria) ##

The composition should perform POST without any error. 

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by stefanspiska** [comment]
this works as of https://github.com/ehrbase/ehrbase/pull/662

Note that 
```
    "ncd/urinalysis/point_in_time:0/glucose|terminology": "undefined",
    "ncd/urinalysis/point_in_time:0/protein|terminology": "undefined",
```

are ignored  and will be replaces by "local"

**Comment by sidharthramesh** [comment]
Thanks a lot @stefanspiska for the quick fix!

**Comment by sidharthramesh** [comment]
The issue is now fixed with the latest commit. However, please note that we had to clear out the database for the fix to work. It may not be ideal in a production setting. Maybe something to do with web template caches not updating properly?

Anyway, this issue is definitely resolved.

**Comment by stefanspiska** [comment]
@sidharthramesh 
Where the templates at any point in time updated , without updating the version of the template?

**Comment by sidharthramesh** [comment]
The admin endpoint was never used. So, I don't think the templates could have been updated like that.
