### ISSUE TITLE
AQL Query; Result rows are not returned if a select field is empty.

### ISSUE THREAD

**Issue by pgmullar** [ehrbase/ehrbase#660]
## Configuration information

[minimal_action.zip](https://github.com/ehrbase/ehrbase/files/7513559/minimal_action.zip)

    <ehrbase_version>0.17.2</ehrbase_version>
    <openehr_sdk_version>321ef09</openehr_sdk_version>
    <archie_version>1.0.3</archie_version>
    <jvm_version>Ubuntu 11.0.11+9-Ubuntu-0ubuntu2.20.04</jvm_version>
    <os_version>Linux amd64 5.4.0-90-generic</os_version>
    <postgres_version>PostgreSQL 11.5 on x86_64-pc-linux-musl, compiled by gcc (Alpine 8.3.0) 8.3.0, 64-bit</postgres_version>

## Steps to reproduce ## 

- Create two compositions;

One with an optional field populated;  i.e. Multimedia|alternatetext
{
    "ctx/language": "en",
    "ctx/territory": "US",
    "ctx/composer_name": "Silvia Blake",
    "ctx/id_namespace": "HOSPITAL-NS",
    "ctx/id_scheme": "HOSPITAL-NS",
    "minimal/minimal:0/ism_transition/current_state|code": "532",
    "minimal/minimal:0/ism_transition/current_state|value": "completed",
    "minimal/minimal:0/multimedia": "http://med.tube.com/sample",
    "minimal/minimal:0/multimedia|mediatype": "application/pdf",
    "minimal/minimal:0/multimedia|alternatetext": "Alternative text",
    "minimal/minimal:0/multimedia|size": 504903212,
    "minimal/minimal:0/time": "2021-11-10T14:08:05.928Z"
}

and one without the optional field populated;

{
    "ctx/language": "en",
    "ctx/territory": "US",
    "ctx/composer_name": "Silvia Blake",
    "ctx/id_namespace": "HOSPITAL-NS",
    "ctx/id_scheme": "HOSPITAL-NS",
    "minimal/minimal:0/ism_transition/current_state|code": "532",
    "minimal/minimal:0/ism_transition/current_state|value": "completed",
    "minimal/minimal:0/multimedia": "http://med.tube.com/sample",
    "minimal/minimal:0/multimedia|mediatype": "application/pdf",
    "minimal/minimal:0/multimedia|size": 504903212,
    "minimal/minimal:0/time": "2021-11-10T14:08:05.928Z"
}

- Write an AQL query to fetch values from within the compositions where some of the values may not yet be populated.

e.g.

"Select a/uid/value as composition_uid, a0/description[at0001]/items[at0002]/value/alternate_text as alternate_text, a0/description[at0001]/items[at0002]/value/size as size, a0/language/code_string as language from EHR e contains COMPOSITION a contains ACTION a0[openEHR-EHR-ACTION.minimal.v1]"

## Actual result ##

A row is not returned if any of the requested fields in the select statement are empty.

e.g.
{
    "q": "Select a/uid/value as composition_uid, a0/description[at0001]/items[at0002]/value/alternate_text as alternate_text, a0/description[at0001]/items[at0002]/value/size as size, a0/language/code_string as language from EHR e contains COMPOSITION a contains ACTION a0[openEHR-EHR-ACTION.minimal.v1]",
    "columns": [
        {
            "path": "/uid/value",
            "name": "composition_uid"
        },
        {
            "path": "/description[at0001]/items[at0002]/value/alternate_text",
            "name": "alternate_text"
        },
        {
            "path": "/description[at0001]/items[at0002]/value/size",
            "name": "size"
        },
        {
            "path": "/language/code_string",
            "name": "language"
        }
    ],
    "rows": [
        [
            "01c5fae9-809e-4b9f-84b0-f71d2dae08f4::local.ehrbase.org::1",
            "Alternative text",
            "504903212",
            "en"
        ]
    ]
}

## Expected result (Acceptance Criteria) ##

Row are returned with empty fields populated with null as per previous versions of ehrbase.

e.g.
    <ehrbase_version>0.17.2</ehrbase_version>
    <openehr_sdk_version>fac6c67</openehr_sdk_version>

{
    "q": "Select a/uid/value as composition_uid, a0/description[at0001]/items[at0002]/value/alternate_text as alternate_text, a0/description[at0001]/items[at0002]/value/size as size, a0/language/code_string as language from EHR e contains COMPOSITION a contains ACTION a0[openEHR-EHR-ACTION.minimal.v1]",
    "columns": [
        {
            "path": "/uid/value",
            "name": "composition_uid"
        },
        {
            "path": "/description[at0001]/items[at0002]/value/alternate_text",
            "name": "alternate_text"
        },
        {
            "path": "/description[at0001]/items[at0002]/value/size",
            "name": "size"
        },
        {
            "path": "/language/code_string",
            "name": "language"
        }
    ],
    "rows": [
        [
            "360df1fd-dbfb-4565-877c-42e2c5a16328::local.ehrbase.org::1",
            null,
            "504903212",
            "en"
        ],
        [
            "01c5fae9-809e-4b9f-84b0-f71d2dae08f4::local.ehrbase.org::1",
            "Alternative text",
            "504903212",
            "en"
        ]
    ]
}

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by chevalleyc** [comment]
@pgmullar could you please upload the corresponding template you have been using above? Thanks!

**Comment by chevalleyc** [comment]
@pgmullar the second composition cannot be posted using the current code base:
```
{
    "error": "java.lang.IllegalArgumentException: Message at /description (/content[openEHR-EHR-ACTION.minimal.v1, 1]/description):  Attribute description of class ACTION does not match existence 1..1\n",
    "status": "Internal Server Error"
}
```
Could you please update it so I can reproduce this issue locally? Thanks

**Comment by pgmullar** [comment]
The example compositions have been updated to use "multimedia|alternatetext" as the optional field to illustrate the issue.
