### ISSUE TITLE
Composer id & id_scheme not returned when committed using FLAT

### ISSUE THREAD

**Issue by dileep-ehr** [ehrbase/ehrbase#663]
## Configuration information
<?xml version='1.0' encoding='UTF-8'?>
<status>
    <ehrbase_version>0.17.2</ehrbase_version>
    <openehr_sdk_version>321ef09</openehr_sdk_version>
    <archie_version>1.0.3</archie_version>
    <jvm_version>Ubuntu 11.0.11+9-Ubuntu-0ubuntu2.18.04</jvm_version>
    <os_version>Linux amd64 5.4.0-90-generic</os_version>
    <postgres_version>PostgreSQL 14.0 (Ubuntu 14.0-1.pgdg18.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, 64-bit</postgres_version>
</status>

## Steps to reproduce ## 

Commit composition

{
"ctx/language": "en",
"ctx/territory": "IN",
"ctx/time": "2020-07-29T13:04:02.506+05:30",
"clinical_notes/composer|name": "Dr Joyce Smith",
"clinical_notes/composer|id": "1234-5678",
"clinical_notes/composer|id_scheme": "UUID",
"clinical_notes/composer|id_namespace": "EHR.NETWORK",
"clinical_notes/context/_health_care_facility|id": "12342341",
"clinical_notes/context/_health_care_facility|id_scheme": "UUID",
"clinical_notes/context/_health_care_facility|id_namespace": "EHR.NETWORK",
"clinical_notes/context/_health_care_facility|name": "HealtheLife",
"clinical_notes/context/_participation:0|name": "Frederick Wolfstein",
"clinical_notes/context/_participation:0|id": "999",
"clinical_notes/context/_participation:0|function": "performer",
"clinical_notes/context/_participation:0|mode": "face-to-face communication",
"clinical_notes/context/_participation:0|id_namespace": "Test",
"clinical_notes/context/_participation:0|id_scheme": "Test",
"clinical_notes/context/_participation:1|name": "Caris Wooler",
"clinical_notes/context/_participation:1|id": "998",
"clinical_notes/context/_participation:1|id_namespace": "Test",
"clinical_notes/context/_participation:1|id_scheme": "Test",
"clinical_notes/context/_participation:1|function": "instructor",
"clinical_notes/context/_participation:1|mode": "videoconferencing",
"clinical_notes/context/setting|code": "228",
"clinical_notes/context/setting|value": "primary medical care",
"clinical_notes/context/setting|terminology": "openehr",
"clinical_notes/category|code":"433",
"clinical_notes/category|value":"event",
"clinical_notes/category|terminology":"openehr",
"clinical_notes/clinical_synopsis:0/synopsis": "Clinical notes"
}

## Actual result ##
Get composition

{
  "meta": {
    "href": {
      "url": "http://ip6-localhost:8080/ehr/rest/ecis/v1/composition/2e684432-e2af-4ef8-9025-b8314074e8d6"
    }
  },
  "action": "RETRIEVE",
  "composition": {
    "clinical_notes/category|value": "event",
    "clinical_notes/category|code": "433",
    "clinical_notes/category|terminology": "openehr",
    "clinical_notes/context/start_time": "2020-07-29T13:04:02.506+05:30",
    "clinical_notes/context/setting|terminology": "openehr",
    "clinical_notes/context/setting|value": "primary medical care",
    "clinical_notes/context/setting|code": "228",
    "clinical_notes/context/_health_care_facility|id_scheme": "UUID",
    "clinical_notes/context/_health_care_facility|id_namespace": "EHR.NETWORK",
    "clinical_notes/context/_health_care_facility|name": "HealtheLife",
    "clinical_notes/context/_health_care_facility|id": "12342341",
    "clinical_notes/context/_participation:0|function": "performer",
    "clinical_notes/context/_participation:0|name": "Frederick Wolfstein",
    "clinical_notes/context/_participation:0|id_namespace": "Test",
    "clinical_notes/context/_participation:0|id_scheme": "Test",
    "clinical_notes/context/_participation:0|mode": "face-to-face communication",
    "clinical_notes/context/_participation:0|id": "999",
    "clinical_notes/context/_participation:1|name": "Caris Wooler",
    "clinical_notes/context/_participation:1|id_namespace": "Test",
    "clinical_notes/context/_participation:1|mode": "videoconferencing",
    "clinical_notes/context/_participation:1|id_scheme": "Test",
    "clinical_notes/context/_participation:1|function": "instructor",
    "clinical_notes/context/_participation:1|id": "998",
    "clinical_notes/clinical_synopsis:0/synopsis": "Clinical notes",
    "clinical_notes/clinical_synopsis:0/language|code": "en",
    "clinical_notes/clinical_synopsis:0/language|terminology": "ISO_639-1",
    "clinical_notes/clinical_synopsis:0/encoding|code": "UTF-8",
    "clinical_notes/clinical_synopsis:0/encoding|terminology": "IANA_character-sets",
    "clinical_notes/composer|name": "Dr Joyce Smith",
    "clinical_notes/language|code": "en",
    "clinical_notes/language|terminology": "ISO_639-1",
    "clinical_notes/territory|code": "IN",
    "clinical_notes/territory|terminology": "ISO_3166-1",
    "clinical_notes/_uid": "2e684432-e2af-4ef8-9025-b8314074e8d6::local.ehr.network::1"
  },
  "format": "FLAT",
  "templateId": "EHRN Clinical notes.v1",
  "ehrId": "0d0db4fb-2b6b-415f-8cf9-fa4416d0810b",
  "compositionUid": "2e684432-e2af-4ef8-9025-b8314074e8d6"
}

## Expected result (Acceptance Criteria) ##

The followign values are missing in GET composition

"clinical_notes/composer|id": "1234-5678",
"clinical_notes/composer|id_scheme": "UUID",
"clinical_notes/composer|id_namespace": "EHR.NETWORK",

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by dileep-ehr** [comment]
This same behaviour observed in 0.19.0-SNAPSHOT also

**Comment by stefanspiska** [comment]
This works now on dev

see
sdk
DbConformanceTest.testRoundTrip:
EHRBASE_CONFORMANCE_COMPOSITION
