### ISSUE TITLE
null_reason not getting committed

### ISSUE THREAD

**Issue by dileep-ehr** [ehrbase/ehrbase#668]
## Configuration information

    <ehrbase_version>0.17.3-SNAPSHOT</ehrbase_version>
    <openehr_sdk_version>1e26bf1</openehr_sdk_version>
    <archie_version>1.0.4</archie_version>
    <jvm_version>Ubuntu 11.0.11+9-Ubuntu-0ubuntu2.18.04</jvm_version>
    <os_version>Linux amd64 5.4.0-90-generic</os_version>
    <postgres_version>PostgreSQL 14.0 (Ubuntu 14.0-1.pgdg18.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, 64-bit</postgres_version>

## Steps to reproduce ## 

Tried to commit the following
```
"clinical_notes/clinical_synopsis:0/synopsis/_null_flavour|code": "271",
"clinical_notes/clinical_synopsis:0/synopsis/_null_flavour|value": "no information",
"clinical_notes/clinical_synopsis:0/synopsis/_null_flavour|terminology": "local",
"clinical_notes/clinical_synopsis:0/synopsis/_null_reason": "sample reason"
```

## Actual result ##
On get composition, the following is returned
```
"clinical_notes/clinical_synopsis:0/synopsis/_null_flavour|code": "271",
"clinical_notes/clinical_synopsis:0/synopsis/_null_flavour|value": "no information",
"clinical_notes/clinical_synopsis:0/synopsis/_null_flavour|terminology": "local",
```
"clinical_notes/clinical_synopsis:0/synopsis/_null_reason": "sample reason" is missing

## Expected result (Acceptance Criteria) ##

Should also return "clinical_notes/clinical_synopsis:0/synopsis/_null_reason": "sample reason"

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by stefanspiska** [comment]
see also

DbConformanceTest.testRoundTrip
EHRBASE_CONFORMANCE_ELEMENT_NULL_FLAVOR

see also
https://jira.vitagroup.ag/browse/CDR-222
