### ISSUE TITLE
Link not geting committed at node level using FLAT format

### ISSUE THREAD

**Issue by dileep-ehr** [ehrbase/ehrbase#671]
## Configuration information

 <ehrbase_version>0.17.3-SNAPSHOT</ehrbase_version>
    <openehr_sdk_version>1e26bf1</openehr_sdk_version>
    <archie_version>1.0.4</archie_version>
    <jvm_version>Ubuntu 11.0.11+9-Ubuntu-0ubuntu2.18.04</jvm_version>
    <os_version>Linux amd64 5.4.0-90-generic</os_version>
    <postgres_version>PostgreSQL 14.0 (Ubuntu 14.0-1.pgdg18.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, 64-bit</postgres_version>
## Actual result ##

Link values at the archetype node level are accepted on commit but not returned. 
```
"clinical_notes/clinical_synopsis:0/synopsis/_link:0|type": "problem",
"clinical_notes/clinical_synopsis:0/synopsis/_link:0|meaning": "problem related note",
"clinical_notes/clinical_synopsis:0/synopsis/_link:0|target": "ehr://ehr.network/347a5490-55ee-4da9-b91a-9bba710f730e"
```
At the archetype and composition level there work properly
At composition level
```
"clinical_notes/_link:0|type": "problem",
"clinical_notes/_link:0|meaning": "problem related note",
"clinical_notes/_link:0|target": "ehr://ehr.network/347a5490-55ee-4da9-b91a-9bba710f730e",

```At archetype level
```
"clinical_notes/clinical_synopsis:0/_link:0|type": "problem",
"clinical_notes/clinical_synopsis:0/_link:0|meaning": "problem related note",
"clinical_notes/clinical_synopsis:0/_link:0|target": "ehr://ehr.network/347a5490-55ee-4da9-b91a-9bba710f730e",

```

## Expected result (Acceptance Criteria) ##
Should commit values and return on get

## Definition of Done ##

<!-- These checklist entries are used by our developers to deliver a solution with a base quality
we want to acheive. If you want to add other points specific to this issue, put them into the section
"Expected result (Acceptance Criteria)" -->

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by stefanspiska** [comment]
I assume this is a section:

see also 
sdk:
DbConformanceTest.testRoundTrip:
EHRBASE_CONFORMANCE_SECTION

see also https://jira.vitagroup.ag/browse/CDR-220
