### ISSUE TITLE
PUT /ehr/ehr_id/directory overrides timestamp of initially created folder

### ISSUE THREAD

**Issue by wlad** [ehrbase/ehrbase#674]
After updating a folder, it's not possible to get the initial version of it via GET /directory?version_at_time because it has the same timestamp as the updated folder. 

![image](https://user-images.githubusercontent.com/64201310/143145076-aebdaa65-03b5-4420-b5fd-7bc6526241b0.png)

https://user-images.githubusercontent.com/64201310/143145158-510f1e60-36b5-486d-a2d1-29b89aa93d6c.mp4

## Test Case/s To Reproduce Issue

```
# path to test case
GET_DIRECTORY_AT_TIME/G.8__EHR_with_directory_with_multiple_versions_first_version.robot


```

```
# robot command to execute related test case(s)

robot -i 674 -d results -L TRACE robot/DIRECTORY_TESTS 

```

## Actual Result

all versions of a folder have the same timestamp

## Expected Result

each version of a folder has it's own timestamp (of when it was created)

**Comment by vladislavploaia** [comment]
Bug fixed. Test refactored.
![image](https://user-images.githubusercontent.com/100927963/221800344-8dcef198-8479-42be-9029-f4f10455f5b3.png)
[results.zip](https://github.com/ehrbase/ehrbase/files/10848200/results.zip)
Ticket closed.
CC: @vidi42 , @stefanspiska
