### ISSUE TITLE
Endlessly running request without response/error on posting a composition via FLAT API

### ISSUE THREAD

**Issue by richter122-goe** [ehrbase/ehrbase#679]
## Configuration information

    <ehrbase_version>0.17.2</ehrbase_version>
    <openehr_sdk_version>fac6c67</openehr_sdk_version>
    <archie_version>5a4a9442e5e2516aed5f25636ac236682aace7b9</archie_version>
    <jvm_version>Oracle Corporation 11.0.12+7</jvm_version>
    <os_version>Linux amd64 5.4.0-90-generic</os_version>
    <postgres_version>PostgreSQL 11.5 on x86_64-pc-linux-musl, compiled by gcc (Alpine 8.3.0) 8.3.0, 64-bit</postgres_version>

## Steps to reproduce ## 

1. Post Composition via FLAT API

POST {{host}}ehrbase//rest/ecis/v1/composition/?format=FLAT&ehrId=8b442eed-6d56-43a7-9416-0423b5e4d5a3&templateId=Anamnese

Payload (working):
```
{
"bericht/größe_länge/größe|magnitude": 182, 
"bericht/größe_länge/größe|unit": "cm",
"bericht/größe_länge/time": "2020-02-02T00:00:00",
"bericht/größe_länge/language|code": "de",
"bericht/größe_länge/language|terminology": "ISO_639-1",
"bericht/composer|name": "ucc_goettingen_j_richter",
"bericht/language|code": "de",
"bericht/language|terminology": "ISO_639-1",
"bericht/territory|code": "DE",
"bericht/territory|terminology": "ISO_3166-1"
}
```

Payload (not working):
```
{

"bericht/größe_länge/time": "2020-02-02T00:00:00",
"bericht/composer|name": "ucc_goettingen_j_richter",
"bericht/language|code": "de",
"bericht/language|terminology": "ISO_639-1",
"bericht/territory|code": "DE",
"bericht/territory|terminology": "ISO_3166-1"
}
```

Template: [Anamnese.opt.txt](https://github.com/ehrbase/ehrbase/files/7603723/Anamnese.opt.txt)

2. Leave some values of an element blank but contain "bericht/größe_länge/time": "2020-02-02T00:00:00" and necessary metadata

## Actual result ##

The (working) payload gives a correct return of 500 with error message about missing attributes.

The (not working) payload returns nothing and the requests is running forever with no timeout.
forever = at least 44 minutes (before manual canceling)

## Expected result (Acceptance Criteria) ##

Timeout OR appropiate error with error message

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by sidharthramesh** [comment]
@richter122-goe this is very similar to #360 that was closed on PR https://github.com/ehrbase/openEHR_SDK/pull/264 which was merged on 11th October. The EHRBase SDK version you're using - `fac6c67` was released on 7th September. Maybe try to check if the error happens on the develop branch? If you're using docker, use the `ehrbase/ehrbase:next` image.

**Comment by richter122-goe** [comment]
@sidharthramesh thank you for your reply. I updated to 0.17.3 and the problem does not occur with the example provided above.
I get the correct error message from the server.

Thank you for your efforts.

**Comment by sidharthramesh** [comment]
@richter122-goe great to hear it worked for you. Close the issue?
