### ISSUE TITLE
SQL syntax error when contributing (valid?) JSON

### ISSUE THREAD

**Issue by nr23730** [ehrbase/ehrbase#68]
This may be related to #67 but I'm not 100% sure.

Currently I'm switching from XML to JSON and unfortunately ran into a few issues.
At first I thought that there might be an issue with my JSON document but it looks fine. 

So I did the following: Generated an XML composition and uploaded it to the Server. to get a valid JSON document I set the following headers:

- Prefer: return=representation
- Accept: application/json

Then I took the returned JSON document and tried to upload it. It returned the following error:
```
<?xml version='1.0' encoding='UTF-8'?>
<Map>
  <error>Internal Server Error: java.lang.IllegalArgumentException: Could not commit content:org.springframework.jdbc.BadSqlGrammarException: Access database using Jooq; bad SQL grammar [insert into "ehr"."containment" ("comp_id", "label", "path") values (?, 'openEHR_EHR_COMPOSITION_report_result_v1.openEHR_EHR_OBSERVATION_laboratory_test_result_v1.openEHR_EHR_CLUSTER_genetic_variant_v0]'::ltree, ?)]; nested exception is org.postgresql.util.PSQLException: ERROR: syntax error at position 129
  Position: 74</error>
  <status>Internal Server Error</status>
</Map>
```

I tried the same with another template and it worked fine, so it maybe has something to do with my template.

In the attachments:
- Template (*.opt and *.oet)
- XML Document I successfully uploaded
- JSON document that I tried to upload

[upload-json.txt](https://github.com/ehrbase/ehrbase/files/3917291/upload-json.txt)
[upload-xml.txt](https://github.com/ehrbase/ehrbase/files/3917292/upload-xml.txt)
[MTB-oet.txt](https://github.com/ehrbase/ehrbase/files/3917294/MTB-oet.txt)
[MTB-opt.txt](https://github.com/ehrbase/ehrbase/files/3917299/MTB-opt.txt)

**Comment by nr23730** [comment]
I had a further look at the problem by analyzing the Postgres-log file.

The generated JSON-output misses the name attribute of clusters (see attached files).

So it's more like a minor bug in returning the representation.

[log-xml.txt](https://github.com/ehrbase/ehrbase/files/3921341/log-xml.txt)
[log-json.txt](https://github.com/ehrbase/ehrbase/files/3921342/log-json.txt)

**Comment by chevalleyc** [comment]
These changes have been integrated into #82 (for use with the CI framework). Many thanks for the contribution!
