### ISSUE TITLE
On project service: Compilation failure

### ISSUE THREAD

**Issue by agustinpallares94** [ehrbase/ehrbase#681]
## Configuration information

- EHRbase version: latest
- openEHR_SDK version: 1e26bf1
- Archie version: 1.0.4
- PostgreSQL version: docker container with ehrbase/ehrbase-postgres:latest image
- Java Runtime version: 13.0.6
- Operating System version: Mac OS Monterrey 12.0.1

## Steps to reproduce ## 

I added to the applciation yaml External Terminology Validation Properties. 

Then I ran a postgres container with the following details: docker run --name ehrdb --network ehrbase-net -e POSTGRES_PASSWORD=postgres -d -p 5432:5432 ehrbase/ehrbase-postgres:latest 

I checked the connection data to the database and all were ok. 

Finally i ran the command ` mvn package  `

## Actual result ##

I obtained the following logs: 

`[INFO] Reactor Summary for EHRbase 0.17.3-SNAPSHOT:
[INFO] 
[INFO] EHRbase ............................................ SUCCESS [  0.850 s]
[INFO] api ................................................ SUCCESS [  3.634 s]
[INFO] base ............................................... SUCCESS [  0.246 s]
[INFO] jooq-pq ............................................ SUCCESS [ 12.407 s]
[INFO] rest-openehr ....................................... SUCCESS [  1.233 s]
[INFO] service ............................................ FAILURE [  2.114 s]
[INFO] rest-ehr-scape ..................................... SKIPPED
[INFO] application ........................................ SKIPPED
[INFO] test-coverage ...................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  21.411 s
[INFO] Finished at: 2021-11-26T13:39:16+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project service: Compilation failure: Compilation failure: 
[ERROR] /Users/agustinpallares/Downloads/Medicació/EHRbase/ehrbase_prueba/ehrbase/service/src/main/java/org/ehrbase/aql/sql/QueryProcessor.java:[356,68] reference to Record is ambiguous
[ERROR]   both interface org.jooq.Record in org.jooq and class java.lang.Record in java.lang match
[ERROR] /Users/agustinpallares/Downloads/Medicació/EHRbase/ehrbase_prueba/ehrbase/service/src/main/java/org/ehrbase/aql/sql/QueryProcessor.java:[356,20] reference to Record is ambiguous
[ERROR]   both interface org.jooq.Record in org.jooq and class java.lang.Record in java.lang match
[ERROR] /Users/agustinpallares/Downloads/Medicació/EHRbase/ehrbase_prueba/ehrbase/service/src/main/java/org/ehrbase/aql/sql/QueryProcessor.java:[68,35] reference to Record is ambiguous
[ERROR]   both interface org.jooq.Record in org.jooq and class java.lang.Record in java.lang match
[ERROR] /Users/agustinpallares/Downloads/Medicació/EHRbase/ehrbase_prueba/ehrbase/service/src/main/java/org/ehrbase/aql/sql/QueryProcessor.java:[73,36] reference to Record is ambiguous
[ERROR]   both interface org.jooq.Record in org.jooq and class java.lang.Record in java.lang match
[ERROR] /Users/agustinpallares/Downloads/Medicació/EHRbase/ehrbase_prueba/ehrbase/service/src/main/java/org/ehrbase/aql/sql/QueryProcessor.java:[79,28] reference to Record is ambiguous
[ERROR]   both interface org.jooq.Record in org.jooq and class java.lang.Record in java.lang match
[ERROR] /Users/agustinpallares/Downloads/Medicació/EHRbase/ehrbase_prueba/ehrbase/service/src/main/java/org/ehrbase/dao/access/jooq/FolderHistoryAccess.java:[124,81] reference to Record is ambiguous
[ERROR]   both interface org.jooq.Record in org.jooq and class java.lang.Record in java.lang match
[ERROR] /Users/agustinpallares/Downloads/Medicació/EHRbase/ehrbase_prueba/ehrbase/service/src/main/java/org/ehrbase/dao/access/jooq/FolderHistoryAccess.java:[182,161] reference to Record is ambiguous
[ERROR]   both interface org.jooq.Record in org.jooq and class java.lang.Record in java.lang match
[ERROR] /Users/agustinpallares/Downloads/Medicació/EHRbase/ehrbase_prueba/ehrbase/service/src/main/java/org/ehrbase/dao/access/jooq/FolderHistoryAccess.java:[511,27] reference to Record is ambiguous
[ERROR]   both interface org.jooq.Record in org.jooq and class java.lang.Record in java.lang match
[ERROR] /Users/agustinpallares/Downloads/Medicació/EHRbase/ehrbase_prueba/ehrbase/service/src/main/java/org/ehrbase/dao/access/jooq/FolderHistoryAccess.java:[661,190] reference to Record is ambiguous
[ERROR]   both interface org.jooq.Record in org.jooq and class java.lang.Record in java.lang match
[ERROR] /Users/agustinpallares/Downloads/Medicació/EHRbase/ehrbase_prueba/ehrbase/service/src/main/java/org/ehrbase/dao/access/jooq/ContextAccess.java:[488,81] reference to Record is ambiguous
[ERROR]   both interface org.jooq.Record in org.jooq and class java.lang.Record in java.lang match
[ERROR] /Users/agustinpallares/Downloads/Medicació/EHRbase/ehrbase_prueba/ehrbase/service/src/main/java/org/ehrbase/dao/access/jooq/ContextAccess.java:[499,54] reference to Record is ambiguous
[ERROR]   both interface org.jooq.Record in org.jooq and class java.lang.Record in java.lang match
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
`

## Expected result (Acceptance Criteria) ##

I wanted to obtain the jar of the ehrbase project

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by birgerhaarbrandt** [comment]
Have you tried to delete the local folders inside .m2 with the corresponding dependencies?

**Comment by wlad** [comment]
ehrbase/ehrbase-postgres:latest is not a multiarch image, I don't think it'll work on M1. Please try **ehrbase/ehrbase-postgres:13.4** instead
The Java version might be an issue as well, we use Java 11 on CI and all in the team locally. Not tested on Java 13.

**Comment by agustinpallares94** [comment]
> Checked this after updating to Monterrey 12.0.1 and can reproduce. Are you also using M1 Arm CPU?

I'm using Core i9 8 cores.  I've switched my Java version to 11 and It has worked

**Comment by agustinpallares94** [comment]
> ehrbase/ehrbase-postgres:latest is not a multiarch image, I don't think it'll work on M1. Please try **ehrbase/ehrbase-postgres:13.4** instead The Java version might be an issue as well, we use Java 11 on CI and all in the team locally. Not tested on Java 13.

I switched to version 11 and it worked. Thank you very much

**Comment by wlad** [comment]
@agustinpallares94  thanks for reporting!

@birgerhaarbrandt should we opend a dedicated ticket about issue with Java 13?
