### ISSUE TITLE
Precision not being committed as FLAT

### ISSUE THREAD

**Issue by dileep-ehr** [ehrbase/ehrbase#682]
## Configuration information

<ehrbase_version>0.17.3-SNAPSHOT</ehrbase_version>
    <openehr_sdk_version>1e26bf1</openehr_sdk_version>
    <archie_version>1.0.4</archie_version>
    <jvm_version>Ubuntu 11.0.11+9-Ubuntu-0ubuntu2.18.04</jvm_version>
    <os_version>Linux amd64 5.4.0-90-generic</os_version>
    <postgres_version>PostgreSQL 14.0 (Ubuntu 14.0-1.pgdg18.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, 64-bit</postgres_version>

## Steps to reproduce ## 
Commit quantity value along with precision using FLAT format
```
"vital_signs/vital_signs:0/blood_pressure:0/any_event:0/systolic|magnitude": 120.00,
“vital_signs/vital_signs:0/blood_pressure:0/any_event:0/systolic|unit": "mm[Hg]",
"vital_signs/vital_signs:0/blood_pressure:0/any_event:0/systolic|precision": 2
```
## Actual result ##

Throws error saying that could not consume the precision path

## Expected result (Acceptance Criteria) ##

Should commit and return

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by stefanspiska** [comment]
This works now on dev 

see 
sdk
DbConformanceTest.testRoundTrip:
EHRBASE_CONFORMANCE_DATA_TYPES_DV_QUANTITY
