### ISSUE TITLE
RM values for DV_QUANTITY not recognized in FLAT  format

### ISSUE THREAD

**Issue by dileep-ehr** [ehrbase/ehrbase#683]
## Configuration information

<ehrbase_version>0.17.3-SNAPSHOT</ehrbase_version>
<openehr_sdk_version>1e26bf1</openehr_sdk_version>
<archie_version>1.0.4</archie_version>
<jvm_version>Ubuntu 11.0.11+9-Ubuntu-0ubuntu2.18.04</jvm_version>
<os_version>Linux amd64 5.4.0-90-generic</os_version>
<postgres_version>PostgreSQL 14.0 (Ubuntu 14.0-1.pgdg18.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, 64-bit</postgres_version>

## Steps to reproduce ## 
Commit a DV_QUANTITY data with following RM values
```
"vital_signs/vital_signs:0/blood_pressure:0/any_event:0/systolic/magnitude_status": "<="
"vital_signs/vital_signs:0/blood_pressure:0/any_event:0/systolic/accuracy_is_percent": "True",
"vital_signs/vital_signs:0/blood_pressure:0/any_event:0/systolic/accuracy": 10
"vital_signs/vital_signs:0/blood_pressure:0/any_event:0/systolic/normal_status": "LL"
"vital_signs/vital_signs:0/blood_pressure:0/any_event:0/systolic/normal_range|lower": 100,
"vital_signs/vital_signs:0/blood_pressure:0/any_event:0/systolic/normal_range|upper": 140,
"vital_signs/vital_signs:0/blood_pressure:0/any_event:0/systolic/normal_range|lower_unbounded": "True",
"vital_signs/vital_signs:0/blood_pressure:0/any_event:0/systolic/normal_range|upper_unbounded": "True",
"vital_signs/vital_signs:0/blood_pressure:0/any_event:0/systolic/normal_range|lower_included": "True",
"vital_signs/vital_signs:0/blood_pressure:0/any_event:0/systolic/normal_range|upper_included": "True"

```
## Actual result ##

Throws error saying that unable to consume the data

## Expected result (Acceptance Criteria) ##

Should be able to POST, GET and retrieve via AQL

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by stefanspiska** [comment]
normal_range is an optional RM attribute and thus would be set via _normal_range, etc also accuracy_is_percent is  a calculated value and thus can not be set.

see https://github.com/better-care/web-template-tests/blob/master/src/test/java/care/better/platform/web/template/NormalRangeTest.java

**Comment by stefanspiska** [comment]
should be fixed on dev 

see sdk: DbConformanceTest.testRoundTrip :: EHRBASE_CONFORMANCE_DATA_TYPES_DV_QUANTITY

https://github.com/ehrbase/openEHR_SDK/blob/develop/test-data/src/main/resources/composition/flat/simSDT/ehrbase_conformance_data_types_dv_quantity.json
