### ISSUE TITLE
Type definition error: [simple type, class org.ehrbase.response.ehrscape.query.ResultHolder]

### ISSUE THREAD

**Issue by jessarcher** [ehrbase/ehrbase#692]
## Configuration information

- EHRbase version: 0.17.2 (docker `next` tag)
- openEHR_SDK version: 321ef09
- Archie version: 1.0.3
- PostgreSQL version: PostgreSQL 14.0 (Debian 14.0-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
- Java Runtime version: Oracle Corporation 11.0.13+8
- Operating System version: Linux amd64 5.14.13-200.fc34.x86_64

## Steps to reproduce ## 

1. Upload a template (E.g. [body_temperature.opt.txt](https://github.com/ehrbase/ehrbase/files/7666155/body_temperature.opt.txt))
2. Create an EHR
3. Create a composition from the template via the `ecis` API.
4. **Make a `POST` request to the `ecis` query API at `http://localhost:8453/ehrbase/rest/ecis/v1/query`**
    Simple examples:
    ```json
    {
      "aql": "SELECT c FROM EHR e CONTAINS COMPOSITION c[openEHR-EHR-COMPOSITION.encounter.v1]"
    }
    ```
    ```json
    {
      "aql": "SELECT c/archetype_details/template_id/value FROM EHR e CONTAINS COMPOSITION c[openEHR-EHR-COMPOSITION.encounter.v1]"
    }
    ```
    etc...

## Actual result ##

```json
{
  "action": "EXECUTE",
  "executedAQL": "SELECT c FROM EHR e CONTAINS COMPOSITION c[openEHR-EHR-COMPOSITION.encounter.v1]",
  "resultSet": []
}{
  "error": "Type definition error: [simple type, class org.ehrbase.response.ehrscape.query.ResultHolder]; nested exception is com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class org.ehrbase.response.ehrscape.query.ResultHolder and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: org.ehrbase.rest.ehrscape.responsedata.QueryResponseData[\"resultSet\"]->java.util.ArrayList[0])",
  "status": "Internal Server Error"
}
```

**Important notes:**

1. When running a query that returns no results (e.g. for a non-existent composition), the error does not occur.

2. The same queries also run successfully via the openEHR query API at `http://localhost:8453/ehrbase/rest/openehr/v1/query/aql` however I'm interested in the flat format.

3. This has also been confirmed on a separate machine running macOS and by compiling and running the latest `develop` branch rather than the `next` docker image.

## Expected result (Acceptance Criteria) ##

The results of the query in the flat format.

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by stefanspiska** [comment]
@jessarcher 
I'am not sure abut that issue but you will not get beak a query in FLAT format any way. That's not something supported in ehrbase.

**Comment by jessarcher** [comment]
Yeah fair point, I can see how that would be hard/impossible when dealing with substructures.

I don't intend for this to be a support issue, but just for clarity I'm trying to retrieve a flat composition when I don't know its ID (i.e. based on EHR ID and the template ID) so I'm assuming I need to run an AQL query to get the composition ID I'm interested in, and then I can hit the `ecis/v1/composition/{id}` endpoint to get the flat composition by its ID.

I do think this issue is still valid though, as I can't seem to get any results from the `ecis` query endpoint due to the serialization issue above. In my case I can just use the `openehr/v1/query/aql` though.

**Comment by vladislavploaia** [comment]
Hello @jessarcher,
Based on comments provided by:
1. @stefanspiska, it is not possible to get back the result of the query in FLAT format;
2. @birgerhaarbrandt, ecis aql endpoint will be deprecated. See the comments here: https://discourse.openehr.org/t/software-development-kit-for-app-development/790/44
Considering above two comments, I can assign this ticket back to you and in case you have any other questions/concerns/issue details, just let me know, otherwise, it will be closed correspondingly.
Happy to support you!

**Comment by jessarcher** [comment]
Hi @vladislavploaia, Thanks for your response. I've changed jobs so I'm not working with this anymore. All the best!
