### ISSUE TITLE
Could not resolve type id 'DV_E_H_R_URI'

### ISSUE THREAD

**Issue by agustinpallares94** [ehrbase/ehrbase#713]
## Configuration information

- EHRbase version: latest
- openEHR_SDK version: 1e26bf1
- Archie version: 1.0.4
- PostgreSQL version: docker container with ehrbase/ehrbase-postgres:latest image
- Java Runtime version: 11.0.13
- Operating System version: Mac OS Monterrey 12.0.1

## Steps to reproduce ## 

I am trying to test all the possible variables that exist to create an archetype and a composition. When I went to save a composition with a DV_EHR_URI data type, Ehrbase threw an error due to the Archie library. 

When you go to save the composition it gives the following error:
`{
    "error": "DB inconsistency:java.lang.IllegalArgumentException: Could not resolve type id 'DV_E_H_R_URI' as a subtype of com.nedap.archie.base.OpenEHRBase: no such class found\n at [Source: (StringReader); line: 3, column: 108008] (through reference chain: com.nedap.archie.rm.composition.Composition[\"content\"]->java.util.ArrayList[0]->com.nedap.archie.rm.composition.Instruction[\"activities\"]->java.util.ArrayList[0]->com.nedap.archie.rm.composition.Activity[\"description\"]->com.nedap.archie.rm.datastructures.ItemTree[\"items\"]->java.util.ArrayList[7]->com.nedap.archie.rm.datastructures.Element[\"value\"])",
    "status": "Bad Request"
}`

Even though it gives the error, Ehrbase saves the composition. As it remains bugged in the CDR you can neither delete nor recover the composition. In addition, the template associated with this composition can not be deleted either.

Thank you very much for everything.

**Comment by chevalleyc** [comment]
@agustinpallares94 could you please post the template and a sample composition so I can reproduce it locally? Thanks!

**Comment by agustinpallares94** [comment]
> @agustinpallares94 could you please post the template and a sample composition so I can reproduce it locally? Thanks!

I've deleted the template, but I can share with you the composition that I used. It is just a test composition to know how the different variables can affect EhrBase. I've changed the file type to .txt because Github doesn't support .json.

Thank you!

**Comment by stefanspiska** [comment]
see also 

DbConformanceTest.testRoundTrip

EHRBASE_CONFORMANCE_DATA_TYPES_DV_EHR_URI

 
see also https://jira.vitagroup.ag/browse/CDR-214
