### ISSUE TITLE
Error: 'Invariant Encoding_valid failed on type...'

### ISSUE THREAD

**Issue by kn-934** [ehrbase/ehrbase#717]
## Configuration information

- EHRbase version: 0.18.3
- openEHR_SDK version:
- Archie version:
- PostgreSQL version:
- Java Runtime version:
- Operating System version:

## Steps to reproduce ## 

Storing a composition [IDCR_Problem_List.v1.txt](https://github.com/ehrbase/ehrbase/files/7755367/IDCR_Problem_List.v1.txt). This worked with previous ehrbase versions (<0.18). The same error also occurs with other compositions.

POST /ehrbase/rest/openehr/v1/ehr/{ehr_id}/composition

headers = {"Prefer": "return=representation",
        	'Content-type': 'application/xml'}

## Actual result ##

Error:
<Response [400]>

{"error":"java.lang.IllegalArgumentException: Message at /content[openEHR-EHR-SECTION.problems_issues_rcp.v1, 1]/items[openEHR-EHR-EVALUATION.exclusion-problem_diagnosis.v0, 1] (/content[openEHR-EHR-SECTION.problems_issues_rcp.v1, 1]/items[openEHR-EHR-EVALUATION.exclusion-problem_diagnosis.v0, 1]):  Invariant Encoding_valid failed on type EVALUATION\nMessage at /content[openEHR-EHR-SECTION.problems_issues_rcp.v1, 1]/items[openEHR-EHR-EVALUATION.exclusion-problem_diagnosis.v0, 1] (/content[openEHR-EHR-SECTION.problems_issues_rcp.v1, 1]/items[openEHR-EHR-EVALUATION.exclusion-problem_diagnosis.v0, 1]):  Invariant Is_archetypeRoot failed on type EVALUATION\nMessage at /content[openEHR-EHR-SECTION.problems_issues_rcp.v1, 1]/items[openEHR-EHR-EVALUATION.problem_diagnosis.v1, 2] (/content[openEHR-EHR-SECTION.problems_issues_rcp.v1, 1]/items[openEHR-EHR-EVALUATION.problem_diagnosis.v1, 2]):  Invariant Encoding_valid failed on type EVALUATION\nMessage at /content[openEHR-EHR-SECTION.problems_issues_rcp.v1, 1]/items[openEHR-EHR-EVALUATION.problem_diagnosis.v1, 2] (/content[openEHR-EHR-SECTION.problems_issues_rcp.v1, 1]/items[openEHR-EHR-EVALUATION.problem_diagnosis.v1, 2]):  Invariant Is_archetypeRoot failed on type EVALUATION\n","status":"Bad Request"}

## Expected result (Acceptance Criteria) ##

Composition can be stored.

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by stefanspiska** [comment]
@kn-934 The new version has strikter validation rules. namely it cheeks no also the invariantes of the rm Modell.

In your case Is_archetypeRoot of 
https://specifications.openehr.org/releases/RM/latest/common.html#_locatable_class
https://specifications.openehr.org/releases/RM/latest/ehr.html#_entry_class
which means  Evaluation has to have archetype_details and not only compositions.

You can set the (Spring) config  server.disable-strict-validation= true to switch of the strikter validation. But I would recombined to fix you composition in stat. (see for example https://github.com/ehrbase/openEHR_SDK/blob/develop/test-data/src/main/resources/composition/canonical_json/compo_corona.json archetype_details  there the is set on each level correctly )
