### ISSUE TITLE
REST API - Missing CORS-headers for some DELETE and PUT endpoints

### ISSUE THREAD

**Issue by ErikTute** [ehrbase/ehrbase#727]
## Configuration information

- EHRbase version: 0.18.3
- openEHR_SDK version: 1.6.0
- Archie version: 1.0.4
- PostgreSQL version: 11.5
- Java Runtime version: Oracle Corporation 11.0.13+8
- Operating System version: Linux amd64 5.10.60.1-microsoft-standard-WSL2

## Steps to reproduce ## 

Sending composition DELETE request or ehr PUT request (create with id) from page in browser.

Example to reproduce (save as html and open locally if you have an ehrbase docker running on your machine.):
```
﻿<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width">
    <script language=javascript type=text/javascript src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  </head>
  <body>
    <button onclick="put_example()">Put example</button> (does not work)<br>
    <button onclick="delete_example()">Delete example</button> (does not work)<br>
    <button onclick="post_example()">Post example</button> (works)

    <script language="JavaScript">

  function post_example() {
    $.ajax({
    		async: true,
    		type: "POST",
    		dataType: "json",
    		contentType:"application/json",
    		data: JSON.stringify({
            "_type": "EHR_STATUS",
            "name": {
              "_type": "DV_TEXT",
              "value": "EHR Status"
            },
            "subject": {
              "_type": "PARTY_SELF",
        			"external_ref": {
        				"namespace": "DEMOGRAPHIC",
        				"type": "PERSON",
        				"id": {
        					"_type": "HIER_OBJECT_ID",
        					"value": "09876543210000467467567"
        				}
        			}
            },
            "archetype_node_id": "openEHR-EHR-EHR_STATUS.generic.v1",
            "is_modifiable": true,
            "is_queryable": true
        }),
    		url: "http://localhost:8080/ehrbase/rest/openehr/v1/ehr/",
    		success: function(data, status, xhr) {
    			console.log(status);
    		},
    		beforeSend: function (xhr) {
    			xhr.setRequestHeader ("Authorization", "Basic " + btoa("ehrbase-user:SuperSecretPassword"));
    		},
    		error: function(jqxhr, textStatus, error) {
          if (jqxhr.status==409) {}//probably just ehr that already exists
          else {
      			console.warn(jqxhr);
      			console.warn(jqxhr.responseText);
          }
    		}
    	});
  }

  function put_example() {
    $.ajax({
    		async: true,
    		type: "PUT",
    		dataType: "json",
    		contentType:"application/json",
    		data: JSON.stringify({
            "_type": "EHR_STATUS",
            "name": {
              "_type": "DV_TEXT",
              "value": "EHR Status"
            },
            "subject": {
              "_type": "PARTY_SELF",
        			"external_ref": {
        				"namespace": "DEMOGRAPHIC",
        				"type": "PERSON",
        				"id": {
        					"_type": "HIER_OBJECT_ID",
        					"value": "9876543210"
        				}
        			}
            },
            "archetype_node_id": "openEHR-EHR-EHR_STATUS.generic.v1",
            "is_modifiable": true,
            "is_queryable": true
        }),
    		url: "http://localhost:8080/ehrbase/rest/openehr/v1/ehr/00000000-0000-0000-0000-123456789012",
    		success: function(data, status, xhr) {
    			console.log(status);
    		},
    		beforeSend: function (xhr) {
    			xhr.setRequestHeader ("Authorization", "Basic " + btoa("ehrbase-user:SuperSecretPassword"));
    		},
    		error: function(jqxhr, textStatus, error) {
          if (jqxhr.status==409) {}//probably just ehr that already exists
          else {
      			console.warn(jqxhr);
      			console.warn(jqxhr.responseText);
          }
    		}
    	});
  }

  function delete_example() {
    $.ajax({
    		async: true,
    		type: "DELETE",
    		dataType: "json",
    		contentType:"application/json",
    		url: "http://localhost:8080/ehrbase/rest/openehr/v1/ehr/ea12d3b3-123c-4fd2-9865-5bed6df01658/composition/7555b590-d689-4adb-b100-60a01249105c::local.ehrbase.org::1",
    		success: function(data, status, xhr) {
    			console.log(status);
    		},
    		beforeSend: function (xhr) {
    			xhr.setRequestHeader ("Authorization", "Basic " + btoa("ehrbase-user:SuperSecretPassword"));
    		},
    		error: function(jqxhr, textStatus, error) {
          if (jqxhr.status==409) {}//probably just ehr that already exists
          else {
      			console.warn(jqxhr);
      			console.warn(jqxhr.responseText);
          }
    		}
    	});
  }

    </script>
  </body>
</html>
```

## Actual result ##

- POST works, i.e. creating EHR without specified ehr-id works from browser. 
- PUT doesn't work, i.e. creating EHR with given eher-id doesn't work from browser. Browser shows CORS Missing Allow Origin error (tested on current Firefox and Chrome). Postman works with same request, so CORS issues seems plausible.
- DELETE doesn't work, i.e. deleting composition doesn't work from browser. Browser shows CORS Missing Allow Origin error (tested on current Firefox and Chrome). Postman works with same request, so CORS issues seems plausible.

## Expected result (Acceptance Criteria) ##

All three requests should work from a webapp not hosted on same server as ehrbase.

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by sidharthramesh** [comment]
Can confirm that this bug exists on `ehrbase:next`. Tested it today and had some errors showing up in some apps when creating EHRs.

Also, this bug wasn’t present on previous versions. But I’ve had CORS trouble with other endpoints like composition on some of the older releases.

I’m up for contributing to this if I get the time.

We'll need to add tests for all endpoints and methods along with the tests for the template endpoint here to prevent these bugs in future releases:
[ehrbase/ehrbase/application/src/test/java/org/ehrbase/application/cors/CorsNoAuthIT.java](https://github.com/ehrbase/ehrbase/tree/develop/application/src/test/java/org/ehrbase/application/cors)

Regarding the source of the bug, I've been looking at
https://github.com/ehrbase/ehrbase/blob/5ceb8e4843912f847f6ac3b542545bae9d0af898/application/src/main/java/org/ehrbase/application/config/web/WebConfiguration.java#L64-L68

and 

https://github.com/ehrbase/ehrbase/blob/5ceb8e4843912f847f6ac3b542545bae9d0af898/application/src/main/java/org/ehrbase/application/config/web/CorsProperties.java#L109-L123

But can't really understand how the CORS configuration is not reflecting on just some particular endpoints since this seems to be a global configuration.

**Comment by ErikTute** [comment]
I am absolutely not an expert on this and don't want to mislead anybody who may be capable of solving this, but I suspected that the request methode, i.e. GET, POST, PUT, DELETE, ... is the relevant difference. The GET and POST endpoints I tried responded as I expected it. PUT and DELETE did not work. It seems like this could for example happen if some default values are used (cf. applyPermitDefaultValues at https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/cors/CorsConfiguration.html) But I have to admit I don't even know where the actual values which are mapped here come from.

**Comment by sidharthramesh** [comment]
Okay so, it's supposed to come from the application.yaml file. And I've tested that by adding the following to it:
```yaml
web:
  cors:
    allowedOriginPatterns:
      - https://*.test-cors.org
    allowedMethods:
      - GET
      - PUT
      - DELETE
      - POST
      - OPTIONS
    allowCredentials: "true"
```

CORS works on the EHR endpoint without issue. Tested using [CORS Tester](https://www.test-cors.org/#?client_method=GET&client_credentials=true&server_url=http%3A%2F%2Flocalhost%3A8080%2Fehrbase%2Frest%2Fopenehr%2Fv1%2Fehr%2F9a1d9ee4-7b7c-4a83-a996-f7b9912c2194&server_enable=true&server_status=200&server_credentials=false&server_tabs=remote).

**Comment by sidharthramesh** [comment]
Works as environment variables in a docker-compose yaml too:
```yaml
ehrbase:
    restart: on-failure
    image: ehrbase/ehrbase:next
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ehrbase
      SPRING_DATASOURCE_USERNAME: ehrbase
      SPRING_DATASOURCE_PASSWORD: ehrbase
      SERVER_AQLCONFIG_USEJSQUERY: 'false'
      SERVER_NODENAME: localhost
      SECURITY_AUTHTYPE: NONE
      WEB_CORS_ALLOWEDORIGINS: https://www.test-cors.org/
      WEB_CORS_ALLOWEDORIGINPATTERNS: https://*.test-cors.org
      WEB_CORS_ALLOWEDMETHODS: GET,PUT,DELETE,POST,OPTIONS
      WEB_CORS_ALLOWCREDENTIALS: 'true'
    ports:
      - 8080:8080
```

**Comment by ErikTute** [comment]
Nice, thank you very much for these infos! I'm currently stuck in meetings, but can't wait to try this out tomorrow ;-)

**Comment by ErikTute** [comment]
Ok, I guess this is solved now on the ehrbase part. 
@sidharthramesh Thank you for showing me how to do this configuration. 
I still have some CORS issues left, but as far as I understand it, these are due to opening a local file instead of hosting my webapp on a webserver, which leads to problems with the origin.
