### ISSUE TITLE
AQL not returning all instances of an archetype

### ISSUE THREAD

**Issue by svituz** [ehrbase/ehrbase#728]
## Configuration information

- EHRbase version: 0.18.3
- openEHR_SDK version: 1.6.0
- Archie version: 1.0.4
- PostgreSQL version: PostgreSQL 11.5 on x86_64-pc-linux-musl, compiled by gcc (Alpine 8.3.0) 8.3.0, 64-bit
- Java Runtime version: Oracle Corporation 11.0.13+8
- Operating System version: Linux amd64 5.15.7-arch1-1

## Description

My composition has several instances of an archetype. I would expect that all instances matching the AQL query criteria would be returned but I'm getting only one instance. 

## Steps to reproduce ## 

1. Create the template you can find  [here](https://gist.github.com/svituz/904f52c616b5d5ef939932e145464ce7#file-template-opt)
2. Create an ehr
3. Create the composition you can find [here](https://gist.github.com/svituz/904f52c616b5d5ef939932e145464ce7#file-composition-json)
4. Perform the query 
```
select c/content[openEHR-EHR-SECTION.result_details.v0, 'Histopathology']/items[at0002]/items[openEHR-EHR-OBSERVATION.laboratory_test_result.v1]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.specimen.v1]/items[at0088, 'Sample ID']/value/id as sample_id 
from EHR e 
contains COMPOSITION c 
contains (CLUSTER c_a[openEHR-EHR-CLUSTER.case_identification.v0]) 
where c/content[openEHR-EHR-SECTION.result_details.v0, 'Histopathology']/items[at0002]/items[openEHR-EHR-OBSERVATION.laboratory_test_result.v1]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.specimen.v1]/items[at0088, 'Sample ID']/value/id IS NOT NULL limit 10000
```

## Actual result ##

EHRbase returns
```
{
    "q": "select c/content[openEHR-EHR-SECTION.result_details.v0, 'Histopathology']/items[at0002]/items[openEHR-EHR-OBSERVATION.laboratory_test_result.v1]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.specimen.v1]/items[at0088, 'Sample ID']/value/id as sample_id from EHR e contains COMPOSITION c contains (CLUSTER c_a[openEHR-EHR-CLUSTER.case_identification.v0]) where c/content[openEHR-EHR-SECTION.result_details.v0, 'Histopathology']/items[at0002]/items[openEHR-EHR-OBSERVATION.laboratory_test_result.v1]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.specimen.v1]/items[at0088, 'Sample ID']/value/id IS NOT NULL limit 10000",
    "columns": [
        {
            "path": "/content[openEHR-EHR-SECTION.result_details.v0,'Histopathology']/items[at0002]/items[openEHR-EHR-OBSERVATION.laboratory_test_result.v1]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.specimen.v1]/items[at0088,'Sample ID']/value/id",
            "name": "sample_id"
        }
    ],
    "rows": [
        [
            "sample_0"
        ]
    ]
}
```

## Expected result (Acceptance Criteria) ##

I would expect two samples
```
{
    "q": "select c/content[openEHR-EHR-SECTION.result_details.v0, 'Histopathology']/items[at0002]/items[openEHR-EHR-OBSERVATION.laboratory_test_result.v1]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.specimen.v1]/items[at0088, 'Sample ID']/value/id as sample_id from EHR e contains COMPOSITION c contains (CLUSTER c_a[openEHR-EHR-CLUSTER.case_identification.v0]) where c/content[openEHR-EHR-SECTION.result_details.v0, 'Histopathology']/items[at0002]/items[openEHR-EHR-OBSERVATION.laboratory_test_result.v1]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.specimen.v1]/items[at0088, 'Sample ID']/value/id IS NOT NULL limit 10000",
    "columns": [
        {
            "path": "/content[openEHR-EHR-SECTION.result_details.v0,'Histopathology']/items[at0002]/items[openEHR-EHR-OBSERVATION.laboratory_test_result.v1]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.specimen.v1]/items[at0088,'Sample ID']/value/id",
            "name": "sample_id"
        }
    ],
    "rows": [
        [
            "sample_0"
        ],
        [
            "sample_1"
        ]
    ]
}
```
## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by ErikTute** [comment]
I have the same problem with an even simpler query. THe compositions look like this: 
`{
    "ctx/language": "de",
    "ctx/territory": "DE",
    "ctx/composer_name": "HaMSTR",
    "bericht/herzfrequenz/jedes_ereignis:0/time": "2022-01-14T12:01:00+01:00",
    "bericht/herzfrequenz/jedes_ereignis:0/frequenz|magnitude": "120",
    "bericht/herzfrequenz/jedes_ereignis:1/time": "2022-01-14T12:02:00+01:00",
    "bericht/herzfrequenz/jedes_ereignis:1/frequenz|magnitude": "124",
    "bericht/herzfrequenz/jedes_ereignis:2/time": "2022-01-14T12:03:00+01:00",
    "bericht/herzfrequenz/jedes_ereignis:2/frequenz|magnitude": "126",
    "bericht/herzfrequenz/jedes_ereignis:3/time": "2022-01-14T12:04:00+01:00",
    "bericht/herzfrequenz/jedes_ereignis:3/frequenz|magnitude": "130",
    "bericht/herzfrequenz/jedes_ereignis:4/time": "2022-01-14T12:05:00+01:00",
    "bericht/herzfrequenz/jedes_ereignis:4/frequenz|magnitude": "135",
    "bericht/herzfrequenz/jedes_ereignis:5/time": "2022-01-14T12:06:00+01:00",
    "bericht/herzfrequenz/jedes_ereignis:5/frequenz|magnitude": "120",
    "bericht/herzfrequenz/jedes_ereignis:6/time": "2022-01-14T12:07:00+01:00",
    "bericht/herzfrequenz/jedes_ereignis:6/frequenz|magnitude": "115",
    "bericht/herzfrequenz/jedes_ereignis:7/time": "2022-01-14T12:08:00+01:00",
    "bericht/herzfrequenz/jedes_ereignis:7/frequenz|magnitude": "130",
    "bericht/herzfrequenz/jedes_ereignis:8/time": "2022-01-14T12:09:00+01:00",
    "bericht/herzfrequenz/jedes_ereignis:8/frequenz|magnitude": "133"
  }
`
AQL is this:
`select
a_a/data[at0002]/events[at0003]/data[at0001]/items[at0004]/value/magnitude as Pulse
from OBSERVATION a_a[openEHR-EHR-OBSERVATION.pulse.v2]`

This only returns the first value for each composition. (If I query the whole compositions they contain all elements)

Broke it down a bit more:

`select
a_a/data[at0002] as Pulse
from OBSERVATION a_a[openEHR-EHR-OBSERVATION.pulse.v2]`

retrieves as expected one object per result row where each object containts multiple events whereas

`select
a_a/data[at0002]/events[at0003] as Pulse
from OBSERVATION a_a[openEHR-EHR-OBSERVATION.pulse.v2]`

only retrieves the same number of result rows but the object contains just one event (it expect each result to contain just one event per row but I would expect as many result rows as there are events).

**Comment by richter122-goe** [comment]
I got another example with a workind and a non-working AQL:
Template: [KDS_Laborbericht.opt.txt](https://github.com/ehrbase/ehrbase/files/8327003/KDS_Laborbericht.opt.txt)
Composition: [Laborbericht_Example_Comp.txt](https://github.com/ehrbase/ehrbase/files/8327006/Laborbericht_Example_Comp.txt)

This AQL-Query does not give all selected values from all compositions (or only distinct values?):
```
SELECT 
c/content[openEHR-EHR-OBSERVATION.laboratory_test_result.v1]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.laboratory_test_analyte.v1]/items[at0001]/value/magnitude
FROM EHR e
CONTAINS COMPOSITION c
WHERE c/content[openEHR-EHR-OBSERVATION.laboratory_test_result.v1]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.laboratory_test_analyte.v1]/items[at0024]/value/defining_code/terminology_id/value = '//fhir.hl7.org/ValueSet/$expand?url=http://hl7.org/fhir/uv/ips/ValueSet/results-laboratory-observations-uv-ips'
```

But this AQL-Query does give all selected values from all compositions:
```
SELECT 
c/content[openEHR-EHR-OBSERVATION.laboratory_test_result.v1]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.laboratory_test_analyte.v1]/items[at0001]/value/magnitude
FROM EHR e
CONTAINS COMPOSITION c
    CONTAINS OBSERVATION o [openEHR-EHR-OBSERVATION.laboratory_test_result.v1]
    CONTAINS CLUSTER cl [openEHR-EHR-CLUSTER.laboratory_test_analyte.v1]
WHERE cl/items[at0024]/value/defining_code/terminology_id/value = '//fhir.hl7.org/ValueSet/$expand?url=http://hl7.org/fhir/uv/ips/ValueSet/results-laboratory-observations-uv-ips'
```

**Comment by chevalleyc** [comment]
@svituz I posted a branch with multiple fixes and optimization regarding paths resolution (https://github.com/ehrbase/ehrbase/tree/feature/sync/737_value_point_paths). Could you please check it out? Thanks!

**Comment by vladislavploaia** [comment]
Hello @svituz ,
I was not able to commit composition with content you sent in issue description, therefore I cannot test your AQL statements.
![image](https://user-images.githubusercontent.com/100927963/204300630-37929685-ec35-47a4-95c0-4fe154a0b751.png)
Please share fresh OPT and Composition content so I can check this bug.
Thank you!
CC: @stefanspiska , @vidi42
