### ISSUE TITLE
AQL - variables (instead of only paths) in WHERE-Clause 

### ISSUE THREAD

**Issue by richter122-goe** [ehrbase/ehrbase#736]
## Background ##

At the moment I am not able to use variables in the WHERE-Clause. E.g.
```
SELECT distinct   
  e/ehr_status/subject/external_ref/id/value as id,  
  e/ehr_id/value as ehr_id, x/items[at0002]/value/value as studie  
FROM EHR e 
  CONTAINS COMPOSITION c 
    CONTAINS CLUSTER x[openEHR-EHR-CLUSTER.study_details.v1] 
WHERE studie = 'studyname'
```
EHRBase expects a path: 
![image](https://user-images.githubusercontent.com/64580653/151777870-50d046ac-6160-450a-9088-61420d296cb5.png)

So this is accepted at the moment:
```
WHERE x/items[at0002]/value/value = 'studyname'
```

Supporting variable names from the SELECT-Clause would make the AQL-Creation easier and more accessible.
As far a I am informed the Better Platform supports this. Implementing would therefore help users building truly interoperable AQLs.

## Acceptance criteria ##

- [ ] EHRBase accepts variables in WHERE-Clause
- [ ] EHRBase interprets variables in WHERE-Clause in a correct way

## Definition of Done ##

- [ ] Review / Merge request approved (P2P session)
- [ ] Unit tests passed
- [ ] Updated documentation (Javadoc and Sphinx)
- [ ] Acceptance criteria fulfilled
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] Runtime warnings

**Comment by birgerhaarbrandt** [comment]
Hi Jendrik,

the underlying issue is that you can put aliases on calculates columns like subselects or expressions. Such aliases don’t simply point to one column and so can’t be used in the where clause.

See this example (in SQL) which is problematic:

SELECT first_name + last_name AS employee_name
FROM employees
WHERE employee_name = 'Sarah'

Hence, I'm a bit hesitant to adapt this behavior from Better. 

@chevalleyc: any additional thought on this?

**Comment by richter122-goe** [comment]
Hey Birger,

thank you for the reply. Your example points out an interesting problem this might cause. I totally understand your hesitation. 
Maybe it is feasible to catch cases where an alias points to a calculated column? 

PS:
When using openEHR and AQL in particular, we are currently in a learning process. Please understand the suggestions and other issues i opened as an expression of this learning process and nothing else. 

I think it's great that the EHRBase is close to the standard and it is great that the EHRBase Team (as far as i can tell) is involved in the further development of the standard and tries to avoid implementing for example non-standard-conform functionalities :)
