### ISSUE TITLE
AQL not returning correct values using "CONTAINS Observation xyz"

### ISSUE THREAD

**Issue by richter122-goe** [ehrbase/ehrbase#737]
## Configuration information

<ehrbase_version>0.19.0-SNAPSHOT</ehrbase_version>
    <openehr_sdk_version>1.7.0-SNAPSHOT</openehr_sdk_version>
    <archie_version>1.0.4</archie_version>
    <jvm_version>Oracle Corporation 11.0.13+8</jvm_version>
    <os_version>Linux amd64 5.4.0-90-generic</os_version>
    <postgres_version>PostgreSQL 13.4 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20210424) 10.3.1 20210424, 64-bit</postgres_version>

## Steps to reproduce ## 

Used this OPT: [Anamnese.txt](https://github.com/ehrbase/ehrbase/files/7970364/Anamnese.txt)

AQL looks like this:
```
SELECT distinct e/ehr_id/value as ehrval,
        s/data[at0001]/events[at0006]/data[at0003]/items[at0004]/value/magnitude as sys_bp_m_alt,
        s/data[at0001]/events[at0006]/data[at0003]/items[at0004]/value/units as sys_bp_u_alt,
        c/content[openEHR-EHR-SECTION.adhoc.v1,'Blutdruck nach 5 Minuten Ruhe']/items[openEHR-EHR-OBSERVATION.blood_pressure.v2]/data[at0001]/events[at0006]/data[at0003]/items[at0004]/value/magnitude as sys_bp_m,
        c/content[openEHR-EHR-SECTION.adhoc.v1,'Blutdruck nach 5 Minuten Ruhe']/items[openEHR-EHR-OBSERVATION.blood_pressure.v2]/data[at0001]/events[at0006]/data[at0003]/items[at0004]/value/units as sys_bp_u
FROM EHR e
CONTAINS COMPOSITION c
    CONTAINS OBSERVATION s[openEHR-EHR-OBSERVATION.blood_pressure.v2]
WHERE c/archetype_details/template_id/value = 'Anamnese'
```

## Actual result ##

Result looks like this:
![image](https://user-images.githubusercontent.com/64580653/151786730-95251bd8-d54a-405f-914f-e778d555646a.png)

The Values that were selected first via "s/>path</value" where s is (or should be) the cluster OBSERVATION.blood_pressure.v2 are null.
The other two values selected via the full path from c aka "c/>section</>path</value" are correct.

## Expected result (Acceptance Criteria) ##

I expected both variants to give equal results. This worked for other AQLs but not in this blood_pressure case...

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by richter122-goe** [comment]
The above described error is about selected values that are not returned correctly.
But this might be connected to issues with using logical operators in CONTAINS-Statements.

The following two screenshots show a simple example about a flaw in using logical operators:
- First AQL gives back 399 Compositions with the blood-pressure archetype.
- Second AQL (using other archetypes with or operator) gives back only 44. But should give all 399.
First AQL:
![Clipboard - 11  Februar 2022 17_28](https://user-images.githubusercontent.com/64580653/154279514-4aa34fd6-3ce8-4a0b-965d-b3f7bc055280.png)
Second AQL:
![Clipboard - 11  Februar 2022 17_32](https://user-images.githubusercontent.com/64580653/154279732-02576a07-5c9f-4a29-b659-bc423c5fb93c.png)

**Comment by chevalleyc** [comment]
@richter122-goe Hi! Do you have a sample composition I can use to reproduce this issue? Thanks!

**Comment by chevalleyc** [comment]
@richter122-goe Hi, I have posted a branch with multiple fixes and optimizations related to this issue. Could you pls check it out? The branch is https://github.com/ehrbase/ehrbase/tree/feature/sync/737_value_point_paths . Thanks!

**Comment by vladislavploaia** [comment]
Hello all,
- Checked below AQL with [Composition_Anamnese_small.txt] - **PASSED** (https://github.com/ehrbase/ehrbase/files/8252851/Composition_Anamnese_small.txt)
![image](https://user-images.githubusercontent.com/100927963/204305539-c4a99833-ce51-4341-8303-c1bc61b450e0.png)
- And with [Composition_Anamnese_bigger.txt](https://github.com/ehrbase/ehrbase/files/8252853/Composition_Anamnese_bigger.txt) - **PASSED**
![image](https://user-images.githubusercontent.com/100927963/204306369-acd6a2d3-0eca-4ead-8340-9e7a207e9555.png)
CC: @stefanspiska, @vidi42
