### ISSUE TITLE
Conformance tests for EHR should include test data sets for empty subject.external_ref which is optional in the RM

### ISSUE THREAD

**Issue by ppazos** [ehrbase/ehrbase#754]
## Background ##

Current test data sets don't include empty subject.external_ref checks https://github.com/ehrbase/ehrbase/blob/develop/doc/conformance_testing/EHR.md

It should be valid to commit such data based on the RM https://specifications.openehr.org/releases/RM/Release-1.1.0/common.html#_overview_3

## Acceptance Criteria ##

Add the test data sets.

**Comment by stefanspiska** [comment]
@ppazos 
Is this issue still valid?

**Comment by ppazos** [comment]
@stefanspiska the definitions of the tests were merged. I don't think the robot tests were updated.

**Comment by ppazos** [comment]
@stefanspiska I will close this one, I guess some other issue should be created to implement the tests but it's been a long time since I was able to coordinate with @wlad  so I don't know what is happening at the implementation side of things.

**Comment by stefanspiska** [comment]
@ppazos 
The Implementation of test sits now on @vladislavploaia shoulders.

**Comment by ppazos** [comment]
Thanks @stefanspiska I don't have contact with @vladislavploaia since I'm not invited to the Vita meetings via Teams. Anyway, if needed he can contact me via email.
