### ISSUE TITLE
https and reverse proxy

### ISSUE THREAD

**Issue by ic3cool** [ehrbase/ehrbase#766]
## Background ##

Running the server behind traefik in my case is fine, and working except swagger
"Browse to Swagger UI --> http://localhost:8080/ehrbase/swagger-ui.html"
example and tests will be done with http

also when for example creating an EHR. The location response in headers is reported back with http

i cant find any settings around proxy or am i missing this function somewhere?

## Acceptance criteria ##

understand if this is already possible. or there is no plan for this at all.

- [ ] Item 1

## Definition of Done ##

- [ ] Review / Merge request approved (P2P session)
- [ ] Unit tests passed
- [ ] Updated documentation (Javadoc and Sphinx)
- [ ] Acceptance criteria fulfilled
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] Runtime warnings

**Comment by stefanspiska** [comment]
this is indeed a bug in ehrbase https://github.com/ehrbase/ehrbase/blob/develop/rest-openehr/src/main/java/org/ehrbase/rest/BaseController.java

**Comment by stefanspiska** [comment]
with https://github.com/ehrbase/ehrbase/pull/767 location will respect the
X-Forwarded-Host
X-Forwarded-Port
X-Forwarded-Proto

headers

**Comment by ic3cool** [comment]
hi,
nice! any estamate when its published on docker hub?

**Comment by stefanspiska** [comment]
next ist updated on each merge on dev.
