### ISSUE TITLE
Advice on (production) deployment

### ISSUE THREAD

**Issue by connec** [ehrbase/ehrbase#78]
The README currently notes:

> Deployment in production with real patient data is not recommended yet.

That said, is there a plan currently for what the recommended deployment configuration for EHRbase would be?  I appreciate this is an early stage project, I'm just looking to understand what information is already available, if any. In particular I'm wondering about things like:

- Advice for the configuration of the dependency PostgreSQL instance – is there any understanding currently of the performance that can be expected for different instance sizes, requirements around memory vs. CPU vs. storage etc.?
- Advice for scaling the application – would it be suitable to run multiple instance of the EHRbase application against a single database? What kind of concurrency constraints does a single EHRbase application have?
- Any known or expected limits in terms of concurrent requests, number of EHRs, etc. etc.

**Comment by Geisterfalle** [comment]
Hi Chris,

load testing will come next when our basic functions are mature and stable. We are aiming for an iterative approach and deployment strategies and working on scalability are on the roadmap for 2020. Of course we highly appreciate any feedback on the current state and we have some early adopters that will certainly report on this.

Just as a further remark: for this questions that are a bit broader, we recommend to open a topic at https://discourse.openehr.org/c/platform-implem/7 and tag the topic with EHRbase.

Cheers

**Comment by connec** [comment]
Thanks @Geisterfalle! I appreciate that more information about scalability will only be available later, and I've no doubt we will feed back anything we find out in our tests.

Is there currently an answer to the specific question: would it be suitable to run multiple instance of the EHRbase application against a single database? If this isn't known then I think this issue can be closed and we can revisit the discussion later (perhaps on Discourse as you suggest).

**Comment by Geisterfalle** [comment]
@connec ah, sorry for being late on this. We have not tested multiple instances running against one db. Our educated guess is that this should work, but the proof is as always in the pudding...
