### ISSUE TITLE
EHRbase-Docker-Container can't be terminated with Ctrl+C

### ISSUE THREAD

**Issue by tobihein** [ehrbase/ehrbase#781]
## Configuration information

- Docker-Container ehrbase/ehrbase:0.19.0 and ehrbase/ehrbase:next
- Operating System: Linux
- Environment: docker

## Steps to reproduce ## 
Start ehrbase-Database and ehrbase as docker-containers (not with docker-compose)
Try to terminate the ehrbase-container with Strg+C

```
docker network create ehrbase
docker run --rm --name ehrbasedb --network ehrbase -e POSTGRES_PASSWORD=postgres -e EHRBASE_USER=ehrbase -e EHRBASE_PASSWORD=ehrbase ehrbase/ehrbase-postgres:13.4

# open a new console because the previous one is blocked
docker run --rm --name ehrbase --network ehrbase -p 8088:8080 -e SPRING_DATASOURCE_URL=jdbc:postgresql://ehrbasedb:5432/ehrbase -e SPRING_DATASOURCE_USERNAME=ehrbase -e SPRING_DATASOURCE_PASSWORD=ehrbase -e SERVER_AQLCONFIG_USEJSQUERY=false ehrbase/ehrbase:0.19.0

Press Ctrl+C
```
## Actual result ##

The ehrbase-container is not terminated. You just see `^C`
The ehrbase-postgres container can be terminated by pressing Ctrl+C

## Expected result (Acceptance Criteria) ##

The ehrbase-container is terminated

## Definition of Done ##

The EHRbase container can be terminated with Ctrl+C

Maybe the root cause is described in [1] and using the recommended json-syntax [2] can solve the issue. But that's currently just a guess.

[1] https://engineeringblog.yelp.com/2016/01/dumb-init-an-init-for-docker.html#process-behavior-inside-docker-containers
[2] https://docs.docker.com/engine/reference/builder/#run

**Comment by sidharthramesh** [comment]
I’ve seen this happen with other containers also on some docker versions on some operating systems. 

Can you verify if it’s only the docker image or if it happens with all images?

**Comment by tobihein** [comment]
It is only the ehrbase-image. Other images (e.g. the ehrbase-postgres-image) terminate with Ctrl+C

Maybe it is just enough to change the last line in the docker-file with `CMD [./docker-entrypoint.sh]` or `"/bin/bash", "-c", "./docker-entrypoint.sh"`

But as I said, it's just a guess.

**Comment by flowrider3000** [comment]
I can confirm this behaviour (also only at the ehrbase image).
```
docker -v
Docker version 20.10.12, build e91ed57

sw_vers
ProductName:	macOS
ProductVersion:	12.3
BuildVersion:	21E230
```

**Comment by agustinpallares94** [comment]
Normally if you want to terminate a container process using ctrl + c you have u add -t -i to the docker run command.
Here an example:

`docker run -t -d ubuntu /usr/bin/top -b`
`Control-C`
The container is still listed 

If you run:
`docker run -t -i -d ubuntu /usr/bin/top -b`
`Control-C`

The container is not there

I've tried with the ehrbase container and it worked

**Comment by tobihein** [comment]
Thanks, with `-t -i` it works. But other containers work without it (actually I never used it before). That's why I think a change would be possible.

But for me it has low priority.

**Comment by vladislavploaia** [comment]
Hello All,
As per @agustinpallares94 , I see that solution was provided already.
Closing ticket.
CC: @vidi42
