### ISSUE TITLE
Question about server error while trying ABAC

### ISSUE THREAD

**Issue by mobilars** [ehrbase/ehrbase#785]
I'm trying to set up ABAC on my demo server, and I get an error message. I'm probably doing something wrong here, so no bug really. More a question if you give me guidance of how to fix. My guess is that the patient values is set up wrong in the EHR-object or my OAuth token is wrong. 

I have an ehrbase of the latest Docker-image version running towards a Keycloak OAuth server. I don't have an ABAC server (since I don't really understand what it's supposed to do), so I've just set up a Node server to try to receive requests (but it doesn't seem to get that far). 

**My OAuth token is as follows:**

eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJHd0x6eHRuVFBENEVFTDNxVEpFMVUtQjkzdW92b28xNjZoSXhxUHgwNnlJIn0.eyJleHAiOjE2NDgzNjk1MTIsImlhdCI6MTY0ODMzMzUxMiwiYXV0aF90aW1lIjoxNjQ4MzMzNTEyLCJqdGkiOiI0YTRkMjA2ZS1jMzE4LTQzZjEtODJjZi1jNTRlMjZmZjgyNzEiLCJpc3MiOiJodHRwOi8vMTcyLjE3LjI0Ljk6MzIwNDcvcmVhbG1zL2VocmJhc2UiLCJhdWQiOiJhY2NvdW50Iiwic3ViIjoiYmZmZDdhMzItM2FiNy00ODczLWE4MjYtMjEwZWMyMDBmMTFhIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoid2ViZWhyIiwibm9uY2UiOiJnNDJjS0pQSTFEdGtvSnZ4YUtXNE9WM2pMbVpTV3Ezc04temJ1aUphYm1ZIiwic2Vzc2lvbl9zdGF0ZSI6IjdlMzJmODU2LTMzMzMtNGExOC1iNWI5LWI1MjBhNDQwZTYwMyIsImFjciI6IjEiLCJhbGxvd2VkLW9yaWdpbnMiOlsiaHR0cHM6Ly9vYXV0aC50b29scy8iLCJodHRwOi8vbG9jYWxob3N0OjQyMDAvKiIsImh0dHA6Ly8xNzIuMTcuMjQuOSJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsiZGVmYXVsdC1yb2xlcy1laHJiYXNlIiwib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoib3BlbmlkIHBhdGllbnRfaWQgb3JnYW5pemF0aW9uX2lkIHByb2ZpbGUgZW1haWwgcmVhZCIsInNpZCI6IjdlMzJmODU2LTMzMzMtNGExOC1iNWI5LWI1MjBhNDQwZTYwMyIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJwYXRpZW50X2lkIjoicGF0MiIsIm9yZ2FuaXphdGlvbl9pZCI6IkxlZ2Vrb250b3JldCIsIm5hbWUiOiJMYXJzIEtyaXN0aWFuIFJvbGFuZCIsInByZWZlcnJlZF91c2VybmFtZSI6ImxhcnMiLCJnaXZlbl9uYW1lIjoiTGFycyBLcmlzdGlhbiIsImZhbWlseV9uYW1lIjoiUm9sYW5kIiwiZW1haWwiOiJsYXJzQHJvbGFuZC5ieiJ9.a-bOtz9fD_ponSrtlTORx7BK8sdpMATV92WFbc6Qn93KHGT9ooWaL-7P9KFfFCdcJy7CRIAfwMLa8L8M_yUMs1NzM9swvPK_mxbU6krmXVkzzEDgjfySHJkVp5MhVsUHLkoOBV6Mxwq2Wlq9MPZWPWVjVXvSTXBmLaTQg70qKyZ8tknhmAm-sXKEH2ILX7kOn-PsyXqAHmPeeBTc88pzAnq-M3DvckTVzK7rTAo9UPQGefVD4WEFCh2mVxalSHp_uxLJNV2mYA0TOmJqfif7oRpLx21UGxjBOA-UpZN9pWQI6NAK32qBAydCGURjkeiP_zxTCbKecjQISN7QDoLUQg

**With ABAC on, and running the following request:**

{"q":"select c/context/start_time/value as date, c/content[openEHR-EHR-OBSERVATION.story.v1]/data[at0001]/events[at0002]/data[at0003]/items[at0004]/value/value as note, c/content[openEHR-EHR-OBSERVATION.blood_pressure.v2]/data[at0001]/events[at0006]/data[at0003]/items[at0004]/value/magnitude as systolic, c/content[openEHR-EHR-OBSERVATION.blood_pressure.v2]/data[at0001]/events[at0006]/data[at0003]/items[at0005]/value/magnitude as diastolic  from ehr e contains composition c [openEHR-EHR-COMPOSITION.encounter.v1] where e/ehr_id/value='cc61c5d5-96ff-48f5-97a4-afa54a1124bf' ORDER by c/context/start_time/value DESC"}

**Gives an error message on the server:**

org.ehrbase.api.exception.InternalServerException: **ABAC: AQL audit patient data unavailable.**
        at org.ehrbase.application.abac.CustomMethodSecurityExpressionRoot.patientHandling(CustomMethodSecurityExpressionRoot.java:289)
        at org.ehrbase.application.abac.CustomMethodSecurityExpressionRoot.checkAbac(CustomMethodSecurityExpressionRoot.java:212)
        at org.ehrbase.application.abac.CustomMethodSecurityExpressionRoot.checkAbacPostQuery(CustomMethodSecurityExpressionRoot.java:117)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)

**Then I turn off ABAC and the request is accepted (Oauth is still on):**

{"q":"select c/context/start_time/value as date, c/content[openEHR-EHR-OBSERVATION.story.v1]/data[at0001]/events[at0002]/data[at0003]/items[at0004]/value/value as note, c/content[openEHR-EHR-OBSERVATION.blood_pressure.v2]/data[at0001]/events[at0006]/data[at0003]/items[at0004]/value/magnitude as systolic, c/content[openEHR-EHR-OBSERVATION.blood_pressure.v2]/data[at0001]/events[at0006]/data[at0003]/items[at0005]/value/magnitude as diastolic  from ehr e contains composition c [openEHR-EHR-COMPOSITION.encounter.v1] where e/ehr_id/value='cc61c5d5-96ff-48f5-97a4-afa54a1124bf' ORDER by c/context/start_time/value DESC"}

Gives:
{"q":"select c/context/start_time/value as date, c/content[openEHR-EHR-OBSERVATION.story.v1]/data[at0001]/events[at0002]/data[at0003]/items[at0004]/value/value as note, c/content[openEHR-EHR-OBSERVATION.blood_pressure.v2]/data[at0001]/events[at0006]/data[at0003]/items[at0004]/value/magnitude as systolic, c/content[openEHR-EHR-OBSERVATION.blood_pressure.v2]/data[at0001]/events[at0006]/data[at0003]/items[at0005]/value/magnitude as diastolic  from ehr e contains composition c [openEHR-EHR-COMPOSITION.encounter.v1] where e/ehr_id/value='cc61c5d5-96ff-48f5-97a4-afa54a1124bf' ORDER by c/context/start_time/value DESC","columns":[{"path":"/context/start_time/value","name":"date"},{"path":"/content[openEHR-EHR-OBSERVATION.story.v1]/data[at0001]/events[at0002]/data[at0003]/items[at0004]/value/value","name":"note"},{"path":"/content[openEHR-EHR-OBSERVATION.blood_pressure.v2]/data[at0001]/events[at0006]/data[at0003]/items[at0004]/value/magnitude","name":"systolic"},{"path":"/content[openEHR-EHR-OBSERVATION.blood_pressure.v2]/data[at0001]/events[at0006]/data[at0003]/items[at0005]/value/magnitude","name":"diastolic"}],"rows":[["2022-03-26T13:14:44.645Z","I dag er pasienten litt svimmel igjen",null,null],["2022-03-26T13:14:32.821Z","I dag er pasienten litt svimmel igjen",null,null],["2022-03-25T17:05:57.794Z","Pasienten er i god form, men er nervøs. ",120.0,80.0],["2022-03-25T14:59:15.712Z","Pasienten føler seg frisk",null,null],["2022-03-25T14:58:11.290Z","Svimmel",null,null]]}

**Here is a request for the patient EHR, still with ABAC off (with ABAC on it fails)**

http://172.17.24.9/ehrbase/rest/openehr/v1/ehr/cc61c5d5-96ff-48f5-97a4-afa54a1124bf

Gives:
{
  "system_id": {
    "_type": "HIER_OBJECT_ID",
    "value": "6257705b-4063-4d3b-835e-b599d95538a4"
  },
  "ehr_id": {
    "_type": "HIER_OBJECT_ID",
    "value": "cc61c5d5-96ff-48f5-97a4-afa54a1124bf"
  },
  "ehr_status": {
    "_type": "EHR_STATUS",
    "name": {
      "_type": "DV_TEXT",
      "value": "EHR Status"
    },
    "subject": {
      "_type": "PARTY_SELF",
      "external_ref": {
        "_type": "PARTY_REF",
        "namespace": "examples",
        "type": "PERSON",
        "id": {
          "_type": "GENERIC_ID",
          "value": "pat1",
          "scheme": "id_scheme"
        }
      }
    },
    "archetype_node_id": "openEHR-EHR-EHR_STATUS.generic.v1",
    "uid": {
      "_type": "HIER_OBJECT_ID",
      "value": "10f79e03-86e3-486f-8ff7-07500c198af3::local.ehrbase.org::1"
    },
    "is_modifiable": true,
    "is_queryable": true
  },
  "time_created": {
    "_type": "DV_DATE_TIME",
    "value": "2022-03-23T20:29:11.445Z"
  }
}

**Comment by mobilars** [comment]
Actually it now seems that my GET-request for the EHR-object on the following URL also works with ABAC:

http://172.17.24.9/ehrbase/rest/openehr/v1/ehr/cc61c5d5-96ff-48f5-97a4-afa54a1124bf

My self-made NODE-based ABAC server is getting the following, and the ehrbase-server serves up the correct data. 
_/has_consent_patient
{ patient: 'pat1', organization: 'Legekontoret' }_

So it's just the query that isn't working...

**Comment by stefanspiska** [comment]
https://ehrbase.readthedocs.io/en/latest/03_development/09_abac/index.html#query

```
Note: Currently this handling relies on the AuditResultMap of the QueryService to provide the ABAC logic with patient and template context data. This entails, that patient and template ID(s - multiple per query possible) are only given, when the query directly sets them in the SELECT.
```

ABAC on aql only woks if the quere contains patient  and template Ids like

```
select e/ehr_id/value, c/uid/value, c/archetype_details/template_id/value, c/feeder_audit from EHR e CONTAINS composition c
```

**Comment by mobilars** [comment]
Thank you. It works! It only seems to work twice, but I need to check if this is a problem on my side before I complain.  If you have hint or idea about why subsequent requests would time out, let me know.
