### ISSUE TITLE
Column alias does not work when rows are returned

### ISSUE THREAD

**Issue by robahs** [ehrbase/ehrbase#787]
## Configuration information

    "ehrbase_version": "0.20.0-SNAPSHOT",
    "openehr_sdk_version": "1.18.0-SNAPSHOT",
    "archie_version": "2.0.1",
    "jvm_version": "Oracle Corporation 11.0.14.1+1",
    "os_version": "Linux amd64 5.10.76-linuxkit",
    "postgres_version": "PostgreSQL 13.4 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20210424) 10.3.1 20210424, 64-bit"

## Steps to reproduce ## 
Column aliases are not returned when executing an ad-hoc AQL query that returns rows, eg:
 ` "q": "SELECT c as COMPOSITION FROM EHR e CONTAINS composition c"`

Column aliases are set correctly when no rows are returned. This can be verified by filtering on a bogus ehr_id
` "q": "SELECT c as COMPOSITION FROM EHR e CONTAINS composition c where e/ehr_id/value='00000000-0000-0000-0000-000000000000'"`

## Actual result ##
`"columns": [
        {
            "path": "c",
            "name": "#0"
        }
    ],`

## Expected result (Acceptance Criteria) ##
` "columns": [
        {
            "path": "c",
            "name": "COMPOSITION"
        }
    ],`

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by ErikSundvall** [comment]
Even though "COMPOSITION is not a reserved worf in AQL (https://specifications.openehr.org/releases/QUERY/latest/AQL.html#_reserved_words_and_characters) I could imagine it might confuse an AQL engine implementations trying to resolve queries based on the openEHR RM where it is a class. Do other variable names, e.g. "comp" give the same error?

**Comment by robahs** [comment]
Yes, I get the same behavior using different names too.

**Comment by vladislavploaia** [comment]
Covered by Robot Test Case.
Artifact: https://output.circle-artifacts.com/output/job/0cf48c30-0c75-43d2-bed2-2856a90ba016/artifacts/0/~/projects/tests/results/COMPOSITION_2/log-20220513-070155.html
![image](https://user-images.githubusercontent.com/100927963/168229599-59340b50-6423-4329-b9e8-3912ed7fb9c1.png)
Pull request: https://github.com/ehrbase/ehrbase/pull/860
Merged to develop.
