### ISSUE TITLE
Multiple dubious WARN when running AQL integration tests

### ISSUE THREAD

**Issue by chevalleyc** [ehrbase/ehrbase#792]
## Configuration information

{
    "ehrbase_version": "0.20.0-SNAPSHOT",
    "openehr_sdk_version": "1.18.0-SNAPSHOT",
    "archie_version": "2.0.1",
    "jvm_version": "Oracle Corporation 11.0.13+10-LTS-370",
    "os_version": "Linux amd64 5.4.0-91-generic",
    "postgres_version": "PostgreSQL 12.9 (Ubuntu 12.9-0ubuntu0.20.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, 64-bit"
}

## Steps to reproduce ## 

Run the SDK integration tests `org.ehrbase.client in client`

## Actual result ##

There are many WARN some indicating an error (!) and INFO with actual SQL exception thrown (!!). See attached [ehrbase.log](https://github.com/ehrbase/ehrbase/files/8367425/ehrbase.log)

NB. These warnings don't cause the tests to fail

## Expected result (Acceptance Criteria) ##

WARN and Exceptions shouldn't be present.

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by chevalleyc** [comment]
Notes:
- The issue is potentially with Folder DAO with the JOIN structure!
- the following config in `ehcache,xml` (on my system) deals with the `Max Object Graph Size reached for the object` warning
```
  <cache-template name="query-cache">
    <expiry>
      <none/>
    </expiry>
    <resources>
      <heap unit="MB">200</heap>
      <disk unit="MB">400</disk>
    </resources>
    <heap-store-settings>
      <max-object-graph-size>2000</max-object-graph-size>
      <max-object-size unit="MB">5</max-object-size>
    </heap-store-settings>
  </cache-template>
```

**Comment by vladislavploaia** [comment]
Hello @HolgerReiseVSys ,
Could you please take a look at this issue and confirm on its status (fixed/not) ?
I will handle it afterwards.
Thank you!
CC: @vidi42 , @stefanspiska
