### ISSUE TITLE
AQL - IndexOutOfBoundsException on selecting COMPOSITION

### ISSUE THREAD

**Issue by sidharthramesh** [ehrbase/ehrbase#808]
## Configuration information

image: `ehrbase/ehrbase@sha256:2933b4248e77f84f1812059eb204c1b6871ed5a5ed54e13c6fe0726885ca34b1`

```
{
    "ehrbase_version": "0.21.0-SNAPSHOT",
    "openehr_sdk_version": "1.19.0-SNAPSHOT",
    "archie_version": "2.0.1",
    "jvm_version": "Oracle Corporation 11.0.14.1+1",
    "os_version": "Linux amd64 5.10.0-0.bpo.9-amd64",
    "postgres_version": "PostgreSQL 14.2 on x86_64-pc-linux-gnu, compiled by gcc, a cf00366d51 p a16b4ae78f, 64-bit"
}
```

## Steps to reproduce ## 

Query: {{openehrBaseUrl}}/query/aql
```
{ "q" : "select c from EHR e contains COMPOSITION c"}
```

## Actual result ##

```
{
    "error": "Bad Request",
    "message": "Could not process query/stored-query, reason: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0"
}
```

Error logs:
```
2022-04-08 07:37:01.981  WARN [traceId=16b53ef6-5e16-4712-a5da-9b2770cf7ee2] 10 --- [nio-8080-exec-6] o.ehrbase.rest.DefaultExceptionHandler   : Could not process query/stored-query, reason: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
```

## Expected result (Acceptance Criteria) ##
200 OK

@chevalleyc I haven't tested with with your branch with the AQL improvements yet.

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by sidharthramesh** [comment]
Still present in #807

**Comment by chevalleyc** [comment]
Hi @sidharthramesh this is somehow related to CR https://github.com/ehrbase/ehrbase/issues/787

**Comment by sidharthramesh** [comment]
Oh...That's weird.
I've tried other words too:
```json
{
  "q": "select comp from EHR e contains COMPOSITION comp"
}
```
gives the same error.

Any short-term solution to retreive the full composition?

**Comment by chevalleyc** [comment]
@sidharthramesh it's on my ToDo list for this week ;-)

**Comment by chevalleyc** [comment]
@sidharthramesh re your comment in https://github.com/ehrbase/ehrbase/pull/807 please note that this change is at SDK level. To test it locally, you need to install this version of SDK into your maven directory (`mvn clean install`) and rebuild ehrbase with this version in pom.xml (1.19.0-SNAPSHOT). I have tested your AQL examples with both a composition containing an instruction and without. It passes. Could you please retest it? Many thanks for your help and support btw :-)

**Comment by sidharthramesh** [comment]
Hey @chevalleyc, this issue was fixed once I updated the SDK. Thank you!
I've also updated my comment [here](https://github.com/ehrbase/ehrbase/pull/807#issuecomment-1099030243) to reflect the same.

**Comment by vladislavploaia** [comment]
Hello All,
Checked below AQLs and it is passed
{
  "q": "select c from EHR e contains COMPOSITION c"
}
![image](https://user-images.githubusercontent.com/100927963/204303869-dee44087-21b8-4752-b07b-b7a521553555.png)
CC: @stefanspiska, @vidi42
