### ISSUE TITLE
Consistent compositionUid for APIs

### ISSUE THREAD

**Issue by sidharthramesh** [ehrbase/ehrbase#811]
## Configuration information

```
{
	"ehrbase_version": "0.21.0-SNAPSHOT",
	"openehr_sdk_version": "1.19.0-SNAPSHOT",
	"archie_version": "2.0.1",
	"jvm_version": "Oracle Corporation 11.0.14.1+1",
	"os_version": "Linux amd64 5.10.0-0.bpo.9-amd64",
	"postgres_version": "PostgreSQL 14.2 on x86_64-pc-linux-gnu, compiled by gcc, a cf00366d51 p a16b4ae78f, 64-bit"
}
```

## Steps to reproduce ## 

Creating compositions using POST `{{ehrscapeBaseUrl}}/composition?ehrId={{ehrId}}&templateId={{templateId}}&format=FLAT` returns compositionUid in fully versioned format:

```
{
"compositionUid": "fea1c081-252d-4c0f-8e78-8c788395aa8a::ehrbase.course.voiceintern.com::1"
}
```

Reading it using GET `{{ehrscapeBaseUrl}}/composition/{{compositionId}}?format=FLAT` returns only the uuid:
```
{
"compositionUid": "fea1c081-252d-4c0f-8e78-8c788395aa8a"
}
```

## Expected result (Acceptance Criteria) ##
Consistent compositionUid format in both APIs.

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by stefanspiska** [comment]
The two apis are part of different  specs and those specs also sets the uuid format. So this is not a bug. To solve this we would need a spec how to commit flat on the openehr api.
