### ISSUE TITLE
Wrong GET endpoint in "get web template by template id" function

### ISSUE THREAD

**Issue by gregorberger** [ehrbase/ehrbase#822]
## Test Case/s To Reproduce Issue

```
# path to test case
tests/robot/_resources/keywords/composition_keywords.robot:657
```

```
# robot command to execute related test case(s) in your terminal/console

robot -v SUT:EHRSCAPE -d results/composition -e future -e circleci -e TODO -e obsolete -e libtest -L TRACE --noncritical not-ready --name COMPO robot/COMPOSITION_TESTS

# Valid test suite folder names
COMPOSITION_TESTS
```

## Actual Result
GET Response : url=http://localhost:8082/rest/openehr/v1/template/genericFHIRTemplate 
 status=404, reason=Not Found 
 headers={'Cache-Control': 'must-revalidate,no-cache,no-store', 'Content-Type': 'application/json', 'Content-Length': '118'} 
 body={
"servlet":"default",
"message":"Not Found",
"url":"/rest/openehr/v1/template/genericFHIRTemplate",
"status":"404"
} 

## Expected Result
GET Response : url=http://localhost:8082/rest/openehr/v1/definition/template/adl1.4/genericFHIRTemplate 
 status=200, reason=OK 
 ...

In openEHR specification:
https://specifications.openehr.org/releases/ITS-REST/latest/definitions.html#definitions-adl-1.4-template-get-1 
you can see the GET endpoint is different from the one in "get web template by template id" function.

**Comment by vladislavploaia** [comment]
Hello @gregorberger,
As per my analysis, seems to be not a bug, as I executed all test cases under COMPOSITION_TESTS folder and found this one:
![image](https://user-images.githubusercontent.com/100927963/165323482-80245ece-949a-44e7-912c-82545841aaf4.png)
This is actually the endpoint for ECIS.
I will rename this keyword to contain ECIS name, as this is confusing.

I see that the expected result in covered in keyword, **retrieve OPT by template_id**, located under **template_opt1.4_keywords.robot**
![image](https://user-images.githubusercontent.com/100927963/165324043-15b38fd6-3eb2-4001-a4b2-6643eb652b2d.png)

Please let me know if you still face any other issues.
CC: @stefanspiska

**Comment by vladislavploaia** [comment]
@gregorberger - Execution was done using the command you pasted in above.
`robot -v SUT:EHRSCAPE -d results/composition -e future -e circleci -e TODO -e obsolete -e libtest -L TRACE --noncritical not-ready --name COMPO robot/COMPOSITION_TESTS`
Results can be found below.
I see no errors there.
In case you still face any issues, just let me know the test case or the .robot file with test case, where the error is reproducible.
[compositionResults.zip](https://github.com/ehrbase/ehrbase/files/8564643/compositionResults.zip)

**Comment by gregorberger** [comment]
@vladislavploaia thank you for your response.
