### ISSUE TITLE
Problems inserting a composition

### ISSUE THREAD

**Issue by agustinpallares94** [ehrbase/ehrbase#827]
I got an error when I wanted to insert a composition. I don't know if it is a failure of how the template is composed because it doesn't limit the maximum of a duration or if it is some limitation of the ehrbase when dealing with durations.
 
I attach the template and the composition.
The composition is filled with junk data as an example.

Here the error:
`{
    "error": "org.ehrbase.validation.constraints.wrappers.ValidationException: :-Validation error at /content[openEHR-EHR-INSTRUCTION.medication_order.v0]/activities[at0001]/description[at0002]/items[at0056]/items[at0058]/items[at0102]:Validation error at /content[openEHR-EHR-INSTRUCTION.medication_order.v0]/activities[at0001]/description[at0002]/items[at0056]/items[at0058]/items[at0102], ELT02:Validation error at /content[openEHR-EHR-INSTRUCTION.medication_order.v0]/activities[at0001]/description[at0002]/items[at0056]/items[at0058]/items[at0102], ELT01:Validation error at /content[openEHR-EHR-INSTRUCTION.medication_order.v0]/activities[at0001]/description[at0002]/items[at0056]/items[at0058]/items[at0102], Validation error at /content[openEHR-EHR-INSTRUCTION.medication_order.v0]/activities[at0001]/description[at0002]/items[at0056]/items[at0058]/items[at0102], ELT01:Validation error at /content[openEHR-EHR-INSTRUCTION.medication_order.v0]/activities[at0001]/description[at0002]/items[at0056]/items[at0058]/items[at0102], Boundaries are invalid, please make sure that only durations are specified. Found: lower:PT0H, upper:null.\n\n-Validation error at /content[openEHR-EHR-INSTRUCTION.medication_order.v0]/activities[at0001]/description[at0002]/items[at0056]/items[openEHR-EHR-CLUSTER.timing_repetition.v0]/items[at0002]:Validation error at /content[openEHR-EHR-INSTRUCTION.medication_order.v0]/activities[at0001]/description[at0002]/items[at0056]/items[openEHR-EHR-CLUSTER.timing_repetition.v0]/items[at0002], ELT02:Validation error at /content[openEHR-EHR-INSTRUCTION.medication_order.v0]/activities[at0001]/description[at0002]/items[at0056]/items[openEHR-EHR-CLUSTER.timing_repetition.v0]/items[at0002], ELT01:Validation error at /content[openEHR-EHR-INSTRUCTION.medication_order.v0]/activities[at0001]/description[at0002]/items[at0056]/items[openEHR-EHR-CLUSTER.timing_repetition.v0]/items[at0002], Validation error at /content[openEHR-EHR-INSTRUCTION.medication_order.v0]/activities[at0001]/description[at0002]/items[at0056]/items[openEHR-EHR-CLUSTER.timing_repetition.v0]/items[at0002], ELT01:Validation error at /content[openEHR-EHR-INSTRUCTION.medication_order.v0]/activities[at0001]/description[at0002]/items[at0056]/items[openEHR-EHR-CLUSTER.timing_repetition.v0]/items[at0002], Boundaries are invalid, please make sure that only durations are specified. Found: lower:P0W, upper:null.\n\n-Validation error at /content[openEHR-EHR-INSTRUCTION.medication_order.v0]/activities[at0001]/description[at0002]/items[at0129]/items[openEHR-EHR-CLUSTER.medication_supply_amount.v0]/items[at0142]:Validation error at /content[openEHR-EHR-INSTRUCTION.medication_order.v0]/activities[at0001]/description[at0002]/items[at0129]/items[openEHR-EHR-CLUSTER.medication_supply_amount.v0]/items[at0142], ELT02:Validation error at /content[openEHR-EHR-INSTRUCTION.medication_order.v0]/activities[at0001]/description[at0002]/items[at0129]/items[openEHR-EHR-CLUSTER.medication_supply_amount.v0]/items[at0142], ELT01:Validation error at /content[openEHR-EHR-INSTRUCTION.medication_order.v0]/activities[at0001]/description[at0002]/items[at0129]/items[openEHR-EHR-CLUSTER.medication_supply_amount.v0]/items[at0142], Validation error at /content[openEHR-EHR-INSTRUCTION.medication_order.v0]/activities[at0001]/description[at0002]/items[at0129]/items[openEHR-EHR-CLUSTER.medication_supply_amount.v0]/items[at0142], ELT01:Validation error at /content[openEHR-EHR-INSTRUCTION.medication_order.v0]/activities[at0001]/description[at0002]/items[at0129]/items[openEHR-EHR-CLUSTER.medication_supply_amount.v0]/items[at0142], Boundaries are invalid, please make sure that only durations are specified. Found: lower:P0D, upper:null.\n\n-Validation error at /content[openEHR-EHR-INSTRUCTION.medication_order.v0]/activities[at0001]/description[at0002]/items[at0062]/items[at0051]/items[at0053]:Validation error at /content[openEHR-EHR-INSTRUCTION.medication_order.v0]/activities[at0001]/description[at0002]/items[at0062]/items[at0051]/items[at0053], ELT02:Validation error at /content[openEHR-EHR-INSTRUCTION.medication_order.v0]/activities[at0001]/description[at0002]/items[at0062]/items[at0051]/items[at0053], ELT01:Validation error at /content[openEHR-EHR-INSTRUCTION.medication_order.v0]/activities[at0001]/description[at0002]/items[at0062]/items[at0051]/items[at0053], Validation error at /content[openEHR-EHR-INSTRUCTION.medication_order.v0]/activities[at0001]/description[at0002]/items[at0062]/items[at0051]/items[at0053], ELT01:Validation error at /content[openEHR-EHR-INSTRUCTION.medication_order.v0]/activities[at0001]/description[at0002]/items[at0062]/items[at0051]/items[at0053], Boundaries are invalid, please make sure that only durations are specified. Found: lower:PT0S, upper:null.\n\n",
    "status": "Bad Request"
}`

[Template_Composition.zip](https://github.com/ehrbase/ehrbase/files/8582380/Template_Composition.zip)

**Comment by stefanspiska** [comment]
@agustinpallares94 

I had to remove the double "Date ordered/recommended" otherweise I could save teh composition in dev.

Which version of ehrbase are you using ? (GET on `%ehrbaseBaseUri%/ehrbase/rest/status`)

**Comment by agustinpallares94** [comment]
I got the error with 0.16.5.  But when you told me, I upgraded to version 0.20.0 and everything went fine. My fault for not using the latest version.

Sorry about that.
