### ISSUE TITLE
Could not resize shared memory segment using AQL queries 

### ISSUE THREAD

**Issue by agustinpallares94** [ehrbase/ehrbase#830]
I am filling the CDR with data and I have reached the limit in which I had the volume of the Postgres pod. I have increased the size of the Postgres Pod and I have restarted it but when I do AQLs I still get the same error.

On the other hand, if I attack the CDR through other endpoints other than AQL it works.

The error that i got is:

`{
    "error": "Bad Request",
    "message": "Could not perform SQL query:org.postgresql.util.PSQLException: ERROR: could not resize shared memory segment \"/PostgreSQL.2038992847\" to 8388608 bytes: No space left on device, AQL expression:SELECTcount(e/ehr_id/value)ascounterFROMEHReCONTAINSCOMPOSITIONc<EOF>, Translated SQL:select count(DISTINCT \"counter\") as \"counter\" from (select \"ehr_join\".\"id\" as \"counter\" from \"ehr\".\"entry\" right outer join \"ehr\".\"composition\" as \"composition_join\" on \"composition_join\".\"id\" = \"ehr\".\"entry\".\"composition_id\" right outer join \"ehr\".\"ehr\" as \"ehr_join\" on \"ehr_join\".\"id\" = \"composition_join\".\"ehr_id\" where \"ehr\".\"entry\".\"template_id\" = ? union select \"ehr_join\".\"id\" as \"counter\" from \"ehr\".\"entry\" right outer join \"ehr\".\"composition\" as \"composition_join\" on \"composition_join\".\"id\" = \"ehr\".\"entry\".\"composition_id\" right outer join \"ehr\".\"ehr\" as \"ehr_join\" on \"ehr_join\".\"id\" = \"composition_join\".\"ehr_id\" where \"ehr\".\"entry\".\"template_id\" = ? union select \"ehr_join\".\"id\" as \"counter\" from \"ehr\".\"entry\" right outer join \"ehr\".\"composition\" as \"composition_join\" on \"composition_join\".\"id\" = \"ehr\".\"entry\".\"composition_id\" right outer join \"ehr\".\"ehr\" as \"ehr_join\" on \"ehr_join\".\"id\" = \"composition_join\".\"ehr_id\" where \"ehr\".\"entry\".\"template_id\" = ? union select \"ehr_join\".\"id\" as \"counter\" from \"ehr\".\"entry\" right outer join \"ehr\".\"composition\" as \"composition_join\" on \"composition_join\".\"id\" = \"ehr\".\"entry\".\"composition_id\" right outer join \"ehr\".\"ehr\" as \"ehr_join\" on \"ehr_join\".\"id\" = \"composition_join\".\"ehr_id\" where \"ehr\".\"entry\".\"template_id\" = ? union select \"ehr_join\".\"id\" as \"counter\" from \"ehr\".\"entry\" right outer join \"ehr\".\"composition\" as \"composition_join\" on \"composition_join\".\"id\" = \"ehr\".\"entry\".\"composition_id\" right outer join \"ehr\".\"ehr\" as \"ehr_join\" on \"ehr_join\".\"id\" = \"composition_join\".\"ehr_id\" where \"ehr\".\"entry\".\"template_id\" = ? union select \"ehr_join\".\"id\" as \"counter\" from \"ehr\".\"entry\" right outer join \"ehr\".\"composition\" as \"composition_join\" on \"composition_join\".\"id\" = \"ehr\".\"entry\".\"composition_id\" right outer join \"ehr\".\"ehr\" as \"ehr_join\" on \"ehr_join\".\"id\" = \"composition_join\".\"ehr_id\" where \"ehr\".\"entry\".\"template_id\" = ? union select \"ehr_join\".\"id\" as \"counter\" from \"ehr\".\"entry\" right outer join \"ehr\".\"composition\" as \"composition_join\" on \"composition_join\".\"id\" = \"ehr\".\"entry\".\"composition_id\" right outer join \"ehr\".\"ehr\" as \"ehr_join\" on \"ehr_join\".\"id\" = \"composition_join\".\"ehr_id\" where \"ehr\".\"entry\".\"template_id\" = ? union select \"ehr_join\".\"id\" as \"counter\" from \"ehr\".\"entry\" right outer join \"ehr\".\"composition\" as \"composition_join\" on \"composition_join\".\"id\" = \"ehr\".\"entry\".\"composition_id\" right outer join \"ehr\".\"ehr\" as \"ehr_join\" on \"ehr_join\".\"id\" = \"composition_join\".\"ehr_id\" where \"ehr\".\"entry\".\"template_id\" = ? union select \"ehr_join\".\"id\" as \"counter\" from \"ehr\".\"entry\" right outer join \"ehr\".\"composition\" as \"composition_join\" on \"composition_join\".\"id\" = \"ehr\".\"entry\".\"composition_id\" right outer join \"ehr\".\"ehr\" as \"ehr_join\" on \"ehr_join\".\"id\" = \"composition_join\".\"ehr_id\" where \"ehr\".\"entry\".\"template_id\" = ? union select \"ehr_join\".\"id\" as \"counter\" from \"ehr\".\"entry\" right outer join \"ehr\".\"composition\" as \"composition_join\" on \"composition_join\".\"id\" = \"ehr\".\"entry\".\"composition_id\" right outer join \"ehr\".\"ehr\" as \"ehr_join\" on \"ehr_join\".\"id\" = \"composition_join\".\"ehr_id\" where \"ehr\".\"entry\".\"template_id\" = ?) as \"alias_117890577\""
}`

**Comment by stefanspiska** [comment]
How many ehrs do you have in the system?

 Do other queries work?  For example some which are only hit one template and or have a where e/ehr_id/value = some ehrId

**Comment by stefanspiska** [comment]
maybe this helps https://www.osso.nl/blog/postgresql-inside-kubernetes-no-space-left-on-device/

**Comment by vladislavploaia** [comment]
Hello @agustinpallares94,
Could you please check the link provided by @stefanspiska and let us know if you still face any issues after trying out the solutions exposed there?
Assigning ticket to you, as we are waiting for your feedback.
Thank you!

**Comment by agustinpallares94** [comment]
> Hello @agustinpallares94, Could you please check the link provided by @stefanspiska and let us know if you still face any issues after trying out the solutions exposed there? Assigning ticket to you, as we are waiting for your feedback. Thank you!

Of course!!! I remember I tried it but I don't know if it worked. I'll keep it, try it again and let you know!

**Comment by agustinpallares94** [comment]
I tried that and it didn't work. Postgres got dumb because when I increased the size of the machine I launched queries on the DB to see what size DB it had and it kept showing the size before increasing the machine. It was a Postgres issue as such when I made it reach the limit of the machine's capacity. The solution was to create a backup at the DB level and clean it up.
