### ISSUE TITLE
AQL datapoints not returning correctly

### ISSUE THREAD

**Issue by ATHULKNAIR** [ehrbase/ehrbase#833]
## Configuration information

-EHRbase version: 0.21.0-SNAPSHOT
-openEHR_SDK version: 1.19.0-SNAPSHOT
-Archie version: 2.0.1
-PostgreSQL version: PostgreSQL 14.2 (Debian 14.2-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
-Java Runtime version: Oracle Corporation 11.0.14.1+1
-Operating System version: Linux amd64 5.4.0-107-generic

## Steps to reproduce ## 

[opt.txt](https://github.com/ehrbase/ehrbase/files/8602770/opt.txt)  -- OPT uploaded to openEHR server.

I have POSTed 2 compositions to the server, and is returning 200 OK.

[Composition 1.txt](https://github.com/ehrbase/ehrbase/files/8602804/Composition.1.txt)
[Composition 2.txt](https://github.com/ehrbase/ehrbase/files/8602863/Composition.2.txt)

I queried back some of the data points using the AQL provided below

{
	"q": "SELECT c/uid/value as uid, c/content[openEHR-EHR-SECTION.adhoc.v1]/items[openEHR-EHR-OBSERVATION.body_weight.v2]/data[at0002]/events[at0003]/data[at0001]/items[at0004]/value/magnitude as weight, c/content[openEHR-EHR-SECTION.adhoc.v1]/items[openEHR-EHR-EVALUATION.can_be_weighed.v1]/data[at0001]/items[at0002]/value/value as canbe from EHR e CONTAINS COMPOSITION c  "
}	

## Actual result ##

For composition 1 :
           [
                  "ec11d7b9-c211-4444-b440-b8bd1acf381e::localhost::1",
	           null,
		   null,
	   ],

For composition 2 : 
          [
		"05f99bd0-d4cc-408d-b38a-7f1a82b132f4::localhost::1",
		 80.0,
		"Yes",
	   ]

## Expected result (Acceptance Criteria) ##

For composition 1:
            [
		"05f99bd0-d4cc-408d-b38a-7f1a82b132f4::localhost::1",
		 80.0,
		"Yes",
	   ]
For composition 2 : 
          [
		"05f99bd0-d4cc-408d-b38a-7f1a82b132f4::localhost::1",
		 80.0,
		"Yes",
	   ]

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by chevalleyc** [comment]
@ATHULKNAIR I have tested using branch `feature/sync/737_value_point_paths` and get the expected results with an expression like the following:
```
{
"q": "select c/uid/value as uid, c/content[openEHR-EHR-SECTION.adhoc.v1,'Physiological parameters']/items[openEHR-EHR-OBSERVATION.body_weight.v2]/data[at0002]/events[at0003]/data[at0001]/items[at0004]/value/magnitude as weight, eval/data[at0001]/items[at0002]/value/value as canbe from EHR e contains composition c contains (observation obs[openEHR-EHR-OBSERVATION.body_weight.v2] AND evaluation eval[openEHR-EHR-EVALUATION.can_be_weighed.v1])"
}
```
The result is:
```
{
    "q": "select c/uid/value as uid, c/content[openEHR-EHR-SECTION.adhoc.v1,'Physiological parameters']/items[openEHR-EHR-OBSERVATION.body_weight.v2]/data[at0002]/events[at0003]/data[at0001]/items[at0004]/value/magnitude as weight, eval/data[at0001]/items[at0002]/value/value as canbe from EHR e contains composition c contains (observation obs[openEHR-EHR-OBSERVATION.body_weight.v2] AND evaluation eval[openEHR-EHR-EVALUATION.can_be_weighed.v1])",
    "columns": [
        {
            "path": "/uid/value",
            "name": "uid"
        },
        {
            "path": "/content[openEHR-EHR-SECTION.adhoc.v1,'Physiological parameters']/items[openEHR-EHR-OBSERVATION.body_weight.v2]/data[at0002]/events[at0003]/data[at0001]/items[at0004]/value/magnitude",
            "name": "weight"
        },
        {
            "path": "/data[at0001]/items[at0002]/value/value",
            "name": "canbe"
        }
    ],
    "rows": [
        [
            "cc0c36d8-f566-4406-87a0-f90e707e69c5::local.ehrbase.org::1",
            80.0,
            "Yes"
        ],
        [
            "a29c4c2d-7aa9-4a46-826b-9e4a80a8a359::local.ehrbase.org::1",
            80.0,
            "Yes"
        ]
    ]
}
```
The issue is that archetype `openEHR-EHR-OBSERVATION.body_weight.v2` occurs twice in different sections. As a result, the processor deals with the sections as separate tree instances. This causes the observed cartesian product. To avoid this, the actual section needs to be disambiguated by passing the node/name value predicate as indicated above. HTH -- Christian

PS. I had to remove the `medical_equipment_at_home_evaluation` section from compo 1 to be able to post it.

**Comment by rtchaya** [comment]
@ATHULKNAIR  Is this issue fixed? If not are there any work arounds?

**Comment by vladislavploaia** [comment]
Hello @rtchaya , @ATHULKNAIR ,
I was trying to reproduce the issue described above and was not able to add composition.
Could you please check composition content (from both files), fix them and check one more time the same steps?
![image](https://user-images.githubusercontent.com/100927963/212679817-4dc6e25a-ded5-46e1-88e4-cf29595e1910.png)
CC: @vidi42

**Comment by rtchaya** [comment]
@vladislavploaia  

can you please remove  medical_equipment_at_home_evaluation  section as indicated above

PS. I had to remove the medical_equipment_at_home_evaluation section from compo 1 to be able to post it.

**Comment by vladislavploaia** [comment]
@rtchaya,
- First query result, mentioned in issue description - **NOK**
`"rows": [
        [
            "60ad61ef-d878-49ef-9888-92f1fe2b569f::local.ehrbase.org::1",
            80.0,
            "Yes"
        ],
        [
            "60ad61ef-d878-49ef-9888-92f1fe2b569f::local.ehrbase.org::1",
            80.0,
            null
        ],
        [
            "60ad61ef-d878-49ef-9888-92f1fe2b569f::local.ehrbase.org::1",
            80.0,
            "Yes"
        ],
        [
            "60ad61ef-d878-49ef-9888-92f1fe2b569f::local.ehrbase.org::1",
            80.0,
            null
        ],
        [
            "a9d5b6e0-46a3-4722-8ad6-59823f9719c6::local.ehrbase.org::1",
            80.0,
            "Yes"
        ]
    ]`

- Second query, mentioned by @chevalleyc - **NOK**
`"rows": [
        [
            "60ad61ef-d878-49ef-9888-92f1fe2b569f::local.ehrbase.org::1",
            80.0,
            "Yes"
        ],
        [
            "60ad61ef-d878-49ef-9888-92f1fe2b569f::local.ehrbase.org::1",
            80.0,
            null
        ],
        [
            "a9d5b6e0-46a3-4722-8ad6-59823f9719c6::local.ehrbase.org::1",
            80.0,
            "Yes"
        ]
    ]`
Will inform team about that and ticket will be reported in our internal JIRA.
CC: @vidi42

**Comment by stefanspiska** [comment]
please recheck  with https://github.com/ehrbase/ehrbase/releases/tag/v2.0.0
