### ISSUE TITLE
AQL Query; Result rows are not returned if the "health_care_facility select" field is empty

### ISSUE THREAD

**Issue by pgmullar** [ehrbase/ehrbase#848]
## Configuration information

[minimal_action(1).zip](https://github.com/ehrbase/ehrbase/files/8639468/minimal_action.1.zip)

    <ehrbase_version>0.20.0</ehrbase_version>
    <openehr_sdk_version>1.18.0</openehr_sdk_version>
    <archie_version>2.0.1</archie_version>
    <jvm_version>Private Build 11.0.15+10-Ubuntu-0ubuntu0.20.04.1</jvm_version>
    <os_version>Linux amd64 5.4.0-109-generic</os_version>
    <postgres_version>PostgreSQL 13.4 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20210424) 10.3.1 20210424, 64-bit</postgres_version>

## Steps to reproduce ## 

Create two compositions;

One with the "health_care_facility" select field populated;

{
"ctx/language": "en",
"ctx/territory": "US",
"ctx/composer_name": "Silvia Blake",
"ctx/id_namespace": "HOSPITAL-NS",
"ctx/id_scheme": "HOSPITAL-NS",
"ctx/health_care_facility|id_scheme": "HOSPITAL-NS",
"ctx/health_care_facility|name": "Hospital A",
"ctx/health_care_facility|id_namespace": "HOSPITAL-NS",
"ctx/health_care_facility|id": "71a44d35-06a7-4e36-82f6-3e0f915a8eb5",
"minimal/minimal:0/ism_transition/current_state|code": "532",
"minimal/minimal:0/ism_transition/current_state|value": "completed",
"minimal/minimal:0/multimedia": "http://med.tube.com/sample",
"minimal/minimal:0/multimedia|mediatype": "application/pdf",
"minimal/minimal:0/multimedia|size": 504903212,
"minimal/minimal:0/time": "2021-11-10T14:08:05.928Z"
}

and one without the "health_care_facility select" populated;

{
"ctx/language": "en",
"ctx/territory": "US",
"ctx/composer_name": "Silvia Blake",
"ctx/id_namespace": "HOSPITAL-NS",
"ctx/id_scheme": "HOSPITAL-NS",
"minimal/minimal:0/ism_transition/current_state|code": "532",
"minimal/minimal:0/ism_transition/current_state|value": "completed",
"minimal/minimal:0/multimedia": "http://med.tube.com/sample",
"minimal/minimal:0/multimedia|mediatype": "application/pdf",
"minimal/minimal:0/multimedia|size": 504903212,
"minimal/minimal:0/time": "2021-11-10T14:08:05.928Z"
}

Write an AQL query to fetch values including the "health_care_facility" select;

"Select a/uid/value as composition_uid, a/context/health_care_facility/name from EHR e contains COMPOSITION a contains ACTION a0[openEHR-EHR-ACTION.minimal.v1]"

## Actual result ##

The row with the health_care_facility not populated is not returned;

{
    "q": "Select a/uid/value as composition_uid, a/context/health_care_facility/name from EHR e contains COMPOSITION a contains ACTION a0[openEHR-EHR-ACTION.minimal.v1]",
    "columns": [
        {
            "path": "/uid/value",
            "name": "composition_uid"
        },
        {
            "path": "/context/health_care_facility/name",
            "name": "#1"
        }
    ],
    "rows": [
        [
            "78dba268-b3b7-4d48-89bd-61705c8d84bd::local.ehrbase.org::1",
            "Hospital A"
        ]
    ]
}

Two rows are returned when the health_care_facility is removed from the AQL query.

{
    "q": "Select a/uid/value as composition_uid from EHR e contains COMPOSITION a contains ACTION a0[openEHR-EHR-ACTION.minimal.v1]",
    "columns": [
        {
            "path": "/uid/value",
            "name": "composition_uid"
        }
    ],
    "rows": [
        [
            "78dba268-b3b7-4d48-89bd-61705c8d84bd::local.ehrbase.org::1"
        ],
        [
            "fce09e78-147d-45a6-8b83-6091a45ea311::local.ehrbase.org::1"
        ]
    ]
}

## Expected result (Acceptance Criteria) ##

The missing row is returned with the empty health_care_facilty_name field populated with null.

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by vladislavploaia** [comment]
Covered by Robot Script.
![image](https://user-images.githubusercontent.com/100927963/168098317-863cd4b1-2275-4e83-939c-8dfd61538f01.png)
Pull request: https://github.com/ehrbase/ehrbase/pull/859
Merged to develop branch.
