### ISSUE TITLE
Content archetype_node_id doesn't match archetype_id in archetype_details

### ISSUE THREAD

**Issue by gregorberger** [ehrbase/ehrbase#850]
## Test Case/s To Reproduce Issue

```
# path to test case
tests/robot/CONTRIBUTION_TESTS/...
```

```
# robot command to execute related test case(s) in your terminal/console

robot -v SUT:EHRSCAPE -d results/composition -e future -e circleci -e TODO -e obsolete -e libtest -L TRACE --noncritical not-ready --name COMPO robot/COMPOSITION_TESTS

# Valid test suite folder names
COMPOSITION_TESTS

## Actual Result

<content archetype_node_id="openEHR-EHR-OBSERVATION.minimal.v1" xsi:type="OBSERVATION">
  <archetype_details>
    <archetype_id>
      <value>openEHR-EHR-COMPOSITION.minimal.v1</value>
    </archetype_id>
...


## Expected Result

<content archetype_node_id="openEHR-EHR-OBSERVATION.minimal.v1" xsi:type="OBSERVATION">
    <archetype_details>
      <archetype_id>
        <value>openEHR-EHR-OBSERVATION.minimal.v1</value>
      </archetype_id>
...


Content archetype_node_id should match archetype_id in archetype_details.

**Comment by vladislavploaia** [comment]
Hello @gregorberger,
Could you please let me know what .robot file exactly, is returning the case you described in the issue?
It would be better if you specify the exact .robot file and ideally with Test Case name, to speed-up the response time.
Thank you in advance.

**Comment by gregorberger** [comment]
@vladislavploaia For example, I was running `B.2.a_main_flow_get_existing_COMPOSITION_latest.robot` file on our custom system, when the `Main flow get existing COMPOSITION latest` test failed, because **archetype_node_id**, didn't match **archetype_id** like it should.

I see this problem in the following files:
- `tests/robot/_resources/test_data_sets/valid_templates/minimal/minimal_observation.composition.participations.extdatetimes.xml`
- `tests/robot/_resources/test_data_sets/valid_templates/minimal/minimal_observation.composition.participations.extdatetimes_no_time_zone.xml`
- `tests/robot/_resources/test_data_sets/valid_templates/minimal/minimal_observation.composition.participations.extdatetimes_utc.xml`

I also saw the file `tests/robot/_resources/test_data_sets/valid_templates/minimal/minimal_observation.composition.participations.extdatetimes_FIXED_EXAMPLE.xml`, where the problem is fixed, so I think it should be changed in the above files as well.

**Comment by vladislavploaia** [comment]
Hello @gregorberger,
Thank for such detailed explanation.
I updated all the files suggested by you + checked other files, to have the same value in archetype_node_id and archetype_id value.
Pull request: https://github.com/ehrbase/ehrbase/pull/855
Merged to develop branch. https://github.com/ehrbase/ehrbase
![image](https://user-images.githubusercontent.com/100927963/167864084-c37368b9-b00f-4d3a-af9c-26da1743136d.png)

PFA execution results of COMPOSITION_TESTS folder with .robot files [composition_log_report.zip](https://github.com/ehrbase/ehrbase/files/8670437/composition_log_report.zip)

Please let me know if you still face the same issue. Thank you!
CC: @stefanspiska

**Comment by gregorberger** [comment]
@vladislavploaia Thank you for the quick fix!
