### ISSUE TITLE
ECIS post composition / atritubre Text / CodedText

### ISSUE THREAD

**Issue by xarranzm** [ehrbase/ehrbase#852]
- EHRbase version: 21

When the attribute of the template is defined like Text and Code Text  when the instance informs the Text value the server returns bad Requests

Sample if informs Text 

..../attribute":"Value Text" --> Bad requests, Attribute value of class TERMINOLOGY_ID does not match existence 1..1, ....

Sample if informs coded Text  returns 200 and create the composition

..../attribute|code":"Code",
..../attribute|terminology":"1.22.2332.22",
..../attribute|value":"Sample Value",

**Comment by stefanspiska** [comment]
@xarranzm 

please provide the an opt file as well as a flat example.

**Comment by xarranzm** [comment]
I send the opt, a sample with problems and a sample without problems. In the tree cases the attribute are definend as Text and Coded_Text. 

[flat_CCCE_ok.txt](https://github.com/ehrbase/ehrbase/files/8664172/flat_CCCE_ok.txt)
[flat_CCCE_ko.txt](https://github.com/ehrbase/ehrbase/files/8664174/flat_CCCE_ko.txt)
[OPT.zip](https://github.com/ehrbase/ehrbase/files/8664204/OPT.zip)

The differences between the examples are:
1)	
"clinical_course/meap/soap_headings/assessment_a/clinical_synopsis/synopsis": "Avaluació -TEXTO LIBRE",
    
"clinical_course/meap/soap_headings/assessment_a/clinical_synopsis/synopsis|code": "-",
"clinical_course/meap/soap_headings/assessment_a/clinical_synopsis/synopsis|terminology": "-",
"clinical_course/meap/soap_headings/assessment_a/clinical_synopsis/synopsis|value": "Avaluació -TEXTO LIBRE",

2)
"clinical_course/meap/clinical_synopsis/synopsis": "Altres -TEXTO LIBRE",

"clinical_course/meap/clinical_synopsis/synopsis|code": "-",
"clinical_course/meap/clinical_synopsis/synopsis|terminology": "-",
"clinical_course/meap/clinical_synopsis/synopsis|value": "Altres -TEXTO LIBRE",

3)
"clinical_course/meap/service_request/current_activity/service_name": "Derivacions -TEXTO LIBRE",

"clinical_course/meap/service_request/current_activity/service_name|code": "Derivacions -TEXTO LIBRE",
"clinical_course/meap/service_request/current_activity/service_name|terminology": "Derivacions -TEXTO LIBRE",
"clinical_course/meap/service_request/current_activity/service_name|value": "Derivacions -TEXTO LIBRE",

**Comment by stefanspiska** [comment]
You can save it with

 `clinical_course/meap/soap_headings/assessment_a/clinical_synopsis/synopsis|other": "Avaluació -TEXTO LIBRE"`

note the `other`

this is because the template contains explizite choice between DV_TEXT and DV_CODED_TEXT 

```
 <node_id>at0002</node_id>
        <attributes xsi:type="C_SINGLE_ATTRIBUTE">
            <rm_attribute_name>value</rm_attribute_name>
            <existence>
                <lower_included>true</lower_included>
                <upper_included>true</upper_included>
                <lower_unbounded>false</lower_unbounded>
                <upper_unbounded>false</upper_unbounded>
                <lower>0</lower>
                <upper>1</upper>
            </existence>
            <match_negated>false</match_negated>
            <children xsi:type="C_COMPLEX_OBJECT">
                <rm_type_name>DV_TEXT</rm_type_name>
                <occurrences>
                    <lower_included>true</lower_included>
                    <upper_included>true</upper_included>
                    <lower_unbounded>false</lower_unbounded>
                    <upper_unbounded>false</upper_unbounded>
                    <lower>1</lower>
                    <upper>1</upper>
                </occurrences>
                <node_id/>
            </children>
            <children xsi:type="C_COMPLEX_OBJECT">
                <rm_type_name>DV_CODED_TEXT</rm_type_name>
                <occurrences>
                    <lower_included>true</lower_included>
                    <upper_included>true</upper_included>
                    <lower_unbounded>false</lower_unbounded>
                    <upper_unbounded>false</upper_unbounded>
                    <lower>1</lower>
                    <upper>1</upper>
                </occurrences>
                <node_id/>
            </children>
        </attributes>
```  

instead of a impliziert one 

```
 <node_id>at0002</node_id>
        <attributes xsi:type="C_SINGLE_ATTRIBUTE">
            <rm_attribute_name>value</rm_attribute_name>
            <existence>
                <lower_included>true</lower_included>
                <upper_included>true</upper_included>
                <lower_unbounded>false</lower_unbounded>
                <upper_unbounded>false</upper_unbounded>
                <lower>0</lower>
                <upper>1</upper>
            </existence>
            <match_negated>false</match_negated>
            <children xsi:type="C_COMPLEX_OBJECT">
                <rm_type_name>DV_TEXT</rm_type_name>
                <occurrences>
                    <lower_included>true</lower_included>
                    <upper_included>true</upper_included>
                    <lower_unbounded>false</lower_unbounded>
                    <upper_unbounded>false</upper_unbounded>
                    <lower>1</lower>
                    <upper>1</upper>
                </occurrences>
                <node_id/>
            </children>
        </attributes>
```

it is interpreted by the webtemplate (get /ehrbase/rest/ecis/v1/template/Clinical course), on which flat is based
as a DV_CODED_TEXT with a other input
```
  {
                                                    "id": "synopsis",
                                                    "name": "Synopsis",
                                                    "localizedName": "Synopsis",
                                                    "rmType": "DV_CODED_TEXT",
                                                    "min": 1,
                                                    "max": -1,
                                                    "localizedNames": {
                                                        "en": "Synopsis"
                                                    },
                                                    "localizedDescriptions": {
                                                        "en": "The summary, assessment, conclusions or evaluation of the clinical findings."
                                                    },
                                                    "aqlPath": "/content[openEHR-EHR-SECTION.adhoc.v1 and name/value='MEAP']/items[openEHR-EHR-SECTION.soap.v0]/items[at0003]/items[openEHR-EHR-EVALUATION.clinical_synopsis.v1]/data[at0001]/items[at0002]/value",
                                                    "inputs": [
                                                        {
                                                            "suffix": "value",
                                                            "type": "TEXT"
                                                        },
                                                        {
                                                            "suffix": "code",
                                                            "type": "TEXT",
                                                            "listOpen": true
                                                        },
                                                        {
                                                            "suffix": "other",
                                                            "type": "TEXT"
                                                        }
                                                    ]
                                                }
```

I have to think about /research the spec here. It properly should accept it with out the  `other` as DV_TEXT.

However in  your cases want any DV_TEXT or DV_CODED_TEXT. 
Since DV_CODED_TEXT is also a DV_TEXT you do not need to set expliziert in the template (just remove the DV_CODED_TEXT node ) and then

```clinical_course/meap/clinical_synopsis/synopsis": "Altres -TEXTO LIBRE"```

would work

**Comment by xarranzm** [comment]
Thank you for your support
