### ISSUE TITLE
Performance of find EHR by subject-id

### ISSUE THREAD

**Issue by grantforrester-nes** [ehrbase/ehrbase#856]
### Background

We have been conducting load tests to determine the capabilities of EHRbase and the configuration required to support one of our national workloads.

The test dataset consists of:
- ~ 6 million EHRs
- Each EHR has 1 - 6 compositions with 75% of EHRs having 6 compositions
- ~ 31 million compositions

### Performance of find EHR
During the course of our load testing we found the "find EHR" request (OpenEHR query `GET /ehr?subject_id={id}&subject_namespace={namespace}`) to have response times significantly poorer than other requests in the workload.

The following table is an extract from our test results showing 95%-ile response times at different traffic loads.

users/sec | find comp (aql) | find EHR | post comp
-- | -- | -- | -- 
10  | 449ms | 1281ms | 299ms 
20  | 608ms | 2616ms | 403ms 
30 | 835ms | 8139ms | 568ms 
40 | 1221ms | 22219ms | 726ms

### Cause
The cause appears to be the SQL generated from EHRbase and sent to Postgres can't make use of any of the indexes on the `party_identified` table as only values for the `party_ref_namespace` and `party_ref_value` fields are provided from the original REST request (as defined by the OpenEHR standard).  Therefore, Postgres performs a full table scan and thus the poor response times.

Available indexes to query:

```
Indexes:
    "party_identified_pkey" PRIMARY KEY, btree (id)
    "ehr_subject_id_index" btree (jsonb_extract_path_text(js_party_ref(party_ref_value, party_ref_scheme, party_ref_namespace, party_ref_type)::jsonb, VARIADIC ARRAY['id'::text, 'value'::text]))
    "party_identified_party_ref_idx" btree (party_ref_namespace, party_ref_scheme, party_ref_value)
    "party_identified_party_type_idx" btree (party_type, name)
```

Query plan showing how Postgres would execute query:

```
explain (analyze) select "ehr"."party_identified"."id", "ehr"."party_identified"."name", "ehr"."party_identified"."party_ref_value", "ehr"."party_identified"."party_ref_scheme", "ehr"."party_identified"."party_ref_namespace", "ehr"."party_identified"."party_ref_type", "ehr"."party_identified"."party_type", "ehr"."party_identified"."relationship", "ehr"."party_identified"."object_id_type" from "ehr"."party_identified" where ("ehr"."party_identified"."party_ref_namespace" = '--------' and "ehr"."party_identified"."party_ref_value" = '--------') limit 1;
                                                                 QUERY PLAN                                                                 
--------------------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=1000.00..159330.35 rows=1 width=164) (actual time=1478.354..1479.954 rows=1 loops=1)
   ->  Gather  (cost=1000.00..159330.35 rows=1 width=164) (actual time=1478.352..1479.948 rows=1 loops=1)
         Workers Planned: 2
         Workers Launched: 2
         ->  Parallel Seq Scan on party_identified  (cost=0.00..158330.25 rows=1 width=164) (actual time=1202.982..1202.984 rows=0 loops=3)
               Filter: ((party_ref_namespace = '--------'::text) AND (party_ref_value = '--------'::text))
               Rows Removed by Filter: 1999983
 Planning Time: 0.429 ms
 Execution Time: 1480.017 ms
(9 rows)
```

### Proposed solution

We would suggest adding a new index to the `party_identified` table that can be used by the query.

```
Indexes:
    ...
    "party_identified_namespace_value_idx" btree (party_ref_namespace, party_ref_value)
```

### Results of proposed solution

We implemented the change and could see the difference in the Postgres query plan:

```
explain (analyze) select "ehr"."party_identified"."id", "ehr"."party_identified"."name", "ehr"."party_identified"."party_ref_value", "ehr"."party_identified"."party_ref_scheme", "ehr"."party_identified"."party_ref_namespace", "ehr"."party_identified"."party_ref_type", "ehr"."party_identified"."party_type", "ehr"."party_identified"."relationship", "ehr"."party_identified"."object_id_type"  from "ehr"."party_identified" where ("ehr"."party_identified"."party_ref_namespace" = '--------' and "ehr"."party_identified"."party_ref_value" = '--------') limit 1;
                                                              QUERY PLAN                                                              
--------------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=0.56..8.58 rows=1 width=164) (actual time=0.052..0.055 rows=1 loops=1)
   ->  Index Scan using gf_test_idx on party_identified  (cost=0.56..8.58 rows=1 width=164) (actual time=0.049..0.050 rows=1 loops=1)
         Index Cond: ((party_ref_namespace = '--------'::text) AND (party_ref_value = '--------'::text))
 Planning Time: 0.188 ms
 Execution Time: 0.079 ms
```
We re-ran our load tests with the additional index.  The following table is an extract from our test results showing 95%-ile response times at different traffic loads.

users/sec | find comp (aql) | find EHR | post comp
-- | -- | -- | -- 
10 | 417ms | 209ms | 300ms
20 | 559ms | 225ms | 301ms 
30 | 669ms | 292ms | 357ms 
40 | 786ms | 341ms | 420ms

You can see the change lead to huge improvements to the response time of the "find EHR" request. Another benefit is that as a the DB was generally less busy and we saw improvements in the response times of the other requests in the test also.

**Comment by stefanspiska** [comment]
@grantforrester-nes 
Thanks for you contribution. 
By the way you might want to rest on the soon to be released 0.21.0. Should give even better performance.
