### ISSUE TITLE
Unnecessary check for Location in Composition commit body

### ISSUE THREAD

**Issue by gregorberger** [ehrbase/ehrbase#877]
## Steps to reproduce ## 

`robot -t "Check Headers with Commit Composition" robot/COMPOSITION_TESTS/HEADERS_CHECKS/"check_headers_xforwarded".robot`

## Actual result ##

Dictionary does not contain key 'meta'.

## Expected result (Acceptance Criteria) ##

In test `Check Headers with Commit Composition` there is a check `check that composition body location response has    https   example.com    333` that check for Location in meta attribute.
Attribute meta in body is not necessary in the specification: https://specifications.openehr.org/releases/ITS-REST/latest/ehr.html#composition-composition-post so I think the above check should be modified. 

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by gregorberger** [comment]
@vladislavploaia 
I'm ok with checking Location in headers, but `check that composition body location response has https example.com 333` checks in body, which is not mandatory (because attribute meta is not specified in the specification: https://specifications.openehr.org/releases/ITS-REST/latest/ehr.html#composition-composition-post).

**Comment by vladislavploaia** [comment]
Indeed @gregorberger. It is not mandatory. However, the xforwarded data needed to be validated as well, inside response of committed composition.
As I already mentioned, it was needed in context of https://github.com/ehrbase/ehrbase/issues/766.
For further details, you can contact @stefanspiska, so he can explain you details (he is on vacation for couple of weeks) or check it with @HolgerReiseVSys.
Thanks!
