### ISSUE TITLE
Duration constraints do not consider the period as a whole when validating the constraint

### ISSUE THREAD

**Issue by jryd** [ehrbase/ehrbase#878]
## Configuration information

- EHRbase version: 0.19.0
- openEHR_SDK version: 1.17.0
- Archie version: 1.0.4
- PostgreSQL version: PostgreSQL 14.2 (Debian 14.2-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
- Java Runtime version: Oracle Corporation 11.0.14+9
- Operating System version: Linux amd64 5.10.104-linuxkit

## Steps to reproduce ## 

1. Create a template in [Archetype Designer](https://tools.openehr.org/designer) that contains a duration where a minimum is set to greater than 0 days
<img width="1719" alt="image" src="https://user-images.githubusercontent.com/13251203/170149728-fad1ac14-6a2a-4055-91d5-52305981c6d6.png">

2. Upload the template to EhrBase
3. Attempt to create/update the composition against the template where the period is greater than 0 days, but does not use the day designator (i.e `P1M` - 1 month) using the Ethercis endpoint (i.e `http://localhost:8453/ehrbase/rest/ecis/v1/composition/{composition-id}`)
4. See a 500 error
![image](https://user-images.githubusercontent.com/13251203/170150064-3c28e0d2-22e8-4338-a5c8-f9d2bbc71612.png)

**Operational Template**
[medications_statement.v0.txt](https://github.com/ehrbase/ehrbase/files/8766985/medications_statement.v0.txt)

**Web template**
[medications_statement_web_template.txt](https://github.com/ehrbase/ehrbase/files/8766991/medications_statement_web_template.txt)

<details>
<summary><b>Request payload</b></summary>

```
{
    "medications/category|terminology" : "openehr",
    "medications/category|code" : "433",
    "medications/category|value" : "event",
    "medications/context/start_time" : "2022-05-24T05:57:30.341Z",
    "medications/context/setting|code" : "228",
    "medications/context/setting|terminology" : "openehr",
    "medications/context/setting|value" : "primary medical care",
    "medications/medication_list/medication_statement:0/medication_name|code" : "387517004",
    "medications/medication_list/medication_statement:0/medication_name|terminology" : "//fhir.hl7.org/ValueSet/$expand?url=http://snomed.info/sct?fhir_vs=ecl/%3C%20410942007%20MINUS%20%3E%28%3C410942007%29&activeOnly=true",
    "medications/medication_list/medication_statement:0/medication_name|value" : "Paracetamol",
    "medications/medication_list/medication_statement:0/route|terminology" : "//fhir.hl7.org/ValueSet/$expand?url=http://snomed.info/sct?fhir_vs=ecl/%3C%20284009009&activeOnly=true",
    "medications/medication_list/medication_statement:0/route|value" : "Oral route",
    "medications/medication_list/medication_statement:0/route|code" : "26643006",
    "medications/medication_list/medication_statement:0/status|code" : "at0011",
    "medications/medication_list/medication_statement:0/status|terminology" : "local",
    "medications/medication_list/medication_statement:0/status|value" : "Active",
    "medications/medication_list/medication_statement:0/dosage/dose_amount|unit" : "1",
    "medications/medication_list/medication_statement:0/dosage/dose_amount|magnitude" : 2,
    "medications/medication_list/medication_statement:0/dosage/dose_unit|code" : "428673006",
    "medications/medication_list/medication_statement:0/dosage/dose_unit|value" : "tablets",
    "medications/medication_list/medication_statement:0/dosage/dose_unit|terminology" : "SNOMED-CT",
    "medications/medication_list/medication_statement:0/timing_-_non-daily/repetition_interval" : "P2Y",
    "medications/medication_list/medication_statement:0/timing/is_this_taken_daily|terminology" : "local",
    "medications/medication_list/medication_statement:0/timing/is_this_taken_daily|value" : "non-daily",
    "medications/medication_list/medication_statement:0/timing/is_this_taken_daily|code" : "at0003",
    "medications/medication_list/medication_statement:0/clinical_indication|code" : "25064002",
    "medications/medication_list/medication_statement:0/clinical_indication|value" : "Headache",
    "medications/medication_list/medication_statement:0/clinical_indication|terminology" : "//fhir.hl7.org/ValueSet/$expand?url=http://snomed.info/sct?fhir_vs=ecl/%3C404684003&activeOnly=true",
    "medications/medication_list/medication_statement:0/time" : "2022-05-24T05:58:40.851Z",
    "medications/medication_list/medication_statement:0/language|terminology" : "ISO_639-1",
    "medications/medication_list/medication_statement:0/language|code" : "en",
    "medications/medication_list/medication_statement:0/encoding|code" : "UTF-8",
    "medications/medication_list/medication_statement:0/encoding|terminology" : "IANA_character-sets",
    "medications/composer|id_namespace" : "development-bigpicturemedical-com",
    "medications/composer|id_scheme" : "UUID",
    "medications/composer|id" : "c7c78727-7faf-453e-b573-e5152848ea19",
    "medications/composer|name" : "Super Admin",
    "medications/language|code" : "en",
    "medications/language|terminology" : "ISO_639-1",
    "medications/territory|code" : "AU",
    "medications/territory|terminology" : "ISO_3166-1",
    "medications/_uid" : "288c90f7-5cd7-4c16-97be-44c52daa1cdc::local.ehrbase.org::5"
}
```
</details>

## Actual result ##

Ehrbase will return a 500 error that an internal server error occurred.
If I take a look at the logs in Ehrbase, I can see an error from my request:

> org.ehrbase.api.exception.InternalServerException: org.ehrbase.validation.ConstraintViolationException: /content[openEHR-EHR-SECTION.medication_list.v0]/items[openEHR-EHR-OBSERVATION.medication_statement.v0]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.timing_nondaily.v1]/items[at0002]/value: The value 0 must be greater than 0

I theorise that because my template has constraints around the days that the request is failing because the provided duration does not specify a day designator. However, by virtue of the fact that the duration is using a greater period designator than days, that it must therefore be _implicitly_ greater than 0 days (i.e 1 year is more than 0 days).
If I update the period to include a day designator, EhrBase accepts the request (i.e `P1Y1D`).

## Expected result (Acceptance Criteria) ##

When validating a duration against minimum or maximum constraints, the whole timestamp should be taken into account and the period as a whole considered.

Examples:
* if I constrain days to be greater than 0, then 1 week/month/year should satisfy this without specifying a day designator (i.e `P1M`)
* if I constrain year to be less than 2, then choosing 36 months, 156 weeks, 795 days should produce a validation failure (i.e `P36M`, `P156W`, `P795D`)
* if I constrain weeks to be greater than 2, then 17 days should satisfy this without specifying the day designator (i.e `P17D`)

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by vladislavploaia** [comment]
Hello @jryd ,
I can't reproduce it. Uploaded template and created composition as per Steps To Reproduce data.
I don't see any errors in ehrbase logs. PFA file.
[ehrbase_logs.txt](https://github.com/ehrbase/ehrbase/files/8784688/ehrbase_logs.txt)
Test Case: Create Composition With Fractional Interval Time Duration
[log_success.zip](https://github.com/ehrbase/ehrbase/files/8784697/log_success.zip)
![image](https://user-images.githubusercontent.com/100927963/170650031-16c0f4ee-55c9-4130-9812-f7bb3464f3be.png)

with _"medications/medication_list/medication_statement:0/timing_-_non-daily/repetition_interval" : "P2Y",_

**Comment by jryd** [comment]
Sorry for the delay in getting back to you @vladislavploaia.

I can confirm that in the latest version, 0.21.1, that this is resolved for me.
