### ISSUE TITLE
Duration does not allow fractional units

### ISSUE THREAD

**Issue by jryd** [ehrbase/ehrbase#879]
## Configuration information

- EHRbase version: 0.19.0
- openEHR_SDK version: 1.17.0
- Archie version: 1.0.4
- PostgreSQL version: PostgreSQL 14.2 (Debian 14.2-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
- Java Runtime version: Oracle Corporation 11.0.14+9
- Operating System version: Linux amd64 5.10.104-linuxkit

## Steps to reproduce ## 

1. Create a template in [Archetype Designer](https://tools.openehr.org/designer) that contains a duration
3. Upload the template to EhrBase
4. Attempt to create/update the composition against the template where the period uses fractional units (i.e `P1.5Y`) using the Ethercis endpoint (i.e `http://localhost:8453/ehrbase/rest/ecis/v1/composition/{composition-id}`)
5. See a 400 error
![image](https://user-images.githubusercontent.com/13251203/170157901-136009bf-ee62-4a78-bb48-afcebe0936bc.png)

**Operational Template**
[medications_statement.v0.txt](https://github.com/ehrbase/ehrbase/files/8766985/medications_statement.v0.txt)

**Web template**
[medications_statement_web_template.txt](https://github.com/ehrbase/ehrbase/files/8766991/medications_statement_web_template.txt)

<details>
<summary><b>Request payload</b></summary>

```
{
    "medications/category|terminology" : "openehr",
    "medications/category|code" : "433",
    "medications/category|value" : "event",
    "medications/context/start_time" : "2022-05-24T05:57:30.341Z",
    "medications/context/setting|code" : "228",
    "medications/context/setting|terminology" : "openehr",
    "medications/context/setting|value" : "primary medical care",
    "medications/medication_list/medication_statement:0/medication_name|code" : "387517004",
    "medications/medication_list/medication_statement:0/medication_name|terminology" : "//fhir.hl7.org/ValueSet/$expand?url=http://snomed.info/sct?fhir_vs=ecl/%3C%20410942007%20MINUS%20%3E%28%3C410942007%29&activeOnly=true",
    "medications/medication_list/medication_statement:0/medication_name|value" : "Paracetamol",
    "medications/medication_list/medication_statement:0/route|terminology" : "//fhir.hl7.org/ValueSet/$expand?url=http://snomed.info/sct?fhir_vs=ecl/%3C%20284009009&activeOnly=true",
    "medications/medication_list/medication_statement:0/route|value" : "Oral route",
    "medications/medication_list/medication_statement:0/route|code" : "26643006",
    "medications/medication_list/medication_statement:0/status|code" : "at0011",
    "medications/medication_list/medication_statement:0/status|terminology" : "local",
    "medications/medication_list/medication_statement:0/status|value" : "Active",
    "medications/medication_list/medication_statement:0/dosage/dose_amount|unit" : "1",
    "medications/medication_list/medication_statement:0/dosage/dose_amount|magnitude" : 2,
    "medications/medication_list/medication_statement:0/dosage/dose_unit|code" : "428673006",
    "medications/medication_list/medication_statement:0/dosage/dose_unit|value" : "tablets",
    "medications/medication_list/medication_statement:0/dosage/dose_unit|terminology" : "SNOMED-CT",
    "medications/medication_list/medication_statement:0/timing_-_non-daily/repetition_interval" : "P1.5Y",
    "medications/medication_list/medication_statement:0/timing/is_this_taken_daily|terminology" : "local",
    "medications/medication_list/medication_statement:0/timing/is_this_taken_daily|value" : "non-daily",
    "medications/medication_list/medication_statement:0/timing/is_this_taken_daily|code" : "at0003",
    "medications/medication_list/medication_statement:0/clinical_indication|code" : "25064002",
    "medications/medication_list/medication_statement:0/clinical_indication|value" : "Headache",
    "medications/medication_list/medication_statement:0/clinical_indication|terminology" : "//fhir.hl7.org/ValueSet/$expand?url=http://snomed.info/sct?fhir_vs=ecl/%3C404684003&activeOnly=true",
    "medications/medication_list/medication_statement:0/time" : "2022-05-24T05:58:40.851Z",
    "medications/medication_list/medication_statement:0/language|terminology" : "ISO_639-1",
    "medications/medication_list/medication_statement:0/language|code" : "en",
    "medications/medication_list/medication_statement:0/encoding|code" : "UTF-8",
    "medications/medication_list/medication_statement:0/encoding|terminology" : "IANA_character-sets",
    "medications/composer|id_namespace" : "development-bigpicturemedical-com",
    "medications/composer|id_scheme" : "UUID",
    "medications/composer|id" : "c7c78727-7faf-453e-b573-e5152848ea19",
    "medications/composer|name" : "Super Admin",
    "medications/language|code" : "en",
    "medications/language|terminology" : "ISO_639-1",
    "medications/territory|code" : "AU",
    "medications/territory|terminology" : "ISO_3166-1",
    "medications/_uid" : "288c90f7-5cd7-4c16-97be-44c52daa1cdc::local.ehrbase.org::5"
}
```
</details>

## Actual result ##

Ehrbase will return a 400 bad request error that the text cannot be parsed to a period.
If I take a look at the logs in Ehrbase, I can see an error from my request:

> 2022-05-25 01:16:35.139  WARN [traceId=658c31c8-4935-4935-8b3c-35d72b28054e] 10 --- [nio-8080-exec-7] o.e.r.ehrscape.EhrScapeExceptionHandler  : Text cannot be parsed to a Period:P1.5Y

## Expected result (Acceptance Criteria) ##

As far as I am aware, the ISO 8601 specification allows for the smallest value to have a decimal fraction; https://en.wikipedia.org/wiki/ISO_8601#Durations

This means we can represent half a year as `P0.5Y` or 2 and a half months as `P2.5M`.

I would expect these values to be persisted successfully.

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by vladislavploaia** [comment]
Hello @jryd,
Issue reproduced in our ehrbase.
![image](https://user-images.githubusercontent.com/100927963/170705335-8fe7aa2b-88de-4c5d-8be8-92846fc3e843.png)
Bug will be reported in our JIRA, after alignment with developers.
Robot script already implemented for this case.

**Comment by jryd** [comment]
Thanks @vladislavploaia. 

🤔 A question that we were asking in our team, which we couldn’t find an answer for in our searching was how many decimal places should be allowed; can you enter as many as you want or is there a limit. 

At a minimum, to be able to support milliseconds on seconds, I believe it needs to allow 3 decimal places but maybe others need more.

**Comment by vladislavploaia** [comment]
Hello @jryd,
Here is the comment provided by @HolgerReiseVSys:
![image](https://user-images.githubusercontent.com/100927963/170988702-efb45700-2bfd-4c62-88c2-c05cbe71a5dd.png)
DV_DURATION accepts integers only.

**Comment by jryd** [comment]
Thanks @vladislavploaia - checked out the link that @HolgerReiseVSys mentioned and confirmed that it only supports integer values.

As such, this isn't a bug in EHRBase as it is correctly conforming to the OpenEHR spec; its just a difference between the OpenEHR spec and the ISO8601 standard.
