### ISSUE TITLE
"Retrieve an example of composition" always returns category 431:persistent instead of the valid OPT category

### ISSUE THREAD

**Issue by xurxogr** [ehrbase/ehrbase#897]
## Configuration information

- EHRbase version: 0.21.1
- openEHR_SDK version: 1.19.0
- Archie version: 2.0.1
- PostgreSQL version: PostgreSQL 13.4 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20210424) 10.3.1 20210424, 64-bit
- Java Runtime version: Oracle Corporation 11.0.15+10
- Operating System version: Linux amd64 4.14.273-207.502.amzn2.x86_64

## Steps to reproduce ## 

Upload a template that contains a composition of category Episodic (435) or Event (433).
Get sample composition from template using ECIS api {{ecis_api_uri}}/template/:template_id/example?format=FLAT

## Actual result ##

Category returned: "persistent" with code 431
```
{
    "test_event/coded_text|code": "431",
    "test_event/coded_text|value": "persistent",
    "test_event/coded_text|terminology": "openehr",
    "test_event/category|terminology": "openehr",
    "test_event/category|value": "persistent",
    "test_event/category|code": "431",
   ... other fields
}
```

## Expected result (Acceptance Criteria) ##

Category returned: "event" with code 433 or "episodic" with code 435
```
{
    "test_event/coded_text|code": "433",
    "test_event/coded_text|value": "event",
    "test_event/coded_text|terminology": "openehr",
    "test_event/category|terminology": "openehr",
    "test_event/category|value": "event",
    "test_event/category|code": "433",
   ... other fields
}
```

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by xurxogr** [comment]
Attached Template "test_event". It just contains a composition archetype of category event

Line 95:  <code_list>433</code_list>

[test_event.opt.txt](https://github.com/ehrbase/ehrbase/files/8844670/test_event.opt.txt)

**Comment by vladislavploaia** [comment]
Hello @xurxogr! 
Issue is under analysis.
Will return in case of any updates.

**Comment by vladislavploaia** [comment]
Internal bug reported.
JIRA: https://jira.vitagroup.ag/browse/CDR-432

**Comment by vladislavploaia** [comment]
Issue is fixed.
Tested on EHRBase 2.8.0-SNAPSHOT.
![image](https://github.com/user-attachments/assets/a016e573-4780-4a46-8455-526bcac96eda)

Included in the following released version: https://github.com/ehrbase/ehrbase/releases/tag/v2.7.0
Ticket closed.
