### ISSUE TITLE
Data loss when posting compostions in Canonical Format

### ISSUE THREAD

**Issue by xurxogr** [ehrbase/ehrbase#900]
## Configuration information

- EHRbase version: 0.21.1
- openEHR_SDK version: 1.19.0
- Archie version: 2.0.1
- PostgreSQL version: PostgreSQL 13.4 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20210424) 10.3.1 20210424, 64-bit
- Java Runtime version: Oracle Corporation 11.0.15+10
- Operating System version: Linux amd64 4.14.273-207.502.amzn2.x86_64

## Steps to reproduce ## 

1. Create an archetype with one TEXT and multiple DV_QUANTITY elements. No need to specify anything, just the type. 
2. Upload the template: /ehrbase/rest/openehr/v1/definition/template/adl1.4
3. Generate sample composition in Canonical JSON: /ehrbase/rest/ecis/v1/template/:template_id/example?format=JSON
4. Post the composition using OpenEHR API (also fails with EhrScape API). 

![1template_with_text](https://user-images.githubusercontent.com/259712/172446801-ded8ab91-bc13-496f-b746-83db6f901eb5.jpg)

Template: [test_quantity_with_text.opt.txt](https://github.com/ehrbase/ehrbase/files/8855346/test_quantity_with_text.opt.txt)

## Actual result ##

All the fields of type DV_QUANTITY are gone but the last

![2error_without_text](https://user-images.githubusercontent.com/259712/172447242-437c18a7-05fb-48ed-81d7-fdbe96cb8537.jpg)

## Expected result (Acceptance Criteria) ##

All elements of type DV_QUANTITY should be present in the composition

## Additional Notes ##

If the template doesn't have the element TEXT all the DV_QUANTITY elements are gone

Template: 
[test_quantity_without_text.opt.txt](https://github.com/ehrbase/ehrbase/files/8855357/test_quantity_without_text.opt.txt)

![1template_without_text](https://user-images.githubusercontent.com/259712/172447178-9d311e4b-81e0-472f-b304-d5e4fd2cff5f.jpg)

![2error_with_text](https://user-images.githubusercontent.com/259712/172446856-6dd97a22-8d68-45e3-abb3-023c249fd595.jpg)

- Same error happens with the blood pressure archetype from the CKM: https://ckm.openehr.org/ckm/archetypes/1013.1.3574
- Error does NOT happen if the composition is posted in the FLAT format
- Untested with XML or Structured formats

```diff
- Error does NOT happen if the uid field is removed from the items ("archetype_node_id": "at0003")
```
![removing_uid_from_items](https://user-images.githubusercontent.com/259712/172448156-4cbc7fe7-71a5-479b-a53f-6189e5daf3e5.jpg)

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by vladislavploaia** [comment]
Hello @xurxogr,
Bug reported in Jira: https://jira.vitagroup.ag/browse/CDR-433
Will keep you posted if there are any estimations/updates on that side.

**Comment by xurxogr** [comment]
I have reproduced the error in flat format for another template and strings, but with a common pattern as solution: Remove the "_uid" field of any embed archetype

The template includes other archetypes for anatomical_location and problem_diagnosis_qualifier. If "_uid" is present in any of those, only the last element is persisted and the others are gone:

![image](https://user-images.githubusercontent.com/259712/182619376-fc067e9a-355f-41ca-a860-606cf473f6ad.png)

In green the elements that are not persisted. As you can see only one element from the embed archetype is saved (+ _uid)
![image](https://user-images.githubusercontent.com/259712/182619515-f546244c-82d2-4425-93e6-b7b4044a428b.png)


Note: The composition being posted has been generated by the REST API to get example composition of the template, in this case in FLAT format.

----

As a conclusion, this doesn't affect DV_QUANTITY only but has to do with including "_uid" of subelements
[openEHR-EHR-TEMPLATE.problem_list.opt.txt](https://github.com/ehrbase/ehrbase/files/9251732/openEHR-EHR-TEMPLATE.problem_list.opt.txt)

**Comment by vladislavploaia** [comment]
Tested with [test_quantity_with_text.opt.txt](https://github.com/ehrbase/ehrbase/files/8855346/test_quantity_with_text.opt.txt)
As 27 DV_QUANTITY was posted in Commit Composition call, the same number of DV_QUANTITY was returned in GET composition.
GET call: http://localhost:8080/ehrbase/rest/ecis/v1/composition/ehr_id?format=FLAT
