### ISSUE TITLE
AQL - Search in other_context - Jsonb query builder is not implemented for other_context

### ISSUE THREAD

**Issue by darabosm** [ehrbase/ehrbase#901]
## Configuration information

- EHRbase version: v0.21.1
- openEHR_SDK version: 1.19.0
- Archie version: 1.0.3 ?
- PostgreSQL version: 13.4
- Java Runtime version: 15.0.2
- Operating System version: Windows 10

## Steps to reproduce ## 

Search with value comparison in where clause for values in other_context.
Use alias for archetype in other_context.

## Actual result ##

**Jsonb query builder is not implemented for other_context of context in composition.**

When searching in other_context for values, the search is extremely slow, even with small amount of data in database. 
Also aliasing does not work for archetypes in other_context, stays always null.

query is extremly slow:
```
SELECT  cl FROM
   EHR [ehr_id/value='1234']
      CONTAINS COMPOSITION c 
         CONTAINS CLUSTER cl [openEHR-EHR-CLUSTER.some_identifiier.v0]
   WHERE and  c/context/other_context[at0003]/items[openEHR-EHR-CLUSTER.context_data.v2]/items[openEHR-EHR-CLUSTER.some_identifiier.v0]/items[at0001]/value/value = 'xyz' 
```

"o" stays always null, it returns a resultset with null values: 
```
SELECT  o FROM
   EHR [ehr_id/value='1234']
      CONTAINS COMPOSITION [openEHR-EHR-COMPOSITION.encounter.v1]
         CONTAINS CLUSTER o [openEHR-EHR-CLUSTER.context_data.v1]
   WHERE o/items[at0001]/value/value = 'xyz' 
```

## Expected result (Acceptance Criteria) ##

Search in other_context is as fast as in entry.
Aliasing works for archetypes in other context

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by jpwiedekopf** [comment]
I think this issue is related to the issue and my comments in #925 . Trying a query for [Stationärer Versorgungsfall](https://ckm.highmed.org/ckm/templates/1246.169.620), my result is empty even though I know it shouldn't be:

```
SELECT c/uid/value AS uid,
c/context/other_context[at0001]/items[at0003]/value
FROM EHR e 
CONTAINS COMPOSITION c 
WHERE c/archetype_details/template_id/value = 'Stationärer Versorgungsfall'
AND c/context/other_context[at0001]/items[at0003]/value = '901525439'
```

**Comment by stefanspiska** [comment]
please recheck  with https://github.com/ehrbase/ehrbase/releases/tag/v2.0.0
