### ISSUE TITLE
AQL query for load observation events in time range

### ISSUE THREAD

**Issue by mannro** [ehrbase/ehrbase#915]
## Background ##

We want to load all observations with times on events in a specified time interval.
Problem is that each observation has different at codes and event attributes.

## Acceptance Criteria ##

Implement support for non at codes or regex in at codes predicates

## Definition of Done ##

- [ ] Query like bellow return all observation with at least one event with time attribute large than predicate value
```
SELECT o FROM EHR e CONTAINS composition c[openEHR-EHR-COMPOSITION.encounter.v0] CONTAINS observation o where o/data/events/time/value >= '2022-06-23T00:00.000Z'
```

what do you think @birgerhaarbrandt, it is not implemented or are we doing something wrong?

**Comment by stefanspiska** [comment]
@mannro 
Nn this is not implemented.

**Comment by mannro** [comment]
@stefanspiska 
and is there a possibility that it will be implemented? is it possible to actively cooperate on the implementation?

**Comment by stefanspiska** [comment]
please recheck  with https://github.com/ehrbase/ehrbase/releases/tag/v2.0.0
