### ISSUE TITLE
Building with Docker database

### ISSUE THREAD

**Issue by bjornna** [ehrbase/ehrbase#92]
I am trying to build using `mvn clean install` using the suggested Docker database. 
The build fails when building **base** with the following exception: 

[ERROR] Failed to execute goal org.flywaydb:flyway-maven-plugin:4.0.3:migrate (default) on project base: org.flywaydb.core.api.FlywayException: Unable to obtain Jdbc connection from DataSource (jdbc:postgresql://localhost:5432/ehrbase) for user 'ehrbase': FATAL: password authentication failed for user "ehrbase" -> [Help 1]

I have tried to login to the Docker database using PgAdmin with the same result. 

Is there some special setups to use the Docker database? 

`docker run --name ehrbasedb -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -e EHRBASE_USER=ehrbase -e EHRBASE_PASSWORD=ehrbase -d -p 5432:5432 ehrbaseorg/ehrbase-database-docker:11.5`

Tip: My environment is Windows 10 with the following Java in use: 

openjdk version "1.8.0_192"
OpenJDK Runtime Environment (build 1.8.0_192-amazon-corretto-preview2-b12)
OpenJDK 64-Bit Server VM (build 25.192-b12, mixed mode)

**Comment by Geisterfalle** [comment]
Hi Bjorn, 

as I experienced this myself once, I hope my question does not sound offensive: are you sure that there is no postgres instance running natively on your system? 

Best,

Birger

**Comment by bjornna** [comment]
Thanks Birger! 
Now the maven build worked. Sorry for the issue. I was confused by the message from Postgres. 
Happy new year! 

/Bjørn
