### ISSUE TITLE
missing column aliases in AQL

### ISSUE THREAD

**Issue by xarranzm** [ehrbase/ehrbase#923]
## Configuration information

- EHRbase version: v0.20.0
- openEHR_SDK version:
- Archie version:
- PostgreSQL version: 11.5
- Java Runtime version: openjdk-11
- Operating System version: Ubuntu 20.04.1 LTS

## Steps to reproduce ## 

execute aql 
{
    "q": "SELECT c as compo_value FROM EHR e CONTAINS COMPOSITION c[composition]"
}

## Actual result ##

    "columns": [
        {
            "path": "c",
            "name": "#0"
        }
    ],

## Expected result (Acceptance Criteria) ##

    "columns": [
        {
            "path": "c",
            "name": "compo_value"
        }
    ],

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by vladislavploaia** [comment]
Hello @xarranzm,
Issue was fixed in https://github.com/ehrbase/ehrbase/issues/787.
Present in below EHRbase version:
![image](https://user-images.githubusercontent.com/100927963/175974912-15d4355b-4aa0-4d85-99d4-8a2af1cff2fe.png)
