### ISSUE TITLE
500 Internal Server Error ArithmeticException: integer overflow on far to big values for DV_Duration

### ISSUE THREAD

**Issue by richter122-goe** [ehrbase/ehrbase#926]
## Background ##

When creating Compositions with values higher than MAX-INT the EHRBase return 400 Bad Request - which is fine.
However with values lower than MAX-INT it is possible to cause a 500 Internal Server Error due to Integer Overflow.

Sector of Composition:
```
"medikamentenliste/medikationseintrag:0/dauer_der_einnahme|year": 11,
"medikamentenliste/medikationseintrag:0/dauer_der_einnahme|month": 2147483647,
"medikamentenliste/medikationseintrag:0/dauer_der_einnahme|day": 2147483648
```
Server Response:
```
"error": "Bad Request",
"message": "For input string: \"2147483648\""
```

Example-Composition for Integer-Overflow:
[MAX-INT_BadRequest_Composition.json.txt](https://github.com/ehrbase/ehrbase/files/9008866/MAX-INT_BadRequest_Composition.json.txt)
OPT for this Composition:
[KDS_Medikationseintrag.opt.txt](https://github.com/ehrbase/ehrbase/files/9008870/KDS_Medikationseintrag.opt.txt)
Server-Log:
[MAX-INT_500Arithmetic_Server-Log.txt](https://github.com/ehrbase/ehrbase/files/9008873/MAX-INT_500Arithmetic_Server-Log.txt)

## Acceptance Criteria ##

I would expect the Internal Server Error / Exception to be caught and dealt with.

## Definition of Done ##

- [ ] Output has been reviewed or presented and has been approved
- [ ] Documentation has been updated (Sphinx, Javadoc, Guidelines, etc.) if applicable

**Comment by vladislavploaia** [comment]
Hello @richter122-goe,
Bug reported and will be tracked internally in JIRA: https://jira.vitagroup.ag/browse/CDR-447
Will inform you if I have any updates on that.
Thank you!
