### ISSUE TITLE
Couldn't get the value of DV_BOOLEAN while doing AQL.

### ISSUE THREAD

**Issue by ATHULKNAIR** [ehrbase/ehrbase#946]
## Configuration information

- EHRbase version: 0.21.1
- openEHR_SDK version: 1.19.0
- Archie version: 2.0.1
- PostgreSQL version: PostgreSQL 14.2 (Ubuntu 14.2-1.pgdg18.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, 64-bit
- Java Runtime version: Oracle Corporation 11.0.15+10
- Operating System version: Linux amd64 5.10.0-0.bpo.9-amd64

## Steps to reproduce ## 
OPT file :  [aarthy.screening.v0.txt](https://github.com/ehrbase/ehrbase/files/9180538/aarthy.screening.v0.txt)
Composition to POST : [aarthy.screening.v0-composition.txt](https://github.com/ehrbase/ehrbase/files/9180557/aarthy.screening.v0-composition.txt)

AQL to get the boolean value : 
 {
    "q": " SELECT c/context/start_time/value as time , c/content[openEHR-EHR-OBSERVATION.problem_screening.v0, 
    'Medical History']/data[at0001]/events[at0002]/data[at0003]/items[at0022, 'One Eyed']/items[at0005]/value/value as data from 
    EHR e  CONTAINS COMPOSITION c  WHERE   c/archetype_details/template_id/value='aarthy.screening.v0'"
}	

## Actual result ##

The result that we get when the above aql is performed :
![image](https://user-images.githubusercontent.com/77236185/180765531-3da92e83-cf72-4c92-a1b3-142fcc41437e.png)

The aql is returning value if we do a upper level query : 
 
{
	"q": " SELECT c/context/start_time/value as time,  c/content[openEHR-EHR-OBSERVATION.problem_screening.v0, 'Medical History']/data[at0001]/events[at0002]/data[at0003]/items[at0022, 'One Eyed']/items[at0005]/value as data from EHR e CONTAINS COMPOSITION c  WHERE  c/archetype_details/template_id/value='aarthy.screening.v0'"
}	

The result for upper query : 
![image](https://user-images.githubusercontent.com/77236185/180766148-8681c17d-6c44-4269-afdc-73fe13722ce2.png)

## Expected result (Acceptance Criteria) ##

	"rows": [
		[
			"2022-07-11T09:51:58.481Z",
			 false
		],
         ]

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by xurxogr** [comment]
I could also reproduce it.
It doesn't happen if that template is the only one in EHRBase as there will be no UNION. As soon as there are more templates it fails:
SQL has ```cast(ehr.aql_node_name_predicate([...] as boolean)``` for that template but ```ehr.aql_node_name_predicate(``` for the others

**Comment by vladislavploaia** [comment]
Hello @ATHULKNAIR,
Issue is reproducible as well in EHRBase version **0.22.0**.
Jira bug was reported for tracking purposes: https://jira.vitagroup.ag/browse/CDR-491

Thank you!

**Comment by vladislavploaia** [comment]
Hello @ATHULKNAIR,
Issue seems to be fixed.
![image](https://github.com/user-attachments/assets/e51cb10c-b58f-4cac-8572-4c5965f7e647)
Tested on EHRBase v 2.6.0: https://github.com/ehrbase/ehrbase/releases/tag/v2.6.0
Ticket closed.
CC: @vidi42
