### ISSUE TITLE
Stuck in “2.5. Step 4: Load Data” 

### ISSUE THREAD

**Issue by daguanyu** [ehrbase/ehrbase#954]
I’m new to EHRBase and use docker images to learn EHRbase. According to the document, I have successfully performed the first three steps of “2. Getting Started” (including Data Models, Upload a Template and Create an EHR) .

When trying Step 4: Load Data:

I firstly built the Client Library from “GitHub - nedap/ehrbase_client_library”. But when I tried to create the Java classes from the OPT, “nullPointerException” was reported. It seems that the Client Library cannot correctly analysis the OPT. Also it seems that “/nedap/ehrbase_client_library” is no longer maintained.

Then, I tried to use Flat Format. I tried to send request to “/ehrbase/rest/ecis/v1/composition” according to the “Flat.postman_collection” and the document. but it returned “‘error’: ‘Bad Request’”. So I wonder if there is a detailed document for the API endpoints for the Flat Format to help me use the APIs properly?

What should I do to Load Data successfully?

**Comment by stefanspiska** [comment]
The correct repo for the sdk is https://github.com/ehrbase/openEHR_SDK

what is your exact error message? did you create a ehr first?

there is ta youtube Playlists covering how to get started with openehr/ehrbase:  https://www.youtube.com/playlist?list=PLUr-PTsPYKV4Cl7gUe5sPoCQEfRJ3FpWW

**Comment by daguanyu** [comment]
> The correct repo for the sdk is https://github.com/ehrbase/openEHR_SDK
> 
> what is your exact error message? did you create a ehr first?
> 
> there is ta youtube Playlists covering how to get started with openehr/ehrbase: https://www.youtube.com/playlist?list=PLUr-PTsPYKV4Cl7gUe5sPoCQEfRJ3FpWW

Thank you, I will try again using https://github.com/ehrbase/openEHR_SDK;

The “/ehrbase/rest/ecis/v1/composition” does not response error after I add “composer” to the request body.

Thank you very much for providing the youtube Playlists. I will watch it and learn.

**Comment by vladislavploaia** [comment]
Hello @daguanyu,
Could you please let us know if your issue is still reproducible?
Thank you!

**Comment by daguanyu** [comment]
> Hello @daguanyu, Could you please let us know if your issue is still reproducible? Thank you!

The problem has been solved，thank you！
