### ISSUE TITLE
REST/admin, axios client, DELETE CORS issue

### ISSUE THREAD

**Issue by da-baranov** [ehrbase/ehrbase#956]
I'm trying to implement simple CRUD with ADL 1.4 operational templates using a Chrome/Edge javascript application which is hosted on the same host but uses a different port.

Erhbase server basic auth is turned on. 

GET and POST operations work perfrectly, even if I make cross-origin requests. 

Deletion of operational templates is a responsibility of AdminTemplateController. With default ehrbase config I get CORs error "Access to XMLHttpRequest at 'http://localhost:9001/ehrbase/rest/admin/template/encounter' from origin 'http://localhost:9002' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource."

Changed `WebConfiguration.java` as follows:

```java
@Override
    public void addCorsMappings(CorsRegistry registry) {
        // registry.addMapping("/**").combine(properties.toCorsConfiguration());
        registry
              .addMapping("/**")
                .allowedOrigins("*")
                .allowedMethods("HEAD", "GET", "POST", "PUT", "DELETE", "PATCH");
    }
```
The error has gone. 

Could you please review CORS policies? I'm sure that public REST APIs should not enforce CORs at all.

**Comment by stefanspiska** [comment]
@da-baranov 
please see https://github.com/ehrbase/ehrbase/issues/727#issuecomment-1016420937

**Comment by vladislavploaia** [comment]
Hello @da-baranov,
Based on comment provided by @stefanspiska, there is a comment in https://github.com/ehrbase/ehrbase/issues/727#issuecomment-1016420937.
As I saw there, _CORS works on the EHR endpoint without issue. Tested using_ [CORS Tester](https://www.test-cors.org/#?client_method=GET&client_credentials=true&server_url=http%3A%2F%2Flocalhost%3A8080%2Fehrbase%2Frest%2Fopenehr%2Fv1%2Fehr%2F9a1d9ee4-7b7c-4a83-a996-f7b9912c2194&server_enable=true&server_status=200&server_credentials=false&server_tabs=remote).
Current ticket closed.
