### ISSUE TITLE
time_commited-Value in Response of revisionHistory should provide DateTimeValues with timezone-informations

### ISSUE THREAD

**Issue by tobihein** [ehrbase/ehrbase#988]
As a developer and user of ehbase(-sdk) I would like to have the exact dateTime when a composition is created/updated. Therefore I need to additionally have timezone-informations in the revision_history.

## Configuration information
```
<?xml version='1.0' encoding='UTF-8'?>
	<ehrbase_version>0.22.0-SNAPSHOT</ehrbase_version>
	<openehr_sdk_version>1.21.0-SNAPSHOT</openehr_sdk_version>
	<archie_version>2.0.1</archie_version>
```
## Steps to reproduce ## 

* Create an EHR and a composition
* Call the revisionHistory
`https://<host>:<port>/ehrbase/rest/openehr/v1/ehr/<ehr_id>/versioned_composition/<versioned_object_uid>/revision_history`

## Actual result ##

The `time_commited`-Value does not contain timezone-informations, although it is available in the database in table `audit_details`

```
        "time_committed": {
          "_type": "DV_DATE_TIME",
          "value": "2022-10-04T11:33:50.655"
        },
```

## Expected result (Acceptance Criteria) ##
The `time_commited`-Value should contain timezone-informations that is persisted in the database.

```
        "time_committed": {
          "_type": "DV_DATE_TIME",
          "value": "2022-10-04T11:33:50.655Z"
        },
```

**Comment by vladislavploaia** [comment]
Hello @tobihein,
Issue reported and will be tracked internally using JIRA ticket: https://jira.vitagroup.ag/browse/CDR-560.
Thank you!
CC: @vidi42, @stefanspiska
