### ISSUE TITLE
Unexpected result in AQL query with a DV_DATE_TIME element without fractions of seconds

### ISSUE THREAD

**Issue by lisbethmogseth** [ehrbase/ehrbase#989]
## Configuration information

EHRbase version: 0.21.1
openEHR_SDK version: 1.19.0
Archie version: 2.0.1
PostgreSQL version: PostgreSQL 13.4
Java Runtime version: Oracle Corporation 11.0.15
Operating System version: Linux amd64 4.18.0

## Steps to reproduce ## 

- Write a composition with a DV_DATE_TIME element with value as below, notice that the fractions of seconds are 000

```json
{
    "_type": "ELEMENT",
    "name": {
        "_type": "DV_TEXT",
        "value": "Datum/tid för provtagning"
    },
    "value": {
        "_type": "DV_DATE_TIME",
        "value": "2022-02-03T04:05:06.000"
    },
    "archetype_node_id": "at0015"
}
```

or with no fractions of seconds

```json
{
    "_type": "ELEMENT",
    "name": {
        "_type": "DV_TEXT",
        "value": "Datum/tid för provtagning"
    },
    "value": {
        "_type": "DV_DATE_TIME",
        "value": "2022-02-03T04:05:06"
    },
    "archetype_node_id": "at0015"
}
```

- Create an AQL query to find all compositions matching the value of the DV_DATE_TIME, e.g.

```
SELECT c/uid/value as composition_uid FROM EHR e[ehr_id/value=$ehr_id] WHERE d/items[at0015]/value/value=$time
```
with parameters as below - notice no fractions of a second in the query time as they were 000 or not present in the input

```json
{
    "offset": 0,
    "fetch": 10,
    "query_parameters": {
      "ehr_id": "c69c580f-73e3-44fa-b75f-fcd2e4ad0a8c",
      "time": "2022-02-03T04:05:06"
  }
}
```

## Actual result ##

The query above does not return any results. 

On the other hand the query with input parameters including the fractions of a second as 000 will return a match.
```json
{
    "offset": 0,
    "fetch": 10,
    "query_parameters": {
      "ehr_id": "c69c580f-73e3-44fa-b75f-fcd2e4ad0a8c",
      "time": "2022-02-03T04:05:06.000"
  }
}
```

## Expected result (Acceptance Criteria) ##

As the time written into the composition is the same only not expressed in the exact same format, I expected the query to return a result without having to specify fractions of a second

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings

**Comment by stefanspiska** [comment]
please recheck  with https://github.com/ehrbase/ehrbase/releases/tag/v2.0.0
