### ISSUE TITLE
AQl to retrieve data from cluster with cardinality 0..* for two elements provided in the Where clause

### ISSUE THREAD

**Issue by rtchaya** [ehrbase/ehrbase#995]
## Configuration information

- EHRbase version:0.21.1
- openEHR_SDK version:1.19.0
- Archie version:2.0.1
- PostgreSQL version:PostgreSQL 13.7, compiled by Visual C++ build 1914, 64-bit
- Java Runtime version:Oracle Corporation 18.0.2+9-61

## Steps to reproduce ## 

There is an  issue in AQl while retrieving data for an element with cardinality 0…*

Using Symptom/sign screening questionnaire archetype with Specific symptom/sign as 0…* within the encounter composition.
I have inserted 3 elements with Symptom or sign name and Presence?

0th element has
Symptom or sign name = Depression
Presence = No

1st element has
Symptom or sign name = Anxiety
Presence = No

2nd element has
Symptom or sign name = Feeding/eating
Presence = Yes

Below is the AQl to retrieve all records with Symptom or sign name = Depression and Presence = Yes.
But the AQl  results is not as expetected

`{
    "q" : "SELECT e/ehr_id/value as ehrid, c/uid/value as compid,o/data[at0001]/events[at0002]/data[at0003]/items[at0022]/items[at0004]/value/value as Condition,o/data[at0001]/events[at0002]/data[at0003]/items[at0022]/items[at0005]/value/value as Result FROM ehr e   CONTAINS COMPOSITION c[openEHR-EHR-COMPOSITION.encounter.v1]  CONTAINS (observation o[openEHR-EHR-OBSERVATION.symptom_sign_screening.v0]) WHERE o/data[at0001]/events[at0002]/data[at0003]/items[at0022]/items[at0004]/value/value = 'Depression'  and o/data[at0001]/events[at0002]/data[at0003]/items[at0022]/items[at0005]/value/value = 'Yes' and c/archetype_details/template_id/value='sample_questionnaire.en.v0'"
} `

Attached is the sample-questionnaire.en.v0.opt file along with the sample composition and aql and the sample composition
[sample_questionnaire.en.v0.zip](https://github.com/ehrbase/ehrbase/files/9979375/sample_questionnaire.en.v0.zip)
[sample_questionnaire-composition-2.zip](https://github.com/ehrbase/ehrbase/files/9979376/sample_questionnaire-composition-2.zip)

Same is the case with laboratory_test_analyte
Created a sample composition with three tests
analyte_name : analyte_result quantity
Blood : 10g/dl,
LDL cholesterol: 200mg/dl and
HDL cholesterol : 150mg/dl

for the below aql it is returning LDL as quantity is >170 while i am querying for HDL.
`{
“q” : “SELECT c/uid/value as compid, a/items[at0001]/value/magnitude as magnitude FROM ehr e CONTAINS COMPOSITION c[openEHR-EHR-COMPOSITION.encounter.v1] CONTAINS (CLUSTER a[openEHR-EHR-CLUSTER.laboratory_test_analyte.v1]) WHERE a/items[at0024]/value/value = ‘HDL cholesterol’ AND a/items[at0001]/value/magnitude > 170”
}`

## Actual result ##

The AQl is supposed to retrieve all records with Symptom or sign name = Depression and Presence = Yes.

Note that the composition has only
e3a7fc34-3610-43f2-b620-7a2519039e88::local.ehrbase.org::1
            "Anxiety",
            "No"
            "Depression",
            "No"
            "Feeding/eating",
            "Yes"

But it is returning the below response:
` "rows": [
        [
            "1dbbab66-54e6-432d-a109-21581c990eb7",
            "547bbebf-777d-4fc2-afc2-1763e0f68311::local.ehrbase.org::1",
            "Depression",
            "Yes"
        ],
        [
            "1dbbab66-54e6-432d-a109-21581c990eb7",
            "e3a7fc34-3610-43f2-b620-7a2519039e88::local.ehrbase.org::1",
            "Anxiety",
            "No"
        ],
        [
            "1dbbab66-54e6-432d-a109-21581c990eb7",
            "e3a7fc34-3610-43f2-b620-7a2519039e88::local.ehrbase.org::1",
            "Anxiety",
            "Yes"
        ],
        [
            "1dbbab66-54e6-432d-a109-21581c990eb7",
            "e3a7fc34-3610-43f2-b620-7a2519039e88::local.ehrbase.org::1",
            "Depression",
            "No"
        ],
        [
            "1dbbab66-54e6-432d-a109-21581c990eb7",
            "e3a7fc34-3610-43f2-b620-7a2519039e88::local.ehrbase.org::1",
            "Depression",
            "Yes"
        ],
        [
            "1dbbab66-54e6-432d-a109-21581c990eb7",
            "e3a7fc34-3610-43f2-b620-7a2519039e88::local.ehrbase.org::1",
            "Feeding/eating",
            "No"
        ],
        [
            "1dbbab66-54e6-432d-a109-21581c990eb7",
            "e3a7fc34-3610-43f2-b620-7a2519039e88::local.ehrbase.org::1",
            "Feeding/eating",
            "Yes"
        ]
    ]`

Response with where clause 

`       [
            "1dbbab66-54e6-432d-a109-21581c990eb7",
            "e3a7fc34-3610-43f2-b620-7a2519039e88::local.ehrbase.org::1",
            "Depression",
            "Yes"
        ],
        [
            "1dbbab66-54e6-432d-a109-21581c990eb7",
            "547bbebf-777d-4fc2-afc2-1763e0f68311::local.ehrbase.org::1",
            "Depression",
            "Yes"
        ]`
Note composition e3a7fc34-3610-43f2-b620-7a2519039e88::local.ehrbase.org::1 has Depression No, But the AQl is returning the above record as well as there is a match for Depression and Yes although it is in different indexes.

## Expected result (Acceptance Criteria) ##

Response with where clause  should be retrning only one record

`       
        [
            "1dbbab66-54e6-432d-a109-21581c990eb7",
            "547bbebf-777d-4fc2-afc2-1763e0f68311::local.ehrbase.org::1",
            "Depression",
            "Yes"
        ]`

On analysing the sql logs found the issue is due to lateral join of the where clause:

`join lateral (
 select (ehr.xjsonb_array_elements(("ehr"."entry"."entry"#>>'{/composition[openEHR-EHR-COMPOSITION.encounter.v1],/content[openEHR-EHR-OBSERVATION.symptom_sign_screening.v0],0,/data[at0001],/events,/events[at0002],0,/data[at0003],/items[at0022]}')::jsonb)#>>'{/items[at0004],0,/value,value}')
AS var_1844082057_1546) as "array_1844082057_1545"
on true
  join lateral (
 select (ehr.xjsonb_array_elements(("ehr"."entry"."entry"#>>'{/composition[openEHR-EHR-COMPOSITION.encounter.v1],/content[openEHR-EHR-OBSERVATION.symptom_sign_screening.v0],0,/data[at0001],/events,/events[at0002],0,/data[at0003],/items[at0022]}')::jsonb)#>>'{/items[at0005],0,/value,value}')
AS var_599317576_1548) as "array_599317576_1547"
on true`

When I change this to a single join lateral it gives the expected result
`join lateral (
select (ehr.xjsonb_array_elements(("ehr"."entry"."entry"#>>'{/composition[openEHR-EHR-COMPOSITION.encounter.v1],/content[openEHR-EHR-OBSERVATION.symptom_sign_screening.v0],0,/data[at0001],/events,/events[at0002],0,/data[at0003],/items[at0022]}')::jsonb)#>>'{/items[at0004],0,/value,value}')
AS var_1844082057_1546,(ehr.xjsonb_array_elements(("ehr"."entry"."entry"#>>'{/composition[openEHR-EHR-COMPOSITION.encounter.v1],/content[openEHR-EHR-OBSERVATION.symptom_sign_screening.v0],0,/data[at0001],/events,/events[at0002],0,/data[at0003],/items[at0022]}')::jsonb)#>>'{/items[at0005],0,/value,value}')
AS var_599317576_1548 ) as array_599317576_1547
on true`

**Comment by stefanspiska** [comment]
@rtchaya Can you test if https://github.com/ehrbase/ehrbase/pull/1001 fixed you issues?

**Comment by vladislavploaia** [comment]
Hello @stefanspiska, @rtchaya,
Loaded system with shared OPT and Composition. Performed AQL and received empty rows array.
![image](https://user-images.githubusercontent.com/100927963/204010639-c18ecd1a-271a-4337-8cc6-639ceb2d66c2.png)
@rtchaya , please check the shared files and let me know if something changed.
The actual response can be found here as well: 
[response.txt](https://github.com/ehrbase/ehrbase/files/10093717/response.txt)

**Comment by rtchaya** [comment]
@vladislavploaia  Sure, will test and update you

**Comment by rtchaya** [comment]
> @rtchaya Can you test if #1001 fixed you issues?

@stefanspiska  The fix is working as expected. Thanks.
